"""Akun @ayat.tersembunyi - minggu 1. Satu carousel per hari (19:00 WIB).
Tiap post punya "tema" warna (lihat akun_baru.AL_TEMA). Tiap slide = daftar baris (jenis, teks[, jarak_bawah]). Jenis:
  judul, judul2 (merah miring), sub, label (merah kecil), teks, kutip, kutip_kecil, ref, poin, kecil
Kutipan ayat memakai Alkitab TB. Kalau ada tafsiran (bukan isi ayat), tulis sebagai tafsiran."""

TAGS = "#ayatalkitab #faktaalkitab #alkitab #kristenindonesia #belajaralkitab #renunganalkitab #ayattersembunyi"

POSTS = [
    {   # 1 — Eutikhus
        "tema": "malam",
        "slides": [
            [("judul", "Ada orang yang ketiduran", 0), ("judul", "waktu khotbah…", 30), ("judul2", "lalu jatuh dari lantai 3.", 50),
             ("kecil", "Dan ini beneran ada di Alkitab.")],
            [("label", "Konteksnya"), ("teks", "Paulus sedang di kota Troas. Besok pagi ia harus berangkat, jadi malam itu ia berbicara kepada jemaat…"),
             ("kutip", "“Pembicaraan itu berlangsung sampai tengah malam.”"), ("ref", "Kisah Para Rasul 20:7")],
            [("label", "Lalu terjadilah ini"),
             ("kutip", "“Seorang muda bernama Eutikhus duduk di jendela. Karena Paulus amat lama berbicara, orang muda itu tidak dapat menahan kantuknya. Akhirnya ia tertidur lelap dan jatuh dari tingkat ketiga ke bawah. Ketika ia diangkat orang, ia sudah mati.”"),
             ("ref", "Kisah Para Rasul 20:9")],
            [("label", "Tapi ceritanya belum selesai"),
             ("kutip", "“Tetapi Paulus turun ke bawah. Ia merebahkan diri ke atas orang muda itu, mendekapnya, dan berkata: ‘Jangan ribut, sebab ia masih hidup.’”"),
             ("ref", "Kisah Para Rasul 20:10", 30),
             ("kutip_kecil", "“…mereka mengantarkan orang muda itu hidup ke rumahnya, dan mereka semua merasa sangat terhibur.”"), ("ref", "Kisah Para Rasul 20:12")],
            [("sub", "Kenapa kisah ini penting?", 30),
             ("poin", "1.  Gereja mula-mula juga berisi orang biasa: bisa capek, bisa ngantuk."),
             ("poin", "2.  Tuhan tetap bekerja, bahkan di tengah kejadian yang memalukan."),
             ("poin", "3.  Alkitab tidak menyembunyikan sisi manusiawi umat-Nya.", 40),
             ("kecil", "(Dan mungkin… pengingat untuk pengkhotbah juga.)")],
            [("judul", "Ayat jarang dibahas", 0), ("judul2", "mana lagi yang mau kamu tahu?", 40),
             ("kecil", "Tulis di komentar. Yang paling banyak diminta, akan kami bahas.")],
        ],
        "caption": "Ada orang yang ketiduran waktu khotbah… lalu jatuh dari lantai 3. Dan itu ada di Alkitab 😳\n\nKisah Para Rasul 20:7-12. Paulus berkhotbah sampai tengah malam, seorang pemuda bernama Eutikhus tertidur di jendela, jatuh, dan diangkat sudah meninggal. Tapi ceritanya tidak berhenti di situ.\n\nYang kami suka dari kisah ini: gereja mula-mula juga berisi orang biasa yang bisa capek dan ngantuk. Dan Tuhan tetap bekerja di tengah mereka.\n\nPernah baca kisah ini sebelumnya? Jawab: PERNAH / BARU TAHU 👇\n\nFollow untuk ayat-ayat lain yang jarang dibahas 📜",
    },
    {   # 2 — Elia burnout
        "tema": "gurun",
        "slides": [
            [("judul", "Nabi besar ini pernah", 0), ("judul", "minta mati.", 30), ("judul2", "Tuhan tidak memarahinya.", 50),
             ("kecil", "Tuhan menyuruhnya tidur dan makan.")],
            [("label", "Siapa dia?"), ("teks", "Elia. Baru saja ia melihat api turun dari langit di Gunung Karmel. Tapi setelah diancam ratu Izebel, ia lari ke padang gurun, sendirian."),
             ("kutip", "“Cukuplah itu! Sekarang, ya TUHAN, ambillah nyawaku, sebab aku ini tidak lebih baik dari pada nenek moyangku.”"), ("ref", "1 Raja-raja 19:4")],
            [("label", "Respons Tuhan"),
             ("kutip", "“Sesudah itu ia berbaring dan tidur di bawah pohon arar itu. Tetapi tiba-tiba seorang malaikat menyentuh dia serta berkata kepadanya: ‘Bangunlah, makanlah!’”"),
             ("ref", "1 Raja-raja 19:5")],
            [("label", "Dan Tuhan melakukannya dua kali"),
             ("kutip", "“Bangunlah, makanlah! Sebab kalau tidak, perjalananmu nanti terlalu jauh bagimu.”"), ("ref", "1 Raja-raja 19:7", 40),
             ("teks", "Tidak ada ceramah. Tidak ada teguran. Roti, air, dan tidur.")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Orang yang imannya kuat pun bisa kelelahan dan putus asa."),
             ("poin", "2.  Kadang yang kamu butuhkan bukan ‘lebih rohani’, tapi istirahat."),
             ("poin", "3.  Tuhan peduli pada tubuhmu, bukan hanya pada pelayananmu.")],
            [("judul", "Kalau kamu lagi capek banget,", 0), ("judul2", "istirahat itu juga bentuk percaya.", 40),
             ("kecil", "Kirim ke temanmu yang lagi burnout.")],
        ],
        "caption": "Nabi Elia pernah sampai minta mati. Dan respons Tuhan bukan marah, tapi: “Bangunlah, makanlah.” 🍞\n\n1 Raja-raja 19:4-8. Setelah kemenangan besar di Gunung Karmel, Elia lari ketakutan dan kehabisan tenaga. Tuhan mengirim malaikat, dua kali, dengan roti dan air, lalu membiarkannya tidur.\n\nKadang yang kita butuhkan bukan dimarahi karena kurang iman, tapi istirahat.\n\nKamu lagi di fase capek juga? Ketik 🍞 kalau butuh diingatkan untuk istirahat.\n\nFollow untuk ayat-ayat lain yang jarang dibahas 📜",
    },
    {   # 3 — Hagar & El-Roi
        "tema": "mata_air",
        "slides": [
            [("judul", "Seorang budak yang kabur", 0), ("judul", "ke padang gurun…", 30), ("judul2", "memberi Tuhan sebuah nama.", 50),
             ("kecil", "Namanya Hagar.")],
            [("label", "Siapa Hagar?"), ("teks", "Hamba perempuan Sarai. Ia hamil, diperlakukan dengan kasar, lalu melarikan diri ke padang gurun. Sendirian, tanpa siapa-siapa."),
             ("ref", "Kejadian 16:1-7")],
            [("label", "Tapi Tuhan menemuinya di sana"),
             ("teks", "Malaikat TUHAN mendapatinya di dekat sebuah mata air, berbicara dengannya, dan memberinya janji tentang anaknya."),
             ("ref", "Kejadian 16:7-11")],
            [("label", "Lalu Hagar berkata"),
             ("kutip", "“Kemudian Hagar menamakan TUHAN yang telah berfirman kepadanya itu dengan sebutan: ‘Engkaulah El-Roi.’ Sebab katanya: ‘Bukankah di sini kulihat Dia yang telah melihat aku?’”"),
             ("ref", "Kejadian 16:13", 30), ("teks", "El-Roi artinya: Allah yang melihat aku.")],
            [("sub", "Kenapa ini luar biasa?", 30),
             ("poin", "1.  Orang yang paling tidak dianggap justru ditemui Tuhan secara pribadi."),
             ("poin", "2.  Tuhan tidak menunggu Hagar kembali ‘ke tempat yang benar’. Dia datang ke padang gurunnya."),
             ("poin", "3.  Kalau tidak ada yang melihatmu, El-Roi melihat.")],
            [("judul", "Kamu mungkin merasa tak terlihat.", 0), ("judul2", "Tapi Dia melihatmu.", 40),
             ("kecil", "Save untuk hari-hari kamu merasa sendirian.")],
        ],
        "caption": "Salah satu nama Tuhan di Alkitab diberikan oleh seorang budak perempuan yang melarikan diri 👁️\n\nKejadian 16. Hagar diperlakukan kasar, kabur ke padang gurun dalam keadaan hamil, dan justru di sana Tuhan menemuinya. Hagar lalu menyebut Tuhan “El-Roi”: Allah yang melihat aku.\n\nKalau hari ini kamu merasa tidak dilihat siapa pun, Dia melihat.\n\nPernah dengar nama El-Roi sebelumnya? Jawab: PERNAH / BARU TAHU 👇\n\nFollow untuk ayat-ayat lain yang jarang dibahas 📜",
    },
    {   # 4 — Keledai Bileam
        "tema": "jalan",
        "slides": [
            [("judul", "Di Alkitab, ada keledai", 0), ("judul", "yang berbicara.", 30), ("judul2", "Dan ia menyelamatkan nyawa tuannya.", 50),
             ("kecil", "Bukan dongeng. Bilangan 22.")],
            [("label", "Konteksnya"), ("teks", "Bileam sedang dalam perjalanan. Tiga kali keledainya menyimpang dari jalan, dan tiga kali Bileam memukulnya karena kesal."),
             ("ref", "Bilangan 22:21-27")],
            [("label", "Lalu terjadilah ini"),
             ("kutip", "“Ketika itu TUHAN membuka mulut keledai itu, sehingga ia berkata kepada Bileam: ‘Apakah yang kulakukan kepadamu, sampai engkau memukul aku tiga kali?’”"),
             ("ref", "Bilangan 22:28")],
            [("label", "Ternyata…"),
             ("teks", "Ketika mata Bileam dibuka, ia melihat Malaikat TUHAN berdiri menghadang di jalan dengan pedang terhunus. Keledai itu sudah melihatnya sejak awal."),
             ("ref", "Bilangan 22:31-33", 30),
             ("teks", "Yang Bileam anggap penghalang, ternyata penyelamat.")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Tidak semua ‘hambatan’ itu musuh. Kadang itu perlindungan."),
             ("poin", "2.  Tuhan bisa memakai apa saja, bahkan seekor keledai, untuk berbicara."),
             ("poin", "3.  Sebelum marah pada yang menghalangi, tanyakan dulu kenapa.")],
            [("judul", "Jalan yang tertutup hari ini", 0), ("judul2", "mungkin sedang menyelamatkanmu.", 40),
             ("kecil", "Kirim ke temanmu yang lagi kesal karena rencananya gagal.")],
        ],
        "caption": "Keledai berbicara di Alkitab? Iya, dan ceritanya lebih dalam dari yang kamu kira 🫏\n\nBilangan 22. Keledai Bileam tiga kali menolak jalan terus, dan tiga kali dipukul. Ternyata ia melihat Malaikat TUHAN menghadang di jalan. Kalau ia tidak menyimpang, Bileam yang celaka.\n\nKadang yang kita anggap penghalang, sebenarnya perlindungan.\n\nPernah ada “jalan tertutup” di hidupmu yang belakangan kamu syukuri? Cerita di komentar 👇\n\nFollow untuk ayat-ayat lain yang jarang dibahas 📜",
    },
    {   # 5 — pemuda yang lari telanjang (Markus)
        "tema": "plum",
        "slides": [
            [("judul", "Malam Yesus ditangkap,", 0), ("judul", "ada satu pemuda…", 30), ("judul2", "yang kabur tanpa busana.", 50),
             ("kecil", "Hanya ada di Injil Markus.")],
            [("label", "Ayatnya"),
             ("kutip", "“Ada seorang muda, yang pada waktu itu hanya memakai sehelai kain lenan untuk menutup badannya, mengikuti Dia. Mereka hendak menangkapnya, tetapi ia melepaskan kainnya dan lari dengan telanjang.”"),
             ("ref", "Markus 14:51-52")],
            [("label", "Siapa dia?"),
             ("teks", "Alkitab tidak menyebut namanya. Tapi banyak penafsir sejak zaman dulu menduga itu Markus sendiri, penulis Injil ini, yang diam-diam ‘menandatangani’ kisahnya."),
             ("kecil", "(Ini tafsiran, bukan isi ayat.)")],
            [("label", "Kalau benar itu Markus…"),
             ("teks", "Belakangan Markus juga pernah meninggalkan Paulus di tengah pelayanan (Kis 13:13). Tapi di akhir hidupnya, Paulus menulis:"),
             ("kutip", "“Jemputlah Markus dan bawalah ia kemari, karena pelayanannya penting bagiku.”"), ("ref", "2 Timotius 4:11")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Orang yang pernah lari tetap bisa dipakai Tuhan."),
             ("poin", "2.  Kegagalanmu yang paling memalukan bukan akhir ceritamu."),
             ("poin", "3.  Orang yang ‘kabur’ itu akhirnya menulis kisah Yesus yang kita baca sampai sekarang.")],
            [("judul", "Pernah lari dari Tuhan?", 0), ("judul2", "Pintunya masih terbuka.", 40),
             ("kecil", "Save & kirim ke seseorang yang merasa sudah terlalu jauh.")],
        ],
        "caption": "Ada satu detail aneh di malam Yesus ditangkap yang jarang dibahas 😶\n\nMarkus 14:51-52. Seorang pemuda mengikuti Yesus hanya dengan sehelai kain lenan. Saat hendak ditangkap, ia melepaskan kainnya dan lari telanjang. Banyak penafsir menduga pemuda itu adalah Markus sendiri, penulis Injil ini.\n\nKalau benar, orang yang pernah kabur itu akhirnya menulis kisah Yesus untuk kita semua.\n\nMenurutmu, kenapa detail ini dicatat di Alkitab? Tulis pendapatmu 👇\n\nFollow untuk ayat-ayat lain yang jarang dibahas 📜",
    },
    {   # 6 — Yesus menulis di tanah
        "tema": "debu",
        "slides": [
            [("judul", "Satu-satunya catatan", 0), ("judul", "Yesus menulis…", 30), ("judul2", "dan kita tidak tahu apa yang Ia tulis.", 50),
             ("kecil", "Yohanes 8.")],
            [("label", "Konteksnya"), ("teks", "Orang-orang membawa seorang perempuan yang kedapatan berzinah. Mereka menunggu Yesus mengizinkan hukuman rajam."),
             ("kutip", "“Tetapi Yesus membungkuk lalu menulis dengan jari-Nya di tanah.”"), ("ref", "Yohanes 8:6")],
            [("label", "Lalu Ia berdiri dan berkata"),
             ("kutip", "“Barangsiapa di antara kamu tidak berdosa, hendaklah ia yang pertama melemparkan batu kepada perempuan itu.”"),
             ("ref", "Yohanes 8:7", 30),
             ("kutip_kecil", "“Lalu Ia membungkuk pula dan menulis di tanah.”"), ("ref", "Yohanes 8:8")],
            [("label", "Apa yang Yesus tulis?"),
             ("teks", "Alkitab tidak memberi tahu. Ada yang menduga dosa-dosa para penuduh, ada yang menduga ayat Taurat. Tapi hasilnya jelas: satu per satu, mereka pergi."),
             ("kecil", "(Dugaan-dugaan ini tafsiran, bukan isi ayat.)")],
            [("sub", "Yang pasti tertulis", 30),
             ("kutip", "“Aku pun tidak menghukum engkau. Pergilah, dan jangan berbuat dosa lagi mulai dari sekarang.”"), ("ref", "Yohanes 8:11", 30),
             ("teks", "Anugerah dan kebenaran, dalam satu kalimat.")],
            [("judul", "Batu apa yang sedang kamu genggam", 0), ("judul2", "untuk orang lain?", 40),
             ("kecil", "Renungkan, lalu kirim ke temanmu.")],
        ],
        "caption": "Ini satu-satunya catatan di Injil tentang Yesus menulis sesuatu. Dan kita tidak tahu apa yang Ia tulis ✍️\n\nYohanes 8:6-11. Saat orang-orang siap merajam seorang perempuan, Yesus membungkuk dan menulis di tanah. Setelah satu kalimat dari-Nya, para penuduh pergi satu per satu.\n\nApa pun yang Ia tulis, yang pasti tercatat adalah kalimat terakhirnya: “Aku pun tidak menghukum engkau. Pergilah, dan jangan berbuat dosa lagi.”\n\nMenurutmu, Yesus menulis apa? Tulis tebakanmu 👇\n\nFollow untuk ayat-ayat lain yang jarang dibahas 📜",
    },
    {   # 7 — Yohanes 21:25
        "tema": "perkamen",
        "slides": [
            [("judul", "Ayat terakhir Injil Yohanes", 0), ("judul", "menyimpan fakta", 30), ("judul2", "yang jarang kita pikirkan.", 50),
             ("kecil", "Yohanes 21:25.")],
            [("label", "Ayatnya"),
             ("kutip", "“Masih banyak hal-hal lain lagi yang diperbuat oleh Yesus, tetapi jikalau semuanya itu harus dituliskan satu per satu, maka agaknya dunia ini tidak dapat memuat semua kitab yang harus ditulis itu.”"),
             ("ref", "Yohanes 21:25")],
            [("label", "Artinya"),
             ("teks", "Semua yang kita baca di keempat Injil hanyalah sebagian kecil dari apa yang Yesus lakukan. Ada mujizat, percakapan, dan kebaikan yang tidak pernah dicatat.")],
            [("label", "Lalu kenapa yang ini dicatat?"),
             ("kutip", "“…tetapi semua yang tercantum di sini telah dicatat, supaya kamu percaya, bahwa Yesuslah Mesias, Anak Allah, dan supaya kamu oleh imanmu memperoleh hidup dalam nama-Nya.”"),
             ("ref", "Yohanes 20:31")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Yang tertulis sudah cukup untuk kita percaya."),
             ("poin", "2.  Tuhan juga melakukan banyak hal dalam hidupmu yang tidak kamu sadari."),
             ("poin", "3.  Ceritanya belum selesai. Dia masih bekerja sampai hari ini.")],
            [("judul", "Sudah 7 kisah kita bahas.", 0), ("judul2", "Mana favoritmu?", 40),
             ("kecil", "Tulis nomornya di komentar (1–7). Berikutnya: seri Yunus, 14 bagian.")],
        ],
        "caption": "Ayat penutup Injil Yohanes bilang: kalau semua yang Yesus lakukan ditulis, dunia tidak akan cukup untuk menampung bukunya 📚\n\nYohanes 21:25. Yang kita baca di Alkitab hanyalah sebagian. Tapi Yohanes 20:31 menjelaskan: yang tertulis sudah cukup, supaya kita percaya.\n\nKita sudah bahas 7 kisah yang jarang diangkat: Eutikhus, Elia, Hagar, keledai Bileam, pemuda yang kabur, Yesus menulis di tanah, dan ayat ini.\n\nMana yang paling berkesan? Tulis nomornya 1–7 👇\n\nBerikutnya: seri Yunus, 14 bagian. Follow supaya tidak ketinggalan 📜",
    },
]
