"""@ayat.tersembunyi - minggu 3: seri YUNUS bagian 2 (pasal 2-4, "Kesempatan kedua"). Post #15-#21.
Bahan: presentasi "Merpati yang Melarikan Diri" (Yunus-FreeShow.html). Kutipan ayat: Alkitab TB."""

TAGS = "#yunus #kitabyunus #ayatalkitab #faktaalkitab #alkitab #kristenindonesia #ayattersembunyi"
NOMOR_AWAL = 15

POSTS = [
    {   # 15 — diantar ke darat
        "tema": "badai",
        "slides": [
            [("judul", "Yunus tidak berenang", 0), ("judul", "ke pantai.", 30), ("judul2", "Ia diantar.", 50),
             ("kecil", "Seri Yunus · bagian 8")],
            [("label", "Ayatnya"),
             ("kutip", "“Lalu berfirmanlah TUHAN kepada ikan itu, dan ikan itupun memuntahkan Yunus ke darat.”"),
             ("ref", "Yunus 2:10", 30), ("teks", "Tuhan berfirman kepada seekor ikan, dan ikan itu taat. Lebih cepat daripada nabinya.")],
            [("label", "Detail yang sering terlewat"),
             ("teks", "Yunus tidak menyelamatkan dirinya sendiri. Ia tidak berenang, tidak berjuang, tidak menemukan jalan keluar."),
             ("teks", "Ia dibawa ke darat. Dan ‘dimuntahkan’ jelas bukan cara yang anggun.")],
            [("label", "Setelah doanya"),
             ("teks", "Ayat ini datang tepat setelah Yunus berseru, “Keselamatan adalah dari TUHAN!”"),
             ("ref", "Yunus 2:9", 30), ("teks", "Pemulihan dimulai ketika kita berhenti mengandalkan diri sendiri.")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Kita tidak harus ‘berenang’ keluar dari masalah sendirian."),
             ("poin", "2.  Cara Tuhan memulihkan tidak selalu rapi. Tapi Ia memulihkan."),
             ("poin", "3.  Seluruh ciptaan taat kepada-Nya, termasuk laut dan ikan.")],
            [("judul", "Pemulihanmu mungkin tidak rapi.", 0), ("judul2", "Tapi Tuhan yang mengantarmu.", 40),
             ("kecil", "Bagian kedua seri Yunus dimulai. Follow supaya tidak ketinggalan.")],
        ],
        "caption": "Yunus tidak berenang ke pantai. Ia diantar… dengan cara yang tidak anggun sama sekali 😅\n\nYunus 2:10: “Lalu berfirmanlah TUHAN kepada ikan itu, dan ikan itupun memuntahkan Yunus ke darat.” Tuhan berfirman, ikan itu taat. Dan ini terjadi tepat setelah Yunus berseru, “Keselamatan adalah dari TUHAN!”\n\nPemulihan dari Tuhan tidak selalu rapi, tapi selalu nyata.\n\nPernah dipulihkan Tuhan dengan cara yang tidak kamu duga? Cerita di komentar 👇\n\nSeri Yunus bagian 8/14 📜",
    },
    {   # 16 — untuk kedua kalinya
        "tema": "perkamen",
        "slides": [
            [("judul", "Tiga kata di Yunus 3:1", 0), ("judul", "yang mungkin paling", 30), ("judul2", "menghibur di kitab ini.", 50),
             ("kecil", "Seri Yunus · bagian 9")],
            [("label", "Ayatnya"),
             ("kutip", "“Datanglah firman TUHAN kepada Yunus untuk kedua kalinya, demikian: ‘Bangunlah, pergilah ke Niniwe, kota yang besar itu…’”"),
             ("ref", "Yunus 3:1-2", 30), ("sub", "“untuk kedua kalinya”")],
            [("label", "Perintah yang sama"),
             ("teks", "Tuhan tidak mengganti tugasnya dengan yang lebih mudah. Tidak ada ceramah panjang tentang kegagalan Yunus."),
             ("teks", "Hanya panggilan yang sama, diberikan sekali lagi.")],
            [("label", "Dan kali ini"),
             ("kutip", "“Bersiaplah Yunus, lalu pergi ke Niniwe, sesuai dengan firman Allah.”"),
             ("ref", "Yunus 3:3")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Kegagalanmu tidak membatalkan panggilanmu."),
             ("poin", "2.  Tuhan adalah Allah kesempatan kedua, dan ketiga, dan seterusnya."),
             ("poin", "3.  Kesempatan kedua bukan untuk ditunda lagi. Yunus kali ini pergi.")],
            [("judul", "Tuhan belum selesai denganmu.", 0), ("judul2", "Ini kesempatan keduamu.", 40),
             ("kecil", "Kirim ke seseorang yang merasa sudah gagal terlalu jauh.")],
        ],
        "caption": "Tiga kata di Yunus 3:1 yang mungkin paling menghibur di seluruh kitab: “untuk kedua kalinya” 🤍\n\nSetelah lari, badai, dan perut ikan, Tuhan tidak memberi Yunus tugas yang lebih ringan dan tidak menceramahinya. Ia memberikan panggilan yang sama, sekali lagi. Dan kali ini Yunus pergi.\n\nKegagalanmu tidak membatalkan panggilanmu.\n\nKetik “KEDUA” kalau kamu sedang butuh kesempatan kedua dari Tuhan. Kita doakan bersama.\n\nSeri Yunus bagian 9/14 📜",
    },
    {   # 17 — latar budaya Niniwe & ikan
        "tema": "plum",
        "slides": [
            [("judul", "Kenapa satu kota kafir", 0), ("judul", "mau mendengarkan", 30), ("judul2", "nabi dari negeri musuh?", 50),
             ("kecil", "Seri Yunus · bagian 10 · latar sejarah")],
            [("label", "Satu petunjuk dari Yesus"),
             ("kutip", "“Sebab seperti Yunus menjadi tanda untuk orang-orang Niniwe, demikian pulalah Anak Manusia akan menjadi tanda untuk angkatan ini.”"),
             ("ref", "Lukas 11:30", 30), ("teks", "Yunus sendiri menjadi ‘tanda’ bagi orang Niniwe.")],
            [("label", "Latar budaya Asyur"),
             ("teks", "Relief di istana-istana Asyur menggambarkan sosok bijak berjubah kulit ikan. Dan tanda tulisan paku untuk nama Niniwe menyerupai ikan di dalam sebuah bangunan."),
             ("kecil", "(Temuan arkeologi & latar sejarah)")],
            [("label", "Dugaan sebagian penafsir"),
             ("teks", "Bayangkan seorang nabi datang dengan kisah ‘keluar dari perut ikan’, ke kota yang budayanya lekat dengan simbol ikan. Pesannya pasti didengar."),
             ("kecil", "(Ini dugaan dan tafsiran, bukan isi ayat.)")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Tuhan mengenal budaya orang yang ingin Ia jangkau."),
             ("poin", "2.  Pengalaman terburukmu bisa menjadi kesaksian yang paling didengar."),
             ("poin", "3.  Tanda yang lebih besar dari Yunus adalah Yesus sendiri.")],
            [("judul", "Kisah ‘perut ikan’mu", 0), ("judul2", "bisa jadi pintu untuk orang lain.", 40),
             ("kecil", "Save & kirim ke temanmu yang suka sejarah Alkitab.")],
        ],
        "caption": "Kenapa satu kota kafir yang kejam mau mendengarkan nabi dari negeri musuhnya? 🤔\n\nYesus berkata Yunus menjadi “tanda” untuk orang Niniwe (Lukas 11:30). Menariknya, relief di istana Asyur menggambarkan sosok bijak berjubah kulit ikan, dan tanda tulisan paku untuk nama Niniwe menyerupai ikan di dalam bangunan.\n\nSebagian penafsir menduga: seorang nabi yang “keluar dari perut ikan” akan sangat didengar di kota seperti itu. (Ini tafsiran, bukan isi ayat, tapi latarnya menarik untuk direnungkan.)\n\nSuka konten sejarah Alkitab seperti ini? Ketik 📜 dan kami buat lebih banyak.\n\nSeri Yunus bagian 10/14",
    },
    {   # 18 — khotbah satu kalimat
        "tema": "debu",
        "slides": [
            [("judul", "Khotbahnya hanya", 0), ("judul", "satu kalimat.", 30), ("judul2", "Satu kota bertobat.", 50),
             ("kecil", "Seri Yunus · bagian 11")],
            [("label", "Isi khotbah Yunus"),
             ("kutip", "“Empat puluh hari lagi, maka Niniwe akan ditunggangbalikkan.”"),
             ("ref", "Yunus 3:4", 30),
             ("teks", "Dalam bahasa Ibrani hanya 5 kata. Tanpa ajakan, tanpa janji pengampunan.")],
            [("label", "Responsnya"),
             ("kutip", "“Orang Niniwe percaya kepada Allah, lalu mereka mengumumkan puasa dan mereka, baik orang dewasa maupun anak-anak, mengenakan kain kabung.”"),
             ("ref", "Yunus 3:5")],
            [("label", "Bahkan rajanya"),
             ("kutip", "“…turunlah ia dari singgasananya, ditanggalkannya jubahnya, diselubungkannya kain kabung, lalu duduklah ia di abu.”"),
             ("ref", "Yunus 3:6", 30),
             ("kutip_kecil", "“…maka menyesallah Allah karena malapetaka yang telah dirancangkan-Nya terhadap mereka, dan Iapun tidak jadi melakukannya.”"),
             ("ref", "Yunus 3:10")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Yang mengubah hati bukan kefasihan pengkhotbah, tapi Tuhan."),
             ("poin", "2.  Tidak ada orang atau kota yang terlalu jahat untuk bertobat."),
             ("poin", "3.  Tuhan jauh lebih ingin mengampuni daripada menghukum.")],
            [("judul", "Tapi kisah ini belum selesai.", 0), ("judul2", "Coba tebak reaksi Yunus…", 40),
             ("kecil", "Tulis tebakanmu. Jawabannya di post berikutnya.")],
        ],
        "caption": "Mungkin khotbah paling singkat di Alkitab: “Empat puluh hari lagi, maka Niniwe akan ditunggangbalikkan.” Dalam bahasa Ibrani hanya 5 kata 😮\n\nTanpa ajakan, tanpa janji pengampunan. Tapi seluruh kota percaya kepada Allah, dari anak-anak sampai rajanya yang turun dari takhta dan duduk di abu. Dan Tuhan tidak jadi mendatangkan malapetaka (Yunus 3:4-10).\n\nYang mengubah hati bukan kefasihan pengkhotbah, tapi Tuhan.\n\nMenurutmu, Yunus senang atau marah melihat ini? Tebak di komentar 👇 Jawabannya di post berikutnya.\n\nSeri Yunus bagian 11/14 📜",
    },
    {   # 19 — kota bertobat, nabinya marah
        "tema": "malam",
        "slides": [
            [("judul", "Kotanya bertobat.", 0), ("judul", "Nabinya marah.", 30), ("judul2", "Sampai ingin mati.", 50),
             ("kecil", "Seri Yunus · bagian 12")],
            [("label", "Reaksi Yunus"),
             ("kutip", "“Tetapi hal itu sangat mengesalkan hati Yunus, lalu marahlah ia.”"),
             ("ref", "Yunus 4:1", 30),
             ("teks", "Kebangunan rohani terbesar dalam kisah para nabi, dan nabinya kesal.")],
            [("label", "Sifat Tuhan dijadikan keluhan"),
             ("kutip", "“…sebab aku tahu, bahwa Engkaulah Allah yang pengasih dan penyayang, yang panjang sabar dan berlimpah kasih setia…”"),
             ("ref", "Yunus 4:2", 30),
             ("teks", "Kalimat pujian yang indah, diucapkan Yunus sebagai protes.")],
            [("label", "Lalu Tuhan bertanya"),
             ("kutip", "“Jadi sekarang, ya TUHAN, cabutlah kiranya nyawaku, karena lebih baik aku mati dari pada hidup.”"),
             ("ref", "Yunus 4:3", 30),
             ("kutip", "“Tetapi firman TUHAN: ‘Layakkah engkau marah?’”"), ("ref", "Yunus 4:4")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Kita bisa taat secara lahiriah, tapi hati masih belum berubah."),
             ("poin", "2.  Kasih karunia terasa indah untuk kita, tapi sulit diterima untuk orang lain."),
             ("poin", "3.  Tuhan tetap sabar, bahkan terhadap nabi yang marah kepada-Nya.")],
            [("judul", "“Layakkah engkau marah?”", 0), ("judul2", "Pertanyaan itu untuk kita juga.", 40),
             ("kecil", "Renungkan dengan jujur. Save untuk dibaca lagi.")],
        ],
        "caption": "Kotanya bertobat. Nabinya marah. Sampai minta mati 😶\n\nYunus 4:1-4. Setelah seluruh Niniwe bertobat, Yunus justru kesal. Ia mengutip sifat Tuhan yang paling indah, “pengasih dan penyayang, panjang sabar dan berlimpah kasih setia”, sebagai keluhan.\n\nDan Tuhan dengan lembut bertanya: “Layakkah engkau marah?”\n\nPernah sulit menerima ketika Tuhan memberkati orang yang menurutmu tidak layak? Kamu tidak sendirian.\n\nSeri Yunus bagian 12/14 📜",
    },
    {   # 20 — pohon jarak, ulat, angin timur
        "tema": "jalan",
        "slides": [
            [("judul", "Frasa yang sama muncul", 0), ("judul", "4 kali di kitab Yunus.", 30), ("judul2", "Hampir tidak ada yang sadar.", 50),
             ("kecil", "Seri Yunus · bagian 13")],
            [("sub", "“Atas penentuan TUHAN…”", 30),
             ("poin", "1.  …datanglah seekor ikan besar (1:17)"),
             ("poin", "2.  …tumbuhlah sebatang pohon jarak (4:6)"),
             ("poin", "3.  …datanglah seekor ulat (4:7)"),
             ("poin", "4.  …bertiuplah angin timur yang panas terik (4:8)")],
            [("label", "Pohon yang menaungi"),
             ("kutip", "“Lalu atas penentuan TUHAN Allah tumbuhlah sebatang pohon jarak melampaui kepala Yunus untuk menaunginya… Yunus sangat bersukacita karena pohon jarak itu.”"),
             ("ref", "Yunus 4:6", 30), ("teks", "Satu-satunya saat Yunus bersukacita di seluruh kitab.")],
            [("label", "Lalu pelajarannya"),
             ("kutip", "“Engkau sayang kepada pohon jarak itu, yang untuknya sedikitpun engkau tidak berjerih payah dan yang tidak engkau tumbuhkan…”"),
             ("ref", "Yunus 4:10", 30),
             ("teks", "Yunus menangisi sebatang pohon, tapi tidak peduli pada satu kota penuh manusia.")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Tuhan memakai hal kecil (ulat, angin, pohon) untuk mengajar hati kita."),
             ("poin", "2.  Hal yang menyenangkan dan hal yang mengecewakan bisa sama-sama ‘atas penentuan Tuhan’."),
             ("poin", "3.  Hati kita sering lebih sayang pada kenyamanan daripada pada jiwa orang lain.")],
            [("judul", "“Pohon jarak” apa", 0), ("judul2", "yang paling kamu sayangi?", 40),
             ("kecil", "Renungkan. Berikutnya: ending kitab Yunus yang tidak biasa.")],
        ],
        "caption": "Ada satu frasa yang muncul 4 kali di kitab Yunus dan jarang disadari: “atas penentuan TUHAN” 🌿\n\nAtas penentuan TUHAN datanglah ikan (1:17), tumbuhlah pohon jarak (4:6), datanglah seekor ulat (4:7), dan bertiuplah angin timur (4:8). Yang menyelamatkan, yang menghibur, dan yang mengecewakan, semuanya ada di tangan-Nya.\n\nLalu Tuhan menunjukkan isi hati Yunus: ia menangisi sebatang pohon, tapi tidak peduli pada satu kota penuh manusia (4:10).\n\n“Pohon jarak” apa yang paling kamu sayangi sekarang? Jawab dalam hati, atau tulis di komentar.\n\nSeri Yunus bagian 13/14 📜",
    },
    {   # 21 — akhir yang terbuka & yang lebih besar dari Yunus
        "tema": "laut",
        "slides": [
            [("judul", "Kitab Yunus", 0), ("judul", "tidak berakhir dengan jawaban.", 30), ("judul2", "Tapi dengan pertanyaan.", 50),
             ("kecil", "Seri Yunus · bagian 14 (terakhir)")],
            [("label", "Ayat terakhirnya"),
             ("kutip", "“Bagaimana tidak Aku akan sayang kepada Niniwe, kota yang besar itu, yang berpenduduk lebih dari seratus dua puluh ribu orang, yang semuanya tak tahu membedakan tangan kanan dari tangan kiri, dengan ternaknya yang banyak?”"),
             ("ref", "Yunus 4:11")],
            [("label", "Jawaban Yunus?"),
             ("teks", "Tidak pernah ditulis. Kitabnya berhenti di sini."),
             ("teks", "Seolah pertanyaan itu sekarang diarahkan kepada kita yang membacanya.")],
            [("label", "Yesus menyebut ‘tanda nabi Yunus’"),
             ("kutip", "“Sebab seperti Yunus tinggal di dalam perut ikan tiga hari tiga malam, demikian juga Anak Manusia akan tinggal di dalam rahim bumi tiga hari tiga malam.”"),
             ("ref", "Matius 12:40", 30),
             ("kutip_kecil", "“…dan sesungguhnya yang ada di sini lebih dari pada Yunus!”"), ("ref", "Matius 12:41")],
            [("sub", "Yunus dan Yesus", 30),
             ("poin", "1.  Yunus dilempar ke laut. Yesus menyerahkan diri-Nya."),
             ("poin", "2.  Yunus tiga hari di perut ikan. Yesus tiga hari di kubur, lalu bangkit."),
             ("poin", "3.  Yunus menangisi pohon. Yesus menangisi kota Yerusalem."),
             ("poin", "4.  Yunus lari dari musuhnya. Yesus mati untuk musuh-musuh-Nya.")],
            [("judul", "Seri Yunus selesai.", 0), ("judul2", "Bagian mana yang paling kena?", 40),
             ("kecil", "Tulis nomornya (1–14). Kitab apa yang harus kita bahas berikutnya?")],
        ],
        "caption": "Kitab Yunus tidak berakhir dengan jawaban, tapi dengan pertanyaan dari Tuhan. Dan jawaban Yunus tidak pernah ditulis 🌊\n\nYunus 4:11: “Bagaimana tidak Aku akan sayang kepada Niniwe…?” Seolah pertanyaan itu kini diarahkan kepada kita.\n\nLalu Yesus menyebut “tanda nabi Yunus” (Matius 12:39-41): tiga hari di perut ikan, tiga hari di rahim bumi. Dan “yang ada di sini lebih dari pada Yunus.” Yunus lari dari musuhnya; Yesus mati untuk musuh-musuh-Nya.\n\nSeri Yunus selesai! Bagian mana yang paling berkesan untukmu (1–14)? Dan kitab apa yang harus kita bahas berikutnya? 👇\n\nTerima kasih sudah mengikuti seri ini 📜",
    },
]
