"""@ayat.tersembunyi - minggu 2: seri YUNUS bagian 1 (pasal 1-2, "Pelarian"). Post #08-#14.
Bahan: presentasi "Merpati yang Melarikan Diri" (Yunus-FreeShow.html). Kutipan ayat: Alkitab TB.
Jenis slide khusus: ("peta",) = diagram arah Tarsis-Yafo-Niniwe, ("tangga", teks) = baris menurun bertingkat."""

TAGS = "#yunus #kitabyunus #ayatalkitab #faktaalkitab #alkitab #kristenindonesia #ayattersembunyi"
NOMOR_AWAL = 8

POSTS = [
    {   # 8 — Yunus nabi yang sukses
        "tema": "laut",
        "slides": [
            [("judul", "Sebelum ditelan ikan,", 0), ("judul", "Yunus adalah nabi", 30), ("judul2", "yang nubuatnya digenapi.", 50),
             ("kecil", "Seri Yunus · bagian 1 dari 14")],
            [("label", "Dari mana Yunus?"), ("teks", "Yunus bin Amitai, dari Gat-Hefer di Galilea. Letaknya hanya sekitar 5 km dari Nazaret, kota tempat Yesus dibesarkan berabad-abad kemudian.")],
            [("label", "Nabi yang dipakai Tuhan"),
             ("kutip", "“…sesuai dengan firman TUHAN, Allah Israel, yang diucapkan-Nya dengan perantaraan hamba-Nya, nabi Yunus bin Amitai, dari Gat-Hefer.”"),
             ("ref", "2 Raja-raja 14:25", 30), ("teks", "Di zaman Raja Yerobeam II, nubuat Yunus tentang pemulihan wilayah Israel benar-benar terjadi.")],
            [("label", "Lalu datang perintah baru"),
             ("kutip", "“Bangunlah, pergilah ke Niniwe, kota yang besar itu, berserulah terhadap mereka, karena kejahatannya telah sampai kepada-Ku.”"),
             ("ref", "Yunus 1:2", 30), ("teks", "Tiga kata kerja: bangunlah, pergilah, berserulah.")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Dipakai Tuhan kemarin tidak menjamin taat hari ini."),
             ("poin", "2.  Tugas yang paling sulit sering datang setelah keberhasilan."),
             ("poin", "3.  Nabi yang hebat pun bisa memilih lari.")],
            [("judul", "Kenapa nabi sesukses ini", 0), ("judul2", "memilih kabur?", 40),
             ("kecil", "Besok kita bahas. Follow supaya tidak ketinggalan seri Yunus.")],
        ],
        "caption": "Semua orang tahu Yunus ditelan ikan. Tapi jarang yang tahu: sebelumnya ia adalah nabi yang sukses 🌊\n\n2 Raja-raja 14:25 mencatat nubuat Yunus bin Amitai yang digenapi di zaman Raja Yerobeam II. Ia berasal dari Gat-Hefer, hanya beberapa kilometer dari Nazaret.\n\nLalu datang perintah baru: pergi ke Niniwe. Dan nabi yang sukses ini memilih lari.\n\nKenapa? Tebak dulu di komentar 👇 Jawabannya besok.\n\nIni bagian 1 dari seri Yunus (14 post). Follow supaya tidak ketinggalan 📜",
    },
    {   # 9 — takut berhasil
        "tema": "debu",
        "slides": [
            [("judul", "Yunus tidak lari", 0), ("judul", "karena takut gagal.", 30), ("judul2", "Ia takut berhasil.", 50),
             ("kecil", "Seri Yunus · bagian 2")],
            [("label", "Siapa Niniwe?"), ("teks", "Ibu kota Asyur, kerajaan yang terkenal kejam dalam perang. Bagi Israel, Asyur adalah musuh dan ancaman nyata."),
             ("kecil", "(Latar sejarah)")],
            [("label", "Alasan Yunus, dari mulutnya sendiri"),
             ("kutip", "“Itulah sebabnya, maka aku dahulu melarikan diri ke Tarsis, sebab aku tahu, bahwa Engkaulah Allah yang pengasih dan penyayang, yang panjang sabar dan berlimpah kasih setia…”"),
             ("ref", "Yunus 4:2")],
            [("label", "Artinya"),
             ("teks", "Yunus tahu: kalau Niniwe bertobat, Tuhan pasti mengampuni mereka. Dan itulah yang tidak bisa ia terima."),
             ("teks", "Kasih Tuhan bertabrakan dengan rasa adilnya sendiri.")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Kadang kita menolak taat bukan karena takut, tapi karena tidak setuju dengan kasih Tuhan."),
             ("poin", "2.  Tuhan mengasihi orang yang kita anggap tidak layak."),
             ("poin", "3.  Mengenal sifat Tuhan tidak sama dengan setuju dengan cara-Nya.")],
            [("judul", "Siapa “Niniwe”", 0), ("judul2", "dalam hidupmu?", 40),
             ("kecil", "Orang yang sulit kamu harapkan diampuni Tuhan. Jawab dalam hati, lalu kirim ke temanmu.")],
        ],
        "caption": "Yunus tidak lari karena takut gagal. Ia lari karena takut BERHASIL 😶\n\nNiniwe adalah ibu kota Asyur, musuh Israel yang terkenal kejam. Di Yunus 4:2 ia sendiri mengaku: “aku tahu, bahwa Engkaulah Allah yang pengasih dan penyayang.” Ia tahu, kalau Niniwe bertobat, Tuhan akan mengampuni. Dan itu yang tidak bisa ia terima.\n\nPernah merasa berat melihat orang yang menyakitimu diberkati? Kamu tidak sendirian.\n\nSeri Yunus bagian 2/14. Save & follow 📜",
    },
    {   # 10 — 180 derajat dan membayar tiket
        "tema": "malam",
        "slides": [
            [("judul", "Disuruh ke timur,", 0), ("judul", "ia berlayar ke barat.", 30), ("judul2", "Dan ia membayar tiketnya sendiri.", 50),
             ("kecil", "Seri Yunus · bagian 3")],
            [("peta", "")],
            [("label", "Ayatnya"),
             ("kutip", "“Tetapi Yunus bersiap untuk melarikan diri ke Tarsis, jauh dari hadapan TUHAN; ia pergi ke Yafo dan mendapat di sana sebuah kapal, yang akan berangkat ke Tarsis. Ia membayar biaya perjalanannya…”"),
             ("ref", "Yunus 1:3")],
            [("label", "Bukan tersesat. Disengaja."),
             ("teks", "Niniwe ada di timur, sekitar 900 km lewat darat. Tarsis ada di barat, di ujung dunia yang dikenal saat itu (kemungkinan di Spanyol)."),
             ("teks", "Arahnya berlawanan 180 derajat.")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Lari dari Tuhan selalu ada harganya, dan kita sendiri yang membayarnya."),
             ("poin", "2.  Kapal ke arah yang salah bisa saja tersedia. Pintu terbuka belum tentu kehendak Tuhan."),
             ("poin", "3.  Sejauh apa pun kita pergi, kita tidak pernah benar-benar jauh dari hadapan-Nya.")],
            [("judul", "Tiket apa yang sedang", 0), ("judul2", "kamu bayar untuk lari?", 40),
             ("kecil", "Renungkan. Besok: kata Ibrani yang terus berulang di kisah ini.")],
        ],
        "caption": "Tuhan menyuruh Yunus ke timur. Yunus naik kapal ke barat. Dan ia membayar tiketnya sendiri 🧭\n\nYunus 1:3. Niniwe di timur, Tarsis di ujung barat. Arahnya berlawanan 180 derajat. Ini bukan tersesat, tapi keputusan sadar.\n\nDetail kecil yang sering terlewat: “Ia membayar biaya perjalanannya.” Lari dari Tuhan selalu ada harganya.\n\nPernah melihat “pintu terbuka” yang ternyata ke arah yang salah? Cerita di komentar 👇\n\nSeri Yunus bagian 3/14 📜",
    },
    {   # 11 — turun, turun, turun
        "tema": "gurun",
        "slides": [
            [("judul", "Ada satu kata Ibrani", 0), ("judul", "yang terus berulang", 30), ("judul2", "di kisah Yunus: turun.", 50),
             ("kecil", "Seri Yunus · bagian 4")],
            [("label", "Dalam bahasa Ibrani: yarad (turun)", 30),
             ("tangga", "ke Yafo (1:3)"), ("tangga", "ke ruang kapal paling bawah (1:5)"), ("tangga", "sampai ke dasar gunung-gunung (2:6)")],
            [("label", "Turun ke ruang kapal"),
             ("kutip", "“Tetapi Yunus telah turun ke dalam ruang kapal yang paling bawah dan berbaring di situ, lalu tertidur dengan nyenyak.”"),
             ("ref", "Yunus 1:5", 30),
             ("kecil", "Di TB, kata yang sama diterjemahkan ‘pergi’ (1:3), ‘turun’ (1:5), dan ‘tenggelam’ (2:6).")],
            [("label", "Sampai titik paling bawah… lalu"),
             ("kutip", "“Aku tenggelam sampai ke dasar gunung-gunung… Ketika itulah Engkau naikkan nyawaku dari dalam liang kubur, ya TUHAN, Allahku.”"),
             ("ref", "Yunus 2:6")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Menjauh dari Tuhan jarang terjadi sekaligus. Biasanya turun sedikit demi sedikit."),
             ("poin", "2.  Titik terendahmu bukan tempat yang terlalu dalam untuk Tuhan."),
             ("poin", "3.  Kita yang turun. Dia yang menaikkan.")],
            [("judul", "Kamu sedang di anak tangga", 0), ("judul2", "yang mana?", 40),
             ("kecil", "Tidak apa-apa. Dia sanggup menaikkanmu. Save ini.")],
        ],
        "caption": "Satu kata Ibrani yang terus muncul di kisah Yunus: yarad, artinya TURUN ⬇️\n\nTurun ke Yafo (1:3). Turun ke ruang kapal paling bawah (1:5). Tenggelam ke dasar gunung-gunung (2:6). Di Alkitab bahasa Indonesia kata ini diterjemahkan berbeda-beda, jadi polanya jarang disadari.\n\nTapi lihat akhir Yunus 2:6: “Ketika itulah Engkau naikkan nyawaku.” Kita yang turun, Dia yang menaikkan.\n\nKetik ⬆️ kalau kamu percaya Tuhan sanggup menaikkanmu.\n\nSeri Yunus bagian 4/14 📜",
    },
    {   # 12 — pelaut berdoa, nabi tidur
        "tema": "badai",
        "slides": [
            [("judul", "Saat badai datang,", 0), ("judul", "para pelaut kafir berdoa.", 30), ("judul2", "Sang nabi tertidur.", 50),
             ("kecil", "Seri Yunus · bagian 5")],
            [("label", "Badai itu bukan kebetulan"),
             ("kutip", "“Tetapi TUHAN menurunkan angin ribut ke laut, lalu terjadilah badai besar, sehingga kapal itu hampir-hampir terpukul hancur.”"),
             ("ref", "Yunus 1:4", 30), ("teks", "Tuhan tidak melepaskan Yunus. Ia mengejarnya.")],
            [("label", "Di atas dek dan di bawah"),
             ("kutip", "“Awak kapal menjadi takut, masing-masing berteriak-teriak kepada allahnya… Tetapi Yunus telah turun ke dalam ruang kapal yang paling bawah… lalu tertidur dengan nyenyak.”"),
             ("ref", "Yunus 1:5")],
            [("label", "Nakhoda membangunkan nabi"),
             ("kutip", "“Bagaimana mungkin engkau tidur begitu nyenyak? Bangunlah, berserulah kepada Allahmu…”"),
             ("ref", "Yunus 1:6", 30),
             ("teks", "Ironisnya, di akhir pasal ini justru para pelaut itu yang takut kepada TUHAN dan mempersembahkan korban (1:16).")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Orang yang belum mengenal Tuhan kadang lebih peka daripada kita."),
             ("poin", "2.  Tuhan tetap bekerja, bahkan lewat orang yang sedang lari dari-Nya."),
             ("poin", "3.  Badai bisa jadi cara Tuhan membangunkan kita.")],
            [("judul", "Kalau hari ini ada badai,", 0), ("judul2", "mungkin Tuhan sedang membangunkanmu.", 40),
             ("kecil", "Kirim ke temanmu yang lagi di tengah badai.")],
        ],
        "caption": "Salah satu ironi paling tajam di Alkitab: para pelaut kafir berdoa, sang nabi Allah tertidur nyenyak ⛈️\n\nYunus 1:4-16. Tuhan mengirim badai. Awak kapal berteriak kepada allah mereka, sementara Yunus tidur di ruang kapal paling bawah. Nakhoda kafir yang harus membangunkan nabi untuk berdoa.\n\nDan di akhir pasal, justru para pelaut itu yang takut akan TUHAN.\n\nPernah “dibangunkan” Tuhan lewat orang yang tidak kamu sangka? Cerita di komentar 👇\n\nSeri Yunus bagian 5/14 📜",
    },
    {   # 13 — ikan: penyelamatan
        "tema": "jalan",
        "slides": [
            [("judul", "Ikan besar itu", 0), ("judul", "bukan hukuman.", 30), ("judul2", "Itu penyelamatan.", 50),
             ("kecil", "Seri Yunus · bagian 6")],
            [("label", "Titik terendah Yunus"),
             ("kutip", "“Angkatlah aku, campakkanlah aku ke dalam laut, maka laut akan menjadi reda dan tidak menyerang kamu lagi. Sebab aku tahu, bahwa karena akulah badai besar ini menyerang kamu.”"),
             ("ref", "Yunus 1:12", 30), ("teks", "Ini bukan pertobatan. Ini keputusasaan.")],
            [("label", "Laut pun reda"),
             ("kutip", "“Kemudian mereka mengangkat Yunus, lalu mencampakkannya ke dalam laut, dan laut berhenti mengamuk.”"),
             ("ref", "Yunus 1:15")],
            [("label", "Lalu…"),
             ("kutip", "“Maka atas penentuan TUHAN datanglah seekor ikan besar yang menelan Yunus; dan Yunus tinggal di dalam perut ikan itu tiga hari tiga malam lamanya.”"),
             ("ref", "Yunus 1:17", 30),
             ("teks", "“Atas penentuan TUHAN.” Ikan itu sudah disiapkan. Tanpa ikan itu, Yunus tenggelam.")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Tidak semua yang terasa menelan kita adalah hukuman."),
             ("poin", "2.  Kadang ‘perut ikan’ adalah tempat Tuhan menyelamatkan kita dari tenggelam."),
             ("poin", "3.  Tuhan sudah menyiapkan pertolongan bahkan sebelum kita tahu kita butuh.")],
            [("judul", "Kamu sedang di “perut ikan”?", 0), ("judul2", "Itu belum akhir ceritamu.", 40),
             ("kecil", "Save untuk hari-hari yang terasa gelap.")],
        ],
        "caption": "Kita sering membayangkan ikan besar itu sebagai hukuman untuk Yunus. Coba baca lagi Yunus 1:17 🐋\n\n“Maka atas penentuan TUHAN datanglah seekor ikan besar yang menelan Yunus.” Yunus baru saja dicampakkan ke laut dalam keadaan putus asa. Tanpa ikan itu, ia tenggelam. Ikan itu sudah disiapkan Tuhan untuk menyelamatkannya.\n\nKadang yang terasa “menelan” hidup kita justru tempat Tuhan menjaga kita tetap hidup.\n\nKetik 🐋 kalau kamu sedang di fase “perut ikan”, kita doakan bersama.\n\nSeri Yunus bagian 6/14 📜",
    },
    {   # 14 — doa di perut ikan
        "tema": "mata_air",
        "slides": [
            [("judul", "Doa pertama Yunus", 0), ("judul", "di seluruh kitab ini", 30), ("judul2", "lahir di perut ikan.", 50),
             ("kecil", "Seri Yunus · bagian 7")],
            [("label", "Dari tempat paling gelap"),
             ("kutip", "“Berdoalah Yunus kepada TUHAN, Allahnya, dari dalam perut ikan itu, katanya: ‘Dalam kesusahanku aku berseru kepada TUHAN, dan Ia menjawab aku…’”"),
             ("ref", "Yunus 2:1-2")],
            [("label", "Doa yang tersusun dari Mazmur"),
             ("teks", "Banyak kalimat dalam doa Yunus mirip dengan Mazmur. Bandingkan:"),
             ("kutip", "“Dalam kesesakanku aku berseru kepada TUHAN dan Ia menjawab aku.”"), ("ref", "Mazmur 120:1", 30),
             ("teks", "Di perut ikan, Yunus berdoa dengan firman yang ia hafal.")],
            [("label", "Kalimat puncaknya"),
             ("kutip", "“…apa yang kunazarkan akan kubayar. Keselamatan adalah dari TUHAN!”"),
             ("ref", "Yunus 2:9")],
            [("sub", "Pelajarannya", 30),
             ("poin", "1.  Tidak ada tempat yang terlalu gelap untuk berdoa."),
             ("poin", "2.  Firman yang kita simpan hari ini menjadi doa kita di hari yang gelap."),
             ("poin", "3.  Keselamatan bukan hasil usaha kita. Keselamatan adalah dari TUHAN.")],
            [("judul", "Minggu depan:", 0), ("judul2", "ikan itu memuntahkan Yunus… dan kesempatan kedua.", 40),
             ("kecil", "Follow supaya tidak ketinggalan bagian 8–14.")],
        ],
        "caption": "Di seluruh kitab Yunus, doa pertama sang nabi tidak diucapkan di bait suci. Doa itu lahir di perut ikan 🙏\n\nYunus 2:1-9. Dan menariknya, banyak kalimat dalam doanya mirip dengan Mazmur, misalnya Mazmur 120:1. Di tempat paling gelap, Yunus berdoa dengan firman yang ia hafal.\n\nPuncaknya: “Keselamatan adalah dari TUHAN!”\n\nAyat apa yang paling sering kamu doakan saat hari terasa gelap? Tulis di komentar 👇\n\nSeri Yunus bagian 7/14. Minggu depan: kesempatan kedua 📜",
    },
]
