"""@ayat.tersembunyi - minggu 2 format pendek.
FAKTA: 'Fakta 30 detik' (1 slide, skema sama dengan ayat_singkat.py).
SALAH: format baru 3 slide "Bukan kata Alkitab" (kutipan populer -> yang sebenarnya -> pelajaran).
Kutipan ayat: Alkitab Terjemahan Baru (TB)."""

TAGS = "#faktaalkitab #ayatalkitab #alkitab #kristenindonesia #belajaralkitab #ayattersembunyi"

FAKTA = [
    {"tema": "perkamen", "judul": "Dalam teks Ibraninya, kitab Ester tidak menyebut nama Allah sekali pun.",
     "isi": "Kitab Ester. Tapi tangan Tuhan terasa di setiap “kebetulan” dalam kisahnya.", "ref": "Kitab Ester",
     "caption": "Satu kitab penuh, tanpa sekali pun menyebut nama Allah. Itulah kitab Ester 📜\n\nTapi baca kisahnya: raja yang tidak bisa tidur, waktu yang pas, orang yang tepat di tempat yang tepat. Tuhan bekerja, bahkan saat Ia tidak disebut.\n\nPernah mengalami “kebetulan” yang ternyata cara Tuhan? Cerita di komentar 👇"},
    {"tema": "malam", "judul": "Alkitab mencatat ukuran ranjang seorang raja raksasa.",
     "isi": "Ranjang besi Og, raja Basan: 9 × 4 hasta, kurang lebih 4 × 1,8 meter.", "ref": "Ulangan 3:11",
     "caption": "Detail yang jarang dibaca: Alkitab mencatat ukuran ranjang besi Og, raja Basan 🛏️\n\nSembilan hasta panjangnya, empat hasta lebarnya, kurang lebih 4 × 1,8 meter. Og adalah sisa terakhir orang Refaim, tapi Israel tetap menang karena TUHAN menyertai mereka.\n\n📖 Ulangan 3:11\n\nBaru tahu detail ini? Ketik “BARU TAHU” 👇"},
    {"tema": "gurun", "judul": "Pasal terpendek dan terpanjang di Alkitab hampir bersebelahan.",
     "isi": "Mazmur 117 hanya 2 ayat. Dua pasal kemudian, Mazmur 119 punya 176 ayat.", "ref": "Mazmur 117 · Mazmur 119",
     "caption": "Mazmur 117 cuma 2 ayat. Mazmur 119 ada 176 ayat. Jaraknya hanya satu pasal 😮\n\nYang pendek mengajak semua bangsa memuji TUHAN. Yang panjang memuji firman-Nya dari awal sampai akhir.\n\nCoba baca Mazmur 117 sekarang, cuma 20 detik. Sudah? Ketik “AMIN” 🙏"},
    {"tema": "mata_air", "judul": "Sesosok jenazah hidup kembali setelah menyentuh tulang Nabi Elisa.",
     "isi": "Jenazah itu dilemparkan ke kubur Elisa. Begitu kena tulangnya, orang itu hidup kembali dan berdiri.", "ref": "2 Raja-raja 13:21",
     "caption": "Salah satu mukjizat paling aneh di Alkitab: bahkan setelah Elisa meninggal, Tuhan masih bekerja 🤯\n\nSebuah jenazah dilemparkan ke kuburnya, menyentuh tulang Elisa, lalu hidup kembali dan berdiri.\n\n📖 2 Raja-raja 13:21\n\nKuasa itu bukan milik Elisa, tapi milik Tuhan. Pernah dengar kisah ini? PERNAH / BARU TAHU 👇"},
    {"tema": "debu", "judul": "Raja Salomo menggubah 3.000 amsal dan 1.005 nyanyian.",
     "isi": "Hanya sebagian kecil yang sampai kepada kita di dalam Alkitab.", "ref": "1 Raja-raja 4:32",
     "caption": "3.000 amsal. 1.005 nyanyian. Itu karya Salomo menurut 1 Raja-raja 4:32 ✍️\n\nYang tercatat di Alkitab hanya sebagian kecilnya. Hikmat itu karunia dari Tuhan, bukan hasil kepintaran semata (1 Raja-raja 4:29).\n\nAmsal favoritmu yang mana? Tulis di komentar 👇"},
    {"tema": "laut", "judul": "Ada 700 prajurit kidal yang bisa mengumban batu tanpa meleset sehelai rambut pun.",
     "isi": "Mereka dari suku Benyamin, dalam kisah perang saudara yang tragis (Hakim-hakim 20). Detail kecil yang menunjukkan Alkitab mencatat sejarah dengan jujur.", "ref": "Hakim-hakim 20:16",
     "caption": "700 orang kidal, dan tidak meleset sehelai rambut pun 🎯\n\n📖 Hakim-hakim 20:16\n\nDetail kecil dari kisah perang saudara yang tragis di Hakim-hakim 20. Alkitab mencatat sejarah umat-Nya dengan jujur, termasuk bagian yang kelam.\n\nTag temanmu yang kidal 😄👇"},
    {"tema": "plum", "judul": "Tuhan memenuhi seorang seniman dengan Roh-Nya… untuk membuat karya seni.",
     "isi": "Namanya Bezaleel. Ia dipenuhi Roh Allah dengan keahlian untuk mengerjakan emas, perak, tembaga, batu, dan kayu.", "ref": "Keluaran 31:2-5",
     "caption": "Salah satu orang yang Alkitab sebut dipenuhi Roh Allah adalah… seorang pengrajin 🎨\n\nBezaleel diberi keahlian untuk membuat perabot Kemah Suci dari emas, perak, tembaga, batu, dan kayu.\n\n📖 Keluaran 31:2-5\n\nBakatmu juga bisa jadi ibadah. Kamu pandai di bidang apa? 👇"},
]

SALAH = [
    {"tema": "perkamen", "kutipan": "“Tuhan menolong orang yang menolong dirinya sendiri.”",
     "label": "TIDAK ADA DI ALKITAB",
     "sebenarnya": "Kalimat ini pepatah lama yang dipopulerkan Benjamin Franklin. Alkitab justru berkata Tuhan menolong kita saat kita tidak mampu menolong diri sendiri.",
     "ayat": "“Karena waktu kita masih lemah, Kristus telah mati untuk kita orang-orang durhaka pada waktu yang ditentukan oleh Allah.”",
     "ref": "Roma 5:6",
     "pelajaran": "Kasih karunia tidak menunggu kamu kuat dulu.",
     "caption": "Kalimat ini sering dikira ayat Alkitab. Ternyata bukan 😮\n\n“Tuhan menolong orang yang menolong dirinya sendiri” adalah pepatah lama yang dipopulerkan Benjamin Franklin. Alkitab justru berkata Kristus mati untuk kita “waktu kita masih lemah” (Roma 5:6).\n\nKerja keras tetap baik, tapi keselamatan adalah kasih karunia.\n\nKamu pernah dengar kalimat ini disebut sebagai ayat? PERNAH / BELUM 👇"},
    {"tema": "malam", "kutipan": "“Uang adalah akar segala kejahatan.”",
     "label": "SERING SALAH DIKUTIP",
     "sebenarnya": "Alkitab tidak berkata uang itu jahat. Yang disebut akar segala kejahatan adalah cinta uang: saat uang merebut tempat Tuhan di hati.",
     "ayat": "“Karena akar segala kejahatan ialah cinta uang. Sebab oleh memburu uanglah beberapa orang telah menyimpang dari iman dan menyiksa dirinya dengan berbagai-bagai duka.”",
     "ref": "1 Timotius 6:10",
     "pelajaran": "Uang itu alat. Masalahnya ada di hati yang mencintainya.",
     "caption": "Beda satu kata, beda besar artinya 💰\n\nAlkitab tidak berkata “uang adalah akar segala kejahatan”, tapi “akar segala kejahatan ialah CINTA uang” (1 Timotius 6:10).\n\nUang itu alat. Yang berbahaya adalah saat uang merebut tempat Tuhan di hati kita.\n\nKamu selama ini dengar versi yang mana? 👇"},
    {"tema": "gurun", "kutipan": "“Tuhan tidak akan memberi cobaan melebihi kemampuanmu.”",
     "label": "SERING SALAH DIKUTIP",
     "sebenarnya": "Ayat ini bicara soal pencobaan, yaitu godaan untuk berdosa, dan janjinya adalah jalan keluar. Untuk beban hidup yang terlalu berat, kita diajak bersandar pada Tuhan.",
     "ayat": "“…Allah setia dan karena itu Ia tidak akan membiarkan kamu dicobai melampaui kekuatanmu. Pada waktu kamu dicobai Ia akan memberikan kepadamu jalan ke luar, sehingga kamu dapat menanggungnya.”",
     "ref": "1 Korintus 10:13",
     "pelajaran": "Kamu tidak harus kuat sendirian. Tuhan setia.",
     "caption": "Kalimat yang sering diucapkan untuk menghibur, tapi isi ayat aslinya sedikit berbeda 🤍\n\n1 Korintus 10:13 bicara tentang pencobaan (godaan untuk berdosa), dan janjinya: Allah setia dan memberi jalan keluar.\n\nKalau hidup terasa terlalu berat untuk ditanggung, itu bukan tanda imanmu lemah. Paulus sendiri pernah merasa bebannya begitu berat sampai putus asa akan hidupnya (2 Korintus 1:8). Kita diajak bersandar pada Tuhan, bukan pada kekuatan sendiri.\n\nKamu pernah dengar kalimat ini? Kirim ke teman yang lagi berat bebannya 💌"},
    {"tema": "mata_air", "kutipan": "“Kebersihan adalah sebagian dari iman.”",
     "label": "TIDAK ADA DI ALKITAB",
     "sebenarnya": "Ungkapan populer ini bukan kutipan Alkitab. Hidup bersih tentu baik, tapi Yesus menekankan kebersihan hati.",
     "ayat": "“Berbahagialah orang yang suci hatinya, karena mereka akan melihat Allah.”",
     "ref": "Matius 5:8",
     "pelajaran": "Rumah boleh rapi. Hati juga perlu dibersihkan.",
     "caption": "Banyak yang mengira ini ada di Alkitab. Ternyata tidak ada 🙂\n\n“Kebersihan adalah sebagian dari iman” adalah ungkapan populer, bukan ayat Alkitab. Hidup bersih tetap baik, tapi Yesus berbicara tentang kebersihan yang lebih dalam: “Berbahagialah orang yang suci hatinya” (Matius 5:8).\n\nKamu pernah mengira kalimat ini ayat Alkitab? YA / TIDAK 👇"},
    {"tema": "plum", "kutipan": "Yeremia 29:11 = janji hidupku pasti lancar dan tanpa masalah.",
     "label": "SERING SALAH DIKUTIP",
     "sebenarnya": "Janji ini ditulis untuk umat yang sedang dibuang ke Babel. Pemulihannya datang setelah 70 tahun (ay. 10). Harapan dari Tuhan tetap nyata, bahkan di tengah masa sulit.",
     "ayat": "“Sebab Aku ini mengetahui rancangan-rancangan apa yang ada pada-Ku mengenai kamu, demikianlah firman TUHAN, yaitu rancangan damai sejahtera dan bukan rancangan kecelakaan…”",
     "ref": "Yeremia 29:11",
     "pelajaran": "Harapan dari Tuhan tidak hilang di tengah masa sulit.",
     "caption": "Salah satu ayat paling favorit, tapi konteksnya jarang dibaca 📖\n\nYeremia 29:11 ditulis untuk umat yang sedang dibuang ke Babel. Tuhan berkata pemulihan akan datang setelah 70 tahun (ayat 10). Artinya: janji ini bukan jaminan hidup tanpa masalah, tapi kepastian bahwa Tuhan punya rancangan damai sejahtera, bahkan di tengah pembuangan.\n\nJustru itu yang bikin ayat ini makin kuat. Kamu baru tahu konteksnya? 👇"},
    {"tema": "debu", "kutipan": "Filipi 4:13 = dengan Tuhan, aku pasti bisa menang apa saja.",
     "label": "SERING SALAH DIKUTIP",
     "sebenarnya": "Paulus menulisnya dari penjara. Di ayat sebelumnya ia bicara soal belajar cukup, baik saat kenyang maupun lapar, saat berkelimpahan maupun kekurangan.",
     "ayat": "“Segala perkara dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku.”",
     "ref": "Filipi 4:13",
     "pelajaran": "Kekuatan dari Tuhan bukan hanya untuk menang, tapi untuk bertahan.",
     "caption": "Ayat yang sering ditulis di kaos olahraga, padahal konteksnya lebih dalam 💪\n\nPaulus menulis Filipi 4:13 dari penjara. Ayat 11-12 bercerita tentang belajar merasa cukup, baik saat kenyang maupun lapar, saat berkelimpahan maupun kekurangan.\n\n“Segala perkara dapat kutanggung” artinya: apa pun keadaannya, Kristus memberi kekuatan untuk bertahan.\n\nKamu sedang butuh kekuatan untuk menang, atau untuk bertahan? 👇"},
    {"tema": "laut", "kutipan": "“Hawa memakan buah apel di Taman Eden.”",
     "label": "TIDAK ADA DI ALKITAB",
     "sebenarnya": "Alkitab tidak pernah menyebut apel, hanya “buah” dari pohon pengetahuan tentang yang baik dan yang jahat. Gambaran apel muncul belakangan lewat tradisi dan lukisan.",
     "ayat": "“…Lalu ia mengambil dari buahnya dan dimakannya dan diberikannya juga kepada suaminya yang bersama-sama dengan dia, dan suaminyapun memakannya.”",
     "ref": "Kejadian 3:6",
     "pelajaran": "Yang penting bukan jenis buahnya, tapi ketidaktaatannya.",
     "caption": "Plot twist: Alkitab tidak pernah menyebut apel 🍎\n\nKejadian 3 hanya menyebut “buah” dari pohon pengetahuan tentang yang baik dan yang jahat. Gambaran apel muncul belakangan lewat tradisi dan lukisan.\n\nYang penting bukan jenis buahnya, tapi pilihan untuk tidak taat, dan kabar baiknya, Tuhan tidak berhenti mencari manusia (Kejadian 3:9).\n\nDari kecil kamu juga membayangkan apel? YA / TIDAK 👇"},
]
