"""@kapi.percaya - minggu 2 (Minggu 4 - Sabtu 10 Okt 2026), 5 post/hari. Kutipan ayat: Alkitab TB.
Format sama dengan konten/kapi_tambahan.py:
  KATA  = kata besar; indeks 0-6 dipakai gambar pagi, 7-20 dipakai Reels (sore & malam)
  KOMIK = carousel 4 slide lucu: tiap slide = (teks, ekspresi, properti); slide terakhir + ayat
  PILIH = "pilih satu": dua pilihan A/B, jawab di komentar
Ekspresi: senang | capek | merem | sedih | semangat. Properti: alkitab | jeruk | keringat | hati | bintang | none."""

TAGS = "#kapi #kristen #anakmudakristen #renungan #ayatalkitab #kristenindonesia #humorkristen"

KATA = [
    # ---------- 0-6: gambar pagi ----------
    {"bg": "#16324F", "atas": "apa pun agendamu minggu ini,", "besar": "RAJA", "bawah": "tetap Dia yang pegang.", "ekspresi": "semangat", "properti": "bintang",
     "caption": "selamat hari Minggu! 👑\nkalender boleh penuh, tapi takhtanya tetap punya Dia.\n\n“…Raja segala raja dan Tuan di atas segala tuan.” — Wahyu 19:16\n\nketik 👑 kalau hari ini kamu mau serahin minggumu ke Dia"},
    {"bg": "#1E9BD7", "atas": "senin lagi, senin lagi…", "besar": "SEGAR", "bawah": "kekuatan baru dari Dia.", "ekspresi": "capek", "properti": "keringat",
     "caption": "kalau baterai sosialmu udah 3% dari pagi, kamu nggak sendirian 🫠🔋\ncharge-nya bukan di kopi aja, tapi di Dia.\n\n“…orang-orang yang menanti-nantikan TUHAN mendapat kekuatan baru: mereka seumpama rajawali yang naik terbang dengan kekuatan sayapnya; mereka berlari dan tidak menjadi lesu, mereka berjalan dan tidak menjadi lelah.” — Yesaya 40:31\n\nsave buat Senin-Senin berikutnya 🔖"},
    {"bg": "#F26B1D", "atas": "deg-degan mau presentasi?", "besar": "BERANI", "bawah": "Tuhan ikut masuk kelas.", "ekspresi": "semangat", "properti": "jeruk",
     "caption": "tangan dingin, suara gemeter, slide belum selesai 😭\ntenang, kamu nggak masuk ruangan itu sendirian 🍊\n\n“…kuatkan dan teguhkanlah hatimu? Janganlah kecut dan tawar hati, sebab TUHAN, Allahmu, menyertai engkau, ke mana pun engkau pergi.” — Yosua 1:9\n\ntag temen yang hari ini mau presentasi / interview 👇"},
    {"bg": "#EDE6DA", "atas": "bingung harus ke mana?", "besar": "TUNTUN", "bawah": "Dia yang pegang peta.", "ekspresi": "merem", "properti": "alkitab",
     "caption": "Google Maps aja bisa “rerouting”, apalagi Tuhan 🗺️\n\n“Akuilah Dia dalam segala lakumu, maka Ia akan meluruskan jalanmu.” — Amsal 3:6\n\nketik 🗺️ kalau kamu lagi nunggu arahan dari Tuhan"},
    {"bg": "#111111", "atas": "tugas numpuk, deadline mepet?", "besar": "MAMPU", "bawah": "di dalam Dia kok.", "ekspresi": "semangat", "properti": "keringat",
     "caption": "bukan karena kamu super, tapi karena Dia yang kasih kekuatan 💪\n\n“Segala perkara dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku.” — Filipi 4:13\n\nkirim ke bestie yang lagi dikejar deadline"},
    {"bg": "#2F5E45", "atas": "ditanya soal imanmu?", "besar": "SIAP", "bawah": "jawab dengan lembut.", "ekspresi": "senang", "properti": "alkitab",
     "caption": "nggak perlu debat kusir, cukup cerita pengharapanmu dengan lembut 🤍\n\n“…Dan siap sedialah pada segala waktu untuk memberi pertanggungan jawab kepada tiap-tiap orang yang meminta pertanggungan jawab dari kamu tentang pengharapan yang ada padamu, tetapi haruslah dengan lemah lembut dan hormat.” — 1 Petrus 3:15-16\n\nsave buat pengingat 🔖"},
    {"bg": "#F2B705", "atas": "akhirnya weekend,", "besar": "SENYUM", "bawah": "dulu, jangan lupa.", "ekspresi": "senang", "properti": "jeruk+bintang",
     "caption": "hari Sabtu = izin resmi buat senyum lebih lebar 😁🍊\n\n“Hati yang gembira adalah obat yang manjur, tetapi semangat yang patah mengeringkan tulang.” — Amsal 17:22\n\nsebutin satu hal kecil yang bikin kamu senyum minggu ini 👇"},

    # ---------- 7-20: Reels (sore & malam) ----------
    {"bg": "#5E7F63", "atas": "udah jauh banget ya?", "besar": "PULANG", "bawah": "pintunya masih kebuka.", "ekspresi": "sedih", "properti": "hati",
     "caption": "sejauh apa pun kamu pergi, Bapa masih nunggu di depan pintu 🏠🤍\n\n“Ketika ia masih jauh, ayahnya telah melihatnya, lalu tergeraklah hatinya oleh belas kasihan. Ayahnya itu berlari mendapatkan dia lalu merangkul dan mencium dia.” — Lukas 15:20\n\nketik 🏠 kalau kamu mau pulang"},
    {"bg": "#D6456B", "atas": "hari ini berat banget?", "besar": "PELUK", "bawah": "lengan-Nya kekal.", "ekspresi": "merem", "properti": "hati",
     "caption": "kalau nggak ada yang bisa meluk kamu malam ini, ingat: ada lengan yang nggak pernah capek 🤍\n\n“Allah yang abadi adalah tempat perlindunganmu, dan di bawahmu ada lengan-lengan yang kekal.” — Ulangan 33:27\n\nkirim ke orang yang butuh dipeluk hari ini"},
    {"bg": "#111111", "atas": "ngerasa udah di batas?", "besar": "TAHAN", "bawah": "Dia tau batasmu.", "ekspresi": "capek", "properti": "keringat",
     "caption": "Tuhan tau kapasitasmu, bahkan lebih dari kamu sendiri 🫂\n\n“…Allah setia dan karena itu Ia tidak akan membiarkan kamu dicobai melampaui kekuatanmu. Pada waktu kamu dicobai Ia akan memberikan kepadamu jalan ke luar, sehingga kamu dapat menanggungnya.” — 1 Korintus 10:13\n\nketik 🫂 kalau kamu lagi di titik ini"},
    {"bg": "#EDE6DA", "atas": "masih mikirin semuanya?", "besar": "LEPAS", "bawah": "serahin ke Dia.", "ekspresi": "merem", "properti": "none",
     "caption": "genggamanmu capek. taruh dulu ke tangan yang lebih kuat 🫧\n\n“Serahkanlah segala kekuatiranmu kepada-Nya, sebab Ia yang memelihara kamu.” — 1 Petrus 5:7\n\nsave buat malam-malam overthinking 🔖"},
    {"bg": "#16324F", "atas": "dunia goyang terus?", "besar": "TEGUH", "bawah": "jangan goyah.", "ekspresi": "semangat", "properti": "alkitab",
     "caption": "semua orang lagi ribut, kamu tetap berdiri 🧱\njerih payahmu buat Tuhan nggak ada yang sia-sia.\n\n“…berdirilah teguh, jangan goyah, dan giatlah selalu dalam pekerjaan Tuhan! Sebab kamu tahu, bahwa dalam persekutuan dengan Tuhan jerih payahmu tidak sia-sia.” — 1 Korintus 15:58\n\nketik “TEGUH” kalau kamu lagi berjuang"},
    {"bg": "#111111", "atas": "mau tidur tapi was-was?", "besar": "JAGA", "bawah": "Dia yang jagain.", "ekspresi": "merem", "properti": "bintang",
     "caption": "kamu boleh tidur. yang jagain kamu nggak pernah ngantuk 🌙✨\n\n“Ia takkan membiarkan kakimu goyah, Penjagamu tidak akan terlelap.” — Mazmur 121:3\n\nselamat istirahat 🤍"},
    {"bg": "#F26B1D", "atas": "nggak pernah kepilih?", "besar": "DIPILIH", "bawah": "kamu, sama Dia.", "ekspresi": "senang", "properti": "bintang",
     "caption": "nggak kepilih jadi tim inti, nggak kepilih jadi panitia… tapi kamu dipilih Tuhan 🌟\n\n“Bukan kamu yang memilih Aku, tetapi Akulah yang memilih kamu.” — Yohanes 15:16\n\ntag temen yang perlu dengar ini 👇"},
    {"bg": "#2F5E45", "atas": "insecure lagi?", "besar": "BERHARGA", "bawah": "karya ajaib-Nya kamu.", "ekspresi": "senang", "properti": "hati",
     "caption": "sebelum scroll dan bandingin diri lagi, baca ini dulu 🤍\n\n“Aku bersyukur kepada-Mu oleh karena kejadianku dahsyat dan ajaib; ajaib apa yang Kaubuat, dan jiwaku benar-benar menyadarinya.” — Mazmur 139:14\n\nketik 🤍 kalau kamu lagi butuh ini"},
    {"bg": "#5E7F63", "atas": "ngerasa jalan di tempat?", "besar": "TUMBUH", "bawah": "pelan tapi pasti.", "ekspresi": "senang", "properti": "jeruk",
     "caption": "akar tumbuh duluan sebelum kelihatan buahnya 🌱\nDia belum selesai sama kamu.\n\n“…Ia, yang memulai pekerjaan yang baik di antara kamu, akan meneruskannya sampai pada akhirnya pada hari Kristus Yesus.” — Filipi 1:6\n\nsave buat pengingat 🔖"},
    {"bg": "#1E9BD7", "atas": "doamu kayak nggak nyampe?", "besar": "DENGAR", "bawah": "Dia, tiap kata.", "ekspresi": "merem", "properti": "alkitab",
     "caption": "sinyal ke surga nggak pernah “no service” 📶🙏\n\n“Berserulah kepada-Ku, maka Aku akan menjawab engkau dan akan memberitahukan kepadamu hal-hal yang besar dan yang tidak terpahami, yakni hal-hal yang tidak kauketahui.” — Yeremia 33:3\n\ntulis doamu di komentar, kita doakan bareng 🙏"},
    {"bg": "#D6456B", "atas": "circle makin kecil?", "besar": "SAHABAT", "bawah": "Yesus nggak ninggalin.", "ekspresi": "senang", "properti": "hati",
     "caption": "teman bisa sibuk, grup bisa sepi. ada Sahabat yang udah buktiin kasih-Nya 🤍\n\n“Tidak ada kasih yang lebih besar dari pada kasih seorang yang memberikan nyawanya untuk sahabat-sahabatnya.” — Yohanes 15:13\n\ntag sahabat yang selalu ada buat kamu 👇"},
    {"bg": "#16324F", "atas": "jatuh di dosa yang sama?", "besar": "AMPUN", "bawah": "masih tersedia.", "ekspresi": "sedih", "properti": "alkitab",
     "caption": "malu boleh, tapi jangan kabur. datang aja, jujur aja 🤍\n\n“Jika kita mengaku dosa kita, maka Ia adalah setia dan adil, sehingga Ia akan mengampuni segala dosa kita dan menyucikan kita dari segala kejahatan.” — 1 Yohanes 1:9\n\nketik 🤍 kalau kamu mau mulai lagi"},
    {"bg": "#F2B705", "atas": "masih kebawa masa lalu?", "besar": "BEBAS", "bawah": "Yesus udah bayar.", "ekspresi": "semangat", "properti": "bintang",
     "caption": "rantainya udah dipatahin. nggak usah dipakai lagi ✨\n\n“Jadi apabila Anak itu memerdekakan kamu, kamupun benar-benar merdeka.” — Yohanes 8:36\n\nketik “BEBAS” kalau kamu percaya"},
    {"bg": "#F4F4F2", "atas": "Tuhan kerasa jauh?", "besar": "NYATA", "bawah": "coba rasain sendiri.", "ekspresi": "senang", "properti": "jeruk",
     "caption": "bukan cuma katanya orang. coba cicipi sendiri kebaikan-Nya 🍊\n\n“Kecaplah dan lihatlah, betapa baiknya TUHAN itu! Berbahagialah orang yang berlindung pada-Nya!” — Mazmur 34:9\n\nbesok ibadah, yuk! tag temen yang mau kamu ajak 👇"},
]

KOMIK = [
    {"judul": "Kapi & kantong persembahan", "bg": "#FBE8C8",
     "slides": [("kantong persembahan mulai keliling…", "senang", "none"),
                ("Kapi baru sadar: dompet ketinggalan di rumah", "sedih", "keringat"),
                ("lalu lihat layar: “bisa juga lewat QRIS”", "semangat", "bintang"),
                ("memberi itu soal hati yang sukacita, bukan soal jumlahnya", "senang", "hati")],
     "ayat": "“…sebab Allah mengasihi orang yang memberi dengan sukacita.” — 2 Korintus 9:7",
     "caption": "panik 3 detik pas kantong persembahan makin dekat, dompet nggak ada 😭 siapa yang pernah?\n\nyang Tuhan lihat bukan nominalnya, tapi hatinya 🤍\n\n“Hendaklah masing-masing memberikan menurut kerelaan hatinya, jangan dengan sedih hati atau karena paksaan, sebab Allah mengasihi orang yang memberi dengan sukacita.” — 2 Korintus 9:7\n\nselamat hari Minggu! 🍊"},
    {"judul": "Kapi & grup WA pemuda", "bg": "#DCEBFA",
     "slides": [("grup WA pemuda: “yang bisa datang rapat, reply ya 🙏”", "senang", "none"),
                ("dibaca 42 orang. yang reply: 2", "sedih", "none"),
                ("Kapi reply “hadir”… lalu ketiduran", "capek", "keringat"),
                ("besoknya Kapi datang. walau bertiga, tetap seru!", "semangat", "hati")],
     "ayat": "“Dan marilah kita saling memperhatikan supaya kita saling mendorong dalam kasih dan dalam pekerjaan baik.” — Ibrani 10:24",
     "caption": "grup WA pemuda: rame pas bahas makan, sepi pas bahas rapat 😂📱\n\ntapi yang datang sedikit pun tetap berarti. yuk saling dorong!\n\n“Dan marilah kita saling memperhatikan supaya kita saling mendorong dalam kasih dan dalam pekerjaan baik.” — Ibrani 10:24\n\ntag temen segrup yang suka read doang 👀"},
    {"judul": "Kapi & latihan Natal", "bg": "#E6F2E6",
     "slides": [("udah Oktober. gereja: “yuk mulai latihan Natal!”", "semangat", "bintang"),
                ("Kapi dapet peran: domba nomor 3", "sedih", "none"),
                ("latihan tiap Sabtu. dialognya cuma “mbeee”", "capek", "keringat"),
                ("gapapa. kabar sukacitanya buat semua, termasuk domba nomor 3", "senang", "bintang")],
     "ayat": "“Jangan takut, sebab sesungguhnya aku memberitakan kepadamu kesukaan besar untuk seluruh bangsa.” — Lukas 2:10",
     "caption": "baru Oktober, gereja udah mulai latihan Natal 🎄😂\nkamu dulu dapet peran apa? malaikat, gembala, atau domba?\n\n“Jangan takut, sebab sesungguhnya aku memberitakan kepadamu kesukaan besar untuk seluruh bangsa.” — Lukas 2:10\n\ntulis peran Natalmu di komentar 👇"},
    {"judul": "Kapi & file belum ke-save", "bg": "#FDE2D8",
     "slides": [("dosen: “tugas dikumpul besok pagi ya”", "sedih", "none"),
                ("Kapi begadang, tiga gelas kopi", "capek", "keringat"),
                ("jam 3 pagi: laptop mati. file belum di-save", "sedih", "keringat"),
                ("tarik napas, doa, mulai lagi. Tuhan tetap penolong", "senang", "alkitab")],
     "ayat": "“Allah itu bagi kita tempat perlindungan dan kekuatan, sebagai penolong dalam kesesakan sangat terbukti.” — Mazmur 46:2",
     "caption": "trauma terbesar mahasiswa: “file belum di-save” 😭💻\n\nkecewa boleh, nyerah jangan. Dia penolong yang sudah terbukti.\n\n“Allah itu bagi kita tempat perlindungan dan kekuatan, sebagai penolong dalam kesesakan sangat terbukti.” — Mazmur 46:2\n\ntips dari Kapi: Ctrl+S tiap 5 menit 😂 tag temen yang lagi skripsian 👇"},
    {"judul": "Kapi & kumpul keluarga besar", "bg": "#F3E8FA",
     "slides": [("kumpul keluarga besar. makanan enak semua", "senang", "jeruk"),
                ("tante: “kapan nyusul?”", "sedih", "keringat"),
                ("Kapi: “lagi nunggu waktu Tuhan, tante”", "merem", "none"),
                ("dan itu beneran jawaban terbaik", "senang", "alkitab")],
     "ayat": "“Ia membuat segala sesuatu indah pada waktunya.” — Pengkhotbah 3:11",
     "caption": "pertanyaan wajib kumpul keluarga: kapan lulus, kapan kerja, kapan nyusul 😂\n\njawab dengan senyum. waktunya Tuhan nggak pernah telat.\n\n“Ia membuat segala sesuatu indah pada waktunya.” — Pengkhotbah 3:11\n\npertanyaan “kapan” apa yang paling sering kamu dapet? 👇"},
    {"judul": "Kapi & paduan suara Natal", "bg": "#FFF3C4",
     "slides": [("latihan paduan suara Natal dimulai!", "semangat", "bintang"),
                ("Kapi takut fals, nyanyinya pelan banget", "merem", "none"),
                ("pelatih: “Kapi, keluarin aja suaranya!”", "capek", "keringat"),
                ("nyanyi buat Tuhan itu soal sukacita, bukan cuma nada", "senang", "hati")],
     "ayat": "“Bersorak-soraklah bagi TUHAN, hai seluruh bumi, bergembiralah, bersorak-sorailah dan bermazmurlah!” — Mazmur 98:4",
     "caption": "anggota paduan suara yang cuma lip sync, ngaku 🙋‍♂️🎶😂\n\ntetap latihan ya, tapi jangan lupa: yang paling penting hatinya.\n\n“Bersorak-soraklah bagi TUHAN, hai seluruh bumi, bergembiralah, bersorak-sorailah dan bermazmurlah!” — Mazmur 98:4\n\ngerejamu udah mulai latihan Natal belum? 🎄"},
    {"judul": "Kapi & outfit ke gereja", "bg": "#FBE8C8",
     "slides": [("Minggu pagi: “pakai baju apa ya?”", "capek", "none"),
                ("ganti baju lima kali", "capek", "keringat"),
                ("akhirnya telat, pakai kemeja yang pertama", "sedih", "none"),
                ("tenang, Tuhan lihat hati, bukan outfit", "senang", "hati")],
     "ayat": "“…Manusia melihat apa yang di depan mata, tetapi TUHAN melihat hati.” — 1 Samuel 16:7",
     "caption": "“bentar, ganti baju sekali lagi” — kata Kapi, 5 kali 😂👔\n\nrapi boleh, tapi hati yang siap lebih penting.\n\n“…Manusia melihat apa yang di depan mata, tetapi TUHAN melihat hati.” — 1 Samuel 16:7\n\nsiapin bajunya dari malam ini, biar besok nggak telat ibadah 🙏"},
]

PILIH = [
    {"bg": "#16324F", "a": "duduk depan", "b": "duduk belakang", "ekspresi": "senang",
     "caption": "PILIH SATU 👇\n\nA = duduk paling depan 🙋\nB = duduk paling belakang 🫣\n\njawab A atau B di komentar. Kapi tim tengah (biar aman 😂)\n\n“Sebab lebih baik satu hari di pelataran-Mu dari pada seribu hari di tempat lain.” — Mazmur 84:11"},
    {"bg": "#2F5E45", "a": "renungan audio", "b": "renungan tulisan", "ekspresi": "merem",
     "caption": "PILIH SATU 👇\n\nA = renungan audio / podcast 🎧\nB = renungan tulisan 📖\n\njawab A atau B, sebutin juga rekomendasimu!\n\n“…renungkanlah itu siang dan malam…” — Yosua 1:8"},
    {"bg": "#F26B1D", "a": "nastar", "b": "kastengel", "ekspresi": "semangat",
     "caption": "PILIH SATU 👇 (udah Oktober, boleh dong mulai mikirin kue Natal 🎄)\n\nA = nastar 🍍\nB = kastengel 🧀\n\njawab A atau B. jawaban yang salah… nggak ada, dua-duanya enak 😂\n\n“…Hari ini telah lahir bagimu Juruselamat, yaitu Kristus, Tuhan, di kota Daud.” — Lukas 2:11"},
    {"bg": "#EDE6DA", "a": "saat teduh + kopi", "b": "saat teduh + teh", "ekspresi": "senang",
     "caption": "PILIH SATU 👇\n\nA = saat teduh ditemani kopi ☕\nB = saat teduh ditemani teh 🍵\n\njawab A atau B. yang penting saat teduhnya, bukan minumannya 😄\n\n“Diamlah dan ketahuilah, bahwa Akulah Allah!” — Mazmur 46:11"},
    {"bg": "#1E9BD7", "a": "Perjanjian Lama", "b": "Perjanjian Baru", "ekspresi": "merem",
     "caption": "PILIH SATU 👇\n\nA = lebih suka baca Perjanjian Lama 📜\nB = lebih suka baca Perjanjian Baru ✝️\n\njawab A atau B, sebutin kitab favoritmu juga!\n\n“Segala tulisan yang diilhamkan Allah memang bermanfaat untuk mengajar, untuk menyatakan kesalahan, untuk memperbaiki kelakuan dan untuk mendidik orang dalam kebenaran.” — 2 Timotius 3:16"},
    {"bg": "#111111", "a": "main musik", "b": "operator slide", "ekspresi": "semangat",
     "caption": "PILIH SATU 👇\n\nA = pelayanan main musik 🎸\nB = pelayanan operator slide lirik 💻\n\njawab A atau B. salut buat operator slide yang ganti lirik pas banget di detik terakhir 🫡\n\n“Layanilah seorang akan yang lain, sesuai dengan karunia yang telah diperoleh tiap-tiap orang sebagai pengurus yang baik dari kasih karunia Allah.” — 1 Petrus 4:10"},
    {"bg": "#5E7F63", "a": "retret gunung", "b": "retret pantai", "ekspresi": "senang",
     "caption": "PILIH SATU 👇\n\nA = retret di gunung 🏔️\nB = retret di pantai 🏖️\n\njawab A atau B, dan ceritain retret paling berkesanmu!\n\n“Aku melayangkan mataku ke gunung-gunung; dari manakah akan datang pertolonganku? Pertolonganku ialah dari TUHAN, yang menjadikan langit dan bumi.” — Mazmur 121:1-2"},
]

# hari 1..7 = Minggu 4 .. Sabtu 10 Okt 2026. KATA 0-6 pagi; 7-20 Reels (sore, malam).
JADWAL = {d: {"pagi": ("kata", d - 1),
              "siang": ("komik", d - 1),
              "sore": ("reel", 7 + 2 * (d - 1)),
              "malam": ("reel", 8 + 2 * (d - 1)),
              "larut": ("pilih", d - 1)}
          for d in range(1, 8)}
