"""Akun Tenang (@diam.dan.percaya) - minggu 8 (Minggu 15 Nov - Sabtu 21 Nov 2026).
Tema: "Kamu tidak sendirian - Imanuel, Allah beserta kita" + hitung mundur Natal lanjut (40 -> 34 hari).
Hari: 1 Minggu (Imanuel, Allah beserta kita), 2 Senin (Dia menyertai di hari biasa: kerja, kuliah, rumah),
3 Selasa (saat merasa kesepian), 4 Rabu (sahabat dan komunitas, tubuh Kristus, saling menanggung beban),
5 Kamis (Dia tidak pernah meninggalkan), 6 Jumat (Hari Anak Sedunia: kita anak-anak Bapa, Yesus menyambut anak-anak),
7 Sabtu (Raja yang datang dekat, besok Minggu Kristus Raja; siap ibadah besok).
12 slot per hari, setiap slot gaya visual berbeda:
  KORAN    = halaman depan koran "KABAR BAIK": berita dari kisah Alkitab.               pagi 06:00
  LETTER   = papan huruf hitam (letter board) dengan huruf plastik putih.              pagi3 07:30
  ELI      = komik Eli yang sudah jadi (hari 1, 4, 7) / KUIS = kuis Alkitab 2 slide.    pagi2 09:00
  STICKY   = catatan tempel di pintu kulkas, ayat di catatan keempat yang lebih besar.  siang0 10:30
  MENU     = papan menu kapur di kafe.                                                 siang 12:00
  SEARCH   = Reel kolom pencarian: mengetik, saran, lalu hasil + kartu ayat.            siang2 13:30
  ORNAMEN  = hiasan pohon Natal, hitung mundur Natal.                                  sore 15:00
  KODE     = editor kode dengan pseudo-code jenaka.                                    sore2 16:30
  KARTUPOS = kartu pos tulisan tangan.                                                 petang 18:00
  FLIP     = Reel papan keberangkatan split-flap.                                      malam0 19:30
  PETA     = aplikasi peta dengan rute.                                                malam 21:00
  LILIN    = sebatang lilin di gelap, satu kalimat malam.                              larut 22:30
Kutipan ayat: Alkitab TB. Caption tanpa hashtag."""

# ---------- KORAN: halaman depan koran "KABAR BAIK" (pagi 06:00) ----------
KORAN = [
    {"judul": "NAMA-NYA IMANUEL: ALLAH BESERTA KITA",
     "sub": "Malaikat menemui Yusuf dalam mimpi: Anak yang dikandung Maria berasal dari Roh Kudus",
     "isi": "NAZARET — Seorang tukang kayu bernama Yusuf mengurungkan niatnya menceraikan tunangannya diam-diam. Dalam mimpi, malaikat Tuhan memintanya tidak takut mengambil Maria sebagai istri. Anak itu akan dinamai Yesus. Matius mencatat, kelahiran ini menggenapi nubuat nabi: Ia akan disebut Imanuel, yang berarti Allah menyertai kita.",
     "ayat": "“…Yusuf, anak Daud, janganlah engkau takut mengambil Maria sebagai isterimu, sebab anak yang di dalam kandungannya adalah dari Roh Kudus.”",
     "ref": "Matius 1:20",
     "caption": "Berita utama hari Minggu: Allah beserta kita 📰\n\nMinggu ini kita belajar satu kebenaran sederhana yang sering terasa jauh: kamu tidak sendirian. Kabar Natal sudah dimulai di sini, di hati seorang tukang kayu yang bingung dan takut. Allah tidak membiarkan Yusuf menanggung semuanya sendirian. Ia datang, berbicara, dan menyertai.\n\n📖 “…Yusuf, anak Daud, janganlah engkau takut mengambil Maria sebagai isterimu, sebab anak yang di dalam kandungannya adalah dari Roh Kudus.” — Matius 1:20\n\nKetik “Imanuel” kalau kamu mau memulai minggu ini dengan mengingat bahwa Allah beserta kita."},
    {"judul": "YESUS NAIK PERAHU NELAYAN YANG LELAH",
     "sub": "Semalaman tidak menangkap apa-apa, Simon tetap menebarkan jala atas perkataan Yesus",
     "isi": "DANAU GENESARET — Para nelayan sedang membasuh jala setelah semalaman bekerja tanpa hasil. Yesus naik ke perahu Simon dan mengajar orang banyak dari sana. Sesudah itu Ia menyuruh Simon bertolak ke tempat yang dalam. Meski lelah, Simon taat dan menebarkan jala. Tangkapannya begitu banyak sampai jala mereka mulai koyak.",
     "ayat": "“…Guru, telah sepanjang malam kami bekerja keras dan kami tidak menangkap apa-apa, tetapi karena Engkau menyuruhnya, aku akan menebarkan jala juga.”",
     "ref": "Lukas 5:5",
     "caption": "Senin pagi, kabar dari tempat kerja 📰\n\nYesus tidak hanya hadir di rumah ibadah. Ia naik ke perahu Simon, tempat kerja yang bau ikan, pada pagi yang melelahkan setelah semalaman gagal. Kisah ini bukan janji bahwa pekerjaan kita pasti selalu berhasil. Tapi kisah ini menunjukkan bahwa Yesus mau masuk ke dalam pekerjaan kita yang biasa, bahkan yang terasa sia-sia.\n\n📖 “…Guru, telah sepanjang malam kami bekerja keras dan kami tidak menangkap apa-apa, tetapi karena Engkau menyuruhnya, aku akan menebarkan jala juga.” — Lukas 5:5\n\nKetik “Karena Engkau” sebelum mulai bekerja hari ini."},
    {"judul": "YESUS MENDATANGI PRIA YANG SENDIRIAN",
     "sub": "Di kolam Betesda, Ia menyapa orang sakit yang merasa tidak punya siapa-siapa",
     "isi": "YERUSALEM — Di serambi kolam Betesda, seorang pria yang sudah tiga puluh delapan tahun sakit masih menunggu. ‘Tidak ada orang yang menurunkan aku ke dalam kolam itu,’ katanya. Yesus melihatnya dan tahu sudah berapa lama ia dalam keadaan itu. Ia menyapanya, lalu menyembuhkannya. Pria itu mengangkat tilamnya dan berjalan.",
     "ayat": "“Ketika Yesus melihat orang itu berbaring di situ dan karena Ia tahu, bahwa ia telah lama dalam keadaan itu, berkatalah Ia kepadanya: ‘Maukah engkau sembuh?’”",
     "ref": "Yohanes 5:6",
     "caption": "Tiga puluh delapan tahun, lalu ada yang datang 📰\n\nBayangkan menunggu selama itu, sementara orang lain selalu lebih dulu. Pria di kolam Betesda tidak punya siapa-siapa untuk menolongnya. Tapi Yesus melihatnya di antara banyak orang sakit, tahu kisahnya, dan menghampirinya. Kalau hari ini kamu merasa tidak ada yang memperhatikan, ingat: Yesus melihat dan tahu.\n\n📖 “Ketika Yesus melihat orang itu berbaring di situ dan karena Ia tahu, bahwa ia telah lama dalam keadaan itu, berkatalah Ia kepadanya: ‘Maukah engkau sembuh?’” — Yohanes 5:6\n\nKetik “Dia melihatku” kalau hari ini kamu merasa sendirian 🤍"},
    {"judul": "EMPAT SAHABAT BONGKAR ATAP DEMI TEMAN",
     "sub": "Rumah penuh sesak tidak menghentikan mereka membawa teman yang lumpuh kepada Yesus",
     "isi": "KAPERNAUM — Rumah tempat Yesus mengajar penuh sesak sampai ke depan pintu. Empat orang yang menggotong teman mereka yang lumpuh tidak bisa masuk. Mereka tidak menyerah: atap rumah dibuka, lalu tilam teman mereka diturunkan tepat di depan Yesus. Melihat iman mereka, Yesus mengampuni dosa orang itu dan menyuruhnya bangun. Ia pun berjalan keluar.",
     "ayat": "“Ketika Yesus melihat iman mereka, berkatalah Ia kepada orang lumpuh itu: ‘Hai anak-Ku, dosamu sudah diampuni!’”",
     "ref": "Markus 2:5",
     "caption": "Berita hari Rabu: persahabatan yang membongkar atap 📰\n\nOrang lumpuh itu tidak bisa sampai kepada Yesus dengan kakinya sendiri. Ia butuh teman. Perhatikan kalimat Markus: Yesus melihat iman mereka, termasuk iman teman-temannya. Kadang kita yang digotong, kadang kita yang menggotong. Dua-duanya bagian dari hidup sebagai tubuh Kristus.\n\n📖 “Ketika Yesus melihat iman mereka, berkatalah Ia kepada orang lumpuh itu: ‘Hai anak-Ku, dosamu sudah diampuni!’” — Markus 2:5\n\nTag teman yang pernah “menggotong” kamu dalam doa 👇"},
    {"judul": "ADA ORANG KEEMPAT DI DALAM PERAPIAN",
     "sub": "Tiga pemuda dilempar ke dalam api, tetapi raja melihat empat orang berjalan bebas di sana",
     "isi": "BABEL — Raja Nebukadnezar terkejut. Sadrakh, Mesakh, dan Abednego dilempar ke perapian yang menyala-nyala karena menolak menyembah patung emas. Namun raja melihat empat orang berjalan bebas di tengah api. Ketika ketiganya keluar, rambut mereka tidak hangus dan bau kebakaran pun tidak ada. Mereka tidak sendirian di dalam api.",
     "ayat": "“…ada empat orang kulihat berjalan-jalan dengan bebas di tengah-tengah api itu; mereka tidak terluka, dan yang keempat itu rupanya seperti anak dewa!”",
     "ref": "Daniel 3:25",
     "caption": "Berita hari Kamis: mereka tidak sendirian di dalam api 📰\n\nSadrakh, Mesakh, dan Abednego tidak tahu apakah mereka akan diselamatkan. Mereka bahkan berkata kepada raja, seandainya tidak pun, mereka tetap tidak akan menyembah patung itu. Tuhan tidak selalu menjauhkan kita dari api. Tapi kisah ini mengingatkan bahwa Ia tidak meninggalkan umat-Nya sendirian di dalamnya. Nebukadnezar sendiri kemudian mengakui bahwa Allah mereka telah mengutus malaikat-Nya.\n\n📖 “…ada empat orang kulihat berjalan-jalan dengan bebas di tengah-tengah api itu; mereka tidak terluka, dan yang keempat itu rupanya seperti anak dewa!” — Daniel 3:25\n\nKirim ke teman yang sedang berada di tengah “api” 💌"},
    {"judul": "YESUS MARAH KARENA ANAK-ANAK DIHALANGI",
     "sub": "Murid-murid memarahi orang yang membawa anak-anak kecil; Yesus justru memeluk mereka",
     "isi": "YUDEA — Beberapa orang membawa anak-anak kecil kepada Yesus supaya Ia menjamah mereka. Murid-murid memarahi orang-orang itu. Melihat hal itu, Yesus marah kepada murid-murid-Nya. ‘Biarkan anak-anak itu datang kepada-Ku,’ kata-Nya. Ia lalu memeluk anak-anak itu, meletakkan tangan-Nya atas mereka, dan memberkati mereka.",
     "ayat": "“Ketika Yesus melihat hal itu, Ia marah dan berkata kepada mereka: ‘Biarkan anak-anak itu datang kepada-Ku, jangan menghalang-halangi mereka…’”",
     "ref": "Markus 10:14",
     "caption": "Selamat Hari Anak Sedunia 📰\n\nMurid-murid memarahi orang-orang yang membawa anak-anak kepada Yesus. Tapi Yesus justru marah kepada murid-murid-Nya. Ia meluangkan waktu, memeluk, dan memberkati anak-anak itu. Hari ini, doakan anak-anak di sekitarmu. Dan ingat juga: setua apa pun kamu, kamu tetap boleh datang kepada-Nya seperti seorang anak.\n\n📖 “Ketika Yesus melihat hal itu, Ia marah dan berkata kepada mereka: ‘Biarkan anak-anak itu datang kepada-Ku, jangan menghalang-halangi mereka…’” — Markus 10:14\n\nTulis nama anak yang mau kamu doakan hari ini di komentar 👇"},
    {"judul": "RAJA MASUK KOTA MENUNGGANG KELEDAI",
     "sub": "Orang banyak menghamparkan pakaian di jalan dan berseru: Hosana bagi Anak Daud!",
     "isi": "YERUSALEM — Seluruh kota gempar. Orang banyak menghamparkan pakaian dan ranting-ranting di jalan untuk menyambut Yesus, nabi dari Nazaret. Ia masuk bukan dengan kuda perang, melainkan menunggang seekor keledai. Matius mencatat, peristiwa ini menggenapi nubuat nabi: Rajamu datang kepadamu dengan lemah lembut. Orang-orang bertanya, siapakah orang ini?",
     "ayat": "“…Hosana bagi Anak Daud, diberkatilah Dia yang datang dalam nama Tuhan, hosana di tempat yang mahatinggi!”",
     "ref": "Matius 21:9",
     "caption": "Berita akhir pekan: Raja datang dekat 📰\n\nBesok banyak gereja merayakan Minggu Kristus Raja, Minggu terakhir dalam kalender gerejawi sebelum masa Adven. Raja kita tidak datang dengan arak-arakan kuda perang. Ia datang dengan lemah lembut, cukup dekat untuk disambut orang banyak di jalan. Raja yang sama mengundang kita beribadah kepada-Nya besok.\n\n📖 “…Hosana bagi Anak Daud, diberkatilah Dia yang datang dalam nama Tuhan, hosana di tempat yang mahatinggi!” — Matius 21:9\n\nKetik “Hosana” kalau besok kamu mau datang beribadah kepada Sang Raja 👑"},
]

# ---------- LETTER: papan huruf hitam, huruf plastik putih (pagi3 07:30) ----------
LETTER = [
    {"teks": "SELAMAT HARI\nMINGGU.\nIMANUEL:\nALLAH BESERTA\nKITA.",
     "ayat": "“Buatlah rancangan, tetapi akan gagal juga; ambillah keputusan, tetapi tidak terlaksana juga, sebab Allah menyertai kami!”",
     "ref": "Yesaya 8:10",
     "caption": "Papan pesan hari Minggu 🪧\n\nDalam Yesaya 8, Yehuda sedang terancam oleh bangsa-bangsa yang jauh lebih kuat. Di tengah ketakutan itu, nabi menutup dengan satu kalimat. Dalam bahasa Ibrani, kalimat “Allah menyertai kami” berbunyi immanu el, kata yang sama dengan nama Imanuel. Rancangan manusia bisa menakutkan, tapi bukan mereka yang punya kata terakhir.\n\n📖 “Buatlah rancangan, tetapi akan gagal juga; ambillah keputusan, tetapi tidak terlaksana juga, sebab Allah menyertai kami!” — Yesaya 8:10\n\nKetik “Imanuel” kalau hari ini kamu mau mengingat bahwa Allah beserta kita."},
    {"teks": "BEKERJALAH,\nSEBAB AKU INI\nMENYERTAI\nKAMU.",
     "ayat": "“…kuatkanlah hatimu, hai segala rakyat negeri, demikianlah firman TUHAN; bekerjalah, sebab Aku ini menyertai kamu, demikianlah firman TUHAN semesta alam,”",
     "ref": "Hagai 2:5",
     "caption": "Papan pesan untuk Senin pagi 🪧\n\nUmat yang pulang dari pembuangan sedang membangun kembali rumah Tuhan. Hasilnya terlihat kecil dan mengecewakan dibanding kemegahan yang dulu. Tuhan tidak menyuruh mereka berhenti. Ia menyuruh mereka bekerja, dan memberi alasan yang paling kuat: Aku ini menyertai kamu. Kantor, kampus, dapur, atau jalanan macet, kamu tidak bekerja sendirian.\n\n📖 “…kuatkanlah hatimu, hai segala rakyat negeri, demikianlah firman TUHAN; bekerjalah, sebab Aku ini menyertai kamu, demikianlah firman TUHAN semesta alam,” — Hagai 2:5\n\nKetik “Aku tidak sendirian” sebelum mulai bekerja hari ini."},
    {"teks": "DIA TINGGAL\nBERSAMA\nORANG YANG\nREMUK HATI.",
     "ayat": "“…Aku bersemayam di tempat tinggi dan di tempat kudus tetapi juga bersama-sama orang yang remuk dan rendah hati, untuk menghidupkan semangat orang-orang yang rendah hati…”",
     "ref": "Yesaya 57:15",
     "caption": "Untuk kamu yang merasa sepi hari ini 🪧\n\nAllah yang Mahatinggi dan Mahakudus punya dua tempat kediaman: tempat yang tinggi dan kudus, dan bersama orang yang remuk hatinya. Kesepian sering membuat kita merasa tidak terlihat. Tapi justru kepada hati yang remuk itulah Ia memilih untuk dekat.\n\n📖 “…Aku bersemayam di tempat tinggi dan di tempat kudus tetapi juga bersama-sama orang yang remuk dan rendah hati, untuk menghidupkan semangat orang-orang yang rendah hati…” — Yesaya 57:15\n\nKalau hari ini hatimu sedang remuk, tulis 🤍 di komentar. Kami ikut mendoakan."},
    {"teks": "TIDAK BAIK\nKALAU MANUSIA\nSEORANG DIRI\nSAJA.",
     "ayat": "“TUHAN Allah berfirman: ‘Tidak baik, kalau manusia itu seorang diri saja. Aku akan menjadikan penolong baginya, yang sepadan dengan dia.’”",
     "ref": "Kejadian 2:18",
     "caption": "Papan pesan hari Rabu 🪧\n\nSebelum ada dosa di dunia, sudah ada satu hal yang Tuhan sebut tidak baik: manusia yang seorang diri. Ayat ini berbicara tentang Adam dan Hawa, awal dari pernikahan. Tapi di baliknya ada kebenaran yang lebih luas: kita diciptakan untuk hidup bersama, bukan sendirian. Butuh teman bukan tanda iman yang lemah. Itu bagian dari cara Tuhan menciptakan kita.\n\n📖 “TUHAN Allah berfirman: ‘Tidak baik, kalau manusia itu seorang diri saja. Aku akan menjadikan penolong baginya, yang sepadan dengan dia.’” — Kejadian 2:18\n\nTag satu teman yang membuat hidupmu tidak “seorang diri” 👇"},
    {"teks": "TUHAN ITU\nPENYAYANG.\nIA TIDAK AKAN\nMENINGGALKAN\nENGKAU.",
     "ayat": "“Sebab TUHAN, Allahmu, adalah Allah Penyayang, Ia tidak akan meninggalkan atau memusnahkan engkau dan Ia tidak akan melupakan perjanjian yang diikrarkan-Nya dengan sumpah kepada nenek moyangmu.”",
     "ref": "Ulangan 4:31",
     "caption": "Papan pesan hari Kamis 🪧\n\nMusa mengucapkan kalimat ini kepada umat yang ia tahu akan jatuh dan tercerai-berai. Bahkan untuk masa-masa terburuk mereka, alasannya tetap sama: TUHAN adalah Allah Penyayang. Ia tetap setia, bukan karena kita selalu setia, tapi karena Ia tidak melupakan janji-Nya.\n\n📖 “Sebab TUHAN, Allahmu, adalah Allah Penyayang, Ia tidak akan meninggalkan atau memusnahkan engkau dan Ia tidak akan melupakan perjanjian yang diikrarkan-Nya dengan sumpah kepada nenek moyangmu.” — Ulangan 4:31\n\nKetik “Dia Penyayang” kalau hari ini kamu butuh diingatkan."},
    {"teks": "SELAMAT HARI\nANAK SEDUNIA,\nANAK-ANAK\nALLAH!",
     "ayat": "“Sebab kamu semua adalah anak-anak Allah karena iman di dalam Yesus Kristus.”",
     "ref": "Galatia 3:26",
     "caption": "Selamat Hari Anak Sedunia 🪧\n\nHari ini dunia memperhatikan anak-anak, dan kita ikut mendoakan mereka. Tapi ada juga kabar untuk kita yang sudah dewasa: di dalam Yesus, kita adalah anak-anak Allah. Bukan karena prestasi, keturunan, atau umur, tapi karena iman kepada Kristus. Status itu adalah pemberian, bukan upah.\n\n📖 “Sebab kamu semua adalah anak-anak Allah karena iman di dalam Yesus Kristus.” — Galatia 3:26\n\nKetik “Anak Bapa” kalau kamu bersyukur untuk status ini 🤍"},
    {"teks": "BESOK MINGGU\nKRISTUS RAJA.\nSIAPKAN\nHATIMU.",
     "ayat": "“Angkatlah kepalamu, hai pintu-pintu gerbang, dan terangkatlah kamu, hai pintu-pintu yang berabad-abad, supaya masuk Raja Kemuliaan!”",
     "ref": "Mazmur 24:7",
     "caption": "Papan pesan hari Sabtu 🪧\n\nMazmur 24 adalah nyanyian untuk menyambut Raja Kemuliaan masuk. Pintu-pintu gerbang kuno pun disuruh mengangkat kepala, seolah terlalu rendah untuk Raja sebesar itu. Besok banyak gereja merayakan Minggu Kristus Raja. Hari ini, siapkan hati dan waktumu untuk menyambut-Nya dalam ibadah.\n\n📖 “Angkatlah kepalamu, hai pintu-pintu gerbang, dan terangkatlah kamu, hai pintu-pintu yang berabad-abad, supaya masuk Raja Kemuliaan!” — Mazmur 24:7\n\nKetik “Siap menyambut” kalau besok kamu mau beribadah 👑"},
]

# ---------- KUIS: kuis Alkitab 2 slide (pagi2 hari 2, 3, 5, 6) ----------
KUIS = [
    {"tanya": "Sebelum mulai mengajar di depan umum, Yesus dikenal orang sekampung-Nya sebagai apa?",
     "pilihan": ["Nelayan", "Tukang kayu", "Pemungut cukai", "Gembala domba"],
     "jawab": 1,
     "penjelasan": "Orang-orang Nazaret menyebut Yesus tukang kayu. Ia tahu rasanya bekerja dengan tangan, lelah, dan menjalani hari biasa.",
     "ayat": "“Bukankah Ia ini tukang kayu, anak Maria, saudara Yakobus, Yoses, Yudas dan Simon?…”",
     "ref": "Markus 6:3",
     "caption": "Kuis Senin: kamu tahu jawabannya? 🧠\n\nSebelum geser ke slide berikutnya, tulis dulu jawabanmu di komentar: A, B, C, atau D.\n\nYesus tidak datang hanya untuk saat-saat rohani yang besar. Ia pernah menjalani hari kerja biasa di Nazaret, bertahun-tahun sebelum orang banyak mengenal-Nya. Karena itu Ia mengerti hari Senin-mu.\n\n📖 “Bukankah Ia ini tukang kayu, anak Maria, saudara Yakobus, Yoses, Yudas dan Simon?…” — Markus 6:3\n\nTulis A, B, C, atau D di komentar, lalu geser untuk jawabannya 👇"},
    {"tanya": "Elia pernah merasa tinggal seorang diri. Siapa yang kemudian mengikuti dan melayani dia?",
     "pilihan": ["Gehazi", "Obaja", "Natan", "Elisa"],
     "jawab": 3,
     "penjelasan": "Elia berkata hanya dia seorang diri yang masih hidup. Tuhan menjawab, antara lain dengan memanggil Elisa untuk menyertainya.",
     "ayat": "“…Sesudah itu bersiaplah ia, lalu mengikuti Elia dan menjadi pelayannya.”",
     "ref": "1 Raja-raja 19:21",
     "caption": "Kuis Selasa 🧠\n\nTebak dulu di komentar, A, B, C, atau D, sebelum geser ke jawaban.\n\nElia baru saja melewati kemenangan besar, lalu lari ketakutan dan merasa hanya dia yang tersisa. Tuhan memberinya makan, menemuinya dalam bunyi angin sepoi-sepoi basa, lalu memberinya seorang teman seperjalanan. Kesepian Elia dijawab bukan hanya dengan kata-kata, tapi juga dengan kehadiran seseorang.\n\n📖 “…Sesudah itu bersiaplah ia, lalu mengikuti Elia dan menjadi pelayannya.” — 1 Raja-raja 19:21\n\nTulis jawabanmu di komentar 👇 lalu kirim ke teman yang sedang merasa sendirian 💌"},
    {"tanya": "Berapa lama Tuhan memelihara Israel di padang gurun tanpa meninggalkan mereka?",
     "pilihan": ["40 tahun", "7 tahun", "12 tahun", "70 tahun"],
     "jawab": 0,
     "penjelasan": "Empat puluh tahun di padang gurun. Tiang awan pada siang hari dan tiang api pada malam hari tidak berpindah dari atas mereka.",
     "ayat": "“Empat puluh tahun lamanya Engkau memberikan mereka makan di padang gurun… pakaian mereka tidak rusak, dan kaki mereka tidak bengkak.”",
     "ref": "Nehemia 9:21",
     "caption": "Kuis Kamis 🧠\n\nJawab dulu di komentar, A, B, C, atau D, lalu geser.\n\nOrang Israel sering mengeluh, memberontak, bahkan membuat anak lembu tuangan. Tapi doa panjang dalam kitab Nehemia mengingat hal yang luar biasa: selama itu Tuhan tetap memberi makan, menjaga, dan menuntun mereka. Kesetiaan-Nya lebih panjang dari ketidaksetiaan umat-Nya.\n\n📖 “Empat puluh tahun lamanya Engkau memberikan mereka makan di padang gurun… pakaian mereka tidak rusak, dan kaki mereka tidak bengkak.” — Nehemia 9:21\n\nTulis jawabanmu 👇 dan save kuis ini untuk dimainkan bersama keluarga 🔖"},
    {"tanya": "Siapa yang dipanggil TUHAN saat masih muda, lalu menjawab: “Berbicaralah, sebab hamba-Mu ini mendengar”?",
     "pilihan": ["Daud", "Yosia", "Samuel", "Yeremia"],
     "jawab": 2,
     "penjelasan": "Samuel masih muda dan melayani TUHAN di bawah pengawasan Eli ketika TUHAN memanggil namanya. Tuhan tidak menunggunya dewasa.",
     "ayat": "“Lalu datanglah TUHAN, berdiri di sana dan memanggil… ‘Samuel! Samuel!’ Dan Samuel menjawab: ‘Berbicaralah, sebab hamba-Mu ini mendengar.’”",
     "ref": "1 Samuel 3:10",
     "caption": "Kuis Hari Anak Sedunia 🧠\n\nTebak dulu di komentar, A, B, C, atau D, lalu geser untuk melihat jawabannya.\n\nTuhan tidak menunggu seseorang menjadi dewasa, hebat, atau berpengalaman untuk berbicara kepadanya. Ia memanggil seorang anak muda pada waktu malam, sampai empat kali. Anak-anak bukan hanya masa depan gereja. Mereka juga bagian dari umat Tuhan hari ini.\n\n📖 “Lalu datanglah TUHAN, berdiri di sana dan memanggil… ‘Samuel! Samuel!’ Dan Samuel menjawab: ‘Berbicaralah, sebab hamba-Mu ini mendengar.’” — 1 Samuel 3:10\n\nTulis jawabanmu 👇 dan tag guru sekolah minggu yang masih kamu ingat 🤍"},
]

# ---------- STICKY: catatan tempel di pintu kulkas (siang0 10:30) ----------
STICKY = [
    {"catatan": ["Ibadah pagi: Dia sudah di sana duluan", "Bilang ke diri sendiri: aku tidak sendirian", "Imanuel = Allah beserta kita. Hafalkan!"],
     "ayat": "“TUHAN semesta alam menyertai kita, kota benteng kita ialah Allah Yakub.”",
     "ref": "Mazmur 46:8",
     "caption": "Catatan tempel di pintu kulkas 📌\n\nMazmur 46 ditulis untuk umat yang melihat dunia seolah sedang runtuh: gunung goncang, laut bergelora. Tapi dua kali mazmur ini mengulang kalimat yang sama, seperti catatan yang ditempel supaya tidak lupa: TUHAN semesta alam menyertai kita.\n\n📖 “TUHAN semesta alam menyertai kita, kota benteng kita ialah Allah Yakub.” — Mazmur 46:8\n\nSave dan jadikan wallpaper HP-mu minggu ini 🔖"},
    {"catatan": ["Doa dulu, baru buka laptop", "Tugas kuliah dan kerjaan: kerjakan dengan setia", "Cuci piring sambil ngobrol sama Tuhan"],
     "ayat": "“…Allah menyertai engkau dalam segala sesuatu yang engkau lakukan.”",
     "ref": "Kejadian 21:22",
     "caption": "Catatan untuk hari Senin 📌\n\nAbimelekh adalah raja Gerar, bukan bagian dari umat Allah. Tapi setelah melihat kehidupan Abraham dari dekat, ia bisa menyimpulkan satu hal: Allah menyertai orang ini. Penyertaan Tuhan tidak hanya terlihat di saat-saat besar. Kadang justru paling jelas di hari-hari biasa.\n\n📖 “…Allah menyertai engkau dalam segala sesuatu yang engkau lakukan.” — Kejadian 21:22\n\nTulis satu tugas biasa yang mau kamu kerjakan bersama Tuhan hari ini 👇"},
    {"catatan": ["Sepi bukan berarti ditinggalkan", "Telepon satu teman lama, walau canggung", "Yesus juga pernah ditinggal sendirian. Dia mengerti."],
     "ayat": "“…kamu meninggalkan Aku seorang diri. Namun Aku tidak seorang diri, sebab Bapa menyertai Aku.”",
     "ref": "Yohanes 16:32",
     "caption": "Catatan untuk hari yang sepi 📌\n\nMalam sebelum disalibkan, Yesus tahu murid-murid-Nya akan tercerai-berai dan meninggalkan Dia. Ia tahu rasanya ditinggal. Tapi Ia juga tahu satu hal yang lebih dalam dari rasa sepi: Bapa menyertai-Nya. Di dalam Yesus, kita pun tidak pernah sungguh-sungguh sendirian.\n\n📖 “…kamu meninggalkan Aku seorang diri. Namun Aku tidak seorang diri, sebab Bapa menyertai Aku.” — Yohanes 16:32\n\nKirim catatan ini ke teman yang sedang merasa sepi 💌"},
    {"catatan": ["Tanya kabar Rina, lalu benar-benar dengarkan", "Bawa camilan untuk persekutuan Rabu malam", "Minta didoakan. Tidak usah gengsi."],
     "ayat": "“Dan marilah kita saling memperhatikan supaya kita saling mendorong dalam kasih dan dalam pekerjaan baik.”",
     "ref": "Ibrani 10:24",
     "caption": "Catatan tempel hari Rabu 📌\n\nPenulis Ibrani tidak hanya menyuruh kita saling mengasihi. Ia mengajak kita saling memperhatikan, artinya sengaja memikirkan cara untuk mendorong orang lain. Persahabatan dalam Kristus jarang terjadi secara kebetulan. Biasanya dimulai dari satu pesan, satu sapaan, satu kunjungan.\n\n📖 “Dan marilah kita saling memperhatikan supaya kita saling mendorong dalam kasih dan dalam pekerjaan baik.” — Ibrani 10:24\n\nTulis satu nama teman yang mau kamu sapa hari ini 👇"},
    {"catatan": ["Kemarin berat, tapi Dia tetap ada", "Jangan percaya bisikan: kamu sendirian", "Kerjakan bagianmu. Dia tidak pergi."],
     "ayat": "“…janganlah takut dan janganlah tawar hati, sebab TUHAN Allah, Allahku, menyertai engkau. Ia tidak akan membiarkan dan meninggalkan engkau…”",
     "ref": "1 Tawarikh 28:20",
     "caption": "Catatan untuk hari Kamis 📌\n\nDaud menitipkan pekerjaan besar kepada Salomo, anaknya: membangun rumah Tuhan. Tugas itu terlalu besar untuk orang muda yang kurang berpengalaman. Daud tidak berkata semuanya akan mudah. Ia mengingatkan sesuatu yang lebih kuat: Tuhan tidak akan membiarkan dan meninggalkan engkau.\n\n📖 “…janganlah takut dan janganlah tawar hati, sebab TUHAN Allah, Allahku, menyertai engkau. Ia tidak akan membiarkan dan meninggalkan engkau…” — 1 Tawarikh 28:20\n\nKetik “Dia tidak pergi” kalau hari ini kamu sedang memikul tugas berat."},
    {"catatan": ["Telepon Mama, bilang terima kasih", "Doakan anak-anak sekolah minggu", "Aku juga anak. Boleh bersandar pada Bapa."],
     "ayat": "“Roh itu bersaksi bersama-sama dengan roh kita, bahwa kita adalah anak-anak Allah.”",
     "ref": "Roma 8:16",
     "caption": "Catatan untuk Hari Anak Sedunia 📌\n\nKadang kita lupa siapa diri kita. Kita merasa harus membuktikan diri, takut ditolak, atau merasa belum cukup baik. Paulus menulis bahwa Roh Kudus sendiri meneguhkan dalam hati kita: kita anak-anak Allah. Bukan pegawai yang harus terus berprestasi, tapi anak yang dikasihi.\n\n📖 “Roh itu bersaksi bersama-sama dengan roh kita, bahwa kita adalah anak-anak Allah.” — Roma 8:16\n\nSave catatan ini untuk hari-hari ketika kamu lupa siapa dirimu 🔖"},
    {"catatan": ["Setrika baju untuk ibadah besok", "Tidur sebelum jam 11 malam", "Rajaku mendengar doaku. Dia dekat."],
     "ayat": "“Perhatikanlah teriakku minta tolong, ya Rajaku dan Allahku, sebab kepada-Mulah aku berdoa.”",
     "ref": "Mazmur 5:3",
     "caption": "Catatan untuk hari Sabtu 📌\n\nDaud adalah raja, tapi ia tahu ada Raja yang lebih tinggi. Ia menyebut Tuhan Rajaku dan Allahku, lalu membawa teriakannya kepada-Nya. Raja ini tidak terlalu sibuk untuk mendengar rakyat-Nya. Besok, datanglah beribadah kepada Raja yang mau mendengar.\n\n📖 “Perhatikanlah teriakku minta tolong, ya Rajaku dan Allahku, sebab kepada-Mulah aku berdoa.” — Mazmur 5:3\n\nKetik “Rajaku” dan siapkan hatimu untuk ibadah besok ⛪"},
]

# ---------- MENU: papan menu kapur di kafe (siang 12:00) ----------
MENU = [
    {"judul": "MENU HARI MINGGU",
     "item": [["Imanuel", "Allah yang datang dan tinggal dekat", "GRATIS"], ["Kristus di tengahmu", "pengharapan akan kemuliaan", "ANUGERAH"], ["Damai dengan Allah", "dibayar oleh Yesus", "LUNAS"], ["Penyertaan-Nya", "Senin sampai Minggu", "TERSEDIA"]],
     "ayat": "“…Kristus ada di tengah-tengah kamu, Kristus yang adalah pengharapan akan kemuliaan!”",
     "ref": "Kolose 1:27",
     "caption": "Menu hari Minggu, semuanya sudah dibayar ☕\n\nPaulus menyebut ini sebuah rahasia yang dulu tersembunyi lalu sekarang dinyatakan: Kristus ada di tengah-tengah kamu. Allah tidak hanya mengirim hadiah dari jauh. Ia memberikan diri-Nya sendiri, dan tinggal di tengah umat-Nya.\n\n📖 “…Kristus ada di tengah-tengah kamu, Kristus yang adalah pengharapan akan kemuliaan!” — Kolose 1:27\n\nPilih satu menu yang paling kamu butuhkan hari ini, tulis di komentar 👇"},
    {"judul": "MENU MAKAN SIANG",
     "item": [["Nasi hangat", "dinikmati, bukan ditelan sambil kerja", "SYUKUR"], ["Jeda 15 menit", "tarik napas, lalu berterima kasih", "GRATIS"], ["Kekuatan untuk sore", "dari Dia yang menyertai", "ANUGERAH"], ["Kerja yang bermakna", "dikerjakan untuk Tuhan", "BERHARGA"]],
     "ayat": "“…makan dan minum dan bersenang-senang dalam jerih payahnya. Aku menyadari bahwa inipun dari tangan Allah.”",
     "ref": "Pengkhotbah 2:24",
     "caption": "Menu makan siang hari Senin 🍽️\n\nPengkhotbah banyak menulis tentang hidup yang terasa sia-sia. Tapi di tengahnya ia menemukan hal sederhana: makan, minum, dan menikmati hasil kerja adalah pemberian dari tangan Allah. Jadi jangan lewatkan makan siangmu sambil terus menatap layar. Berhenti sebentar, bersyukur, lalu nikmati.\n\n📖 “…makan dan minum dan bersenang-senang dalam jerih payahnya. Aku menyadari bahwa inipun dari tangan Allah.” — Pengkhotbah 2:24\n\nKirim ke teman kantor atau kampus yang suka lupa makan 💌"},
    {"judul": "MENU UNTUK HATI SEPI",
     "item": [["Teh hangat", "diminum sambil bercerita kepada-Nya", "GRATIS"], ["Tempat untuk pulang", "bagi yang merasa sebatang kara", "ANUGERAH"], ["Bapa bagi yatim", "dan Pelindung bagi para janda", "SETIA"], ["Kehadiran Yesus", "Ia mendekati yang tersisih", "GRATIS"]],
     "ayat": "“Allah memberi tempat tinggal kepada orang-orang sebatang kara, Ia mengeluarkan orang-orang tahanan, sehingga mereka bahagia…”",
     "ref": "Mazmur 68:7",
     "caption": "Menu khusus untuk hati yang sepi 🍵\n\nMazmur 68 menggambarkan Allah yang perkasa, yang berjalan di depan umat-Nya. Tapi di tengah pujian tentang kuasa-Nya, pemazmur menyebut siapa yang Ia perhatikan: anak yatim, para janda, dan orang-orang sebatang kara. Allah yang Mahabesar tidak terlalu sibuk untuk orang yang sendirian.\n\n📖 “Allah memberi tempat tinggal kepada orang-orang sebatang kara, Ia mengeluarkan orang-orang tahanan, sehingga mereka bahagia…” — Mazmur 68:7\n\nTulis 🍵 di komentar kalau hari ini kamu merasa sepi. Kami ikut mendoakan."},
    {"judul": "MENU PERSEKUTUAN",
     "item": [["Pengajaran firman", "dinikmati bersama, bukan sendiri", "GRATIS"], ["Persekutuan", "saling menanggung beban", "ANUGERAH"], ["Memecahkan roti", "satu meja, satu Tuhan", "BERBAGI"], ["Doa bersama", "untuk teman yang sedang berat", "SELALU"]],
     "ayat": "“Mereka bertekun dalam pengajaran rasul-rasul dan dalam persekutuan. Dan mereka selalu berkumpul untuk memecahkan roti dan berdoa.”",
     "ref": "Kisah Para Rasul 2:42",
     "caption": "Menu jemaat mula-mula ☕\n\nGereja pertama tidak punya gedung megah atau program yang rumit. Tapi ada empat hal yang terus mereka tekuni bersama: pengajaran, persekutuan, makan bersama, dan doa. Iman memang pribadi, tapi tidak pernah dimaksudkan untuk dijalani sendirian.\n\n📖 “Mereka bertekun dalam pengajaran rasul-rasul dan dalam persekutuan. Dan mereka selalu berkumpul untuk memecahkan roti dan berdoa.” — Kisah Para Rasul 2:42\n\nAjak satu teman ke persekutuan minggu ini, lalu tag dia di komentar 👇"},
    {"judul": "MENU KESETIAAN",
     "item": [["Kasih setia-Nya", "tidak habis-habisnya", "GRATIS"], ["Pegangan tangan-Nya", "tidak dilepas di hari buruk", "ANUGERAH"], ["Janji yang ditepati", "dari dulu sampai sekarang", "PASTI"], ["Status milik-Nya", "tidak akan ditinggalkan-Nya", "LUNAS"]],
     "ayat": "“Sebab TUHAN tidak akan membuang umat-Nya, dan milik-Nya sendiri tidak akan ditinggalkan-Nya;”",
     "ref": "Mazmur 94:14",
     "caption": "Menu hari Kamis, disajikan setia setiap hari ☕\n\nMazmur 94 ditulis di tengah ketidakadilan, saat orang jahat seolah menang. Pemazmur sempat merasa kakinya goyang. Tapi ia berpegang pada satu kepastian: TUHAN tidak akan membuang umat-Nya. Perasaan kita bisa naik-turun, tapi status kita sebagai milik-Nya tidak ditentukan oleh perasaan.\n\n📖 “Sebab TUHAN tidak akan membuang umat-Nya, dan milik-Nya sendiri tidak akan ditinggalkan-Nya;” — Mazmur 94:14\n\nKetik “Milik-Nya” kalau hari ini kamu perlu diingatkan 🤍"},
    {"judul": "MENU ANAK-ANAK",
     "item": [["Pelukan Yesus", "untuk anak-anak yang dibawa kepada-Nya", "GRATIS"], ["Berkat dari tangan-Nya", "diletakkan atas yang kecil", "ANUGERAH"], ["Hak jadi anak Allah", "bagi yang menerima Dia", "DIBERIKAN"], ["Tempat di Kerajaan", "untuk yang datang seperti anak kecil", "GRATIS"]],
     "ayat": "“Lalu Ia memeluk anak-anak itu dan sambil meletakkan tangan-Nya atas mereka Ia memberkati mereka.”",
     "ref": "Markus 10:16",
     "caption": "Menu Hari Anak Sedunia 🧸\n\nYesus tidak sekadar mengizinkan anak-anak datang. Ia memeluk mereka, meletakkan tangan-Nya atas mereka, dan memberkati mereka. Tidak ada biaya pendaftaran, tidak ada syarat harus pintar atau berprestasi. Begitulah Yesus menyambut yang kecil, dan begitulah Ia menyambut kita.\n\n📖 “Lalu Ia memeluk anak-anak itu dan sambil meletakkan tangan-Nya atas mereka Ia memberkati mereka.” — Markus 10:16\n\nTag orang tua, guru, atau kakak yang pernah mengenalkanmu kepada Yesus 👇"},
    {"judul": "PERJAMUAN SANG RAJA",
     "item": [["Undangan pribadi", "untuk siapa saja di persimpangan jalan", "GRATIS"], ["Kursi di meja-Nya", "tidak perlu layak dulu", "ANUGERAH"], ["Roti hidup", "Yesus sendiri, Sang Raja", "GRATIS"], ["Damai sejahtera", "dari Raja Damai", "LUNAS"]],
     "ayat": "“Sebab itu pergilah ke persimpangan-persimpangan jalan dan undanglah setiap orang yang kamu jumpai di sana ke perjamuan kawin itu.”",
     "ref": "Matius 22:9",
     "caption": "Undangan perjamuan dari Sang Raja 👑\n\nDalam perumpamaan Yesus, seorang raja mengadakan perjamuan kawin untuk anaknya. Tamu-tamu yang diundang menolak datang. Maka raja menyuruh hamba-hambanya pergi ke persimpangan jalan dan mengundang siapa saja yang mereka jumpai. Besok Minggu Kristus Raja. Undangan untuk datang menyembah-Nya juga terbuka untukmu.\n\n📖 “Sebab itu pergilah ke persimpangan-persimpangan jalan dan undanglah setiap orang yang kamu jumpai di sana ke perjamuan kawin itu.” — Matius 22:9\n\nAjak satu teman ke ibadah besok, lalu tag dia di komentar 👇"},
]

# ---------- SEARCH: Reel kolom pencarian + hasil (siang2 13:30) ----------
SEARCH = [
    {"cari": "apakah tuhan benar-benar dekat",
     "saran": ["apakah tuhan benar-benar dekat denganku", "apakah tuhan benar-benar dengar doaku", "apakah tuhan benar-benar peduli"],
     "hasil": [["Imanuel: Allah yang memilih datang dekat", "Natal adalah bukti bahwa Allah tidak menonton dari jauh. Ia datang dan tinggal di tengah kita."], ["Dekat, bahkan saat tidak terasa", "Perasaan bisa naik-turun, janji-Nya tidak. Ia dekat setiap kali kita memanggil-Nya."]],
     "ayat": "“Sebab bangsa besar manakah yang mempunyai allah yang demikian dekat kepadanya seperti TUHAN, Allah kita, setiap kali kita memanggil kepada-Nya?”",
     "ref": "Ulangan 4:7",
     "caption": "Pertanyaan yang diam-diam sering kita ketik 🔍\n\nAda hari-hari ketika Tuhan terasa sangat jauh. Musa mengingatkan Israel bahwa hal yang paling istimewa dari mereka bukan kekuatan atau kebesaran mereka, melainkan Allah yang begitu dekat. Di dalam Yesus, Imanuel, kedekatan itu menjadi nyata: Allah datang dan tinggal di tengah kita.\n\n📖 “Sebab bangsa besar manakah yang mempunyai allah yang demikian dekat kepadanya seperti TUHAN, Allah kita, setiap kali kita memanggil kepada-Nya?” — Ulangan 4:7\n\nKetik “Dia dekat” kalau kamu mau mempercayainya hari ini."},
    {"cari": "capek kerja tapi tidak dihargai",
     "saran": ["capek kerja tapi tidak dihargai atasan", "capek kerja tapi tidak dihargai keluarga", "capek kuliah sambil kerja"],
     "hasil": [["Untuk siapa sebenarnya kamu bekerja?", "Atasan mungkin tidak melihat. Tuhan melihat setiap pekerjaan yang dikerjakan dengan setia."], ["Yesus juga pernah bekerja dengan tangan-Nya", "Ia mengerti lelahnya hari kerja biasa, dan Ia menyertaimu di dalamnya."]],
     "ayat": "“Kamu tahu, bahwa dari Tuhanlah kamu akan menerima bagian yang ditentukan bagimu sebagai upah. Kristus adalah tuan dan kamu hamba-Nya.”",
     "ref": "Kolose 3:24",
     "caption": "Untuk kamu yang lelah dan merasa tidak terlihat 🔍\n\nPaulus menulis ayat ini kepada para hamba, orang-orang yang kerja kerasnya jarang dihargai. Ia tidak berkata pekerjaan mereka tidak penting. Ia berkata ada Tuan yang lebih tinggi yang melihat semuanya: Kristus sendiri. Hari ini, kerjakan bagianmu dengan setia. Dia melihat.\n\n📖 “Kamu tahu, bahwa dari Tuhanlah kamu akan menerima bagian yang ditentukan bagimu sebagai upah. Kristus adalah tuan dan kamu hamba-Nya.” — Kolose 3:24\n\nKirim ke teman yang sedang lelah di tempat kerjanya 💌"},
    {"cari": "kenapa aku merasa sendirian",
     "saran": ["kenapa aku merasa sendirian terus", "kenapa aku merasa sendirian di rumah", "kenapa aku merasa sendirian di gereja"],
     "hasil": [["Daud juga pernah merasa tidak ada yang peduli", "Ia tidak menyembunyikan rasa sepinya. Ia membawanya kepada Tuhan dalam doa."], ["Merasa sendirian tidak sama dengan ditinggalkan", "Perasaan sepi itu nyata, tapi bukan kata terakhir. Tuhan tetap hadir, bahkan saat sunyi."]],
     "ayat": "“Pandanglah ke kanan dan lihatlah, tidak ada seorangpun yang menghiraukan aku… Aku berseru-seru kepada-Mu, ya TUHAN, kataku: ‘Engkaulah tempat perlindunganku, bagianku di negeri orang-orang hidup!’”",
     "ref": "Mazmur 142:5-6",
     "caption": "Kalau ini yang sering kamu cari, kamu tidak sendirian 🔍\n\nMazmur 142 adalah doa Daud ketika ia berada di dalam gua. Ia jujur: tidak ada seorang pun yang menghiraukan aku. Tapi ia tidak berhenti di situ. Ia membawa rasa sepinya kepada Tuhan dan menyebut Tuhan sebagai bagiannya. Kesepian boleh diakui, lalu dibawa kepada-Nya.\n\n📖 “Pandanglah ke kanan dan lihatlah, tidak ada seorangpun yang menghiraukan aku… Aku berseru-seru kepada-Mu, ya TUHAN, kataku: ‘Engkaulah tempat perlindunganku, bagianku di negeri orang-orang hidup!’” — Mazmur 142:5-6\n\nKalau hari ini kamu merasa sendirian, tulis 🤍 di komentar. Kami ikut mendoakan."},
    {"cari": "susah dapat teman di gereja",
     "saran": ["susah dapat teman di gereja baru", "susah dapat teman setelah lulus", "susah dapat teman yang seiman"],
     "hasil": [["Gereja adalah tubuh, bukan penonton", "Setiap anggota saling membutuhkan. Kehadiranmu juga dibutuhkan orang lain."], ["Mulai dari satu orang", "Persahabatan jarang dimulai dari acara besar. Biasanya dari satu sapaan sesudah ibadah."]],
     "ayat": "“Karena itu jika satu anggota menderita, semua anggota turut menderita; jika satu anggota dihormati, semua anggota turut bersukacita.”",
     "ref": "1 Korintus 12:26",
     "caption": "Untuk kamu yang masih mencari tempat di komunitas 🔍\n\nPaulus menggambarkan jemaat seperti satu tubuh. Kalau satu anggota menderita, seluruh tubuh ikut merasakannya. Artinya, di dalam tubuh Kristus tidak ada yang seharusnya menderita sendirian, dan tidak ada yang bersukacita sendirian. Mencari teman memang butuh waktu dan keberanian. Tapi kamu memang dipanggil menjadi bagian dari tubuh itu.\n\n📖 “Karena itu jika satu anggota menderita, semua anggota turut menderita; jika satu anggota dihormati, semua anggota turut bersukacita.” — 1 Korintus 12:26\n\nKetik “Aku mau terlibat” kalau minggu ini kamu mau mencoba menyapa satu orang di gereja."},
    {"cari": "apakah tuhan bisa meninggalkan aku",
     "saran": ["apakah tuhan bisa meninggalkan umatnya", "apakah tuhan bisa marah selamanya", "apakah tuhan bisa lelah denganku"],
     "hasil": [["Tidak ada yang bisa merebutmu dari tangan Bapa", "Yesus sendiri yang mengatakannya. Pegangan-Nya lebih kuat dari kegagalan dan ketakutanmu."], ["Saat kamu merasa jauh", "Merasa jauh tidak sama dengan ditinggalkan. Kesetiaan-Nya tidak bergantung pada kuatnya imanmu."]],
     "ayat": "“Bapa-Ku, yang memberikan mereka kepada-Ku, lebih besar dari pada siapapun, dan seorangpun tidak dapat merebut mereka dari tangan Bapa.”",
     "ref": "Yohanes 10:29",
     "caption": "Pertanyaan yang kadang muncul di hari-hari terburuk 🔍\n\nYesus menyebut orang-orang yang mengikut Dia sebagai domba-domba-Nya. Lalu Ia berkata tidak ada seorang pun yang dapat merebut mereka dari tangan Bapa. Bukan karena genggaman kita yang kuat, tapi karena Bapa lebih besar dari siapa pun.\n\n📖 “Bapa-Ku, yang memberikan mereka kepada-Ku, lebih besar dari pada siapapun, dan seorangpun tidak dapat merebut mereka dari tangan Bapa.” — Yohanes 10:29\n\nSave ini untuk hari ketika kamu merasa ditinggalkan 🔖"},
    {"cari": "apa artinya jadi anak allah",
     "saran": ["apa artinya jadi anak allah di alkitab", "apa artinya diadopsi oleh allah", "apa artinya punya bapa di sorga"],
     "hasil": [["Bukan hasil usaha, tapi pemberian", "Hak menjadi anak Allah diberikan kepada semua yang menerima Yesus dan percaya dalam nama-Nya."], ["Anak, bukan pegawai", "Pegawai bekerja supaya diterima. Anak bekerja karena sudah diterima dan dikasihi Bapa."]],
     "ayat": "“Tetapi semua orang yang menerima-Nya diberi-Nya kuasa supaya menjadi anak-anak Allah, yaitu mereka yang percaya dalam nama-Nya;”",
     "ref": "Yohanes 1:12",
     "caption": "Pertanyaan bagus untuk Hari Anak Sedunia 🔍\n\nYohanes menulis bahwa Firman itu datang kepada milik kepunyaan-Nya, tapi banyak yang tidak menerima-Nya. Lalu muncul kabar baik ini: siapa pun yang menerima Dia dan percaya dalam nama-Nya diberi kuasa menjadi anak-anak Allah. Bukan karena keturunan atau usaha manusia, melainkan karena Allah.\n\n📖 “Tetapi semua orang yang menerima-Nya diberi-Nya kuasa supaya menjadi anak-anak Allah, yaitu mereka yang percaya dalam nama-Nya;” — Yohanes 1:12\n\nKetik “Aku anak-Nya” kalau kamu sudah menerima Yesus 🤍"},
    {"cari": "malas ke gereja besok",
     "saran": ["malas ke gereja besok harus gimana", "malas ke gereja karena tidak ada teman", "malas ibadah karena capek"],
     "hasil": [["Ibadah adalah menyambut Sang Raja", "Kita datang bukan untuk tampil, tapi untuk bersyukur kepada Raja yang lebih dulu datang kepada kita."], ["Datang apa adanya", "Kamu tidak perlu menunggu semangat atau merasa layak. Raja itu sendiri yang mengundang."]],
     "ayat": "“Jadi, karena kita menerima kerajaan yang tidak tergoncangkan, marilah kita mengucap syukur dan beribadah kepada Allah menurut cara yang berkenan kepada-Nya, dengan hormat dan takut.”",
     "ref": "Ibrani 12:28",
     "caption": "Jujur saja, kadang kita juga mengetiknya 🔍\n\nRasa malas, capek, atau canggung datang ke gereja itu nyata. Tapi penulis Ibrani mengingatkan alasan kita beribadah: kita sudah menerima kerajaan yang tidak tergoncangkan. Ibadah bukan beban tambahan di akhir pekan, tapi ucapan syukur kepada Raja yang memerintah dan tetap dekat.\n\n📖 “Jadi, karena kita menerima kerajaan yang tidak tergoncangkan, marilah kita mengucap syukur dan beribadah kepada Allah menurut cara yang berkenan kepada-Nya, dengan hormat dan takut.” — Ibrani 12:28\n\nKetik “Sampai jumpa di ibadah” kalau besok kamu mau datang 👑"},
]

# ---------- ORNAMEN: hiasan Natal, hitung mundur (sore 15:00) ----------
ORNAMEN = [
    {"angka": 40,
     "tanggal": "Minggu, 15 November",
     "teks": "Imanuel: Allah tidak menolong dari jauh. Ia datang sendiri.",
     "ayat": "“…Sesungguhnya, seorang perempuan muda mengandung dan akan melahirkan seorang anak laki-laki, dan ia akan menamakan Dia Imanuel.”",
     "ref": "Yesaya 7:14",
     "caption": "40 hari lagi 🎄\n\nLebih dari tujuh ratus tahun sebelum Betlehem, Yesaya menyampaikan sebuah tanda kepada Raja Ahas yang ketakutan: seorang anak bernama Imanuel. Matius kemudian melihat nubuat ini digenapi dalam kelahiran Yesus. Nama itu berarti Allah menyertai kita, dan itulah inti Natal.\n\n📖 “…Sesungguhnya, seorang perempuan muda mengandung dan akan melahirkan seorang anak laki-laki, dan ia akan menamakan Dia Imanuel.” — Yesaya 7:14\n\nKetik 🎄 kalau kamu ikut menghitung mundur bersama kami."},
    {"angka": 39,
     "tanggal": "Senin, 16 November",
     "teks": "Kabar Natal pertama datang kepada gembala yang sedang bekerja.",
     "ayat": "“Di daerah itu ada gembala-gembala yang tinggal di padang menjaga kawanan ternak mereka pada waktu malam.”",
     "ref": "Lukas 2:8",
     "caption": "39 hari lagi 🐑\n\nMalaikat tidak menunggu para gembala libur atau datang ke Bait Allah. Kabar terbesar dalam sejarah datang ke padang, di tengah jam kerja malam, kepada orang-orang biasa yang sedang menjaga ternak. Tuhan tahu jalan menuju tempat kerjamu.\n\n📖 “Di daerah itu ada gembala-gembala yang tinggal di padang menjaga kawanan ternak mereka pada waktu malam.” — Lukas 2:8\n\nKetik 🎄 kalau hari ini kamu bekerja dan mau mengingat bahwa Dia dekat."},
    {"angka": 38,
     "tanggal": "Selasa, 17 November",
     "teks": "Terang itu terbit bagi mereka yang diam dalam gelap.",
     "ayat": "“bangsa yang diam dalam kegelapan, telah melihat Terang yang besar… di negeri yang dinaungi maut, telah terbit Terang.”",
     "ref": "Matius 4:16",
     "caption": "38 hari lagi 🕯️\n\nMatius mengutip nubuat Yesaya ketika Yesus mulai tinggal dan melayani di Galilea, wilayah pinggiran yang juga dihuni bangsa-bangsa lain. Terang itu tidak menunggu orang keluar dari kegelapan dulu. Terang itu datang ke tempat mereka berada. Kalau hari ini kamu merasa sepi dan gelap, Natal adalah kabar bahwa Terang itu mau datang ke sana juga.\n\n📖 “bangsa yang diam dalam kegelapan, telah melihat Terang yang besar… di negeri yang dinaungi maut, telah terbit Terang.” — Matius 4:16\n\nKetik 🎄 kalau kamu menantikan Terang itu bersama kami."},
    {"angka": 37,
     "tanggal": "Rabu, 18 November",
     "teks": "Kabar besar itu tidak Maria pikul sendirian. Ada Elisabet.",
     "ayat": "“Dan Maria tinggal kira-kira tiga bulan lamanya bersama dengan Elisabet, lalu pulang kembali ke rumahnya.”",
     "ref": "Lukas 1:56",
     "caption": "37 hari lagi 🤍\n\nSetelah malaikat datang, Maria langsung berangkat ke rumah Elisabet, sanaknya yang juga sedang mengandung secara ajaib. Dua perempuan dengan dua kehamilan yang sulit dijelaskan, saling menguatkan dan memuji Tuhan bersama. Bahkan cerita Natal pun tidak dijalani sendirian.\n\n📖 “Dan Maria tinggal kira-kira tiga bulan lamanya bersama dengan Elisabet, lalu pulang kembali ke rumahnya.” — Lukas 1:56\n\nTag satu teman yang menemanimu di masa sulit 👇"},
    {"angka": 36,
     "tanggal": "Kamis, 19 November",
     "teks": "Lama terasa sunyi, tapi Allah tidak lupa akan janji-Nya.",
     "ayat": "“Ia menolong Israel, hamba-Nya, karena Ia mengingat rahmat-Nya, seperti yang dijanjikan-Nya kepada nenek moyang kita…”",
     "ref": "Lukas 1:54-55",
     "caption": "36 hari lagi ✨\n\nDalam nyanyiannya, Maria melihat jauh ke belakang, sampai kepada Abraham. Berabad-abad janji itu seakan belum juga digenapi. Tapi Allah tidak pernah lupa. Pada waktu-Nya, Ia datang menolong umat-Nya, bukan dengan mengirim bantuan dari jauh, tapi dengan datang sendiri.\n\n📖 “Ia menolong Israel, hamba-Nya, karena Ia mengingat rahmat-Nya, seperti yang dijanjikan-Nya kepada nenek moyang kita…” — Lukas 1:54-55\n\nKetik 🎄 kalau kamu percaya Dia tidak pernah lupa janji-Nya."},
    {"angka": 35,
     "tanggal": "Jumat, 20 November",
     "teks": "Raja semesta memilih datang sebagai seorang bayi.",
     "ayat": "“Dan inilah tandanya bagimu: Kamu akan menjumpai seorang bayi dibungkus dengan lampin dan terbaring di dalam palungan.”",
     "ref": "Lukas 2:12",
     "caption": "35 hari lagi 👶\n\nDi Hari Anak Sedunia, kita mengingat bahwa Anak Allah sendiri pernah menjadi anak kecil. Tanda yang diberikan malaikat bukan istana atau mahkota, tapi seorang bayi yang dibungkus lampin di palungan. Yesus tahu rasanya kecil, bergantung, dan dirawat orang lain.\n\n📖 “Dan inilah tandanya bagimu: Kamu akan menjumpai seorang bayi dibungkus dengan lampin dan terbaring di dalam palungan.” — Lukas 2:12\n\nKetik 🎄 dan doakan satu anak yang kamu kenal hari ini."},
    {"angka": 34,
     "tanggal": "Sabtu, 21 November",
     "teks": "Orang Majus mencari Raja, lalu datang untuk menyembah-Nya.",
     "ayat": "“…Di manakah Dia, raja orang Yahudi yang baru dilahirkan itu? Kami telah melihat bintang-Nya di Timur dan kami datang untuk menyembah Dia.”",
     "ref": "Matius 2:2",
     "caption": "34 hari lagi 👑\n\nOrang-orang Majus menempuh perjalanan jauh dengan satu tujuan: menyembah Raja yang baru lahir. Besok Minggu Kristus Raja. Kita tidak perlu menempuh perjalanan sejauh mereka. Raja itu sudah datang dekat, dan kita diundang untuk menyembah-Nya bersama-sama.\n\n📖 “…Di manakah Dia, raja orang Yahudi yang baru dilahirkan itu? Kami telah melihat bintang-Nya di Timur dan kami datang untuk menyembah Dia.” — Matius 2:2\n\nKetik 👑 kalau besok kamu mau datang menyembah Sang Raja."},
]

# ---------- KODE: editor kode, pseudo-code jenaka (sore2 16:30) ----------
KODE = [
    {"file": "imanuel.py",
     "baris": ["aku = \"lemah, sibuk, kadang lupa\"", "tuhan = \"Imanuel\"  # Allah beserta kita", "for hari in minggu_ini:", "    tuhan.menyertai(aku)", "    # tidak tergantung perasaanku", "if aku.merasa_sendirian():", "    ingat(tuhan)"],
     "ayat": "“Tetapi Aku akan hadir di tengah-tengahmu dan Aku akan menjadi Allahmu dan kamu akan menjadi umat-Ku.”",
     "ref": "Imamat 26:12",
     "caption": "Kode sederhana untuk minggu ini 💻\n\nSejak dulu, kerinduan Allah tetap sama: hadir di tengah umat-Nya. Di padang gurun lewat Kemah Suci, di Betlehem lewat Yesus, dan hari ini lewat Roh Kudus yang tinggal di dalam orang percaya. Perasaan kita bisa berubah-ubah, tapi kehadiran-Nya tidak bergantung pada perasaan kita.\n\n📖 “Tetapi Aku akan hadir di tengah-tengahmu dan Aku akan menjadi Allahmu dan kamu akan menjadi umat-Ku.” — Imamat 26:12\n\nKetik “Imanuel” kalau kode ini juga berlaku untukmu 🤍"},
    {"file": "senin.py",
     "baris": ["def senin(aku):", "    berdoa(\"sebelum buka laptop\")", "    for tugas in daftar_hari_ini:", "        kerjakan(tugas, sekuat_tenaga)", "        # Dia ikut di setiap tugas", "    makan_siang(buru_buru=False)", "    return \"pulang dengan damai\""],
     "ayat": "“Segala sesuatu yang dijumpai tanganmu untuk dikerjakan, kerjakanlah itu sekuat tenaga…”",
     "ref": "Pengkhotbah 9:10",
     "caption": "Program hari Senin 💻\n\nPengkhotbah mengajak kita mengerjakan apa yang ada di depan mata dengan sungguh-sungguh, karena hidup ini singkat. Bukan supaya kita dikasihi Tuhan, tapi karena kita sudah dikasihi dan disertai-Nya. Laporan, tugas kuliah, cucian, atau rapat, semuanya bisa dikerjakan bersama Dia.\n\n📖 “Segala sesuatu yang dijumpai tanganmu untuk dikerjakan, kerjakanlah itu sekuat tenaga…” — Pengkhotbah 9:10\n\nTulis satu tugas hari ini yang mau kamu kerjakan dengan setia 👇"},
    {"file": "sepi.py",
     "baris": ["def merasa_sendirian(aku):", "    # perasaan ini nyata, boleh diakui", "    cerita_ke(tuhan, jujur=True)", "    # Yesus juga pernah ditinggal", "    kirim_pesan(teman_lama)", "    jalan_sore_sebentar()", "    return \"Dia mengerti\""],
     "ayat": "“Sebab Imam Besar yang kita punya, bukanlah imam besar yang tidak dapat turut merasakan kelemahan-kelemahan kita…”",
     "ref": "Ibrani 4:15",
     "caption": "Fungsi untuk hari yang sepi 💻\n\nYesus tidak menonton kesepian kita dari jauh. Ia pernah ditolak orang sekampung-Nya, ditinggal murid-murid-Nya, dan bergumul sendirian di Getsemani sementara sahabat-sahabat-Nya tertidur. Karena itu Ia dapat turut merasakan kelemahan kita. Kamu boleh datang kepada-Nya tanpa harus pura-pura kuat.\n\n📖 “Sebab Imam Besar yang kita punya, bukanlah imam besar yang tidak dapat turut merasakan kelemahan-kelemahan kita…” — Ibrani 4:15\n\nKalau hari ini kamu merasa sepi, ketik 🫂 dan izinkan kami ikut mendoakanmu."},
    {"file": "persekutuan.py",
     "baris": ["teman = [\"Rina\", \"Bayu\", \"Kak Sarah\"]", "for orang in teman:", "    doakan(orang)", "    tanya_kabar(orang, dengarkan=True)", "if beban > kekuatanku:", "    minta_tolong(teman)  # bukan aib", "# tali tiga lembar tak mudah putus"],
     "ayat": "“Dan bilamana seorang dapat dialahkan, dua orang akan dapat bertahan. Tali tiga lembar tak mudah diputuskan.”",
     "ref": "Pengkhotbah 4:12",
     "caption": "Kode persahabatan 💻\n\nPengkhotbah melihat orang yang bekerja keras tanpa henti tapi sendirian, tanpa saudara dan tanpa teman. Lalu ia menyimpulkan: berdua lebih baik dari seorang diri, dan tali tiga lembar tak mudah diputuskan. Kita tidak dirancang untuk menjalani iman sendirian. Minta tolong bukan tanda lemah. Sering kali itulah cara Tuhan menguatkan kita lewat orang lain.\n\n📖 “Dan bilamana seorang dapat dialahkan, dua orang akan dapat bertahan. Tali tiga lembar tak mudah diputuskan.” — Pengkhotbah 4:12\n\nTag dua teman yang jadi tali tiga lembar bersamamu 👇"},
    {"file": "setia.py",
     "baris": ["while True:", "    tuhan.menyertai(kamu)", "    if kamu.jatuh:", "        tuhan.angkat(kamu)", "    if kamu.lupa:", "        tuhan.tetap_ingat(kamu)", "    # tidak ada break di loop ini"],
     "ayat": "“…tetapi Aku, TUHAN, akan menjawab mereka, dan sebagai Allah orang Israel Aku tidak akan meninggalkan mereka.”",
     "ref": "Yesaya 41:17",
     "caption": "Loop tanpa akhir 💻\n\nDalam pemrograman, loop yang tidak pernah berhenti biasanya dianggap error. Tapi kesetiaan Tuhan memang tidak punya tombol berhenti. Lewat Yesaya, Tuhan berbicara kepada orang-orang sengsara yang kehausan: Ia akan menjawab, dan Ia tidak akan meninggalkan mereka.\n\n📖 “…tetapi Aku, TUHAN, akan menjawab mereka, dan sebagai Allah orang Israel Aku tidak akan meninggalkan mereka.” — Yesaya 41:17\n\nKetik “while True” kalau kamu mau mengingat kesetiaan-Nya hari ini 🤍"},
    {"file": "anak_bapa.py",
     "baris": ["status = \"anak\"  # bukan \"hamba\"", "if aku.gagal:", "    status = \"tetap anak\"", "panggilan = \"Abba, Bapa\"", "warisan = \"dari Allah\"", "# bukan hasil kerja keras,", "# tapi pemberian karena Kristus"],
     "ayat": "“Jadi kamu bukan lagi hamba, melainkan anak; jikalau kamu anak, maka kamu juga adalah ahli-ahli waris, oleh Allah.”",
     "ref": "Galatia 4:7",
     "caption": "Kode identitas untuk Hari Anak Sedunia 💻\n\nHamba bekerja supaya diterima. Anak bekerja karena sudah diterima. Paulus menulis bahwa di dalam Kristus kita bukan lagi hamba, melainkan anak, bahkan ahli waris. Status itu bukan gaji yang kita kumpulkan, tapi pemberian Allah.\n\n📖 “Jadi kamu bukan lagi hamba, melainkan anak; jikalau kamu anak, maka kamu juga adalah ahli-ahli waris, oleh Allah.” — Galatia 4:7\n\nKetik “Abba” kalau hari ini kamu mau datang kepada-Nya sebagai anak 🤍"},
    {"file": "minggu_raja.py",
     "baris": ["raja = \"Yesus\"", "jarak = 0  # Ia datang dekat", "def besok():", "    bangun_pagi()", "    pergi_ibadah(hati=\"siap\")", "    sembah(raja)", "    pulang(sebagai=\"warga kerajaan\")"],
     "ayat": "“Ia telah melepaskan kita dari kuasa kegelapan dan memindahkan kita ke dalam Kerajaan Anak-Nya yang kekasih;”",
     "ref": "Kolose 1:13",
     "caption": "Persiapan untuk Minggu Kristus Raja 💻\n\nPaulus menulis bahwa kita sudah dipindahkan dari kuasa kegelapan ke dalam Kerajaan Anak-Nya. Kita bukan lagi orang asing yang berdiri jauh. Raja itu dekat, dan kita adalah warga kerajaan-Nya. Besok kita beribadah bukan supaya menjadi warga, tapi karena kita sudah dijadikan warga.\n\n📖 “Ia telah melepaskan kita dari kuasa kegelapan dan memindahkan kita ke dalam Kerajaan Anak-Nya yang kekasih;” — Kolose 1:13\n\nKetik 👑 kalau besok kamu mau datang beribadah."},
]

# ---------- KARTUPOS: kartu pos tulisan tangan (petang 18:00) ----------
KARTUPOS = [
    {"dari": "Gunung Sinai",
     "untuk": "Yang merasa jauh",
     "pesan": "Dulu Allah meminta umat-Nya membangun kemah supaya Ia bisa diam di tengah mereka. Lalu Ia datang lebih dekat lagi dalam Yesus. Di mana pun kamu membaca kartu ini, kamu tidak sendirian. Salam hangat, Tenang.",
     "ayat": "“Dan mereka harus membuat tempat kudus bagi-Ku, supaya Aku akan diam di tengah-tengah mereka.”",
     "ref": "Keluaran 25:8",
     "caption": "Kartu pos dari Gunung Sinai ✉️\n\nDi Gunung Sinai, Allah memberi Musa petunjuk yang sangat rinci untuk membangun Kemah Suci. Untuk apa? Supaya Ia bisa diam di tengah-tengah umat-Nya. Allah yang kudus ingin dekat dengan umat-Nya. Kerinduan yang sama membawa Yesus ke Betlehem.\n\n📖 “Dan mereka harus membuat tempat kudus bagi-Ku, supaya Aku akan diam di tengah-tengah mereka.” — Keluaran 25:8\n\nKirim kartu pos ini ke teman yang sedang merasa jauh dari Tuhan 💌"},
    {"dari": "Jalan ke Emaus",
     "untuk": "Kamu di jalan pulang",
     "pesan": "Dua murid berjalan pulang dengan hati berat, lalu Yesus datang dan berjalan bersama mereka. Ia juga tahu jalan ke kantormu, kampusmu, dan rumahmu. Hari biasa pun bisa menjadi tempat bertemu dengan-Nya.",
     "ayat": "“Ketika mereka sedang bercakap-cakap… datanglah Yesus sendiri mendekati mereka, lalu berjalan bersama-sama dengan mereka.”",
     "ref": "Lukas 24:15",
     "caption": "Kartu pos dari jalan ke Emaus ✉️\n\nKedua murid itu tidak sedang berdoa di Bait Allah. Mereka sedang berjalan pulang, bercakap-cakap tentang hari-hari yang berat. Di situlah Yesus datang mendekat. Mereka belum mengenali-Nya, tapi Ia sudah berjalan di samping mereka. Kadang kita pun baru sadar belakangan bahwa Ia ada di sana sepanjang jalan.\n\n📖 “Ketika mereka sedang bercakap-cakap… datanglah Yesus sendiri mendekati mereka, lalu berjalan bersama-sama dengan mereka.” — Lukas 24:15\n\nKetik “Dia berjalan bersamaku” kalau hari ini kamu mau mengingatnya di perjalanan pulang."},
    {"dari": "Taman Getsemani",
     "untuk": "Kamu yang ditinggal",
     "pesan": "Malam itu Yesus meminta sahabat-sahabat-Nya berjaga bersama-Nya, tetapi mereka tertidur. Ia tahu rasanya sendirian saat hati sangat sedih. Jadi Ia tidak akan meremehkan sepimu. Ceritakan semuanya kepada-Nya malam ini.",
     "ayat": "“…Hati-Ku sangat sedih, seperti mau mati rasanya. Tinggallah di sini dan berjaga-jagalah dengan Aku.”",
     "ref": "Matius 26:38",
     "caption": "Kartu pos dari Getsemani ✉️\n\nDi malam paling berat dalam hidup-Nya, Yesus tidak malu berkata kepada sahabat-sahabat-Nya bahwa hati-Nya sangat sedih. Ia meminta mereka menemani. Mereka malah tertidur. Yesus tahu rasanya butuh teman dan tidak mendapatkannya. Karena itu, Ia adalah tempat yang aman untuk membawa kesepianmu.\n\n📖 “…Hati-Ku sangat sedih, seperti mau mati rasanya. Tinggallah di sini dan berjaga-jagalah dengan Aku.” — Matius 26:38\n\nKirim kartu ini ke teman yang sedang merasa ditinggal 💌"},
    {"dari": "Koresa, gurun Zif",
     "untuk": "Sahabat yang lelah",
     "pesan": "Saat Daud dikejar-kejar dan ketakutan, Yonatan datang menemuinya. Ia tidak membawa semua jawaban. Ia membawa dirinya dan mengingatkan Daud kepada Allah. Semoga minggu ini kamu punya teman seperti itu, atau menjadi teman seperti itu.",
     "ayat": "“…bersiaplah Yonatan, anak Saul, lalu pergi kepada Daud di Koresa. Ia menguatkan kepercayaan Daud kepada Allah…”",
     "ref": "1 Samuel 23:16",
     "caption": "Kartu pos dari padang gurun Zif ✉️\n\nYonatan adalah anak Saul, raja yang sedang memburu Daud. Ia punya banyak alasan untuk menjauh. Tapi ia malah pergi mencari sahabatnya di padang gurun, bukan untuk menyelesaikan semua masalahnya, tapi untuk menguatkan kepercayaannya kepada Allah. Itulah persahabatan di dalam Tuhan.\n\n📖 “…bersiaplah Yonatan, anak Saul, lalu pergi kepada Daud di Koresa. Ia menguatkan kepercayaan Daud kepada Allah…” — 1 Samuel 23:16\n\nTag sahabat yang pernah menjadi Yonatan bagimu 👇"},
    {"dari": "Padang gurun",
     "untuk": "Kamu yang lelah",
     "pesan": "Empat puluh tahun Israel berjalan di padang gurun, sering mengeluh dan sering gagal. Tapi tiang awan tidak berpindah dari atas mereka. Hari ini pun, di jalan yang panjang dan berdebu, Dia tidak meninggalkanmu.",
     "ayat": "“Engkau tidak meninggalkan mereka di padang gurun karena kasih sayang-Mu yang besar. Tiang awan tidak berpindah dari atas mereka…”",
     "ref": "Nehemia 9:19",
     "caption": "Kartu pos dari padang gurun ✉️\n\nDoa panjang dalam kitab Nehemia mengingat kembali sejarah Israel dengan jujur: mereka keras kepala dan memberontak. Tapi berulang kali muncul kalimat yang sama: Engkau tidak meninggalkan mereka. Alasannya bukan kesetiaan Israel, tapi kasih sayang Tuhan yang besar.\n\n📖 “Engkau tidak meninggalkan mereka di padang gurun karena kasih sayang-Mu yang besar. Tiang awan tidak berpindah dari atas mereka…” — Nehemia 9:19\n\nKetik “Dia tidak pergi” kalau kamu sedang berjalan di padang gurunmu sendiri 🤍"},
    {"dari": "Nazaret",
     "untuk": "Kamu, anak Bapa",
     "pesan": "Yesus juga pernah menjadi anak kecil di Nazaret: bertumbuh, belajar, dan diasuh orang tua-Nya. Ia tahu rasanya menjadi anak. Selamat Hari Anak Sedunia. Setua apa pun kamu, di dalam Kristus kamu tetap anak yang dikasihi Bapa.",
     "ayat": "“Anak itu bertambah besar dan menjadi kuat, penuh hikmat, dan kasih karunia Allah ada pada-Nya.”",
     "ref": "Lukas 2:40",
     "caption": "Kartu pos dari Nazaret ✉️\n\nAlkitab tidak banyak bercerita tentang masa kecil Yesus. Tapi satu kalimat ini cukup: Ia bertumbuh menjadi besar dan kuat, dan kasih karunia Allah ada pada-Nya. Hari ini, doakan anak-anak di sekitarmu supaya bertumbuh dalam kasih karunia yang sama.\n\n📖 “Anak itu bertambah besar dan menjadi kuat, penuh hikmat, dan kasih karunia Allah ada pada-Nya.” — Lukas 2:40\n\nTulis nama anak yang mau kamu doakan di komentar 👇"},
    {"dari": "Golgota",
     "untuk": "Kamu yang berdoa",
     "pesan": "Raja kami tidak memerintah dari kejauhan. Di atas salib pun Ia masih mendengar seorang penjahat yang meminta untuk diingat. Kalau Ia mendengar orang itu, Ia juga mendengar doamu. Sampai jumpa di ibadah besok.",
     "ayat": "“Lalu ia berkata: ‘Yesus, ingatlah akan aku, apabila Engkau datang sebagai Raja.’”",
     "ref": "Lukas 23:42",
     "caption": "Kartu pos dari Golgota ✉️\n\nDi atas kepala Yesus ada tulisan: Inilah raja orang Yahudi. Banyak orang mengejek-Nya. Tapi seorang penjahat di sebelah-Nya melihat Raja yang sungguh-sungguh. Dan Yesus menjawab permintaannya dengan janji bahwa hari itu juga ia akan bersama-Nya di Firdaus.\n\n📖 “Lalu ia berkata: ‘Yesus, ingatlah akan aku, apabila Engkau datang sebagai Raja.’” — Lukas 23:42\n\nKetik “Ingatlah akan aku” sebagai doamu menjelang Minggu Kristus Raja 👑"},
]

# ---------- FLIP: Reel papan keberangkatan split-flap (malam0 19:30) ----------
FLIP = [
    {"teks": "TUJUAN AKHIR:\nALLAH DIAM\nBERSAMA\nMANUSIA.",
     "ayat": "“…Lihatlah, kemah Allah ada di tengah-tengah manusia dan Ia akan diam bersama-sama dengan mereka. Mereka akan menjadi umat-Nya dan Ia akan menjadi Allah mereka.”",
     "ref": "Wahyu 21:3",
     "caption": "Papan keberangkatan malam ini 🚉\n\nKisah Alkitab dimulai di taman, ketika TUHAN Allah berjalan di tengah ciptaan-Nya, dan berakhir di kota yang baru, ketika Allah diam bersama umat-Nya untuk selamanya. Natal adalah titik di tengah perjalanan itu: Allah datang dalam Yesus. Hari ini kita masih dalam perjalanan, tapi tujuannya sudah pasti.\n\n📖 “…Lihatlah, kemah Allah ada di tengah-tengah manusia dan Ia akan diam bersama-sama dengan mereka. Mereka akan menjadi umat-Nya dan Ia akan menjadi Allah mereka.” — Wahyu 21:3\n\nKetik “Tujuan akhir” kalau kamu juga menantikan hari itu 🤍"},
    {"teks": "TUHAN BERJALAN\nDI DEPANMU,\nALLAH MENUTUP\nBARISANMU.",
     "ayat": "“…sebab TUHAN akan berjalan di depanmu, dan Allah Israel akan menjadi penutup barisanmu.”",
     "ref": "Yesaya 52:12",
     "caption": "Jadwal keberangkatan hari Senin 🚉\n\nYesaya menulis kepada umat yang akan pulang dari pembuangan. Mereka tidak perlu keluar dengan buru-buru seperti orang yang melarikan diri. Tuhan berjalan di depan mereka, dan Tuhan juga menjaga barisan paling belakang. Apa pun jadwalmu minggu ini, kamu tidak berangkat sendirian.\n\n📖 “…sebab TUHAN akan berjalan di depanmu, dan Allah Israel akan menjadi penutup barisanmu.” — Yesaya 52:12\n\nKirim ke teman yang besok harus berangkat pagi-pagi 💌"},
    {"teks": "SEMUA PERGI,\nTETAPI TUHAN\nMENDAMPINGI\nAKU.",
     "ayat": "“Pada waktu pembelaanku yang pertama tidak seorangpun yang membantu aku, semuanya meninggalkan aku… tetapi Tuhan telah mendampingi aku dan menguatkan aku…”",
     "ref": "2 Timotius 4:16-17",
     "caption": "Untuk kamu yang merasa ditinggal 🚉\n\nPaulus menulis surat ini dari penjara, menjelang akhir hidupnya. Saat ia harus membela diri di pengadilan, tidak ada satu orang pun yang datang membantunya. Ia tidak menutupi rasa sakit itu. Tapi ia juga menulis bagian kedua: Tuhan mendampingi dan menguatkan aku.\n\n📖 “Pada waktu pembelaanku yang pertama tidak seorangpun yang membantu aku, semuanya meninggalkan aku… tetapi Tuhan telah mendampingi aku dan menguatkan aku…” — 2 Timotius 4:16-17\n\nSave ini untuk malam-malam ketika kamu merasa semua orang pergi 🔖"},
    {"teks": "TANGAN MUSA\nLELAH. HARUN\nDAN HUR\nMENOPANG.",
     "ayat": "“Maka penatlah tangan Musa… Harun dan Hur menopang kedua belah tangannya, seorang di sisi yang satu, seorang di sisi yang lain, sehingga tangannya tidak bergerak sampai matahari terbenam.”",
     "ref": "Keluaran 17:12",
     "caption": "Kisah tentang tangan yang lelah 🚉\n\nSaat Israel berperang melawan Amalek, Musa berdiri di atas bukit dengan tangan terangkat. Ketika tangannya turun karena lelah, Amalek lebih kuat. Musa tidak bisa melakukannya sendirian. Harun dan Hur tidak memimpin pasukan, tapi mereka menopang tangan Musa sampai matahari terbenam. Kadang pelayanan terbesar adalah menopang orang lain.\n\n📖 “Maka penatlah tangan Musa… Harun dan Hur menopang kedua belah tangannya, seorang di sisi yang satu, seorang di sisi yang lain, sehingga tangannya tidak bergerak sampai matahari terbenam.” — Keluaran 17:12\n\nTag teman yang pernah menopangmu saat kamu lelah 👇"},
    {"teks": "TUHAN TIDAK\nMENINGGALKAN\nORANG YANG\nDIKASIHI-NYA.",
     "ayat": "“…TUHAN mencintai hukum, dan Ia tidak meninggalkan orang-orang yang dikasihi-Nya. Sampai selama-lamanya mereka akan terpelihara…”",
     "ref": "Mazmur 37:28",
     "caption": "Papan malam hari Kamis 🚉\n\nMazmur 37 ditulis untuk orang yang gelisah melihat orang jahat seolah selalu menang. Pemazmur mengajak kita melihat lebih jauh: hidup orang fasik akan berlalu, tapi TUHAN tidak meninggalkan orang-orang yang dikasihi-Nya. Kesetiaan-Nya lebih panjang dari masalah hari ini.\n\n📖 “…TUHAN mencintai hukum, dan Ia tidak meninggalkan orang-orang yang dikasihi-Nya. Sampai selama-lamanya mereka akan terpelihara…” — Mazmur 37:28\n\nKetik “Dikasihi-Nya” kalau malam ini kamu mau beristirahat dalam kesetiaan-Nya 🤍"},
    {"teks": "BAPA TIDAK\nMAU SATU PUN\nANAK INI\nHILANG.",
     "ayat": "“Demikian juga Bapamu yang di sorga tidak menghendaki supaya seorangpun dari anak-anak ini hilang.”",
     "ref": "Matius 18:14",
     "caption": "Untuk setiap anak, termasuk kamu 🚉\n\nYesus baru saja bercerita tentang gembala yang meninggalkan sembilan puluh sembilan domba untuk mencari satu yang sesat. Lalu Ia menutup dengan kalimat ini. Di Hari Anak Sedunia, kita berdoa untuk anak-anak yang rentan, terlupakan, dan terluka. Bapa tidak menghendaki satu pun dari mereka hilang.\n\n📖 “Demikian juga Bapamu yang di sorga tidak menghendaki supaya seorangpun dari anak-anak ini hilang.” — Matius 18:14\n\nTulis 🙏 di komentar sebagai doa untuk anak-anak yang terluka."},
    {"teks": "LIHAT,\nRAJAMU DATANG\nKEPADAMU.",
     "ayat": "“…Lihat, rajamu datang kepadamu; ia adil dan jaya. Ia lemah lembut dan mengendarai seekor keledai, seekor keledai beban yang muda.”",
     "ref": "Zakharia 9:9",
     "caption": "Kedatangan malam ini: Sang Raja 🚉\n\nZakharia menulis nubuat ini untuk umat yang kecil dan lemah, lebih dari lima ratus tahun sebelum Yesus masuk Yerusalem. Raja yang dijanjikan tidak datang dengan kereta perang, tapi menunggang keledai. Ia datang dekat, lemah lembut, dan mudah dihampiri. Besok kita menyembah Raja itu.\n\n📖 “…Lihat, rajamu datang kepadamu; ia adil dan jaya. Ia lemah lembut dan mengendarai seekor keledai, seekor keledai beban yang muda.” — Zakharia 9:9\n\nKetik 👑 kalau kamu siap menyambut-Nya besok."},
]

# ---------- PETA: aplikasi peta dengan rute (malam 21:00) ----------
PETA = [
    {"dari": "Takhta sorga",
     "ke": "Palungan",
     "waktu": "Sudah tiba",
     "langkah": ["Turun dari kemuliaan sorga", "Lahir sebagai bayi di Betlehem", "Tinggal di tengah kita: Imanuel"],
     "ayat": "“melainkan telah mengosongkan diri-Nya sendiri, dan mengambil rupa seorang hamba, dan menjadi sama dengan manusia.”",
     "ref": "Filipi 2:7",
     "caption": "Rute terjauh yang pernah ditempuh 🗺️\n\nKita sering berpikir harus berusaha keras untuk sampai kepada Allah. Tapi Natal menunjukkan arah yang sebaliknya: Allah yang menempuh perjalanan kepada kita. Yesus mengosongkan diri-Nya, menjadi manusia, dan tinggal di tengah kita. Rute itu sudah Ia tempuh sampai tuntas.\n\n📖 “melainkan telah mengosongkan diri-Nya sendiri, dan mengambil rupa seorang hamba, dan menjadi sama dengan manusia.” — Filipi 2:7\n\nSave peta ini dan buka lagi waktu Tuhan terasa jauh 🔖"},
    {"dari": "Rumah",
     "ke": "Kantor / kampus",
     "waktu": "Satu hari",
     "langkah": ["Mulai: doa singkat sebelum berangkat", "Lurus terus, Dia ikut di setiap langkah", "Tiba: kerjakan bagianmu dengan setia"],
     "ayat": "“TUHAN menetapkan langkah-langkah orang yang hidupnya berkenan kepada-Nya;”",
     "ref": "Mazmur 37:23",
     "caption": "Rute hari Senin 🗺️\n\nKita tidak selalu tahu ke mana hari ini akan membawa kita: rapat yang molor, tugas kuliah yang mendadak, atau urusan rumah yang tak ada habisnya. Tapi pemazmur mengingatkan bahwa langkah-langkah kita tidak berjalan sendiri. Tuhan yang menetapkannya, termasuk langkah-langkah yang terasa biasa.\n\n📖 “TUHAN menetapkan langkah-langkah orang yang hidupnya berkenan kepada-Nya;” — Mazmur 37:23\n\nTulis tujuanmu besok pagi di komentar, kami ikut mendoakan 👇"},
    {"dari": "Kesepian",
     "ke": "Disambut TUHAN",
     "waktu": "1 doa lagi",
     "langkah": ["Akui dengan jujur: aku kesepian", "Belok ke kamar, tutup pintu, berdoa", "Tiba: Dia menyambutmu apa adanya"],
     "ayat": "“Sekalipun ayahku dan ibuku meninggalkan aku, namun TUHAN menyambut aku.”",
     "ref": "Mazmur 27:10",
     "caption": "Rute untuk hati yang merasa ditinggal 🗺️\n\nDaud membayangkan hal yang paling menakutkan bagi seorang anak: ditinggal ayah dan ibu. Sebagian dari kita tidak perlu membayangkannya, karena sudah mengalaminya. Tapi ayat ini memberi jaminan yang lebih kuat dari ikatan keluarga mana pun: TUHAN menyambut aku.\n\n📖 “Sekalipun ayahku dan ibuku meninggalkan aku, namun TUHAN menyambut aku.” — Mazmur 27:10\n\nKirim ke teman yang sedang merasa ditinggalkan 💌"},
    {"dari": "Menyendiri",
     "ke": "Persekutuan",
     "waktu": "1 sapaan lagi",
     "langkah": ["Kirim pesan ke satu teman seiman", "Belok ke kelompok kecil minggu ini", "Tiba: saling menanggung beban"],
     "ayat": "“Tetapi Allah, yang menghiburkan orang yang rendah hati, telah menghiburkan kami dengan kedatangan Titus.”",
     "ref": "2 Korintus 7:6",
     "caption": "Rute dari menyendiri ke persekutuan 🗺️\n\nPaulus pernah sangat tertekan: dari luar pertengkaran, dari dalam ketakutan. Bagaimana Allah menghiburnya? Lewat kedatangan seorang teman, Titus. Kadang Allah menjawab doa kita lewat seseorang yang mengetuk pintu. Dan kadang, kitalah yang Ia utus untuk mengetuk.\n\n📖 “Tetapi Allah, yang menghiburkan orang yang rendah hati, telah menghiburkan kami dengan kedatangan Titus.” — 2 Korintus 7:6\n\nSiapa yang perlu kamu kunjungi minggu ini? Tulis inisialnya di komentar 👇"},
    {"dari": "Masa yang gelap",
     "ke": "Kasih setia-Nya",
     "waktu": "Tak selamanya",
     "langkah": ["Tetap melangkah, ujungnya belum terlihat", "Ingat: Dia tidak mengucilkan selamanya", "Tiba: kasih setia-Nya besar"],
     "ayat": "“Karena tidak untuk selama-lamanya Tuhan mengucilkan. Karena walau Ia mendatangkan susah, Ia juga menyayangi menurut kebesaran kasih setia-Nya.”",
     "ref": "Ratapan 3:31-32",
     "caption": "Rute melewati masa yang gelap 🗺️\n\nKitab Ratapan ditulis di tengah reruntuhan Yerusalem. Penulisnya tidak menutupi rasa sakit dan tidak berpura-pura semuanya baik-baik saja. Tapi di tengah ratapannya ia berpegang pada satu hal: masa gelap ini tidak untuk selama-lamanya. Kasih setia Tuhan lebih besar dari musim terberat dalam hidupmu.\n\n📖 “Karena tidak untuk selama-lamanya Tuhan mengucilkan. Karena walau Ia mendatangkan susah, Ia juga menyayangi menurut kebesaran kasih setia-Nya.” — Ratapan 3:31-32\n\nKetik “Tidak selamanya” kalau kamu sedang melewati masa gelap 🤍"},
    {"dari": "Langkah pertama",
     "ke": "Pelukan Bapa",
     "waktu": "Pelan-pelan",
     "langkah": ["Pegang tangan-Nya, jangan dilepas", "Jatuh? Dia mengangkatmu lagi", "Tiba: Bapa sudah menunggu"],
     "ayat": "“Padahal Akulah yang mengajar Efraim berjalan dan mengangkat mereka di tangan-Ku…”",
     "ref": "Hosea 11:3",
     "caption": "Rute seorang anak belajar berjalan 🗺️\n\nLewat Hosea, Tuhan menggambarkan diri-Nya seperti orang tua yang mengajar anaknya berjalan dan mengangkatnya di tangan-Nya. Israel sering lupa dan menjauh, tapi kasih Bapa tetap sabar. Di Hari Anak Sedunia, ingat: kamu pun sedang belajar berjalan, dan Ia sabar menuntunmu.\n\n📖 “Padahal Akulah yang mengajar Efraim berjalan dan mengangkat mereka di tangan-Ku…” — Hosea 11:3\n\nTag orang tua atau siapa pun yang dulu mengajarimu berjalan dalam iman 👇"},
    {"dari": "Kamar tidur",
     "ke": "Rumah TUHAN",
     "waktu": "Besok pagi",
     "langkah": ["Malam ini: tidur cukup, siapkan hati", "Pagi: berangkat sedikit lebih awal", "Tiba: sembah Sang Raja bersama-sama"],
     "ayat": "“…Mari, kita naik ke gunung TUHAN, ke rumah Allah Yakub, supaya Ia mengajar kita tentang jalan-jalan-Nya, dan supaya kita berjalan menempuhnya…”",
     "ref": "Yesaya 2:3",
     "caption": "Rute untuk besok pagi 🗺️\n\nYesaya melihat masa depan ketika bangsa-bangsa saling mengajak naik ke rumah Tuhan. Mereka datang bukan untuk menonton, tapi untuk diajar dan berjalan di jalan-Nya. Besok, Minggu Kristus Raja, kita juga punya kesempatan itu. Ajak satu orang berangkat bersamamu.\n\n📖 “…Mari, kita naik ke gunung TUHAN, ke rumah Allah Yakub, supaya Ia mengajar kita tentang jalan-jalan-Nya, dan supaya kita berjalan menempuhnya…” — Yesaya 2:3\n\nKetik “Mari kita naik” kalau besok kamu mau beribadah 👑"},
]

# ---------- LILIN: lilin di gelap, satu kalimat malam (larut 22:30) ----------
LILIN = [
    {"teks": "Ke mana pun aku pergi hari ini, Engkau sudah ada di sana. Terima kasih, Imanuel.",
     "ayat": "“Ke mana aku dapat pergi menjauhi roh-Mu, ke mana aku dapat lari dari hadapan-Mu? Jika aku mendaki ke langit, Engkau di sana…”",
     "ref": "Mazmur 139:7-8",
     "caption": "Lilin hari Minggu 🕯️\n\nDaud tidak sedang mencari cara kabur dari Tuhan. Ia sedang takjub: tidak ada satu tempat pun yang terlalu tinggi, terlalu dalam, atau terlalu gelap bagi kehadiran Tuhan. Malam ini, sebelum tidur, ingat bahwa kamarmu pun tidak di luar jangkauan-Nya.\n\n📖 “Ke mana aku dapat pergi menjauhi roh-Mu, ke mana aku dapat lari dari hadapan-Mu? Jika aku mendaki ke langit, Engkau di sana…” — Mazmur 139:7-8\n\nKetik “Amin” dan selamat beristirahat 🤍"},
    {"teks": "Tuhan, Senin ini selesai. Terima kasih Engkau menemaniku sejak pagi sampai petang.",
     "ayat": "“manusiapun keluarlah ke pekerjaannya, dan ke usahanya sampai petang.”",
     "ref": "Mazmur 104:23",
     "caption": "Lilin untuk akhir hari kerja 🕯️\n\nMazmur 104 memuji Tuhan atas seluruh ciptaan: gunung, laut, binatang, matahari, dan bulan. Di tengah daftar itu, pemazmur juga menyebut manusia yang pergi bekerja sampai petang. Pekerjaan biasa kita adalah bagian dari dunia yang Tuhan pelihara. Sekarang hari sudah malam. Waktunya beristirahat.\n\n📖 “manusiapun keluarlah ke pekerjaannya, dan ke usahanya sampai petang.” — Mazmur 104:23\n\nKetik 🕯️ kalau kamu bersyukur untuk hari ini, sebiasa apa pun hari itu."},
    {"teks": "Tuhan, malam ini aku merasa sendirian. Aku tidak mau pura-pura. Berpalinglah kepadaku.",
     "ayat": "“Berpalinglah kepadaku dan kasihanilah aku, sebab aku sebatang kara dan tertindas.”",
     "ref": "Mazmur 25:16",
     "caption": "Lilin untuk malam yang sepi 🕯️\n\nDaud pernah berdoa dengan kalimat ini: aku sebatang kara. Alkitab memberi kita kata-kata untuk berdoa justru saat kita tidak tahu harus berkata apa. Malam ini kamu boleh meminjam doa Daud, dan percaya bahwa Tuhan mendengarnya.\n\n📖 “Berpalinglah kepadaku dan kasihanilah aku, sebab aku sebatang kara dan tertindas.” — Mazmur 25:16\n\nKalau kamu mendoakannya malam ini, ketik 🕯️. Kamu tidak sendirian."},
    {"teks": "Terima kasih untuk teman-teman yang Kauberikan, Tuhan. Ajar aku hadir juga bagi mereka.",
     "ayat": "“…Ketika Paulus melihat mereka, ia mengucap syukur kepada Allah lalu kuatlah hatinya.”",
     "ref": "Kisah Para Rasul 28:15",
     "caption": "Lilin untuk teman-teman kita 🕯️\n\nPaulus tiba di Italia sebagai tahanan setelah perjalanan panjang dan kapal karam. Lalu saudara-saudara seiman dari Roma berjalan jauh untuk menjumpainya. Rasul sebesar Paulus pun dikuatkan hanya dengan melihat teman-temannya datang. Jangan pernah meremehkan kehadiranmu bagi orang lain.\n\n📖 “…Ketika Paulus melihat mereka, ia mengucap syukur kepada Allah lalu kuatlah hatinya.” — Kisah Para Rasul 28:15\n\nKetik “Terima kasih, teman” lalu kirim ke satu sahabatmu 💌"},
    {"teks": "Tuhan, Engkau setia kepada generasi sebelum aku. Sertai juga aku malam ini, dan jangan tinggalkan aku.",
     "ayat": "“Kiranya TUHAN, Allah kita, menyertai kita sebagaimana Ia telah menyertai nenek moyang kita, janganlah Ia meninggalkan kita dan janganlah Ia membuangkan kita,”",
     "ref": "1 Raja-raja 8:57",
     "caption": "Lilin hari Kamis 🕯️\n\nSalomo mengucapkan berkat ini ketika Bait Allah ditahbiskan. Ia melihat ke belakang dan mengakui bahwa Tuhan sudah setia kepada generasi-generasi sebelumnya. Lalu ia memohon hal yang sama untuk hari-hari ke depan. Kesetiaan Tuhan di masa lalu menjadi alasan kita berani berharap malam ini.\n\n📖 “Kiranya TUHAN, Allah kita, menyertai kita sebagaimana Ia telah menyertai nenek moyang kita, janganlah Ia meninggalkan kita dan janganlah Ia membuangkan kita,” — 1 Raja-raja 8:57\n\nKetik “Amin” kalau kamu mau menutup hari ini dengan doa ini 🤍"},
    {"teks": "Seperti anak kecil yang tertidur dalam pelukan, malam ini aku beristirahat dalam kasih-Mu, Tuhan.",
     "ayat": "“Seperti seseorang yang dihibur ibunya, demikianlah Aku ini akan menghibur kamu; kamu akan dihibur di Yerusalem.”",
     "ref": "Yesaya 66:13",
     "caption": "Lilin untuk Hari Anak Sedunia 🕯️\n\nTuhan memakai gambaran yang sangat lembut tentang diri-Nya: seperti seorang ibu yang menghibur anaknya. Kita tidak pernah terlalu dewasa untuk dihibur oleh Tuhan. Malam ini, kamu boleh berhenti menjadi orang yang selalu kuat dan datang kepada-Nya seperti anak kecil.\n\n📖 “Seperti seseorang yang dihibur ibunya, demikianlah Aku ini akan menghibur kamu; kamu akan dihibur di Yerusalem.” — Yesaya 66:13\n\nKetik 🕯️ dan selamat beristirahat 🤍"},
    {"teks": "Raja segala zaman, terima kasih karena Engkau mau datang dekat. Siapkan hatiku untuk menyembah-Mu besok.",
     "ayat": "“Hormat dan kemuliaan sampai selama-lamanya bagi Raja segala zaman, Allah yang kekal, yang tak nampak, yang esa! Amin.”",
     "ref": "1 Timotius 1:17",
     "caption": "Lilin malam Minggu 🕯️\n\nPaulus menulis pujian ini setelah mengingat bahwa ia dulu seorang penganiaya, lalu dikasihani oleh Kristus. Raja segala zaman itu tidak jauh dan tidak dingin. Kristus Yesus datang ke dunia untuk menyelamatkan orang berdosa. Besok kita merayakan Minggu Kristus Raja. Tutup minggu ini dengan menyembah-Nya.\n\n📖 “Hormat dan kemuliaan sampai selama-lamanya bagi Raja segala zaman, Allah yang kekal, yang tak nampak, yang esa! Amin.” — 1 Timotius 1:17\n\nKetik “Amin” dan sampai jumpa di ibadah besok 👑"},
]

# kuis: jawabannya jangan terbaca sebelum orang menggeser -> penjelasan & ayat dipindah ke bawah lipatan caption
for _k in KUIS:
    _p = _k["caption"].split("\n\n")
    _k["caption"] = "\n\n".join(_p[:2]) + "\n\nJawaban & ayatnya ada di slide 2 👉\n.\n.\n.\n.\n\n" + "\n\n".join(_p[2:])

# komik Eli yang sudah jadi (folder Eli): hari 1, 4, 7 di pagi2
ELI = [("saran", 0), ("edukasi", 4), ("saran", 2)]

_PAGI2 = {1: ("ELI", 0), 2: ("KUIS", 0), 3: ("KUIS", 1), 4: ("ELI", 1), 5: ("KUIS", 2), 6: ("KUIS", 3), 7: ("ELI", 2)}

# hari 1-7 (Minggu 15 Nov .. Sabtu 21 Nov 2026): 12 slot per hari -> (format, index)
# pagi 06:00, pagi3 07:30, pagi2 09:00, siang0 10:30, siang 12:00, siang2 13:30, sore 15:00, sore2 16:30,
# petang 18:00, malam0 19:30, malam 21:00, larut 22:30
JADWAL = {d: {"pagi": ("KORAN", d - 1), "pagi3": ("LETTER", d - 1), "pagi2": _PAGI2[d],
              "siang0": ("STICKY", d - 1), "siang": ("MENU", d - 1), "siang2": ("SEARCH", d - 1),
              "sore": ("ORNAMEN", d - 1), "sore2": ("KODE", d - 1), "petang": ("KARTUPOS", d - 1),
              "malam0": ("FLIP", d - 1), "malam": ("PETA", d - 1), "larut": ("LILIN", d - 1)} for d in range(1, 8)}
