"""Akun Tenang (@diam.dan.percaya) - minggu 7 (Minggu 8 Nov - Sabtu 14 Nov 2026).
Tema: "Jangan khawatir, Bapa memelihara" + hitung mundur Natal lanjut (47 -> 41 hari).
Hari: 1 Minggu (Bapamu tahu apa yang kamu perlukan), 2 Senin (serahkan kekhawatiranmu, awal minggu kerja),
3 Selasa (Hari Pahlawan: pahlawan iman yang biasa, berani karena Tuhan menyertai, Yesus Sang Pahlawan sejati),
4 Rabu (damai di tengah badai), 5 Kamis (satu hari saja, rahmat baru tiap pagi),
6 Jumat (Hari Kebaikan Sedunia: kebaikan Tuhan mengikuti kita, berbuat baik kepada sesama),
7 Sabtu (istirahat di dalam Dia, siap ibadah besok).
12 slot per hari, setiap slot gaya visual berbeda:
  CUACA    = layar aplikasi cuaca, prakiraan iman yang jenaka.                       pagi 06:00
  KAMUS    = entri kamus: satu kata, arti biasa + arti iman.                          pagi3 07:30
  ELI      = komik Eli yang sudah jadi (hari 1, 4, 7) / TIKET = boarding pass.        pagi2 09:00
  CATATAN  = daftar centang di aplikasi catatan HP (v selesai, x dicoret, o belum).    siang0 10:30
  STRUK    = struk kasir thermal: anugerah gratis karena Kristus sudah membayar.       siang 12:00
  CHAT     = Reel chat animasi antara "aku" dan seorang teman, ditutup kartu ayat.     siang2 13:30
  KALENDER = kalender sobek, hitung mundur Natal.                                       sore 15:00
  POPUP    = jendela galat komputer jadul (jenaka).                                     sore2 16:30
  POLAROID = tiga foto polaroid dengan label tulisan tangan.                            petang 18:00
  NEON     = Reel papan neon di dinding bata.                                           malam0 19:30
  PLAYER   = pemutar musik "sedang diputar", seri lagu-lagu dalam Alkitab.             malam 21:00
  KETIK    = jurnal/doa malam hasil mesin tik.                                          larut 22:30
Kutipan ayat: Alkitab TB. Caption tanpa hashtag."""

# ---------- CUACA: layar aplikasi cuaca (pagi 06:00) ----------
CUACA = [
    {"hari": "Minggu, 8 November", "kondisi": "Cerah berawan", "ikon": "cerah", "besar": "100%",
     "label_besar": "Bapa tahu kebutuhanmu",
     "baris": [["Peluang khawatir", "sedang"], ["Pemeliharaan-Nya", "sepanjang hari"], ["Kebutuhanmu", "diketahui-Nya"]],
     "ayat": "“Semua itu dicari bangsa-bangsa yang tidak mengenal Allah. Akan tetapi Bapamu yang di sorga tahu, bahwa kamu memerlukan semuanya itu.”",
     "ref": "Matius 6:32",
     "caption": "Prakiraan hari Minggu: Bapa tahu ☀️\n\nMinggu ini kita belajar satu hal yang sering kita lupakan: jangan khawatir, Bapa memelihara. Yesus tidak bilang kebutuhan kita tidak penting. Ia bilang Bapa sudah tahu, bahkan sebelum kita menyebutnya dalam doa.\n\n📖 “Semua itu dicari bangsa-bangsa yang tidak mengenal Allah. Akan tetapi Bapamu yang di sorga tahu, bahwa kamu memerlukan semuanya itu.” — Matius 6:32\n\nKetik “Bapa tahu” kalau kamu mau memulai minggu ini dengan percaya."},
    {"hari": "Senin, 9 November", "kondisi": "Berawan tebal", "ikon": "berawan", "besar": "0 kg",
     "label_besar": "beban dipikul sendirian",
     "baris": [["Tumpukan kerjaan", "tinggi"], ["Angin kekhawatiran", "kencang"], ["Tempat bersandar", "selalu ada"]],
     "ayat": "“…Jika ia hidup dalam kegelapan dan tidak ada cahaya bersinar baginya, baiklah ia percaya kepada nama TUHAN dan bersandar kepada Allahnya!”",
     "ref": "Yesaya 50:10",
     "caption": "Senin pagi, langit agak mendung ☁️\n\nTidak semua minggu kerja dimulai dengan terang. Kadang kita berangkat dengan kepala penuh dan hati yang berat. Yesaya tidak menyuruh kita pura-pura cerah. Ia mengajak kita percaya dan bersandar, justru saat jalan di depan belum terlihat.\n\n📖 “…Jika ia hidup dalam kegelapan dan tidak ada cahaya bersinar baginya, baiklah ia percaya kepada nama TUHAN dan bersandar kepada Allahnya!” — Yesaya 50:10\n\nKetik “Aku bersandar” sebelum mulai bekerja hari ini."},
    {"hari": "Selasa, 10 November", "kondisi": "Cerah", "ikon": "cerah", "besar": "100%",
     "label_besar": "penyertaan-Nya",
     "baris": [["Hari Pahlawan", "10 November"], ["Sumber keberanian", "dari Dia"], ["Peluang ditinggalkan", "nol"]],
     "ayat": "“…seperti Aku menyertai Musa, demikianlah Aku akan menyertai engkau; Aku tidak akan membiarkan engkau dan tidak akan meninggalkan engkau.”",
     "ref": "Yosua 1:5",
     "caption": "Selamat Hari Pahlawan 🌤️\n\nHari ini kita mengenang orang-orang yang berani berkorban. Yosua juga pernah berdiri di depan tugas yang terlalu besar baginya: melanjutkan pekerjaan Musa. Keberaniannya tidak berasal dari dirinya sendiri, tapi dari janji penyertaan Tuhan.\n\n📖 “…seperti Aku menyertai Musa, demikianlah Aku akan menyertai engkau; Aku tidak akan membiarkan engkau dan tidak akan meninggalkan engkau.” — Yosua 1:5\n\nKetik “Dia menyertai” kalau hari ini kamu butuh keberanian."},
    {"hari": "Rabu, 11 November", "kondisi": "Badai petir", "ikon": "badai", "besar": "100%",
     "label_besar": "Dia di perahu yang sama",
     "baris": [["Gelombang", "tinggi"], ["Rasa takut", "naik-turun"], ["Kuasa-Nya atas angin", "penuh"]],
     "ayat": "“…Lalu bangunlah Yesus menghardik angin dan danau itu, maka danau itu menjadi teduh sekali.”",
     "ref": "Matius 8:26",
     "caption": "Prakiraan hari ini: badai ⛈️\n\nPara murid berlayar bersama Yesus, dan badai tetap datang. Ikut Yesus ternyata tidak membuat kita kebal badai. Tapi tidak ada badai yang lebih besar dari Dia yang ada di perahu itu.\n\n📖 “Ia berkata kepada mereka: ‘Mengapa kamu takut, kamu yang kurang percaya?’ Lalu bangunlah Yesus menghardik angin dan danau itu, maka danau itu menjadi teduh sekali.” — Matius 8:26\n\nKirim ke teman yang sedang berada di tengah badai 💌"},
    {"hari": "Kamis, 12 November", "kondisi": "Cerah pagi", "ikon": "cerah", "besar": "24 j",
     "label_besar": "rahmat untuk hari ini",
     "baris": [["Beban kemarin", "sudah lewat"], ["Rahmat hari ini", "baru lagi"], ["Urusan besok", "nanti dulu"]],
     "ayat": "“TUHAN, kasihanilah kami, Engkau kami nanti-nantikan! Lindungilah kami setiap pagi dengan tangan-Mu, ya, selamatkanlah kami di waktu kesesakan!”",
     "ref": "Yesaya 33:2",
     "caption": "Pagi baru, rahmat baru 🌅\n\nKita tidak perlu memikul seluruh minggu sekaligus. Tuhan menolong kita satu pagi demi satu pagi. Kekuatan untuk hari ini akan datang hari ini, dan kekuatan untuk besok akan datang besok.\n\n📖 “TUHAN, kasihanilah kami, Engkau kami nanti-nantikan! Lindungilah kami setiap pagi dengan tangan-Mu, ya, selamatkanlah kami di waktu kesesakan!” — Yesaya 33:2\n\nSave dan jadikan doa pagimu hari ini 🔖"},
    {"hari": "Jumat, 13 November", "kondisi": "Pelangi", "ikon": "pelangi", "besar": "100%",
     "label_besar": "kasih setia-Nya",
     "baris": [["Hari Kebaikan Sedunia", "13 November"], ["Kebaikan-Nya", "mengikutimu"], ["Peluang berbuat baik", "tinggi"]],
     "ayat": "“Ia senang kepada keadilan dan hukum; bumi penuh dengan kasih setia TUHAN.”",
     "ref": "Mazmur 33:5",
     "caption": "Selamat Hari Kebaikan Sedunia 🌈\n\nSebelum kita berbuat baik kepada orang lain, ingat dulu: kita sendiri sudah dikelilingi kebaikan Tuhan sejak membuka mata pagi ini. Bumi penuh dengan kasih setia-Nya, termasuk sudut kecil tempatmu berdiri sekarang.\n\n📖 “Ia senang kepada keadilan dan hukum; bumi penuh dengan kasih setia TUHAN.” — Mazmur 33:5\n\nTulis satu kebaikan Tuhan yang kamu lihat pagi ini 👇"},
    {"hari": "Sabtu, 14 November", "kondisi": "Hujan ringan", "ikon": "hujan", "besar": "7",
     "label_besar": "hari Dia memelihara",
     "baris": [["Ajakan istirahat", "sepanjang hari"], ["Ketenangan jiwa", "tersedia"], ["Ibadah besok", "jangan lupa"]],
     "ayat": "“…tanyakanlah jalan-jalan yang dahulu kala, di manakah jalan yang baik, tempuhlah itu, dengan demikian jiwamu mendapat ketenangan…”",
     "ref": "Yeremia 6:16",
     "caption": "Sabtu pagi, gerimis pelan 🌧️\n\nTujuh hari Tuhan memelihara kita minggu ini. Sebelum mengejar daftar tugas akhir pekan, berhenti sebentar. Ketenangan jiwa tidak datang dari jalan pintas, tapi dari jalan yang sudah Tuhan tunjukkan sejak dulu. Umat Yehuda waktu itu menolak ajakan ini. Hari ini kita bisa memilih berbeda.\n\n📖 “…tanyakanlah jalan-jalan yang dahulu kala, di manakah jalan yang baik, tempuhlah itu, dengan demikian jiwamu mendapat ketenangan…” — Yeremia 6:16\n\nKetik “Aku mau” kalau Sabtu ini kamu mau berjalan pelan bersama-Nya."},
]

# ---------- KAMUS: entri kamus, arti biasa + arti iman (pagi3 07:30) ----------
KAMUS = [
    {"kata": "sedia", "suku": "se·di·a", "lafal": "/sə·di·a/", "kelas": "a",
     "arti": ["siap; sudah ada dan bisa dipakai ketika dibutuhkan",
              "TUHAN menyediakan: Ia melihat kebutuhan kita lebih dulu dan mencukupkannya tepat pada waktu-Nya"],
     "ayat": "“Dan Abraham menamai tempat itu: ‘TUHAN menyediakan’; sebab itu sampai sekarang dikatakan orang: ‘Di atas gunung TUHAN, akan disediakan.’”",
     "ref": "Kejadian 22:14", "lihat": "menyediakan, persediaan",
     "caption": "Kata hari ini: sedia ✍️\n\nDi gunung Moria, Abraham belum melihat jalan keluar, tapi ia percaya Allah akan menyediakan. Lalu Tuhan menyediakan seekor domba jantan. Berabad-abad kemudian, Allah menyediakan Anak Domba-Nya sendiri untuk kebutuhan kita yang terbesar: Yesus.\n\n📖 “Dan Abraham menamai tempat itu: ‘TUHAN menyediakan’; sebab itu sampai sekarang dikatakan orang: ‘Di atas gunung TUHAN, akan disediakan.’” — Kejadian 22:14\n\nKetik “TUHAN menyediakan” kalau kamu sedang menunggu pemeliharaan-Nya."},
    {"kata": "serah", "suku": "se·rah", "lafal": "/sə·rah/", "kelas": "v",
     "arti": ["memberikan sesuatu kepada orang lain untuk dijaga, diurus, atau dimiliki",
              "menaruh hidup dan kekhawatiran kita di tangan Tuhan, lalu percaya Ia sanggup menjaganya"],
     "ayat": "“Ke dalam tangan-Mulah kuserahkan nyawaku; Engkau membebaskan aku, ya TUHAN, Allah yang setia.”",
     "ref": "Mazmur 31:6", "lihat": "menyerahkan, berserah",
     "caption": "Kata hari ini: serah ✍️\n\nDaud menulis doa ini saat terdesak. Berabad-abad kemudian, Yesus mengucapkan kalimat yang hampir sama di kayu salib. Berserah bukan menyerah kalah. Berserah adalah menaruh sesuatu di tangan yang jauh lebih aman dari tangan kita sendiri.\n\n📖 “Ke dalam tangan-Mulah kuserahkan nyawaku; Engkau membebaskan aku, ya TUHAN, Allah yang setia.” — Mazmur 31:6\n\nApa yang mau kamu serahkan Senin ini? Tulis satu kata di komentar 👇"},
    {"kata": "berani", "suku": "be·ra·ni", "lafal": "/bə·ra·ni/", "kelas": "a",
     "arti": ["mempunyai hati yang mantap untuk menghadapi bahaya, kesulitan, atau risiko",
              "tetap melangkah taat walau takut, karena tahu Tuhan menyertai, bukan karena merasa diri hebat"],
     "ayat": "“Ketika sidang itu melihat keberanian Petrus dan Yohanes dan mengetahui, bahwa keduanya orang biasa yang tidak terpelajar, heranlah mereka…”",
     "ref": "Kisah Para Rasul 4:13", "lihat": "keberanian, memberanikan",
     "caption": "Kata hari ini: berani ✍️\n\nPetrus dan Yohanes bukan pejabat, bukan juga ahli Taurat. Mereka nelayan, orang biasa. Tapi di depan para pemimpin yang mengancam mereka, mereka berbicara dengan berani. Rahasianya ada di ujung ayat ini.\n\n📖 “Ketika sidang itu melihat keberanian Petrus dan Yohanes dan mengetahui, bahwa keduanya orang biasa yang tidak terpelajar, heranlah mereka; dan mereka mengenal keduanya sebagai pengikut Yesus.” — Kisah Para Rasul 4:13\n\nKetik “Orang biasa” kalau kamu mau dipakai Tuhan apa adanya 🤍"},
    {"kata": "teduh", "suku": "te·duh", "lafal": "/tə·duh/", "kelas": "a",
     "arti": ["tenang, tidak berangin dan tidak bergelombang; juga terlindung dari panas dan hujan",
              "keadaan hati yang tenang karena tahu badai pun tunduk kepada perintah Tuhan"],
     "ayat": "“dibuat-Nyalah badai itu diam, sehingga gelombang-gelombangnya tenang.”",
     "ref": "Mazmur 107:29", "lihat": "keteduhan, meneduhkan",
     "caption": "Kata hari ini: teduh ✍️\n\nMazmur 107 bercerita tentang pelaut yang terjebak badai sampai kehabisan akal. Lalu mereka berseru kepada TUHAN dalam kesesakan mereka. Teduh tidak berarti badai tidak pernah datang. Kadang teduh adalah apa yang tersisa setelah Tuhan berbicara kepada badai itu.\n\n📖 “dibuat-Nyalah badai itu diam, sehingga gelombang-gelombangnya tenang.” — Mazmur 107:29\n\nKetik “Teduhkan hatiku” sebagai doamu hari Rabu ini."},
    {"kata": "cukup", "suku": "cu·kup", "lafal": "/cu·kup/", "kelas": "a",
     "arti": ["sebanyak yang diperlukan; tidak kurang dan tidak berlebih",
              "percaya bahwa pemberian Tuhan untuk hari ini memadai, dan besok Ia akan memberi lagi"],
     "ayat": "“…orang yang mengumpulkan banyak, tidak kelebihan dan orang yang mengumpulkan sedikit, tidak kekurangan. Tiap-tiap orang mengumpulkan menurut keperluannya.”",
     "ref": "Keluaran 16:18", "lihat": "secukupnya, mencukupi",
     "caption": "Kata hari ini: cukup ✍️\n\nDi padang gurun, Israel memungut manna setiap pagi. Yang mengumpulkan banyak tidak kelebihan, yang mengumpulkan sedikit tidak kekurangan. Tuhan sedang mengajar mereka hidup satu hari dalam satu waktu, sambil percaya bahwa besok pagi Ia akan memberi lagi.\n\n📖 “…orang yang mengumpulkan banyak, tidak kelebihan dan orang yang mengumpulkan sedikit, tidak kekurangan. Tiap-tiap orang mengumpulkan menurut keperluannya.” — Keluaran 16:18\n\nKetik “Cukup untuk hari ini” kalau kamu sedang belajar percaya."},
    {"kata": "baik", "suku": "ba·ik", "lafal": "/ba·ik/", "kelas": "a",
     "arti": ["berkelakuan ramah, suka menolong, dan tidak merugikan orang lain",
              "meniru Bapa yang tetap berbuat baik, bahkan kepada orang yang tidak membalas atau tidak berterima kasih"],
     "ayat": "“…berbuatlah baik kepada mereka… sebab Ia baik terhadap orang-orang yang tidak tahu berterima kasih dan terhadap orang-orang jahat.”",
     "ref": "Lukas 6:35", "lihat": "kebaikan, berbuat baik",
     "caption": "Kata hari ini: baik ✍️\n\nHari ini Hari Kebaikan Sedunia. Yesus memberi ukuran kebaikan yang jauh lebih tinggi dari sekadar ramah kepada orang yang ramah kepada kita. Alasannya bukan supaya kita terlihat hebat, tapi karena begitulah Bapa memperlakukan kita.\n\n📖 “…berbuatlah baik kepada mereka… sebab Ia baik terhadap orang-orang yang tidak tahu berterima kasih dan terhadap orang-orang jahat.” — Lukas 6:35\n\nTag seseorang yang pernah baik kepadamu tanpa minta balasan 👇"},
    {"kata": "sabat", "suku": "sa·bat", "lafal": "/sa·bat/", "kelas": "n",
     "arti": ["hari ketujuh, hari perhentian dari pekerjaan bagi bangsa Israel",
              "pemberian Tuhan: waktu berhenti untuk mengingat bahwa hidup kita dipelihara-Nya, bukan oleh kesibukan kita"],
     "ayat": "“Lalu kata Yesus kepada mereka: ‘Hari Sabat diadakan untuk manusia dan bukan manusia untuk hari Sabat,’”",
     "ref": "Markus 2:27", "lihat": "perhentian, istirahat",
     "caption": "Kata hari ini: sabat ✍️\n\nBagi kita yang terbiasa merasa bersalah saat beristirahat, kalimat Yesus ini melegakan. Hari perhentian bukan beban tambahan, tapi hadiah. Tuhan tahu kita ini manusia yang perlu berhenti, dan di dalam Yesus kita belajar beristirahat sambil percaya.\n\n📖 “Lalu kata Yesus kepada mereka: ‘Hari Sabat diadakan untuk manusia dan bukan manusia untuk hari Sabat,’” — Markus 2:27\n\nSabtu ini, ambil waktu untuk benar-benar berhenti. Ketik 🕊️ kalau kamu mau mencobanya."},
]

# ---------- TIKET: boarding pass (pagi2 hari 2, 3, 5, 6) ----------
TIKET = [
    {"dari": "Khawatir", "kode_dari": "KHW", "ke": "Damai", "kode_ke": "DMI", "penumpang": "KAMU",
     "kelas": "Anugerah", "kursi": "1A", "gerbang": "Doa", "berangkat": "Senin pagi",
     "ayat": "“Ya TUHAN, Engkau akan menyediakan damai sejahtera bagi kami, sebab segala sesuatu yang kami kerjakan, Engkaulah yang melakukannya bagi kami.”",
     "ref": "Yesaya 26:12",
     "caption": "Tiket untuk Senin pagi ✈️\n\nDari khawatir ke damai, lewat gerbang doa. Kita tetap bekerja, tetap rapat, tetap mengejar tenggat. Tapi kita tidak bekerja sendirian. Yesaya mengakui bahwa semua yang dikerjakan umat Tuhan sebenarnya dikerjakan Tuhan bagi mereka.\n\n📖 “Ya TUHAN, Engkau akan menyediakan damai sejahtera bagi kami, sebab segala sesuatu yang kami kerjakan, Engkaulah yang melakukannya bagi kami.” — Yesaya 26:12\n\nKirim tiket ini ke teman yang berangkat kerja dengan hati berat 💌"},
    {"dari": "Takut", "kode_dari": "TKT", "ke": "Bertahan", "kode_ke": "BTH", "penumpang": "PAHLAWAN BIASA",
     "kelas": "Iman", "kursi": "11", "gerbang": "Ibrani", "berangkat": "Hari ini",
     "ayat": "“Karena iman maka ia telah meninggalkan Mesir dengan tidak takut akan murka raja. Ia bertahan sama seperti ia melihat apa yang tidak kelihatan.”",
     "ref": "Ibrani 11:27",
     "caption": "Tiket para pahlawan iman 🎫\n\nIbrani 11 berisi daftar orang-orang yang tidak sempurna. Musa salah satunya. Ia pernah melarikan diri dan pernah bertanya, siapakah aku ini? Tapi pada waktunya ia bertahan, bukan karena merasa kuat, melainkan karena matanya tertuju kepada Allah yang tidak kelihatan.\n\n📖 “Karena iman maka ia telah meninggalkan Mesir dengan tidak takut akan murka raja. Ia bertahan sama seperti ia melihat apa yang tidak kelihatan.” — Ibrani 11:27\n\nKetik “Aku bertahan” kalau hari ini kamu butuh keberanian untuk terus melangkah."},
    {"dari": "Kemarin", "kode_dari": "KMR", "ke": "Hari ini", "kode_ke": "HRI", "penumpang": "KAMU",
     "kelas": "Rahmat baru", "kursi": "Depan", "gerbang": "Pagi", "berangkat": "Sekarang",
     "ayat": "“…aku melupakan apa yang telah di belakangku dan mengarahkan diri kepada apa yang di hadapanku,”",
     "ref": "Filipi 3:13",
     "caption": "Tiket sekali jalan: kemarin ke hari ini 🎫\n\nPaulus punya masa lalu yang bisa membuatnya bangga, dan juga masa lalu yang bisa membuatnya malu. Keduanya ia taruh di belakang supaya ia bisa terus mengejar Kristus. Kemarin tidak perlu ikut naik ke pesawat hari ini.\n\n📖 “…aku melupakan apa yang telah di belakangku dan mengarahkan diri kepada apa yang di hadapanku,” — Filipi 3:13\n\nKetik “Hari ini” kalau kamu mau melangkah tanpa membawa beban kemarin."},
    {"dari": "Diriku", "kode_dari": "DRK", "ke": "Sesama", "kode_ke": "SSM", "penumpang": "KAMU",
     "kelas": "Kebaikan", "kursi": "Sebelahmu", "gerbang": "Rumah", "berangkat": "Selagi ada",
     "ayat": "“Karena itu, selama masih ada kesempatan bagi kita, marilah kita berbuat baik kepada semua orang, tetapi terutama kepada kawan-kawan kita seiman.”",
     "ref": "Galatia 6:10",
     "caption": "Tiket kebaikan, berangkat selagi ada kesempatan 🎫\n\nHari Kebaikan Sedunia mengingatkan kita bahwa kesempatan berbuat baik itu ada jadwalnya. Teman yang sedang sakit, orang tua yang menunggu telepon, rekan kerja yang kewalahan. Jangan tunggu sampai pesawatnya lepas landas.\n\n📖 “Karena itu, selama masih ada kesempatan bagi kita, marilah kita berbuat baik kepada semua orang, tetapi terutama kepada kawan-kawan kita seiman.” — Galatia 6:10\n\nTag satu orang yang mau kamu tolong minggu ini 👇"},
]

# ---------- CATATAN: daftar centang di aplikasi catatan HP (siang0 10:30) ----------
CATATAN = [
    {"judul": "Dibawa ke ibadah hari ini",
     "item": [["Datang ibadah pagi", "v"], ["Cerita kebutuhanku ke Bapa", "v"], ["Panik soal tagihan bulan depan", "x"],
              ["Membandingkan hidupku", "x"], ["Percaya Dia tahu, lalu tenang", "o"]],
     "ayat": "“Perhatikanlah burung-burung gagak… diberi makan oleh Allah. Betapa jauhnya kamu melebihi burung-burung itu!”",
     "ref": "Lukas 12:24",
     "caption": "Catatan kecil hari Minggu 📝\n\nYesus menyuruh kita memperhatikan burung gagak, burung yang tidak punya gudang dan tidak menyimpan stok. Tapi setiap hari mereka diberi makan oleh Allah. Kalau burung saja dipelihara, apalagi kamu.\n\n📖 “Perhatikanlah burung-burung gagak yang tidak menabur dan tidak menuai dan tidak mempunyai gudang atau lumbung, namun demikian diberi makan oleh Allah. Betapa jauhnya kamu melebihi burung-burung itu!” — Lukas 12:24\n\nSave catatan ini dan baca lagi waktu kamu mulai panik 🔖"},
    {"judul": "To-do Senin (versi berserah)",
     "item": [["Doa sebelum buka laptop", "v"], ["Serahkan rapat jam 10", "v"], ["Memikul semuanya sendirian", "x"],
              ["Cek email tiap tiga menit", "x"], ["Kerjakan bagianku dengan setia", "o"]],
     "ayat": "“Serahkanlah perbuatanmu kepada TUHAN, maka terlaksanalah segala rencanamu.”",
     "ref": "Amsal 16:3",
     "caption": "To-do list Senin, versi berserah 📝\n\nBerserah bukan berarti berhenti bekerja. Kita tetap mengerjakan bagian kita dengan sungguh-sungguh. Bedanya, kita tidak lagi memikul hasilnya sendirian. Ayat ini bukan jaminan bahwa semua keinginan kita pasti jadi, tapi undangan untuk melibatkan Tuhan sejak awal dan membiarkan Dia meneguhkan yang baik.\n\n📖 “Serahkanlah perbuatanmu kepada TUHAN, maka terlaksanalah segala rencanamu.” — Amsal 16:3\n\nApa yang mau kamu serahkan dari daftar Senin-mu? Tulis di komentar 👇"},
    {"judul": "Keberanian sehari-hari",
     "item": [["Jujur walau rugi sedikit", "v"], ["Minta maaf duluan", "v"], ["Diam saat teman dirundung", "x"],
              ["Membela yang lemah dengan sopan", "o"], ["Mengaku percaya tanpa malu", "o"]],
     "ayat": "“…Mereka telah luput dari mata pedang, telah beroleh kekuatan dalam kelemahan, telah menjadi kuat dalam peperangan…”",
     "ref": "Ibrani 11:34",
     "caption": "Pahlawan tidak selalu memakai seragam 📝\n\nDi Hari Pahlawan ini, ingat bahwa keberanian juga muncul dalam hal kecil: jujur saat bisa curang, minta maaf saat gengsi, membela teman saat semua diam. Para pahlawan iman di Ibrani 11 pun bukan orang yang kuat dari sananya. Mereka orang lemah yang dikuatkan Tuhan.\n\n📖 “…Mereka telah luput dari mata pedang, telah beroleh kekuatan dalam kelemahan, telah menjadi kuat dalam peperangan…” — Ibrani 11:34\n\nKeberanian kecil apa yang mau kamu lakukan hari ini? Tulis di komentar 👇"},
    {"judul": "Saat badai datang",
     "item": [["Berdoa sebelum panik", "v"], ["Baca berita buruk jam 2 pagi", "x"], ["Membayangkan skenario terburuk", "x"],
              ["Minta teman ikut mendoakan", "v"], ["Tidur, karena Dia tetap berjaga", "o"]],
     "ayat": "“Engkaulah yang memerintah kecongkakan laut, pada waktu naik gelombang-gelombangnya, Engkau juga yang meredakannya.”",
     "ref": "Mazmur 89:10",
     "caption": "Daftar untuk hari-hari berbadai 📝\n\nBadai dalam hidup kita tidak selalu cepat berlalu. Tapi kita bisa memilih apa yang kita lakukan di tengahnya. Laut yang paling ganas pun tetap ada di bawah perintah Tuhan.\n\n📖 “Engkaulah yang memerintah kecongkakan laut, pada waktu naik gelombang-gelombangnya, Engkau juga yang meredakannya.” — Mazmur 89:10\n\nKirim catatan ini ke teman yang sedang melewati badai 💌"},
    {"judul": "Rencana hari ini (saja)",
     "item": [["Bangun dan bilang terima kasih", "v"], ["Mengkhawatirkan tahun depan", "x"], ["Kerjakan satu hal dengan setia", "o"],
              ["Makan siang tanpa buru-buru", "o"], ["Mengulang-ulang salah kemarin", "x"]],
     "ayat": "“Sebenarnya kamu harus berkata: ‘Jika Tuhan menghendakinya, kami akan hidup dan berbuat ini dan itu.’”",
     "ref": "Yakobus 4:15",
     "caption": "Rencana untuk hari ini saja 📝\n\nYakobus tidak melarang kita membuat rencana. Ia hanya mengingatkan siapa yang memegang hari esok. Jadi kita merencanakan dengan tangan terbuka, lalu menjalani hari ini dengan sepenuh hati.\n\n📖 “Sebenarnya kamu harus berkata: ‘Jika Tuhan menghendakinya, kami akan hidup dan berbuat ini dan itu.’” — Yakobus 4:15\n\nTulis satu hal yang mau kamu kerjakan dengan setia hari ini 👇"},
    {"judul": "Misi kebaikan hari Jumat",
     "item": [["Traktir kopi satpam kantor", "v"], ["Balas chat Ibu dengan sabar", "v"], ["Balas sindiran dengan sindiran", "x"],
              ["Jenguk teman yang sakit", "o"], ["Doakan orang yang menyebalkan", "o"]],
     "ayat": "“Janganlah menahan kebaikan dari pada orang-orang yang berhak menerimanya, padahal engkau mampu melakukannya.”",
     "ref": "Amsal 3:27",
     "caption": "Misi kecil di Hari Kebaikan Sedunia 📝\n\nKebaikan jarang butuh rencana besar. Seringnya cuma butuh kita berhenti menunda: telepon yang tidak jadi, ucapan terima kasih yang tertahan, bantuan yang sebenarnya bisa kita berikan hari ini.\n\n📖 “Janganlah menahan kebaikan dari pada orang-orang yang berhak menerimanya, padahal engkau mampu melakukannya.” — Amsal 3:27\n\nTambahkan satu misi kebaikanmu di komentar 👇"},
    {"judul": "Sebelum ibadah besok",
     "item": [["Siapkan baju untuk ibadah", "v"], ["Siapkan persembahan", "v"], ["Begadang sampai jam 2 pagi", "x"],
              ["Doakan pendeta dan jemaat", "o"], ["Datang untuk mendengar", "o"]],
     "ayat": "“Jagalah langkahmu, kalau engkau berjalan ke rumah Allah! Menghampiri untuk mendengar adalah lebih baik…”",
     "ref": "Pengkhotbah 4:17",
     "caption": "Checklist sebelum hari Minggu 📝\n\nIbadah besok tidak dimulai saat lagu pertama dinyanyikan. Ibadah dimulai hari ini, dari hati yang disiapkan dan tubuh yang cukup istirahat. Pengkhotbah mengingatkan bahwa datang untuk mendengar lebih baik daripada sekadar hadir.\n\n📖 “Jagalah langkahmu, kalau engkau berjalan ke rumah Allah! Menghampiri untuk mendengar adalah lebih baik…” — Pengkhotbah 4:17\n\nKetik “Siap mendengar” kalau besok kamu mau beribadah ⛪"},
]

# ---------- STRUK: struk kasir thermal (siang 12:00) ----------
STRUK = [
    {"toko": "LUMBUNG KASIH KARUNIA",
     "item": [["Roti hari ini", "GRATIS"], ["Napas pagi ini", "GRATIS"], ["Penyertaan 24 jam", "GRATIS"],
              ["Pengampunan dosa", "LUNAS"], ["Anak-Nya sendiri", "DIBERIKAN"]],
     "total": ["TOTAL", "Rp0"], "bayar": "DARI BAPA, DIBAYAR OLEH YESUS",
     "ayat": "“…yang tidak menyayangkan Anak-Nya sendiri, tetapi yang menyerahkan-Nya bagi kita semua, bagaimanakah mungkin Ia tidak mengaruniakan segala sesuatu…”",
     "ref": "Roma 8:32",
     "caption": "Struk dari Bapa yang memelihara 🧾\n\nKalau Bapa sudah memberikan yang paling berharga, yaitu Anak-Nya sendiri, apakah Ia akan menahan hal lain yang benar-benar kita perlukan? Paulus menjawab dengan sebuah pertanyaan yang membuat hati tenang.\n\n📖 “Ia, yang tidak menyayangkan Anak-Nya sendiri, tetapi yang menyerahkan-Nya bagi kita semua, bagaimanakah mungkin Ia tidak mengaruniakan segala sesuatu kepada kita bersama-sama dengan Dia?” — Roma 8:32\n\nKetik “Sudah dibayar” kalau kamu bersyukur untuk anugerah-Nya 🤍"},
    {"toko": "LOKET PENITIPAN BEBAN",
     "item": [["Kekhawatiran Senin", "DITANGGUNG"], ["Rasa bersalah lama", "DIPIKUL"], ["Hati yang lelah", "DIPIKUL"],
              ["Biaya penitipan", "GRATIS"]],
     "total": ["SISA BEBAN", "0 kg"], "bayar": "DIPIKUL OLEH: YESUS",
     "ayat": "“Tetapi sesungguhnya, penyakit kitalah yang ditanggungnya, dan kesengsaraan kita yang dipikulnya…”",
     "ref": "Yesaya 53:4",
     "caption": "Struk penitipan beban, Senin siang 🧾\n\nYesaya menulis tentang Hamba TUHAN yang menanggung apa yang seharusnya kita tanggung. Perjanjian Baru menunjuk Yesus sebagai Hamba itu. Di kayu salib Ia memikul dosa kita, dan sampai hari ini kita boleh membawa beban apa pun kepada-Nya.\n\n📖 “Tetapi sesungguhnya, penyakit kitalah yang ditanggungnya, dan kesengsaraan kita yang dipikulnya, padahal kita mengira dia kena tulah, dipukul dan ditindas Allah.” — Yesaya 53:4\n\nTitipkan bebanmu dalam doa, lalu ketik “Sudah kutitipkan” 🤍"},
    {"toko": "KANTOR PENEBUSAN",
     "item": [["Kebebasan dari dosa", "LUNAS"], ["Hidup yang baru", "LUNAS"], ["Perak", "TIDAK LAKU"],
              ["Emas", "TIDAK LAKU"], ["Biaya admin", "Rp0"]],
     "total": ["TEBUSAN", "LUNAS"], "bayar": "DIBAYAR DENGAN DARAH KRISTUS",
     "ayat": "“…kamu telah ditebus dari cara hidupmu yang sia-sia… bukan dengan barang yang fana, bukan pula dengan perak atau emas,”",
     "ref": "1 Petrus 1:18",
     "caption": "Struk dari Pahlawan yang sejati 🧾\n\nDi Hari Pahlawan kita mengenang orang-orang yang membayar mahal untuk kebebasan orang lain. Alkitab bercerita tentang harga yang jauh lebih mahal: kebebasan kita dari dosa tidak dibeli dengan perak atau emas, melainkan dengan darah Kristus sendiri.\n\n📖 “Sebab kamu tahu, bahwa kamu telah ditebus dari cara hidupmu yang sia-sia yang kamu warisi dari nenek moyangmu itu bukan dengan barang yang fana, bukan pula dengan perak atau emas,” — 1 Petrus 1:18\n\nKetik “Ditebus” kalau kamu bersyukur untuk harga yang sudah Ia bayar 🤍"},
    {"toko": "KEDAI DAMAI SEJAHTERA",
     "item": [["Damai dengan Allah", "LUNAS"], ["Hukuman dosa", "DIHAPUS"], ["Akses kepada Bapa", "TERBUKA"],
              ["Hati yang tenang", "GRATIS"]],
     "total": ["TOTAL", "Rp0"], "bayar": "DIBAYAR LUNAS OLEH: YESUS",
     "ayat": "“Sebab itu, kita yang dibenarkan karena iman, kita hidup dalam damai sejahtera dengan Allah oleh karena Tuhan kita, Yesus Kristus.”",
     "ref": "Roma 5:1",
     "caption": "Damai yang tidak bisa dibeli 🧾\n\nBadai di luar bisa datang dan pergi. Tapi ada damai yang lebih dalam dari keadaan apa pun: damai dengan Allah. Damai itu tidak kita bayar dengan usaha atau kebaikan kita, tapi diberikan karena Yesus.\n\n📖 “Sebab itu, kita yang dibenarkan karena iman, kita hidup dalam damai sejahtera dengan Allah oleh karena Tuhan kita, Yesus Kristus.” — Roma 5:1\n\nSave struk ini untuk hari-hari yang berbadai 🔖"},
    {"toko": "LOKET PELUNASAN",
     "item": [["Utang dosa kemarin", "DIHAPUS"], ["Kesalahan lama", "DIHAPUS"], ["Rahmat pagi ini", "BARU"],
              ["Denda keterlambatan", "Rp0"]],
     "total": ["SISA UTANG", "Rp0"], "bayar": "DILUNASI DI KAYU SALIB",
     "ayat": "“dengan menghapuskan surat hutang… Dan itu ditiadakan-Nya dengan memakukannya pada kayu salib:”",
     "ref": "Kolose 2:14",
     "caption": "Hari baru, tanpa utang lama 🧾\n\nKadang kita memulai hari sambil membawa catatan kesalahan kemarin. Paulus menulis bahwa surat utang dosa kita sudah dipaku di kayu salib. Karena itu setiap pagi kita bisa mulai lagi, bukan dari nol, tapi dari anugerah.\n\n📖 “dengan menghapuskan surat hutang, yang oleh ketentuan-ketentuan hukum mendakwa dan mengancam kita. Dan itu ditiadakan-Nya dengan memakukannya pada kayu salib:” — Kolose 2:14\n\nKetik “Lunas” kalau kamu mau menjalani hari ini dengan lega 🤍"},
    {"toko": "TOKO KEMURAHAN",
     "item": [["Kemurahan Allah", "GRATIS"], ["Kasih-Nya kepada kita", "GRATIS"], ["Kesempatan kedua", "GRATIS"],
              ["Kopi untuk teman", "1x"], ["Senyum untuk kasir", "1x"]],
     "total": ["TOTAL", "ANUGERAH"], "bayar": "SUDAH DIBAYAR OLEH: YESUS",
     "ayat": "“Tetapi ketika nyata kemurahan Allah, Juruselamat kita, dan kasih-Nya kepada manusia,”",
     "ref": "Titus 3:4",
     "caption": "Struk Hari Kebaikan Sedunia 🧾\n\nSebelum kita belajar baik kepada orang lain, kita sudah lebih dulu menerima kemurahan Allah. Bukan karena kita layak, tapi karena Ia murah hati. Kebaikan yang kita bagikan hari ini hanyalah sebagian kecil dari kebaikan yang sudah kita terima.\n\n📖 “Tetapi ketika nyata kemurahan Allah, Juruselamat kita, dan kasih-Nya kepada manusia,” — Titus 3:4\n\nBagikan satu kebaikan kecil hari ini, lalu ceritakan di komentar 👇"},
    {"toko": "KASIR HARI KETUJUH",
     "item": [["Korban karena dosa", "1x SAJA"], ["Usaha menebus diri", "BATAL"], ["Istirahat untuk jiwa", "GRATIS"],
              ["Tempat di ibadah besok", "DISIAPKAN"]],
     "total": ["SISA KERJA", "SELESAI"], "bayar": "LUNAS. YESUS SUDAH DUDUK.",
     "ayat": "“Tetapi Ia, setelah mempersembahkan hanya satu korban saja karena dosa, Ia duduk untuk selama-lamanya di sebelah kanan Allah,”",
     "ref": "Ibrani 10:12",
     "caption": "Struk akhir pekan 🧾\n\nImam-imam di Perjanjian Lama berdiri setiap hari, mempersembahkan korban yang sama berulang-ulang. Tapi Yesus, setelah satu korban saja, duduk. Karya penebusan sudah selesai. Karena itu kita boleh berhenti berusaha membayar sesuatu yang sudah lunas, dan beristirahat di dalam Dia.\n\n📖 “Tetapi Ia, setelah mempersembahkan hanya satu korban saja karena dosa, Ia duduk untuk selama-lamanya di sebelah kanan Allah,” — Ibrani 10:12\n\nKetik “Sudah lunas” kalau kamu mau beristirahat di dalam anugerah-Nya 🤍"},
]

# ---------- CHAT: Reel chat animasi "aku" & teman, ditutup kartu ayat (siang2 13:30) ----------
CHAT = [
    {"nama": "Nadia",
     "pesan": [["aku", "Nad, aku lagi kepikiran banget. Kontrakku nggak diperpanjang bulan depan 😔"],
               ["dia", "Ya ampun… kamu pasti kaget banget. Sudah tahu sejak kapan?"],
               ["aku", "Baru Jumat kemarin. Tadi di gereja pun pikiranku ke mana-mana."],
               ["dia", "Wajar kok kamu takut. Minggu ini aku temani cari lowongan, ya."],
               ["aku", "Makasih… rasanya kayak semuanya harus aku pikirin sendiri."],
               ["dia", "Kamu nggak sendiri. Bawa semuanya ke Bapa, Dia tahu cara memberi yang baik 👇"]],
     "ayat": "“Jadi jika kamu yang jahat tahu memberi pemberian yang baik kepada anak-anakmu, apalagi Bapamu yang di sorga! Ia akan memberikan yang baik kepada mereka yang meminta kepada-Nya.”",
     "ref": "Matius 7:11",
     "caption": "Kadang yang kita butuhkan cuma teman yang mau mendengar 💬\n\nKekhawatiran soal pekerjaan dan uang itu nyata, dan Yesus tidak meremehkannya. Ia justru mengajak kita membawanya kepada Bapa yang jauh lebih baik dari orang tua mana pun. Ini bukan janji bahwa semua akan berjalan sesuai rencana kita, tapi jaminan bahwa Bapa tahu cara memberi yang baik.\n\n📖 “Jadi jika kamu yang jahat tahu memberi pemberian yang baik kepada anak-anakmu, apalagi Bapamu yang di sorga! Ia akan memberikan yang baik kepada mereka yang meminta kepada-Nya.” — Matius 7:11\n\nKirim ke teman yang sedang khawatir soal pekerjaan 💌"},
    {"nama": "Dimas",
     "pesan": [["aku", "Dim, kantorku katanya mau ada pengurangan karyawan. Aku jadi susah tidur."],
               ["dia", "Waduh, berat banget. Sudah ada pengumuman resmi?"],
               ["aku", "Belum, baru kabar burung. Tapi tiap ada notif email aku langsung deg-degan."],
               ["dia", "Pantas kamu capek. Menunggu kabar yang belum pasti itu melelahkan."],
               ["aku", "Iya… aku takut kabar buruknya beneran datang."],
               ["dia", "Yuk kita doakan bareng. Ayat ini nolong aku waktu kantorku goyang tahun lalu 👇"]],
     "ayat": "“Ia tidak takut kepada kabar celaka, hatinya tetap, penuh kepercayaan kepada TUHAN.”",
     "ref": "Mazmur 112:7",
     "caption": "Untuk kamu yang deg-degan setiap ada notifikasi 💬\n\nMazmur 112 menggambarkan orang yang takut akan TUHAN. Ia tidak dijanjikan hidup tanpa kabar buruk. Tapi hatinya tetap, karena kepercayaannya tidak bergantung pada kabar yang datang, melainkan pada TUHAN.\n\n📖 “Ia tidak takut kepada kabar celaka, hatinya tetap, penuh kepercayaan kepada TUHAN.” — Mazmur 112:7\n\nKetik “Hatiku tetap” kalau kamu sedang menunggu kabar."},
    {"nama": "Bima",
     "pesan": [["aku", "Bim, aku diminta jadi ketua panitia Natal. Rasanya pengin nolak 😅"],
               ["dia", "Hahaha kenapa? Cerita dulu."],
               ["aku", "Aku bukan orang yang berani tampil. Takut salah, takut mengecewakan orang."],
               ["dia", "Takut itu wajar. Yang penting kamu nggak menjalaninya sendirian."],
               ["aku", "Tapi masa orang kayak aku dipakai Tuhan?"],
               ["dia", "Gideon juga lagi sembunyi waktu dipanggil. Lihat Tuhan menyebut dia apa 👇"]],
     "ayat": "“Malaikat TUHAN menampakkan diri kepadanya dan berfirman kepadanya, demikian: ‘TUHAN menyertai engkau, ya pahlawan yang gagah berani.’”",
     "ref": "Hakim-hakim 6:12",
     "caption": "Pahlawan yang sedang bersembunyi 💬\n\nGideon sedang mengirik gandum diam-diam karena takut kepada orang Midian. Sama sekali tidak terlihat seperti pahlawan. Tapi keberaniannya dimulai dari kalimat pertama yang ia dengar: TUHAN menyertai engkau. Pahlawan iman bukan orang yang tidak pernah takut, tapi orang yang tahu siapa yang menyertainya.\n\n📖 “Malaikat TUHAN menampakkan diri kepadanya dan berfirman kepadanya, demikian: ‘TUHAN menyertai engkau, ya pahlawan yang gagah berani.’” — Hakim-hakim 6:12\n\nTag teman yang perlu diingatkan bahwa Tuhan menyertainya 👇"},
    {"nama": "Tiur",
     "pesan": [["aku", "Tiur, bapakku masuk IGD tadi pagi. Aku masih di rumah sakit."],
               ["dia", "Ya Tuhan… aku ikut sedih. Gimana kondisinya sekarang?"],
               ["aku", "Masih diobservasi. Aku duduk di lorong, rasanya kayak di tengah badai."],
               ["dia", "Aku di sini. Kamu sudah makan? Nanti sore aku antar makanan, ya."],
               ["aku", "Belum… makasih ya. Aku cuma takut banget."],
               ["dia", "Daud juga pernah takut waktu sembunyi di gua. Ini doanya, kita doakan bareng 🤍"]],
     "ayat": "“Kasihanilah aku, ya Allah, kasihanilah aku, sebab kepada-Mulah jiwaku berlindung; dalam naungan sayap-Mu aku akan berlindung, sampai berlalu penghancuran itu.”",
     "ref": "Mazmur 57:2",
     "caption": "Badai yang tidak langsung reda 💬\n\nDaud menulis mazmur ini ketika lari dari Saul dan bersembunyi di gua. Ia tidak pura-pura semuanya aman. Ia berlindung di bawah sayap Tuhan sampai bahaya itu berlalu. Kadang Tuhan menenangkan badainya, kadang Ia menenangkan kita di tengah badai.\n\n📖 “Kasihanilah aku, ya Allah, kasihanilah aku, sebab kepada-Mulah jiwaku berlindung; dalam naungan sayap-Mu aku akan berlindung, sampai berlalu penghancuran itu.” — Mazmur 57:2\n\nKalau keluargamu sedang dirawat, tulis namanya di komentar. Kami ikut mendoakan 🙏"},
    {"nama": "Andre",
     "pesan": [["aku", "Ndre, aku kepikiran semester depan, magang, terus nanti kerja apa. Pusing."],
               ["dia", "Wah, banyak banget yang lagi kamu pikul. Yang paling berat yang mana?"],
               ["aku", "Semuanya kerasa harus dipikirin sekarang. Padahal skripsiku aja belum beres."],
               ["dia", "Pantas capek. Kamu lagi mencoba menjalani lima tahun dalam satu malam."],
               ["aku", "Iya juga ya 😅 terus aku harus gimana?"],
               ["dia", "Satu hari dulu. Tuhan pernah mengajari Israel caranya, lewat roti dari langit 👇"]],
     "ayat": "“Lalu berfirmanlah TUHAN kepada Musa: ‘Sesungguhnya Aku akan menurunkan dari langit hujan roti bagimu; maka bangsa itu akan keluar dan memungut tiap-tiap hari sebanyak yang perlu untuk sehari…’”",
     "ref": "Keluaran 16:4",
     "caption": "Satu hari dulu 💬\n\nManna di padang gurun tidak bisa ditimbun. Setiap pagi Israel harus keluar lagi dan memungut secukupnya untuk hari itu. Bukan karena Tuhan pelit, tapi karena Ia ingin umat-Nya belajar bersandar kepada-Nya setiap hari.\n\n📖 “Lalu berfirmanlah TUHAN kepada Musa: ‘Sesungguhnya Aku akan menurunkan dari langit hujan roti bagimu; maka bangsa itu akan keluar dan memungut tiap-tiap hari sebanyak yang perlu untuk sehari…’” — Keluaran 16:4\n\nTag temanmu yang sedang memikirkan terlalu jauh ke depan 👇"},
    {"nama": "Sekar",
     "pesan": [["aku", "Kar, temanku lagi down berat. Aku pengin bantu, tapi takut salah ngomong."],
               ["dia", "Kamu peduli banget sama dia. Dia sudah cerita sesuatu ke kamu?"],
               ["aku", "Sedikit. Katanya dia capek dan merasa nggak berguna. Aku bingung jawab apa."],
               ["dia", "Kadang kita nggak perlu punya jawaban. Cukup hadir dan dengarkan dulu."],
               ["aku", "Tapi rasanya terlalu kecil… cuma kirim pesan."],
               ["dia", "Kita doakan dia juga. Dan jangan remehkan satu kalimat yang baik 👇"]],
     "ayat": "“Kekuatiran dalam hati membungkukkan orang, tetapi perkataan yang baik menggembirakan dia.”",
     "ref": "Amsal 12:25",
     "caption": "Kebaikan bisa sesederhana satu kalimat 💬\n\nDi Hari Kebaikan Sedunia, ingat bahwa kata-kata yang baik bisa menegakkan hati yang sedang membungkuk karena khawatir. Kamu tidak harus punya semua jawaban. Hadir, dengarkan, doakan, dan katakan hal yang baik. Kalau temanmu tampak sangat terpuruk, temani dia mencari bantuan konselor atau tenaga profesional.\n\n📖 “Kekuatiran dalam hati membungkukkan orang, tetapi perkataan yang baik menggembirakan dia.” — Amsal 12:25\n\nKirim satu pesan baik ke teman yang sedang berat hari ini 💌"},
    {"nama": "Yohan",
     "pesan": [["aku", "Han, minggu ini capek banget. Besok kayaknya aku nggak ke gereja deh."],
               ["dia", "Kedengarannya kamu benar-benar terkuras. Minggu ini kenapa?"],
               ["aku", "Lembur terus. Tapi kalau istirahat, aku merasa bersalah, kayak ketinggalan."],
               ["dia", "Hmm, sudah lama kamu nggak benar-benar berhenti, ya?"],
               ["aku", "Iya. Bahkan di gereja pun pikiranku masih di kerjaan."],
               ["dia", "Tidur yang cukup malam ini, besok kita ibadah bareng. Istirahat itu pemberian Tuhan 👇"]],
     "ayat": "“Jadi masih tersedia suatu hari perhentian, hari ketujuh, bagi umat Allah. Sebab barangsiapa telah masuk ke tempat perhentian-Nya, ia sendiri telah berhenti dari segala pekerjaannya…”",
     "ref": "Ibrani 4:9-10",
     "caption": "Capek yang tidak hilang dengan sekadar libur 💬\n\nPenulis Ibrani berbicara tentang perhentian yang lebih dalam dari akhir pekan: berhenti berusaha membuktikan diri, lalu percaya kepada karya Kristus yang sudah selesai. Tidur malam ini dan ibadah besok adalah cara kecil untuk belajar perhentian itu.\n\n📖 “Jadi masih tersedia suatu hari perhentian, hari ketujuh, bagi umat Allah. Sebab barangsiapa telah masuk ke tempat perhentian-Nya, ia sendiri telah berhenti dari segala pekerjaannya, sama seperti Allah berhenti dari pekerjaan-Nya.” — Ibrani 4:9-10\n\nTag teman yang mau kamu ajak ibadah bareng besok 👇"},
]

# ---------- KALENDER: kalender sobek, hitung mundur Natal (sore 15:00), 47 hari (8 Nov) sampai 41 hari (14 Nov) ----------
KALENDER = [
    {"angka": 47, "tanggal": "Minggu, 8 November",
     "teks": "Kebutuhan terbesar kita sudah Bapa jawab di Betlehem.",
     "ayat": "“Ia akan melahirkan anak laki-laki dan engkau akan menamakan Dia Yesus, karena Dialah yang akan menyelamatkan umat-Nya dari dosa mereka.”",
     "ref": "Matius 1:21",
     "caption": "47 hari lagi 🎄\n\nBapa tahu kebutuhan kita, termasuk yang paling dalam dan sering tidak kita sadari: diselamatkan dari dosa. Natal adalah jawaban Bapa untuk kebutuhan itu. Nama Yesus sendiri sudah menjelaskan untuk apa Ia datang.\n\n📖 “Ia akan melahirkan anak laki-laki dan engkau akan menamakan Dia Yesus, karena Dialah yang akan menyelamatkan umat-Nya dari dosa mereka.” — Matius 1:21\n\nKetik 🎄 kalau kamu ikut menghitung mundur bersama kami."},
    {"angka": 46, "tanggal": "Senin, 9 November",
     "teks": "Maria belum tahu semua jawabannya, tapi ia berserah.",
     "ayat": "“Kata Maria: ‘Sesungguhnya aku ini adalah hamba Tuhan; jadilah padaku menurut perkataanmu itu.’…”",
     "ref": "Lukas 1:38",
     "caption": "46 hari lagi 🕊️\n\nMaria masih muda, rencananya mendadak berubah, dan banyak pertanyaan yang belum terjawab. Tapi ia memilih berserah kepada Tuhan yang ia percayai. Natal pertama dimulai dari hati yang berkata ya.\n\n📖 “Kata Maria: ‘Sesungguhnya aku ini adalah hamba Tuhan; jadilah padaku menurut perkataanmu itu.’ Lalu malaikat itu meninggalkan dia.” — Lukas 1:38\n\nKetik “Jadilah padaku” kalau kamu mau belajar berserah minggu ini."},
    {"angka": 45, "tanggal": "Selasa, 10 November",
     "teks": "Pahlawan sejati datang sebagai bayi: Allah yang Perkasa.",
     "ayat": "“Sebab seorang anak telah lahir untuk kita… dan namanya disebutkan orang: Penasihat Ajaib, Allah yang Perkasa, Bapa yang Kekal, Raja Damai.”",
     "ref": "Yesaya 9:5",
     "caption": "45 hari lagi ✨\n\nDi Hari Pahlawan, Yesaya mengingatkan kita tentang Pahlawan yang tidak datang dengan pasukan, tapi lahir sebagai bayi. Namanya Allah yang Perkasa. Ia datang untuk mengalahkan dosa dan maut, demi kita.\n\n📖 “Sebab seorang anak telah lahir untuk kita, seorang putera telah diberikan untuk kita; lambang pemerintahan ada di atas bahunya, dan namanya disebutkan orang: Penasihat Ajaib, Allah yang Perkasa, Bapa yang Kekal, Raja Damai.” — Yesaya 9:5\n\nKetik “Allah yang Perkasa” kalau kamu mau menyambut Natal dengan iman."},
    {"angka": 44, "tanggal": "Rabu, 11 November",
     "teks": "Bayi di palungan itu datang untuk menuntun kita ke jalan damai.",
     "ayat": "“untuk menyinari mereka yang diam dalam kegelapan dan dalam naungan maut untuk mengarahkan kaki kita kepada jalan damai sejahtera.”",
     "ref": "Lukas 1:79",
     "caption": "44 hari lagi 🕯️\n\nZakharia menyanyikan ini saat anaknya, Yohanes, lahir. Ia tahu Yohanes akan mempersiapkan jalan bagi Seseorang yang jauh lebih besar: Dia yang menuntun kaki kita ke jalan damai, bahkan di tengah badai.\n\n📖 “untuk menyinari mereka yang diam dalam kegelapan dan dalam naungan maut untuk mengarahkan kaki kita kepada jalan damai sejahtera.” — Lukas 1:79\n\nKirim ke teman yang sedang butuh damai 💌"},
    {"angka": 43, "tanggal": "Kamis, 12 November",
     "teks": "Setiap matahari terbit mengingatkan: Surya pagi itu sudah datang.",
     "ayat": "“oleh rahmat dan belas kasihan dari Allah kita, dengan mana Ia akan melawat kita, Surya pagi dari tempat yang tinggi,”",
     "ref": "Lukas 1:78",
     "caption": "43 hari lagi 🌅\n\nZakharia menyebut Mesias yang akan datang dengan sebutan yang indah: Surya pagi dari tempat yang tinggi. Setiap kali matahari terbit, kita diingatkan bahwa rahmat Allah datang lagi, dan Terang itu sudah datang ke dunia.\n\n📖 “oleh rahmat dan belas kasihan dari Allah kita, dengan mana Ia akan melawat kita, Surya pagi dari tempat yang tinggi,” — Lukas 1:78\n\nKetik 🌅 kalau hari ini kamu bersyukur untuk rahmat-Nya yang baru."},
    {"angka": 42, "tanggal": "Jumat, 13 November",
     "teks": "Kebaikan Yusuf: menjaga nama baik orang lain, walau hatinya terluka.",
     "ayat": "“Karena Yusuf suaminya, seorang yang tulus hati dan tidak mau mencemarkan nama isterinya di muka umum…”",
     "ref": "Matius 1:19",
     "caption": "42 hari lagi 🤍\n\nSebelum malaikat menjelaskan semuanya, Yusuf hanya tahu satu hal: Maria mengandung, dan anak itu bukan anaknya. Ia bisa saja mempermalukan Maria di depan umum. Tapi ia memilih jalan yang tulus dan lembut. Di Hari Kebaikan Sedunia, kita belajar dari Yusuf.\n\n📖 “Karena Yusuf suaminya, seorang yang tulus hati dan tidak mau mencemarkan nama isterinya di muka umum, ia bermaksud menceraikannya dengan diam-diam.” — Matius 1:19\n\nTag seseorang yang pernah menjaga nama baikmu 👇"},
    {"angka": 41, "tanggal": "Sabtu, 14 November",
     "teks": "Sebelum sibuk menyiapkan Natal, simpan dan renungkan dulu.",
     "ayat": "“Tetapi Maria menyimpan segala perkara itu di dalam hatinya dan merenungkannya.”",
     "ref": "Lukas 2:19",
     "caption": "41 hari lagi 🌙\n\nDi tengah keramaian gembala dan kabar malaikat, Maria memilih diam dan merenung. Sabtu ini, sebelum Desember datang dengan segala kesibukannya, ambil waktu untuk tenang dan menyimpan karya Tuhan di dalam hati.\n\n📖 “Tetapi Maria menyimpan segala perkara itu di dalam hatinya dan merenungkannya.” — Lukas 2:19\n\nSave untuk dibaca lagi saat Desember mulai sibuk 🔖"},
]

# ---------- POPUP: jendela galat komputer jadul (sore2 16:30) ----------
POPUP = [
    {"judul": "kekhawatiran.exe", "ikon": "galat",
     "pesan": "Kekhawatiran gagal menambah sehasta pun pada hidup Anda. Proses ini sudah berjalan 3 jam.",
     "tombol": ["Serahkan ke Bapa", "Khawatir lagi"],
     "ayat": "“Siapakah di antara kamu yang karena kekuatirannya dapat menambahkan sehasta saja pada jalan hidupnya?”",
     "ref": "Matius 6:27",
     "caption": "Error yang kita semua kenal 💻\n\nYesus mengajukan pertanyaan sederhana: siapa yang bisa memperpanjang hidupnya dengan khawatir? Tidak ada. Kekhawatiran menguras tenaga tapi tidak menghasilkan apa-apa. Bapa yang memberi makan burung di udara tahu apa yang kamu perlukan.\n\n📖 “Siapakah di antara kamu yang karena kekuatirannya dapat menambahkan sehasta saja pada jalan hidupnya?” — Matius 6:27\n\nKamu pilih tombol yang mana? Jawab di komentar 👇"},
    {"judul": "pikiran.exe", "ikon": "peringatan",
     "pesan": "Ada 27 kekhawatiran terbuka di latar belakang. Sistem melambat. Bawa semuanya ke Tuhan sekarang?",
     "tombol": ["Bawa ke Tuhan", "Biarkan terbuka"],
     "ayat": "“Selidikilah aku, ya Allah, dan kenallah hatiku, ujilah aku dan kenallah pikiran-pikiranku;”",
     "ref": "Mazmur 139:23",
     "caption": "Terlalu banyak tab terbuka 💻\n\nSenin baru setengah jalan, tapi kepala sudah penuh. Daud tidak menyembunyikan isi pikirannya dari Tuhan. Ia malah mengundang Tuhan menyelidiki semuanya. Tuhan mengenal setiap pikiranmu, termasuk yang paling cemas, dan Ia tidak pergi.\n\n📖 “Selidikilah aku, ya Allah, dan kenallah hatiku, ujilah aku dan kenallah pikiran-pikiranku;” — Mazmur 139:23\n\nBerapa tab kekhawatiran yang terbuka di kepalamu? Tulis angkanya di komentar 👇"},
    {"judul": "keberanian.exe", "ikon": "info",
     "pesan": "File roh_ketakutan.dll tidak berasal dari Allah. Ganti dengan kekuatan, kasih, dan ketertiban?",
     "tombol": ["Ganti sekarang", "Tetap takut"],
     "ayat": "“Sebab Allah memberikan kepada kita bukan roh ketakutan, melainkan roh yang membangkitkan kekuatan, kasih dan ketertiban.”",
     "ref": "2 Timotius 1:7",
     "caption": "Pembaruan sistem di Hari Pahlawan 💻\n\nPaulus menulis ini untuk Timotius, pemimpin muda yang sedang menghadapi banyak tekanan. Keberanian orang percaya tidak berasal dari kepribadian yang lantang, tapi dari Roh yang Allah berikan.\n\n📖 “Sebab Allah memberikan kepada kita bukan roh ketakutan, melainkan roh yang membangkitkan kekuatan, kasih dan ketertiban.” — 2 Timotius 1:7\n\nKetik “Ganti sekarang” kalau kamu mau melangkah dengan berani hari ini."},
    {"judul": "cek_cuaca.exe", "ikon": "tanya",
     "pesan": "Anda sudah memeriksa awan 37 kali hari ini. Benih masih di saku. Mulai menabur sekarang?",
     "tombol": ["Mulai menabur", "Cek awan lagi"],
     "ayat": "“Siapa senantiasa memperhatikan angin tidak akan menabur; dan siapa senantiasa melihat awan tidak akan menuai.”",
     "ref": "Pengkhotbah 11:4",
     "caption": "Kebiasaan kecil saat cemas 💻\n\nKalau kita menunggu sampai semua kondisi aman dan pasti, kita tidak akan pernah mulai. Pengkhotbah mengingatkan bahwa masa depan memang tidak bisa kita kendalikan, tapi itu bukan alasan untuk berhenti menabur hari ini. Hasilnya, serahkan kepada Tuhan.\n\n📖 “Siapa senantiasa memperhatikan angin tidak akan menabur; dan siapa senantiasa melihat awan tidak akan menuai.” — Pengkhotbah 11:4\n\nApa benih yang sudah terlalu lama kamu tunda? Tulis di komentar 👇"},
    {"judul": "besok.exe", "ikon": "galat",
     "pesan": "Gagal memuat hari Senin depan. Saat ini hanya hari ini yang tersedia.",
     "tombol": ["Jalani hari ini", "Coba muat lagi"],
     "ayat": "“Janganlah memuji diri karena esok hari, karena engkau tidak tahu apa yang akan terjadi hari itu.”",
     "ref": "Amsal 27:1",
     "caption": "Error yang sebenarnya hadiah 💻\n\nKita tidak bisa membuka hari esok lebih cepat, sekeras apa pun kita mencoba. Amsal mengingatkan bahwa kita memang tidak tahu apa yang terjadi besok. Kabar baiknya, Tuhan tahu, dan Ia memberi kita hari ini untuk dijalani bersama-Nya.\n\n📖 “Janganlah memuji diri karena esok hari, karena engkau tidak tahu apa yang akan terjadi hari itu.” — Amsal 27:1\n\nKetik “Jalani hari ini” kalau kamu juga sering mencoba memuat hari esok 😅"},
    {"judul": "balasan.exe", "ikon": "peringatan",
     "pesan": "Anda akan membalas sindiran dengan kebaikan. Ini bisa membuat orang bingung. Tetap lanjutkan?",
     "tombol": ["Tetap lakukan", "Batalkan"],
     "ayat": "“Janganlah kamu kalah terhadap kejahatan, tetapi kalahkanlah kejahatan dengan kebaikan!”",
     "ref": "Roma 12:21",
     "caption": "Peringatan yang layak diabaikan 💻\n\nMembalas sindiran dengan sindiran itu mudah dan terasa adil. Tapi Paulus mengajak kita menang dengan cara yang berbeda: kebaikan. Bukan karena kita lemah, tapi karena kita sendiri sudah lebih dulu menerima kebaikan Tuhan saat kita tidak layak.\n\n📖 “Janganlah kamu kalah terhadap kejahatan, tetapi kalahkanlah kejahatan dengan kebaikan!” — Roma 12:21\n\nSelamat Hari Kebaikan Sedunia. Pilih tombol pertama hari ini, lalu ceritakan di komentar 👇"},
    {"judul": "lembur.exe", "ikon": "info",
     "pesan": "Anda sudah bekerja 6 hari berturut-turut. Hari ketujuh terdeteksi. Mulai istirahat sekarang?",
     "tombol": ["Istirahat", "Lembur lagi"],
     "ayat": "“…berhentilah Ia pada hari ketujuh dari segala pekerjaan yang telah dibuat-Nya itu.”",
     "ref": "Kejadian 2:2",
     "caption": "Notifikasi hari Sabtu 💻\n\nAllah tidak berhenti karena lelah. Ia berhenti karena pekerjaan-Nya sudah selesai dan baik. Dengan itu Ia memberi pola bagi kita: bekerja dengan sungguh, lalu berhenti dan percaya bahwa dunia tetap ada di tangan-Nya, bukan di tangan kita.\n\n📖 “Ketika Allah pada hari ketujuh telah menyelesaikan pekerjaan yang dibuat-Nya itu, berhentilah Ia pada hari ketujuh dari segala pekerjaan yang telah dibuat-Nya itu.” — Kejadian 2:2\n\nKetik “Istirahat” kalau Sabtu ini kamu mau benar-benar berhenti sejenak 🕊️"},
]

# ---------- POLAROID: tiga foto polaroid + label tulisan tangan (petang 18:00) ----------
POLAROID = [
    {"judul": "Dia kenal semuanya",
     "foto": [["bintang", "dipanggil namanya"], ["laut", "tak terhitung"], ["fajar", "termasuk kamu"]],
     "ayat": "“Arahkanlah matamu ke langit dan lihatlah: siapa yang menciptakan semua bintang itu… sambil memanggil nama mereka sekaliannya?”",
     "ref": "Yesaya 40:26",
     "caption": "Tiga foto untuk hari Minggu 📷\n\nYesaya menulis kepada umat yang merasa jalan hidupnya tersembunyi dari Tuhan. Jawabannya: lihat ke langit. Allah yang memanggil setiap bintang dengan namanya tidak mungkin melupakan kebutuhanmu.\n\n📖 “Arahkanlah matamu ke langit dan lihatlah: siapa yang menciptakan semua bintang itu dan menyuruh segenap tentara mereka keluar, sambil memanggil nama mereka sekaliannya? Satupun tiada yang tak hadir, oleh sebab Ia maha kuasa dan maha kuat.” — Yesaya 40:26\n\nMalam ini, coba lihat ke langit sebentar. Lalu ketik ✨ di komentar."},
    {"judul": "Sejak awal, milik-Nya",
     "foto": [["fajar", "hari pertamaku"], ["kabut", "Senin ini"], ["laut", "sampai nanti"]],
     "ayat": "“Kepada-Mu aku diserahkan sejak aku lahir, sejak dalam kandungan ibuku Engkaulah Allahku.”",
     "ref": "Mazmur 22:11",
     "caption": "Dari hari pertama sampai Senin ini 📷\n\nMazmur 22 adalah ratapan Daud yang sangat jujur. Tapi di tengahnya, ia mengingat sesuatu: sejak lahir ia sudah ada di tangan Tuhan. Hidupmu juga tidak baru hari ini diserahkan kepada-Nya. Ia sudah memegangnya sejak awal.\n\n📖 “Kepada-Mu aku diserahkan sejak aku lahir, sejak dalam kandungan ibuku Engkaulah Allahku.” — Mazmur 22:11\n\nKetik “Sejak awal” kalau kamu mau menyerahkan minggu ini kepada-Nya."},
    {"judul": "Melambai dari jauh",
     "foto": [["laut", "berangkat"], ["bintang", "janji-Nya"], ["kabut", "tetap berjalan"]],
     "ayat": "“…tidak memperoleh apa yang dijanjikan itu, tetapi yang hanya dari jauh melihatnya dan melambai-lambai kepadanya…”",
     "ref": "Ibrani 11:13",
     "caption": "Pahlawan yang tidak melihat garis akhir 📷\n\nBanyak pahlawan iman di Ibrani 11 tidak sempat melihat janji itu digenapi. Mereka hanya melihatnya dari jauh, lalu tetap setia sampai akhir. Di Hari Pahlawan, kita belajar bahwa kesetiaan tidak diukur dari apa yang sempat kita lihat.\n\n📖 “Dalam iman mereka semua ini telah mati sebagai orang-orang yang tidak memperoleh apa yang dijanjikan itu, tetapi yang hanya dari jauh melihatnya dan melambai-lambai kepadanya dan yang mengakui, bahwa mereka adalah orang asing dan pendatang di bumi ini.” — Ibrani 11:13\n\nTag seseorang yang imannya kamu teladani 👇"},
    {"judul": "Ombaknya besar, tapi…",
     "foto": [["laut", "ombak hebat"], ["kabut", "suara air besar"], ["bintang", "TUHAN lebih hebat"]],
     "ayat": "“Dari pada suara air yang besar, dari pada pecahan ombak laut yang hebat, lebih hebat TUHAN di tempat tinggi.”",
     "ref": "Mazmur 93:4",
     "caption": "Tiga foto dari tengah badai 📷\n\nPemazmur tidak menyangkal bahwa ombaknya hebat dan suaranya menakutkan. Ia hanya menambahkan satu kalimat yang mengubah cara kita melihat badai: TUHAN lebih hebat.\n\n📖 “Dari pada suara air yang besar, dari pada pecahan ombak laut yang hebat, lebih hebat TUHAN di tempat tinggi.” — Mazmur 93:4\n\nKirim ke teman yang sedang mendengar suara ombak yang keras 💌"},
    {"judul": "Pagi dan petang bersorak",
     "foto": [["fajar", "pagi ini"], ["kabut", "siang yang biasa"], ["bintang", "petang nanti"]],
     "ayat": "“…tempat terbitnya pagi dan petang Kaubuat bersorak-sorai.”",
     "ref": "Mazmur 65:9",
     "caption": "Satu hari, dari pagi sampai petang 📷\n\nDaud melihat pagi dan petang bersorak-sorai karena Tuhan. Hari ini tidak perlu luar biasa untuk menjadi berharga. Pagi, siang, dan petangnya cukup dijalani bersama Dia, satu hari saja.\n\n📖 “Sebab itu orang-orang yang diam di ujung-ujung bumi takut kepada tanda-tanda mujizat-Mu; tempat terbitnya pagi dan petang Kaubuat bersorak-sorai.” — Mazmur 65:9\n\nFoto apa yang mewakili harimu hari ini? Ceritakan di komentar 👇"},
    {"judul": "Jejak kebaikan-Nya",
     "foto": [["fajar", "matahari terbit"], ["kabut", "hujan semalam"], ["laut", "makan bersama"]],
     "ayat": "“namun Ia bukan tidak menyatakan diri-Nya dengan berbagai-bagai kebajikan… Ia memuaskan hatimu dengan makanan dan kegembiraan.”",
     "ref": "Kisah Para Rasul 14:17",
     "caption": "Kebaikan Tuhan ada di mana-mana 📷\n\nDi Listra, Paulus berbicara kepada orang-orang yang belum mengenal Allah. Ia menunjuk hal-hal sederhana: hujan, musim panen, makanan, sukacita. Semua itu jejak kebaikan Tuhan yang mengikuti kita setiap hari.\n\n📖 “namun Ia bukan tidak menyatakan diri-Nya dengan berbagai-bagai kebajikan, yaitu dengan menurunkan hujan dari langit dan dengan memberikan musim-musim subur bagi kamu. Ia memuaskan hatimu dengan makanan dan kegembiraan.” — Kisah Para Rasul 14:17\n\nPotret satu kebaikan Tuhan hari ini, lalu ceritakan di komentar 👇"},
    {"judul": "Tempat yang sunyi",
     "foto": [["fajar", "masih gelap"], ["kabut", "tempat sunyi"], ["bintang", "hanya Dia"]],
     "ayat": "“Pagi-pagi benar, waktu hari masih gelap, Ia bangun dan pergi ke luar. Ia pergi ke tempat yang sunyi dan berdoa di sana.”",
     "ref": "Markus 1:35",
     "caption": "Yesus pun mencari tempat sunyi 📷\n\nMalam sebelumnya, setelah matahari terbenam, Yesus menyembuhkan banyak orang. Paginya, Ia tidak langsung lanjut bekerja. Ia mencari tempat yang sunyi untuk berdoa. Kalau Yesus saja meluangkan waktu untuk itu, kita pun perlu.\n\n📖 “Pagi-pagi benar, waktu hari masih gelap, Ia bangun dan pergi ke luar. Ia pergi ke tempat yang sunyi dan berdoa di sana.” — Markus 1:35\n\nDi mana tempat sunyimu akhir pekan ini? Ceritakan di komentar 👇"},
]

# ---------- NEON: Reel papan neon di dinding bata (malam0 19:30) ----------
NEON = [
    {"teks": "Carilah\ndahulu\nKerajaan Allah", "warna": "kuning",
     "ayat": "“Tetapi carilah dahulu Kerajaan Allah dan kebenarannya, maka semuanya itu akan ditambahkan kepadamu.”",
     "ref": "Matius 6:33",
     "caption": "Urutan yang menenangkan ✨\n\nYang Yesus maksud dengan semuanya itu adalah makanan, minuman, dan pakaian, kebutuhan sehari-hari yang sedang Ia bicarakan. Ia tidak menjanjikan kemewahan, tapi mengajak kita membereskan urutan: Allah dulu, lalu percaya Bapa memelihara sisanya.\n\n📖 “Tetapi carilah dahulu Kerajaan Allah dan kebenarannya, maka semuanya itu akan ditambahkan kepadamu.” — Matius 6:33\n\nKetik “Dahulu” kalau kamu mau mendahulukan Dia minggu ini."},
    {"teks": "Kepada-Mu\nkuangkat\njiwaku", "warna": "biru",
     "ayat": "“Kepada-Mu, ya TUHAN, kuangkat jiwaku;”",
     "ref": "Mazmur 25:1",
     "caption": "Doa Senin malam ✨\n\nMazmur 25 dibuka dengan kalimat sederhana dari Daud. Ia tidak memulai dengan daftar permintaan, tapi dengan mengangkat seluruh dirinya kepada Tuhan. Malam ini, angkat juga semua yang membebanimu sejak pagi.\n\n📖 “Kepada-Mu, ya TUHAN, kuangkat jiwaku;” — Mazmur 25:1\n\nKetik “Kuangkat” sebagai doamu malam ini 🤍"},
    {"teks": "Kepada\nsiapakah aku\nharus takut?", "warna": "merah",
     "ayat": "“TUHAN adalah terangku dan keselamatanku, kepada siapakah aku harus takut? TUHAN adalah benteng hidupku, terhadap siapakah aku harus gemetar?”",
     "ref": "Mazmur 27:1",
     "caption": "Pertanyaan yang membuat berani ✨\n\nDaud punya banyak alasan untuk takut: musuh, fitnah, pengkhianatan. Tapi ia balik bertanya kepada ketakutannya. Kalau TUHAN adalah terang dan benteng hidupku, kepada siapa aku harus takut?\n\n📖 “TUHAN adalah terangku dan keselamatanku, kepada siapakah aku harus takut? TUHAN adalah benteng hidupku, terhadap siapakah aku harus gemetar?” — Mazmur 27:1\n\nKetik “Tidak takut” kalau kamu mau menutup Hari Pahlawan dengan iman."},
    {"teks": "Tenanglah!\nAku ini,\njangan takut!", "warna": "ungu",
     "ayat": "“sebab mereka semua melihat Dia dan merekapun sangat terkejut. Tetapi segera Ia berkata kepada mereka: ‘Tenanglah! Aku ini, jangan takut!’”",
     "ref": "Markus 6:50",
     "caption": "Suara di tengah badai ✨\n\nMalam itu para murid payah mendayung melawan angin sakal. Lalu Yesus datang berjalan di atas air, dan kata-kata pertama-Nya bukan teguran, tapi penghiburan. Sesudah itu Ia naik ke perahu mereka, dan angin pun reda.\n\n📖 “sebab mereka semua melihat Dia dan merekapun sangat terkejut. Tetapi segera Ia berkata kepada mereka: ‘Tenanglah! Aku ini, jangan takut!’” — Markus 6:50\n\nSave ini untuk malam-malam yang berangin 🔖"},
    {"teks": "Setiap hari\naku hendak\nmemuji Engkau", "warna": "hijau",
     "ayat": "“Setiap hari aku hendak memuji Engkau, dan hendak memuliakan nama-Mu untuk seterusnya dan selamanya.”",
     "ref": "Mazmur 145:2",
     "caption": "Satu hari, satu pujian ✨\n\nDaud tidak berjanji memuji Tuhan setahun sekali di momen besar. Ia mau memuji setiap hari, termasuk hari Kamis yang biasa-biasa saja. Pujian kecil hari ini adalah cara kita hidup satu hari demi satu hari bersama-Nya.\n\n📖 “Setiap hari aku hendak memuji Engkau, dan hendak memuliakan nama-Mu untuk seterusnya dan selamanya.” — Mazmur 145:2\n\nTulis satu alasan memuji Tuhan hari ini di komentar 👇"},
    {"teks": "Percayalah,\nlakukanlah\nyang baik", "warna": "pink",
     "ayat": "“Percayalah kepada TUHAN dan lakukanlah yang baik, diamlah di negeri dan berlakulah setia,”",
     "ref": "Mazmur 37:3",
     "caption": "Dua hal untuk akhir minggu ✨\n\nMazmur 37 dibuka dengan ajakan untuk tidak panas hati melihat orang yang berbuat jahat. Jawabannya bukan membalas, tapi dua hal sederhana: percaya kepada TUHAN, dan terus melakukan yang baik.\n\n📖 “Percayalah kepada TUHAN dan lakukanlah yang baik, diamlah di negeri dan berlakulah setia,” — Mazmur 37:3\n\nKetik “Percaya dan berbuat baik” kalau ini tekadmu di Hari Kebaikan Sedunia."},
    {"teks": "Kembalilah\ntenang,\nhai jiwaku", "warna": "biru",
     "ayat": "“Kembalilah tenang, hai jiwaku, sebab TUHAN telah berbuat baik kepadamu.”",
     "ref": "Mazmur 116:7",
     "caption": "Sabtu malam, waktunya pulang ke tenang ✨\n\nPemazmur berbicara kepada jiwanya sendiri setelah melewati masa yang berat. Ia mengingat bahwa TUHAN sudah berbuat baik, lalu mengajak hatinya kembali tenang. Malam ini, lakukan hal yang sama sebelum ibadah besok.\n\n📖 “Kembalilah tenang, hai jiwaku, sebab TUHAN telah berbuat baik kepadamu.” — Mazmur 116:7\n\nKetik “Kembali tenang” sebelum tidur malam ini 🤍"},
]

# ---------- PLAYER: pemutar musik, seri lagu-lagu dalam Alkitab (malam 21:00) ----------
PLAYER = [
    {"judul": "Tidak Kekurangan", "penyanyi": "Daud", "album": "Mazmur", "foto": "bintang",
     "ayat": "“Singa-singa muda merana kelaparan, tetapi orang-orang yang mencari TUHAN, tidak kekurangan sesuatupun yang baik.”",
     "ref": "Mazmur 34:11",
     "caption": "Lagu-lagu dalam Alkitab: Mazmur 34 🎧\n\nDaud menulis mazmur ini setelah lolos dari bahaya di depan Abimelekh. Hidupnya sedang tidak nyaman, tapi ia tetap bersaksi bahwa orang yang mencari TUHAN tidak kekurangan sesuatu pun yang baik. Yang baik menurut Tuhan, yang kadang berbeda dari yang kita minta.\n\n📖 “Singa-singa muda merana kelaparan, tetapi orang-orang yang mencari TUHAN, tidak kekurangan sesuatupun yang baik.” — Mazmur 34:11\n\nUlangi lirik ini dalam hati sebelum tidur, lalu ketik 🎧 di komentar."},
    {"judul": "Hatiku Bersukaria", "penyanyi": "Hana", "album": "1 Samuel", "foto": "kabut",
     "ayat": "“Lalu berdoalah Hana, katanya: ‘Hatiku bersukaria karena TUHAN, tanduk kekuatanku ditinggikan oleh TUHAN; mulutku mencemoohkan musuhku, sebab aku bersukacita karena pertolongan-Mu.’”",
     "ref": "1 Samuel 2:1",
     "caption": "Lagu-lagu dalam Alkitab: nyanyian Hana 🎧\n\nBertahun-tahun Hana mencurahkan isi hatinya kepada TUHAN karena belum punya anak. Setelah Samuel lahir, ia menyerahkan anak itu kepada TUHAN. Lalu yang keluar dari mulutnya bukan keluhan, tapi nyanyian sukacita.\n\n📖 “Lalu berdoalah Hana, katanya: ‘Hatiku bersukaria karena TUHAN, tanduk kekuatanku ditinggikan oleh TUHAN; mulutku mencemoohkan musuhku, sebab aku bersukacita karena pertolongan-Mu.’” — 1 Samuel 2:1\n\nKetik 🎶 kalau kamu juga sedang belajar menyerahkan sesuatu yang berharga kepada-Nya."},
    {"judul": "TUHAN itu Pahlawan", "penyanyi": "Musa & orang Israel", "album": "Keluaran", "foto": "fajar",
     "ayat": "“TUHAN itu kekuatanku dan mazmurku, Ia telah menjadi keselamatanku. Ia Allahku, kupuji Dia, Ia Allah bapaku, kuluhurkan Dia. TUHAN itu pahlawan perang; TUHAN, itulah nama-Nya.”",
     "ref": "Keluaran 15:2-3",
     "caption": "Lagu-lagu dalam Alkitab: nyanyian di tepi Laut Teberau 🎧\n\nIsrael baru saja menyeberangi laut, lalu Musa bersama orang Israel menyanyikan lagu ini. Mereka tidak menyebut diri mereka pahlawan. Mereka tahu siapa yang berperang bagi mereka. Di Hari Pahlawan, kita juga mengingat Pahlawan sejati yang sudah menang bagi kita.\n\n📖 “TUHAN itu kekuatanku dan mazmurku, Ia telah menjadi keselamatanku. Ia Allahku, kupuji Dia, Ia Allah bapaku, kuluhurkan Dia. TUHAN itu pahlawan perang; TUHAN, itulah nama-Nya.” — Keluaran 15:2-3\n\nKetik “TUHAN pahlawanku” kalau lagu ini juga lagumu malam ini."},
    {"judul": "Jejak di Atas Air", "penyanyi": "Asaf", "album": "Mazmur", "foto": "laut",
     "ayat": "“Melalui laut jalan-Mu dan lorong-Mu melalui muka air yang luas, tetapi jejak-Mu tidak kelihatan.”",
     "ref": "Mazmur 77:20",
     "caption": "Lagu-lagu dalam Alkitab: Mazmur 77 🎧\n\nDi akhir mazmurnya, Asaf mengingat saat Israel berdiri di depan laut tanpa jalan keluar. Ternyata Tuhan punya jalan di tengah laut itu, walau tidak ada jejak yang bisa dilihat mata. Kalau malam ini kamu belum melihat jalan, bukan berarti Ia tidak sedang memimpin.\n\n📖 “Melalui laut jalan-Mu dan lorong-Mu melalui muka air yang luas, tetapi jejak-Mu tidak kelihatan.” — Mazmur 77:20\n\nKirim ke teman yang belum melihat jalan keluar 💌"},
    {"judul": "Tertulis di Kitab-Mu", "penyanyi": "Daud", "album": "Mazmur", "foto": "bintang",
     "ayat": "“mata-Mu melihat selagi aku bakal anak, dan dalam kitab-Mu semuanya tertulis hari-hari yang akan dibentuk, sebelum ada satupun dari padanya.”",
     "ref": "Mazmur 139:16",
     "caption": "Lagu-lagu dalam Alkitab: Mazmur 139 🎧\n\nHari esok belum terjadi bagi kita, tapi tidak asing bagi Tuhan. Daud bernyanyi bahwa semua harinya sudah dikenal Tuhan sebelum satu pun terjadi. Karena itu kita bisa menjalani satu hari saja, tanpa harus menggenggam semuanya.\n\n📖 “mata-Mu melihat selagi aku bakal anak, dan dalam kitab-Mu semuanya tertulis hari-hari yang akan dibentuk, sebelum ada satupun dari padanya.” — Mazmur 139:16\n\nKetik “Hari-hariku di tangan-Mu” sebagai doa sebelum tidur."},
    {"judul": "Rahmat Turun-temurun", "penyanyi": "Maria", "album": "Lukas", "foto": "fajar",
     "ayat": "“karena Yang Mahakuasa telah melakukan perbuatan-perbuatan besar kepadaku dan nama-Nya adalah kudus. Dan rahmat-Nya turun-temurun atas orang yang takut akan Dia.”",
     "ref": "Lukas 1:49-50",
     "caption": "Lagu-lagu dalam Alkitab: nyanyian Maria 🎧\n\nMaria menyanyikan ini saat mengunjungi Elisabet, sanaknya. Ia melihat kebaikan Tuhan yang tidak berhenti pada dirinya, tapi mengalir dari generasi ke generasi. Kebaikan yang mengikuti kita hari ini juga sudah mengikuti orang-orang sebelum kita.\n\n📖 “karena Yang Mahakuasa telah melakukan perbuatan-perbuatan besar kepadaku dan nama-Nya adalah kudus. Dan rahmat-Nya turun-temurun atas orang yang takut akan Dia.” — Lukas 1:49-50\n\nTag seseorang yang mewariskan iman kepadamu 👇"},
    {"judul": "Sarang di Mezbah-Mu", "penyanyi": "bani Korah", "album": "Mazmur", "foto": "kabut",
     "ayat": "“Bahkan burung pipit telah mendapat sebuah rumah, dan burung layang-layang sebuah sarang, tempat menaruh anak-anaknya, pada mezbah-mezbah-Mu, ya TUHAN semesta alam, ya Rajaku dan Allahku!”",
     "ref": "Mazmur 84:4",
     "caption": "Lagu-lagu dalam Alkitab: Mazmur 84 🎧\n\nBani Korah adalah keluarga orang Lewi yang melayani di rumah Tuhan. Mereka melihat burung pipit bersarang di dekat mezbah dan rindu tinggal sedekat itu dengan Tuhan. Besok kita diundang datang ke rumah-Nya. Ada tempat untukmu juga.\n\n📖 “Bahkan burung pipit telah mendapat sebuah rumah, dan burung layang-layang sebuah sarang, tempat menaruh anak-anaknya, pada mezbah-mezbah-Mu, ya TUHAN semesta alam, ya Rajaku dan Allahku!” — Mazmur 84:4\n\nKetik “Aku datang” kalau besok kamu mau beribadah ⛪"},
]

# ---------- KETIK: jurnal/doa malam hasil mesin tik (larut 22:30) ----------
KETIK = [
    {"tanggal": "Minggu malam, 8 Nov",
     "isi": "Tuhan, tadi pagi aku duduk di bangku gereja sambil menghitung tagihan di kepala. Maaf, aku lebih sibuk menghitung kebutuhanku daripada mendengar firman-Mu. Malam ini aku mau percaya lagi: Engkau tahu semuanya, bahkan jumlah rambut di kepalaku. Kalau Engkau memperhatikan hal sekecil itu, Engkau juga memperhatikan minggu depanku. Aku taruh daftar kebutuhanku di tangan-Mu, lalu aku mau tidur. Amin.",
     "ayat": "“bahkan rambut kepalamupun terhitung semuanya. Karena itu jangan takut, karena kamu lebih berharga dari pada banyak burung pipit.”",
     "ref": "Lukas 12:7",
     "caption": "Catatan malam, Minggu 8 November 🌙\n\nTuhan yang menghitung setiap helai rambutmu tidak akan lupa kebutuhanmu minggu depan.\n\n📖 “bahkan rambut kepalamupun terhitung semuanya. Karena itu jangan takut, karena kamu lebih berharga dari pada banyak burung pipit.” — Lukas 12:7\n\nKetik “Amin” kalau doa ini juga doamu."},
    {"tanggal": "Senin malam, 9 Nov",
     "isi": "Tuhan, hari pertama minggu kerja sudah lewat. Ada email yang belum kubalas dan rapat yang tidak berjalan sesuai rencana. Aku sadar, seharian aku mencoba mengendalikan hal-hal yang terlalu besar bagiku. Malam ini aku mau berhenti. Aku tidak harus mengerti semuanya, tidak harus memegang semuanya. Ajar aku tenang seperti anak kecil di pangkuan ibunya. Aku serahkan besok kepada-Mu. Amin.",
     "ayat": "“…aku tidak mengejar hal-hal yang terlalu besar atau hal-hal yang terlalu ajaib bagiku.”",
     "ref": "Mazmur 131:1",
     "caption": "Catatan malam, Senin 9 November 🌙\n\nBerserah kadang berarti mengakui bahwa ada hal-hal yang terlalu besar untuk kita pegang. Daud menulis nyanyian ziarah yang pendek ini sebagai doa orang yang sedang belajar tenang.\n\n📖 “TUHAN, aku tidak tinggi hati, dan tidak memandang dengan sombong; aku tidak mengejar hal-hal yang terlalu besar atau hal-hal yang terlalu ajaib bagiku.” — Mazmur 131:1\n\nKetik “Amin” dan serahkan hari Selasa-mu kepada-Nya."},
    {"tanggal": "Selasa malam, 10 Nov",
     "isi": "Tuhan, hari ini kami mengenang para pahlawan. Aku jadi ingat Oma yang setiap subuh mendoakan kami satu per satu, tanpa ada yang melihat. Aku bukan orang yang berani. Aku sering diam saat seharusnya bicara. Tapi kalau Oma bisa setia dalam hal kecil karena Engkau, aku juga mau belajar. Beri aku keberanian untuk taat besok, sekecil apa pun langkahnya. Amin.",
     "ayat": "“Karena dengan Engkau aku berani menghadapi gerombolan, dan dengan Allahku aku berani melompati tembok.”",
     "ref": "Mazmur 18:30",
     "caption": "Catatan malam, Hari Pahlawan 🌙\n\nPahlawan iman yang paling dekat dengan kita sering tidak tercatat di buku sejarah: orang tua, nenek, guru sekolah minggu. Keberanian mereka bukan dari diri sendiri, tapi dari Tuhan yang menyertai.\n\n📖 “Karena dengan Engkau aku berani menghadapi gerombolan, dan dengan Allahku aku berani melompati tembok.” — Mazmur 18:30\n\nTulis nama pahlawan iman di hidupmu di komentar 👇"},
    {"tanggal": "Rabu malam, 11 Nov",
     "isi": "Tuhan, hari ini terasa seperti berdiri di tengah hujan angin. Kabar yang tidak kuharapkan datang satu per satu, dan aku lelah pura-pura kuat. Aku tidak tahu kapan badai ini reda. Tapi aku tahu ke mana aku harus lari. Tuntun aku ke gunung batu yang lebih tinggi dari ketakutanku. Kalau malam ini aku belum bisa tenang, biarlah aku tetap berpegang kepada-Mu. Amin.",
     "ayat": "“Dari ujung bumi aku berseru kepada-Mu, karena hatiku lemah lesu; tuntunlah aku ke gunung batu yang terlalu tinggi bagiku.”",
     "ref": "Mazmur 61:3",
     "caption": "Catatan malam, Rabu 11 November 🌙\n\nDaud berseru dari tempat yang jauh, dengan hati yang lemah lesu. Ia tidak meminta badai langsung hilang. Ia meminta dituntun ke tempat yang lebih tinggi dan lebih aman dari dirinya sendiri.\n\n📖 “Dari ujung bumi aku berseru kepada-Mu, karena hatiku lemah lesu; tuntunlah aku ke gunung batu yang terlalu tinggi bagiku.” — Mazmur 61:3\n\nKalau malam ini hatimu lemah lesu, ketik 🤍. Kami ikut mendoakan."},
    {"tanggal": "Kamis malam, 12 Nov",
     "isi": "Tuhan, hari ini selesai. Tidak semua daftar tercoret, tapi aku sudah menjalani hari ini bersama-Mu. Tadi siang aku sempat panik memikirkan bulan depan, lalu aku ingat: bulan depan pun milik-Mu. Siang milik-Mu, malam juga milik-Mu. Jadi malam ini aku tidak perlu begadang menjaga masa depan. Engkau yang menjaganya. Terima kasih untuk rahmat hari ini. Besok pagi aku mau menerimanya lagi. Amin.",
     "ayat": "“Punya-Mulah siang, punya-Mulah juga malam. Engkaulah yang menaruh benda penerang dan matahari.”",
     "ref": "Mazmur 74:16",
     "caption": "Catatan malam, Kamis 12 November 🌙\n\nAsaf menulis mazmur ini di masa yang sangat sulit bagi umatnya. Tapi ia tetap mengakui bahwa siang dan malam sama-sama milik Tuhan. Hari yang sudah lewat dan hari yang belum datang, semuanya ada di tangan-Nya.\n\n📖 “Punya-Mulah siang, punya-Mulah juga malam. Engkaulah yang menaruh benda penerang dan matahari.” — Mazmur 74:16\n\nKetik “Amin”, lalu istirahatlah. Besok rahmat-Nya baru lagi."},
    {"tanggal": "Jumat malam, 13 Nov",
     "isi": "Tuhan, hari ini aku ingin jadi orang baik, tapi tadi sore aku malah ketus kepada adikku. Ternyata berbuat baik kepada orang asing lebih mudah daripada di rumah sendiri. Ampuni aku. Terima kasih karena kebaikan-Mu tetap mengikutiku, bahkan saat aku gagal. Besok pagi aku mau minta maaf duluan. Kenakan padaku belas kasihan dan kesabaran, karena aku tidak punya cukup dari diriku sendiri. Amin.",
     "ayat": "“…kenakanlah belas kasihan, kemurahan, kerendahan hati, kelemahlembutan dan kesabaran.”",
     "ref": "Kolose 3:12",
     "caption": "Catatan malam, Hari Kebaikan Sedunia 🌙\n\nPaulus menyebut kebaikan seperti pakaian yang dikenakan setiap hari. Kita mengenakannya bukan supaya dikasihi, tapi karena kita sudah lebih dulu dipilih dan dikasihi Allah.\n\n📖 “Karena itu, sebagai orang-orang pilihan Allah yang dikuduskan dan dikasihi-Nya, kenakanlah belas kasihan, kemurahan, kerendahan hati, kelemahlembutan dan kesabaran.” — Kolose 3:12\n\nKetik “Amin” kalau kamu juga sedang belajar baik di rumah sendiri."},
    {"tanggal": "Sabtu malam, 14 Nov",
     "isi": "Tuhan, satu minggu lagi Kaupelihara. Aku sempat khawatir soal uang, pekerjaan, dan masa depan, tapi tidak satu hari pun Engkau lalai. Malam ini aku mau beristirahat, bukan karena semuanya sudah beres, tapi karena Engkau setia. Besok aku datang ke rumah-Mu, bukan untuk tampil, tapi untuk bertemu dengan-Mu. Siapkan hatiku untuk mendengar, dan biar aku pulang dengan hati yang tenang. Amin.",
     "ayat": "“TUHAN, aku cinta pada rumah kediaman-Mu dan pada tempat kemuliaan-Mu bersemayam.”",
     "ref": "Mazmur 26:8",
     "caption": "Catatan malam, Sabtu 14 November 🌙\n\nTujuh hari kita belajar satu hal: jangan khawatir, Bapa memelihara. Besok kita datang ke rumah-Nya bukan sebagai orang yang sudah beres, tapi sebagai anak-anak yang sudah dipelihara-Nya sepanjang minggu.\n\n📖 “TUHAN, aku cinta pada rumah kediaman-Mu dan pada tempat kemuliaan-Mu bersemayam.” — Mazmur 26:8\n\nKetik “Sampai jumpa di ibadah” dan selamat beristirahat 🤍"},
]

# komik Eli yang sudah jadi (folder Eli): hari 1, 4, 7 di pagi2
ELI = [("edukasi", 0), ("saran", 3), ("saran", 5)]

_PAGI2 = {1: ("ELI", 0), 2: ("TIKET", 0), 3: ("TIKET", 1), 4: ("ELI", 1), 5: ("TIKET", 2), 6: ("TIKET", 3), 7: ("ELI", 2)}

# hari 1-7 (Minggu 8 Nov .. Sabtu 14 Nov 2026): 12 slot per hari -> (format, index)
# pagi 06:00, pagi3 07:30, pagi2 09:00, siang0 10:30, siang 12:00, siang2 13:30, sore 15:00, sore2 16:30,
# petang 18:00, malam0 19:30, malam 21:00, larut 22:30
JADWAL = {d: {"pagi": ("CUACA", d - 1), "pagi3": ("KAMUS", d - 1), "pagi2": _PAGI2[d],
              "siang0": ("CATATAN", d - 1), "siang": ("STRUK", d - 1), "siang2": ("CHAT", d - 1),
              "sore": ("KALENDER", d - 1), "sore2": ("POPUP", d - 1), "petang": ("POLAROID", d - 1),
              "malam0": ("NEON", d - 1), "malam": ("PLAYER", d - 1), "larut": ("KETIK", d - 1)} for d in range(1, 8)}
