"""Akun Tenang (@diam.dan.percaya) - minggu 4 (Minggu 18 Okt - Sabtu 24 Okt 2026).
Tema: "Tuhan yang melihat" (El-Roi) - perjalanan iman di tengah kesibukan.
Minggu = ibadah, Sabtu malam = persiapan hari Minggu.
Skema sama dengan konten/tenang_w3.py (BUKU, MEME, SKRIP, KISAH, RELATABLE, KINETIK)
dan konten/tenang_keren2.py (DUMP, DULU):
  BUKU     = halaman buku terbuka: judul serif + puisi pendek (3-6 baris, maks 42 karakter per baris)
             pagi (06:00), siang (12:00), larut (22:30)
  MEME     = foto hitam-putih + doa jujur orang pertama (maks 90 karakter); pagi3 (07:30) & sore2 (16:30)
  SKRIP    = janji Tuhan tulisan tangan kuning di foto panggung ibadah; sore (15:00) & malam0 (19:30)
  KISAH    = carousel poster kisah Alkitab (siang0 10:30)
  T        = teks relatable (pagi2 09:00 & malam 21:00)
  K        = Reels tipografi sinematik (siang2 13:30)
  F / V    = photo dump (hari 1, 3, 5, 7) / dulu vs sekarang (hari 2, 4, 6) di petang (18:00)
Kutipan ayat: Alkitab TB. Caption tanpa hashtag."""

# ---------- BUKU: halaman buku terbuka (3 per hari: pagi, siang, larut) ----------
BUKU = [
    # --- Minggu 18 Okt ---
    {"judul": "Di Bangku Mana Pun",
     "baris": ["Di bangku depan atau belakang,", "datang tepat waktu atau terlambat,", "Engkau melihatku masuk,",
               "dan Engkau senang aku datang."],
     "caption": "Di bangku mana pun kamu duduk hari ini 🤍\n\nDepan atau belakang, tepat waktu atau terlambat, Tuhan melihatmu masuk, dan Dia senang kamu datang.\n\n📖 “Satu hal telah kuminta kepada TUHAN, itulah yang kuingini: diam di rumah TUHAN seumur hidupku, menyaksikan kemurahan TUHAN dan menikmati bait-Nya.” — Mazmur 27:4\n\nKetik “Amin” kalau hari ini kamu mau datang ke rumah-Nya. Selamat hari Minggu."},
    {"judul": "Makan Siang Hari Minggu",
     "baris": ["Nasi hangat dan obrolan panjang,", "cerita khotbah yang setengah ingat,", "tawa kecil di meja sederhana.",
               "Terima kasih, Tuhan,", "untuk berkat yang hangat ini."],
     "caption": "Makan siang sepulang gereja 🍲\n\nIbadah tidak berhenti di pintu gereja. Jemaat mula-mula juga melanjutkannya di meja makan, dengan gembira dan tulus hati.\n\n📖 “…Mereka memecahkan roti di rumah masing-masing secara bergilir dan makan bersama-sama dengan gembira dan dengan tulus hati…” — Kisah Para Rasul 2:46\n\nTag orang yang biasa makan siang bareng kamu sepulang ibadah 👇"},
    {"judul": "Sebelum Senin Datang",
     "baris": ["Besok jadwalku kembali penuh,", "tapi malam ini aku mau ingat:", "Engkau yang kutemui di gereja",
               "juga yang memimpinku", "di hari Senin."],
     "caption": "Dia yang kamu temui hari ini, juga yang memimpinmu besok 🌙\n\nTuhan tidak tinggal di gedung gereja saat kamu pulang. Dia tetap Allahmu hari ini, besok, dan seterusnya.\n\n📖 “Sesungguhnya inilah Allah, Allah kitalah Dia seterusnya dan untuk selamanya! Dialah yang memimpin kita!” — Mazmur 48:15\n\nKetik “Dia memimpin” sebelum kamu tidur malam ini 🙏"},
    # --- Senin 19 Okt ---
    {"judul": "Engkau yang Melihat",
     "baris": ["Sebelum orang lain bangun,", "sebelum ada yang menilai,", "Engkau sudah melihatku,",
               "dan tatapan-Mu", "penuh kasih."],
     "caption": "Senin pagi, dan kamu sudah dilihat oleh-Nya 🤍\n\nMinggu ini kita belajar tentang Tuhan yang melihat. Sebelum atasan, dosen, atau siapa pun menilai, Dia sudah melihatmu, dengan mata yang ingin menguatkan.\n\n📖 “Karena mata TUHAN menjelajah seluruh bumi untuk melimpahkan kekuatan-Nya kepada mereka yang bersungguh hati terhadap Dia.” — 2 Tawarikh 16:9\n\nKetik “Amin” kalau kamu mau memulai Senin ini bersama Dia."},
    {"judul": "Jam Makan Siang",
     "baris": ["Nasi bungkus di meja kerja,", "layar masih menyala.", "Sebentar saja, Tuhan,",
               "aku mau bilang terima kasih:", "hari ini pun aku bersama-Mu."],
     "caption": "Jeda makan siang 🍱\n\nSesibuk apa pun hari ini, hadirat-Nya bukan cuma di gereja atau di kamar doa, tapi juga di meja kerjamu.\n\n📖 “Engkau memberitahukan kepadaku jalan kehidupan; di hadapan-Mu ada sukacita berlimpah-limpah, di tangan kanan-Mu ada nikmat senantiasa.” — Mazmur 16:11\n\nKamu makan siang di mana hari ini? Tulis di komentar 👇"},
    {"judul": "Yang Tak Dilihat Orang",
     "baris": ["Lelah yang tak kuceritakan,", "usaha yang tak dipuji,", "doa yang tak didengar siapa pun:",
               "semuanya Kaulihat.", "Malam ini, itu cukup."],
     "caption": "Untuk semua yang tidak dilihat orang hari ini 🌙\n\nMungkin tidak ada yang tahu betapa kerasnya kamu berusaha. Tapi Tuhan tahu, dan Dia tidak lupa.\n\n📖 “Sebab Allah bukan tidak adil, sehingga Ia lupa akan pekerjaanmu dan kasihmu yang kamu tunjukkan terhadap nama-Nya…” — Ibrani 6:10\n\nSave untuk malam kamu merasa usahamu sia-sia 🔖"},
    # --- Selasa 20 Okt ---
    {"judul": "Di Perjalanan Pagi",
     "baris": ["Di motor, di kereta, di angkot,", "di jalan yang sama setiap hari,", "aku tidak berangkat sendiri.",
               "Engkau berjalan di depanku."],
     "caption": "Doa di perjalanan pagi 🛵\n\nDulu Tuhan berjalan di depan umat-Nya dalam tiang awan dan tiang api. Hari ini pun, Dia tidak membiarkanmu berangkat sendirian.\n\n📖 “TUHAN berjalan di depan mereka, pada siang hari dalam tiang awan untuk menuntun mereka di jalan, dan pada waktu malam dalam tiang api untuk menerangi mereka…” — Keluaran 13:21\n\nKamu berangkat naik apa hari ini? Jawab di komentar, kita saling mendoakan 👇"},
    {"judul": "Meja Kerjaku",
     "baris": ["Tumpukan berkas dan tenggat waktu,", "pekerjaan yang tak ada habisnya.", "Biar tanganku bekerja dengan jujur,",
               "karena yang paling memperhatikan", "adalah Engkau."],
     "caption": "Untuk meja kerja yang penuh hari ini 💻\n\nBekerja dengan jujur, bahkan saat tidak ada atasan yang melihat, adalah ibadah yang sederhana.\n\n📖 “…jangan hanya di hadapan mereka saja untuk menyenangkan hati orang, tetapi sebagai hamba-hamba Kristus yang dengan segenap hati melakukan kehendak Allah, dan yang dengan rela menjalankan pelayanannya seperti orang-orang yang melayani Tuhan dan bukan manusia.” — Efesus 6:6-7\n\nKirim ke rekan kerjamu yang sedang dikejar tenggat 💌"},
    {"judul": "Kaki yang Lelah",
     "baris": ["Kakiku lelah malam ini,", "jalanku hari ini panjang.", "Tapi Engkau mendukungku",
               "seperti ayah menggendong anaknya,", "sepanjang jalan sampai ke rumah."],
     "caption": "Untuk kaki yang lelah malam ini 🌙\n\nDi padang gurun, Israel melihat sendiri: Tuhan mendukung mereka seperti seorang ayah menggendong anaknya, sepanjang jalan.\n\n📖 “…TUHAN, Allahmu, mendukung engkau, seperti seseorang mendukung anaknya, sepanjang jalan yang kamu tempuh, sampai kamu tiba di tempat ini.” — Ulangan 1:31\n\nKetik 🤍 kalau hari ini jalanmu terasa panjang."},
    # --- Rabu 21 Okt ---
    {"judul": "Tengah Minggu",
     "baris": ["Rabu pagi, setengah jalan.", "Semangatku mulai menipis,", "tapi kasih setia-Mu",
               "tidak pernah setengah-setengah."],
     "caption": "Rabu pagi, setengah jalan 🌤️\n\nSemangat bisa naik turun di tengah minggu. Kasih setia-Nya tidak. Itu alasan untuk tetap bernyanyi pagi ini.\n\n📖 “Tetapi aku mau menyanyikan kekuatan-Mu, pada waktu pagi aku mau bersorak-sorai karena kasih setia-Mu…” — Mazmur 59:17\n\nLagu pujian apa yang menemanimu pagi ini? Tulis di komentar 👇"},
    {"judul": "Lima Menit Saja",
     "baris": ["Di sela rapat dan pesan masuk,", "aku menutup mata lima menit.", "Bukan untuk lari dari semuanya,",
               "tapi untuk ingat:", "Engkau masih Allahku."],
     "caption": "Lima menit di tengah hari ⏳\n\nTidak harus lama. Berhenti sebentar, diam di hadapan-Nya, lalu lanjutkan harimu dengan hati yang lebih tenang.\n\n📖 “Berdiam dirilah di hadapan TUHAN dan nantikanlah Dia…” — Mazmur 37:7\n\nCoba sekarang: lima menit tanpa notifikasi. Ketik “sudah” kalau kamu berhasil 😊"},
    {"judul": "Tanpa Kata yang Indah",
     "baris": ["Engkau tahu isi hatiku", "sebelum aku mengucapkannya.", "Jadi malam ini aku tidak perlu",
               "mencari kata yang indah.", "Aku cukup datang."],
     "caption": "Tidak perlu kata-kata indah malam ini 🌙\n\nDia sudah tahu keinginanmu, bahkan keluh yang tidak sempat kamu ucapkan.\n\n📖 “Tuhan, Engkau mengetahui segala keinginanku, dan keluhkupun tidak tersembunyi bagi-Mu…” — Mazmur 38:10\n\nSave untuk malam kamu kehabisan kata 🔖"},
    # --- Kamis 22 Okt ---
    {"judul": "Tunjukkan Jalan-Mu",
     "baris": ["Banyak pilihan di depanku,", "banyak suara yang ramai.", "Tunjukkan jalan-Mu, Tuhan,",
               "dan bulatkan hatiku", "untuk mengikuti-Mu."],
     "caption": "Doa untuk hari yang penuh pilihan 🧭\n\nSaat banyak suara bicara bersamaan, minta satu hal: hati yang bulat untuk mengikuti-Nya.\n\n📖 “Tunjukkanlah kepadaku jalan-Mu, ya TUHAN, supaya aku hidup menurut kebenaran-Mu; bulatkanlah hatiku untuk takut akan nama-Mu.” — Mazmur 86:11\n\nKirim ke temanmu yang sedang harus mengambil keputusan 💌"},
    {"judul": "Siang yang Terik",
     "baris": ["Matahari tinggi, tenaga turun,", "dan hari belum juga selesai.", "Aku layu seperti daun siang ini,",
               "tapi Engkau berjanji", "menyegarkan yang lelah."],
     "caption": "Siang yang terik, tenaga yang habis ☀️\n\nKadang yang kita butuhkan bukan kopi ketiga, tapi beberapa menit dekat dengan Dia yang menyegarkan.\n\n📖 “Sebab Aku akan membuat segar orang yang lelah, dan setiap orang yang merana akan Kubuat puas.” — Yeremia 31:25\n\nKetik 💧 kalau siang ini kamu butuh disegarkan."},
    {"judul": "Malam yang Jujur",
     "baris": ["Hari ini aku tidak sebaik", "yang orang lain kira.", "Engkau melihat semuanya,",
               "dan Engkau tidak pergi."],
     "caption": "Untuk malam yang jujur 🌙\n\nOrang lain mungkin hanya melihat versi terbaikmu. Tuhan melihat semuanya, dan Dia lebih besar dari tuduhan hatimu sendiri.\n\n📖 “…kita boleh menenangkan hati kita di hadapan Allah, sebab jika kita dituduh olehnya, Allah adalah lebih besar dari pada hati kita serta mengetahui segala sesuatu.” — 1 Yohanes 3:19-20\n\nSave untuk malam hatimu terus menuduh 🔖"},
    # --- Jumat 23 Okt ---
    {"judul": "Kepala yang Diangkat",
     "baris": ["Kemarin aku terus menunduk,", "malu, lelah, dan kecewa.", "Pagi ini Engkau mengangkat kepalaku,",
               "dan aku mau melangkah lagi."],
     "caption": "Pagi ini, angkat kepalamu 🌅\n\nDia bukan cuma melindungi. Dia juga yang mengangkat kepala yang tertunduk karena malu dan lelah.\n\n📖 “Tetapi Engkau, TUHAN, adalah perisai yang melindungi aku, Engkaulah kemuliaanku dan yang mengangkat kepalaku.” — Mazmur 3:4\n\nKirim ke seseorang yang sedang menunduk minggu ini 💌"},
    {"judul": "Setia di Hal Kecil",
     "baris": ["Membalas pesan dengan sabar,", "membereskan yang tak terlihat,", "menepati janji kecil:",
               "biar semuanya jadi", "ibadahku hari ini."],
     "caption": "Hal kecil yang dikerjakan dengan setia 🤍\n\nKebanyakan kesetiaan tidak terlihat besar. Ia tersembunyi di hal-hal kecil yang kita kerjakan hari ini.\n\n📖 “Barangsiapa setia dalam perkara-perkara kecil, ia setia juga dalam perkara-perkara besar…” — Lukas 16:10\n\nTulis satu hal kecil yang mau kamu kerjakan dengan setia hari ini 👇"},
    {"judul": "Sampai di Sini",
     "baris": ["Kalau kulihat ke belakang,", "minggu ini penuh tikungan.", "Tapi aku bisa bilang dengan jujur:",
               "sampai di sini,", "Engkau menolongku."],
     "caption": "Sampai di sini, Tuhan menolong 🪨\n\nSamuel mendirikan sebuah batu dan menamainya Eben-Haezer, supaya umat ingat pertolongan Tuhan. Malam ini, ingat kembali di mana saja Dia menolongmu minggu ini.\n\n📖 “Sampai di sini TUHAN menolong kita.” — 1 Samuel 7:12\n\nSelamat berakhir pekan. Tulis satu pertolongan Tuhan minggu ini di komentar 👇"},
    # --- Sabtu 24 Okt ---
    {"judul": "Jalan Pagi Sabtu",
     "baris": ["Jalan pagi di sekitar rumah,", "langit masih abu-abu muda.", "Setiap langkah kecil ini",
               "jadi doa tanpa kata:", "terima kasih, Tuhan."],
     "caption": "Jalan pagi hari Sabtu 🌤️\n\nKalau langit saja tidak berhenti bercerita tentang kemuliaan-Nya, langkah kecil kita pagi ini pun bisa jadi pujian.\n\n📖 “Langit menceritakan kemuliaan Allah, dan cakrawala memberitakan pekerjaan tangan-Nya…” — Mazmur 19:2\n\nSabtu pagi ini kamu ngapain? Ceritain di komentar 👇"},
    {"judul": "Rumah yang Ramai",
     "baris": ["Anak-anak berlarian,", "piring berdenting di dapur,", "rumah ini ramai dan berantakan,",
               "tapi Engkau ada di tengahnya,", "dan itu berkat."],
     "caption": "Rumah yang ramai, dan Tuhan di tengahnya 🏠\n\nBukan rumah yang sempurna, tapi rumah yang memilih beribadah kepada Tuhan bersama-sama.\n\n📖 “…Tetapi aku dan seisi rumahku, kami akan beribadah kepada TUHAN!” — Yosua 24:15\n\nTag keluargamu, atau teman serumahmu 👇"},
    {"judul": "Malam Sebelum Ibadah",
     "baris": ["Kuletakkan semua yang berat", "di samping Alkitab di meja.", "Besok aku mau datang ringan,",
               "membawa hati yang haus", "akan suara-Mu."],
     "caption": "Malam sebelum ibadah 🌙\n\nLetakkan dulu yang berat malam ini. Besok, datanglah dengan hati yang haus, seperti rusa yang merindukan air.\n\n📖 “Seperti rusa yang merindukan sungai yang berair, demikianlah jiwaku merindukan Engkau, ya Allah. Jiwaku haus kepada Allah, kepada Allah yang hidup. Bilakah aku boleh datang melihat Allah?” — Mazmur 42:2-3\n\nBesok kamu ibadah jam berapa? Tulis di komentar, kita saling mengingatkan 👇"},
]


# ---------- MEME: foto hitam-putih + doa jujur (pagi3 07:30 & sore2 16:30) ----------
MEME = [
    # Minggu
    {"teks": "Tuhan, hari ini aku mau ibadah bukan untuk dilihat orang, tapi karena aku rindu Engkau.",
     "foto": "panggung",
     "caption": "Ibadah bukan pertunjukan 🤍\n\nBukan soal siapa yang paling terlihat di depan, tapi siapa yang datang dengan hati yang rindu kepada-Nya.\n\n📖 “Ya Allah, Engkaulah Allahku, aku mencari Engkau, jiwaku haus kepada-Mu, tubuhku rindu kepada-Mu, seperti tanah yang kering dan tandus, tiada berair.” — Mazmur 63:2\n\nKetik “Amin” kalau ini doamu pagi ini. Selamat hari Minggu."},
    {"teks": "Tuhan, besok Senin. Ingatkan aku, Engkau juga ada di kantor, bukan cuma di gereja.",
     "foto": "jendela",
     "caption": "Tuhan tidak tinggal di gedung gereja saja 🏢\n\nDia memenuhi langit dan bumi, termasuk ruang kerja, ruang kelas, dan jalan pulangmu besok.\n\n📖 “Masakan Aku ini hanya Allah yang dari dekat, demikianlah firman TUHAN, dan bukan Allah yang dari jauh juga?… Tidakkah Aku memenuhi langit dan bumi? demikianlah firman TUHAN.” — Yeremia 23:23-24\n\nKirim ke temanmu yang besok kembali ke rutinitas 💌"},
    # Senin
    {"teks": "Tuhan, Senin pagi aku sudah capek duluan. Pinjamkan kekuatan-Mu untuk hari ini, ya.",
     "foto": "awan",
     "caption": "Capek duluan di Senin pagi? 🤍\n\nTidak apa-apa. Kekuatan untuk hari ini tidak harus berasal dari dirimu sendiri.\n\n📖 “TUHAN kiranya memberikan kekuatan kepada umat-Nya, TUHAN kiranya memberkati umat-Nya dengan sejahtera!” — Mazmur 29:11\n\nKetik “Amin” kalau kamu butuh kekuatan baru pagi ini."},
    {"teks": "Tuhan, seharian ini aku lupa Engkau. Tapi Engkau nggak sedetik pun lupa aku.",
     "foto": "lilin",
     "caption": "Kita sering lupa. Dia tidak pernah 🕯️\n\nHari ini mungkin kamu tidak sempat berdoa sama sekali. Tapi tidak sedetik pun kamu luput dari perhatian-Nya.\n\n📖 “Aku ini sengsara dan miskin, tetapi Tuhan memperhatikan aku…” — Mazmur 40:18\n\nSave untuk hari-hari yang terlalu sibuk 🔖"},
    # Selasa
    {"teks": "Tuhan, aku belum siap untuk hari ini. Siapkan aku sepanjang jalan, ya.",
     "foto": "jalan",
     "caption": "Belum siap? Berangkat saja bersama-Nya 🛣️\n\nKamu tidak harus siap sempurna sebelum melangkah. Dia yang mengajar dan membawamu berjalan, sepanjang hari.\n\n📖 “Bawalah aku berjalan dalam kebenaran-Mu dan ajarlah aku, sebab Engkaulah Allah yang menyelamatkan aku, Engkau kunanti-nantikan sepanjang hari.” — Mazmur 25:5\n\nKirim ke temanmu yang pagi ini berangkat dengan berat hati 💌"},
    {"teks": "Tuhan, aku sering merasa nggak kelihatan. Terima kasih, Engkau selalu melihatku.",
     "foto": "kabut",
     "caption": "Untuk kamu yang merasa tidak terlihat 🤍\n\nDi kantor, di rumah, di grup pertemanan, mungkin kamu sering terlewat. Tapi Tuhan yang Mahatinggi justru melihat yang dianggap kecil.\n\n📖 “TUHAN itu tinggi, namun Ia melihat orang yang hina…” — Mazmur 138:6\n\nKirim ke seseorang yang perlu tahu bahwa dia dilihat 💌"},
    # Rabu
    {"teks": "Tuhan, jadwalku penuh, tapi aku nggak mau hatiku kosong. Isi aku dulu pagi ini.",
     "foto": "jendela",
     "caption": "Jadwal penuh, hati jangan kosong ☕\n\nSebelum mengisi hari dengan pekerjaan, minta Dia mengisi hatimu dulu: dengan sukacita, damai, dan pengharapan.\n\n📖 “Semoga Allah, sumber pengharapan, memenuhi kamu dengan segala sukacita dan damai sejahtera dalam iman kamu, supaya oleh kekuatan Roh Kudus kamu berlimpah-limpah dalam pengharapan.” — Roma 15:13\n\nKetik “isi aku” sebagai doamu pagi ini 🙏"},
    {"teks": "Tuhan, tadi aku salah bicara ke orang. Beri aku berani untuk minta maaf duluan.",
     "foto": "bintang",
     "caption": "Minta maaf duluan itu berani 🤍\n\nKita tidak bisa mengatur reaksi orang lain. Tapi bagian kita, kita kerjakan: membuka jalan untuk berdamai.\n\n📖 “Sedapat-dapatnya, kalau hal itu bergantung padamu, hiduplah dalam perdamaian dengan semua orang!” — Roma 12:18\n\nAda yang mau kamu chat untuk minta maaf hari ini? Ketik 🤝 kalau kamu mau mencobanya."},
    # Kamis
    {"teks": "Tuhan, hari ini aku presentasi. Tenangkan aku: nilaiku bukan dari hasil hari ini.",
     "foto": "gunung",
     "caption": "Untuk kamu yang hari ini presentasi, ujian, atau wawancara 🎤\n\nLakukan yang terbaik. Tapi ingat, nilai dirimu sudah ditentukan jauh sebelum hasilnya keluar: kamu anak Allah.\n\n📖 “Lihatlah, betapa besarnya kasih yang dikaruniakan Bapa kepada kita, sehingga kita disebut anak-anak Allah, dan memang kita adalah anak-anak Allah…” — 1 Yohanes 3:1\n\nTag temanmu yang hari ini sedang deg-degan 👇"},
    {"teks": "Tuhan, orang tuaku makin tua. Jaga mereka saat aku nggak bisa ada di dekat mereka.",
     "foto": "pohon",
     "caption": "Doa untuk orang tua yang makin tua 🤍\n\nDoa pemazmur ini bisa jadi doa kita untuk papa dan mama, terutama saat kita jauh dari mereka.\n\n📖 “Janganlah membuang aku pada masa tuaku, janganlah meninggalkan aku apabila kekuatanku habis.” — Mazmur 71:9\n\nTelepon orang tuamu sore ini, atau kirim post ini ke mereka 💌"},
    # Jumat
    {"teks": "Tuhan, aku nggak tahu hidupku mau dibawa ke mana. Tapi aku tahu Engkau ikut berjalan.",
     "foto": "jalan",
     "caption": "Belum tahu arahnya, tapi tahu Siapa yang menyertai 🧭\n\nKita tidak selalu mengerti jalan hidup kita sendiri. Karena itu kita butuh Dia yang menentukan langkah.\n\n📖 “Langkah orang ditentukan oleh TUHAN, tetapi bagaimanakah manusia dapat mengerti jalan hidupnya?” — Amsal 20:24\n\nKetik “aku ikut Engkau” kalau ini doamu juga."},
    {"teks": "Tuhan, gajian masih jauh dan dompet makin tipis. Ajar aku percaya, bukan panik.",
     "foto": "awan",
     "caption": "Untuk kamu yang sedang di tanggal tua 😅\n\nYesus tidak menjanjikan dompet tebal, tapi Ia menunjukkan Bapa yang memelihara. Kalau burung di langit diberi makan, kamu jauh lebih berharga.\n\n📖 “Pandanglah burung-burung di langit, yang tidak menabur dan tidak menuai dan tidak mengumpulkan bekal dalam lumbung, namun diberi makan oleh Bapamu yang di sorga. Bukankah kamu jauh melebihi burung-burung itu?” — Matius 6:26\n\nKirim ke temanmu yang sedang di tanggal tua 💌"},
    # Sabtu
    {"teks": "Tuhan, Sabtu ini aku mau hadir buat keluargaku, bukan sibuk sama HP. Bantu aku, ya.",
     "foto": "laut",
     "caption": "Hadir sepenuhnya hari ini 📵\n\nWaktu bersama orang-orang tersayang tidak bisa diulang. Minta Tuhan mengajarmu menghitung hari dengan bijak.\n\n📖 “Ajarlah kami menghitung hari-hari kami sedemikian, hingga kami beroleh hati yang bijaksana.” — Mazmur 90:12\n\nTag orang yang mau kamu ajak quality time hari ini 👇"},
    {"teks": "Tuhan, sudah lama aku nggak ke gereja. Besok aku mau coba datang lagi. Temani aku, ya.",
     "foto": "panggung",
     "caption": "Kalau besok kamu mau kembali 🤍\n\nTidak perlu menunggu jadi lebih baik dulu. Dia pengasih dan penyayang, dan Dia senang menyambut yang pulang.\n\n📖 “…berbaliklah kepada TUHAN, Allahmu, sebab Ia pengasih dan penyayang, panjang sabar dan berlimpah kasih setia…” — Yoel 2:13\n\nKalau besok kamu mau kembali, ketik “aku datang”. Kami ikut mendoakanmu 🙏"},
]


# ---------- SKRIP: tulisan tangan kuning di foto panggung ibadah (sore & malam0) ----------
# "teks" = parafrase singkat janji Tuhan; ayat dasarnya dikutip di caption.
SKRIP = [
    # Minggu
    {"teks": "Aku menunggumu dengan kasih.", "dari": "— Tuhan",
     "caption": "Aku menunggumu dengan kasih. 🤍\n\nBukan menunggu untuk menghukum. Tuhan menanti-nantikan saatnya untuk menunjukkan kasih-Nya kepadamu.\n\n📖 “Sebab itu TUHAN menanti-nantikan saatnya hendak menunjukkan kasih-Nya kepada kamu; sebab itu Ia bangkit hendak menyayangi kamu. Sebab TUHAN adalah Allah yang adil; berbahagialah semua orang yang menanti-nantikan Dia!” — Yesaya 30:18\n\nKetik “Amin” kalau kamu mau datang kepada-Nya hari ini."},
    {"teks": "Damai-Ku menyertaimu.", "dari": "— Tuhan",
     "caption": "Damai-Ku menyertaimu. 🕊️\n\nIbadah hari ini sudah selesai, tapi damai-Nya tidak ikut selesai. Paulus mendoakan damai yang terus-menerus, dalam segala hal, dari Tuhan yang menyertai.\n\n📖 “Dan Ia, Tuhan damai sejahtera, kiranya mengaruniakan damai sejahtera-Nya terus-menerus, dalam segala hal, kepada kamu. Tuhan menyertai kamu sekalian.” — 2 Tesalonika 3:16\n\nKirim ke seseorang yang butuh damai malam ini 💌"},
    # Senin
    {"teks": "I see you.", "dari": "— Tuhan",
     "caption": "Dia melihatmu 🤍\n\nBukan pandangan yang menghakimi, tapi mata yang tertuju kepada mereka yang berharap pada kasih setia-Nya.\n\n📖 “Sesungguhnya, mata TUHAN tertuju kepada mereka yang takut akan Dia, kepada mereka yang berharap akan kasih setia-Nya…” — Mazmur 33:18\n\nKetik “Dia melihatku” kalau kamu butuh diingatkan ini hari ini."},
    {"teks": "Aku memperhatikan perjalananmu.", "dari": "— Ulangan 2:7",
     "caption": "Aku memperhatikan perjalananmu. 🤍\n\nEmpat puluh tahun di padang gurun, dan tidak satu langkah pun luput dari perhatian Tuhan. Perjalananmu juga.\n\n📖 “…Ia memperhatikan perjalananmu melalui padang gurun yang besar ini; keempat puluh tahun ini TUHAN, Allahmu, menyertai engkau…” — Ulangan 2:7\n\nSave untuk hari perjalananmu terasa panjang 🔖"},
    # Selasa
    {"teks": "Aku akan menguatkan hatimu.", "dari": "— 2 Tesalonika 3:3",
     "caption": "Aku akan menguatkan hatimu. 🤍\n\nKesetiaanmu bisa naik turun. Kesetiaan-Nya tidak. Dia yang menguatkan dan memeliharamu.\n\n📖 “Tetapi Tuhan adalah setia. Ia akan menguatkan hatimu dan memelihara kamu terhadap yang jahat.” — 2 Tesalonika 3:3\n\nKetik “Dia setia” kalau hatimu sedang butuh dikuatkan."},
    {"teks": "Bapamu sudah tahu.", "dari": "— Matius 6:8",
     "caption": "Bapamu sudah tahu. 🤍\n\nKamu tidak perlu doa yang panjang dan berbelit supaya didengar. Dia tahu kebutuhanmu, bahkan sebelum kamu memintanya.\n\n📖 “…Bapamu mengetahui apa yang kamu perlukan, sebelum kamu minta kepada-Nya.” — Matius 6:8\n\nSave untuk malam kamu tidak tahu harus berdoa apa 🔖"},
    # Rabu
    {"teks": "Aku tidak jauh darimu.", "dari": "— Tuhan",
     "caption": "Aku tidak jauh darimu. 🤍\n\nDi kantor, di kampus, di jalan pulang: kamu tidak pernah berada di tempat yang terlalu jauh dari-Nya.\n\n📖 “…Ia tidak jauh dari kita masing-masing. Sebab di dalam Dia kita hidup, kita bergerak, kita ada…” — Kisah Para Rasul 17:27-28\n\nKirim ke temanmu yang merasa Tuhan jauh 💌"},
    {"teks": "Aku melihat air matamu.", "dari": "— Tuhan",
     "caption": "Aku melihat air matamu. 🤍\n\nFirman ini pertama kali diterima Raja Hizkia, yang sakit dan menangis di hadapan Tuhan. Jawaban untuk setiap doa bisa berbeda, tapi hati Tuhan tetap sama: Dia mendengar, dan Dia melihat.\n\n📖 “…Telah Kudengar doamu dan telah Kulihat air matamu…” — Yesaya 38:5\n\nKetik 🤍 kalau malam ini kamu sedang menangis. Kita saling mendoakan."},
    # Kamis
    {"teks": "Aku menuntunmu sampai akhir.", "dari": "— Tuhan",
     "caption": "Aku menuntunmu sampai akhir. 🤍\n\nBukan cuma hari ini, bukan cuma minggu ini. Dia menuntun dengan nasihat-Nya, dan pada akhirnya membawa kita ke dalam kemuliaan.\n\n📖 “Dengan nasihat-Mu Engkau menuntun aku, dan kemudian Engkau mengangkat aku ke dalam kemuliaan.” — Mazmur 73:24\n\nKetik “sampai akhir” kalau kamu mau terus mengikut Dia."},
    {"teks": "I know you by name.", "dari": "— Tuhan",
     "caption": "Dia mengenalmu, sampai ke namamu 🤍\n\nBagi dunia mungkin kamu cuma nomor antrean atau nomor karyawan. Bagi Gembala yang baik, kamu dipanggil dengan namamu.\n\n📖 “Untuk dia penjaga membuka pintu dan domba-domba mendengarkan suaranya dan ia memanggil domba-dombanya masing-masing menurut namanya dan menuntunnya ke luar.” — Yohanes 10:3\n\nKirim ke seseorang yang merasa tidak dikenal 💌"},
    # Jumat
    {"teks": "Kasih-Ku tidak akan beranjak.", "dari": "— Yesaya 54:10",
     "caption": "Kasih-Ku tidak akan beranjak. ⛰️\n\nGunung yang paling kokoh pun bisa bergeser. Kasih setia-Nya tidak.\n\n📖 “Sebab biarpun gunung-gunung beranjak dan bukit-bukit bergoyang, tetapi kasih setia-Ku tidak akan beranjak dari padamu dan perjanjian damai-Ku tidak akan bergoyang, firman TUHAN, yang mengasihani engkau.” — Yesaya 54:10\n\nSave untuk minggu-minggu yang mengguncang 🔖"},
    {"teks": "Kamu tidak Kutinggalkan sendirian.", "dari": "— Tuhan",
     "caption": "Kamu tidak Kutinggalkan sendirian. 🤍\n\nYesus mengucapkan janji ini kepada murid-murid yang takut ditinggal. Dia tidak meninggalkan kita sebagai yatim piatu.\n\n📖 “Aku tidak akan meninggalkan kamu sebagai yatim piatu. Aku datang kembali kepadamu.” — Yohanes 14:18\n\nSelamat berakhir pekan. Ketik 🤍 kalau malam ini kamu merasa sepi."},
    # Sabtu
    {"teks": "Even there, My hand holds you.", "dari": "— Tuhan",
     "caption": "Bahkan di sana, tangan-Nya memegangmu 🌊\n\nSejauh apa pun kamu pergi akhir pekan ini, ke ujung laut sekalipun, kamu tidak keluar dari jangkauan tangan-Nya.\n\n📖 “Jika aku terbang dengan sayap fajar, dan membuat kediaman di ujung laut, juga di sana tangan-Mu akan menuntun aku, dan tangan kanan-Mu memegang aku.” — Mazmur 139:9-10\n\nKetik “tangan-Nya” kalau kamu percaya Dia memegangmu 🙏"},
    {"teks": "Yang berjanji itu setia.", "dari": "— Ibrani 10:23",
     "caption": "Yang berjanji itu setia. 🤍\n\nMinggu ini mungkin imanmu naik turun. Pegang erat pengharapanmu, karena Dia yang menjanjikannya tidak pernah ingkar. Besok kita berkumpul lagi untuk mengingatnya bersama.\n\n📖 “Marilah kita teguh berpegang pada pengakuan tentang pengharapan kita, sebab Ia, yang menjanjikannya, setia.” — Ibrani 10:23\n\nSelamat malam, sampai jumpa di ibadah besok. Ketik “Amin” kalau kamu berpegang pada janji-Nya."},
]


# ---------- KISAH: carousel poster kisah Alkitab (siang0) ----------
KISAH = [
    {"judul1": "Pohon", "judul2": "Ara", "sub": "Zakheus yang Dilihat Yesus", "ref": "Lukas 19:1-10",
     "slides": [("Ingin melihat Yesus",
                 "Zakheus adalah kepala pemungut cukai di Yerikho, dan ia kaya. Ia berusaha melihat Yesus, tapi tidak berhasil karena orang banyak, sebab badannya pendek."),
                ("Naik ke pohon ara",
                 "Ia berlari mendahului orang banyak dan memanjat pohon ara. Seorang pejabat kaya, memanjat pohon seperti anak kecil, hanya supaya bisa melihat Yesus lewat."),
                ("Yesus melihat ke atas",
                 "Sampai di tempat itu, Yesus melihat ke atas dan memanggil namanya. Orang-orang bersungut-sungut: Ia menumpang di rumah orang berdosa."),
                ("Dilihat, lalu diubahkan",
                 "Zakheus turun, menerima Yesus dengan sukacita, dan hidupnya berubah. Yang ingin melihat Yesus, ternyata lebih dulu dilihat. Hari ini pun Dia tahu namamu.")],
     "ayat": "“Zakheus, segeralah turun, sebab hari ini Aku harus menumpang di rumahmu.”",
     "ayat_ref": "Lukas 19:5",
     "caption": "Zakheus naik pohon untuk melihat Yesus. Ternyata Yesus yang lebih dulu melihatnya 🌳\n\nGeser sampai akhir 👉\n\n📖 Lukas 19:1-10\n\nSelamat hari Minggu. Kalau hari ini kamu merasa kecil di tengah keramaian, ketik “Dia melihatku” 🤍"},
    {"judul1": "Dia", "judul2": "Melihatku", "sub": "Hagar di Padang Gurun", "ref": "Kejadian 16:1-14",
     "slides": [("Lari ke padang gurun",
                 "Hagar adalah hamba perempuan Sarai, orang Mesir. Setelah ia mengandung, hubungannya dengan Sarai memburuk. Sarai menindasnya, dan Hagar lari ke padang gurun."),
                ("Ditemukan di dekat mata air",
                 "Malaikat TUHAN menjumpainya dekat sebuah mata air di jalan ke Syur. Ia memanggil namanya dan bertanya: dari manakah datangmu, dan ke manakah pergimu?"),
                ("Didengar",
                 "TUHAN memberinya janji tentang anak yang dikandungnya. Anak itu harus dinamai Ismael, sebab TUHAN telah mendengar tentang penindasan atas dirinya."),
                ("El-Roi",
                 "Hamba yang lari dan merasa tak dianggap itu memberi nama kepada TUHAN: El-Roi, Allah yang melihat. Kamu yang merasa tak terlihat minggu ini, kamu pun dilihat.")],
     "ayat": "“Bukankah di sini kulihat Dia yang telah melihat aku?”",
     "ayat_ref": "Kejadian 16:13",
     "caption": "Seorang hamba yang lari, sendirian di padang gurun. Tapi ia tidak luput dari pandangan Tuhan 🤍\n\nGeser sampai akhir 👉\n\n📖 Kejadian 16:1-14\n\nKirim ke seseorang yang merasa tak terlihat minggu ini 💌"},
    {"judul1": "Di Negeri", "judul2": "Asing", "sub": "Yusuf yang Dijual", "ref": "Kejadian 39:1-23",
     "slides": [("Dijual saudara sendiri",
                 "Yusuf dijual oleh saudara-saudaranya, lalu dibawa ke Mesir. Di sana Potifar, kepala pengawal raja, membelinya. Anak kesayangan kini menjadi budak di negeri asing."),
                ("Setia di rumah orang",
                 "Yusuf tidak memilih tempat itu. Tapi TUHAN menyertai dia di sana, dan Potifar mempercayakan seluruh rumahnya kepada Yusuf."),
                ("Jujur, lalu dipenjara",
                 "Istri tuannya terus membujuknya. Yusuf menolak, karena tidak mau berbuat dosa terhadap Allah. Ia difitnah dan dimasukkan ke penjara."),
                ("Tuhan tetap di sana",
                 "Bahkan di penjara, TUHAN menyertai Yusuf. Pekerjaan yang tidak kamu pilih, tempat yang terasa salah: Dia tetap melihat dan menyertaimu di sana.")],
     "ayat": "“Tetapi TUHAN menyertai Yusuf dan melimpahkan kasih setia-Nya kepadanya…”",
     "ayat_ref": "Kejadian 39:21",
     "caption": "Dijual, difitnah, dipenjara. Tapi di setiap tempat itu, satu kalimat terus diulang: TUHAN menyertai Yusuf 🤍\n\nGeser sampai akhir 👉\n\n📖 Kejadian 39:1-23 (awal kisahnya di Kejadian 37)\n\nUntuk kamu yang bekerja di tempat yang bukan pilihanmu: ketik “Dia menyertai” 🙏"},
    {"judul1": "Air", "judul2": "Hidup", "sub": "Perempuan Samaria di Sumur", "ref": "Yohanes 4:1-42",
     "slides": [("Tengah hari di sumur",
                 "Yesus letih oleh perjalanan dan duduk di pinggir sumur Yakub, kira-kira pukul dua belas siang. Seorang perempuan Samaria datang untuk menimba air."),
                ("Percakapan yang tak biasa",
                 "Yesus meminta minum kepadanya. Perempuan itu heran, sebab orang Yahudi tidak bergaul dengan orang Samaria. Lalu Yesus berbicara tentang air hidup."),
                ("Dikenal sepenuhnya",
                 "Yesus tahu seluruh kisah hidupnya, termasuk lima suami dan hidupnya sekarang. Tapi Yesus tidak pergi. Ia tetap menawarkan air hidup kepadanya."),
                ("Tempayan yang ditinggalkan",
                 "Perempuan itu meninggalkan tempayannya dan pergi ke kota. Orang yang dikenal sepenuhnya dan tetap diterima tidak bisa diam. Banyak orang Samaria pun percaya.")],
     "ayat": "“Mari, lihat! Di sana ada seorang yang mengatakan kepadaku segala sesuatu yang telah kuperbuat.”",
     "ayat_ref": "Yohanes 4:29",
     "caption": "Dia tahu seluruh ceritamu, dan Dia tetap menunggumu di sumur 💧\n\nGeser sampai akhir 👉\n\n📖 Yohanes 4:1-42\n\nKirim ke seseorang yang takut dihakimi karena masa lalunya 💌"},
    {"judul1": "Doa", "judul2": "Tanpa Suara", "sub": "Hana di Rumah TUHAN", "ref": "1 Samuel 1:1-20",
     "slides": [("Tahun demi tahun",
                 "Hana belum juga mempunyai anak, dan madunya terus menyakiti hatinya. Setiap tahun, saat keluarganya pergi beribadah ke Silo, Hana menangis dan tidak mau makan."),
                ("Doa tanpa suara",
                 "Dengan hati pedih Hana berdoa sambil menangis tersedu-sedu. Bibirnya bergerak, tapi suaranya tidak terdengar. Imam Eli malah menyangka ia mabuk."),
                ("Mencurahkan isi hati",
                 "Hana menjelaskan: ia sedang mencurahkan isi hatinya di hadapan TUHAN. Lalu ia pergi, mau makan, dan mukanya tidak muram lagi, bahkan sebelum doanya dijawab."),
                ("Tuhan mengingat",
                 "TUHAN ingat kepada Hana, dan lahirlah Samuel. Jawaban-Nya tidak selalu persis seperti yang kita minta, tapi doa tanpa suara pun tidak luput dari-Nya.")],
     "ayat": "“…aku seorang perempuan yang sangat bersusah hati… aku mencurahkan isi hatiku di hadapan TUHAN.”",
     "ayat_ref": "1 Samuel 1:15",
     "caption": "Doa yang tidak bersuara pun sampai kepada-Nya 🤍\n\nGeser sampai akhir 👉\n\n📖 1 Samuel 1:1-20\n\nKetik 🙏 kalau kamu sedang membawa doa yang belum bisa kamu ucapkan. Kita saling mendoakan."},
    {"judul1": "Makan", "judul2": "dan Tidur", "sub": "Elia yang Kelelahan", "ref": "1 Raja-raja 19:1-18",
     "slides": [("Habis setelah menang",
                 "Elia baru saja melihat kuasa Allah di gunung Karmel. Tapi ancaman Izebel membuatnya takut dan lari. Di bawah pohon arar ia berkata: Cukuplah itu, TUHAN."),
                ("Bangunlah, makanlah",
                 "Tuhan tidak memarahinya. Seorang malaikat menyentuhnya dan berkata: Bangunlah, makanlah! Ada roti bakar dan sebuah kendi air. Elia makan, minum, lalu tidur lagi."),
                ("Bukan dalam angin",
                 "Di gunung Horeb datang angin besar, gempa, dan api. Tapi TUHAN tidak ada di dalamnya. Sesudah itu datanglah bunyi angin sepoi-sepoi basa."),
                ("Kamu tidak sendirian",
                 "Elia merasa tinggal seorang diri. Tuhan memberinya tugas baru dan tujuh ribu orang yang masih setia. Kalau kamu habis minggu ini, istirahat juga bagian dari iman.")],
     "ayat": "“Bangunlah, makanlah! Sebab kalau tidak, perjalananmu nanti terlalu jauh bagimu.”",
     "ayat_ref": "1 Raja-raja 19:7",
     "caption": "Kadang langkah rohani berikutnya adalah makan, minum, dan tidur 🍞\n\nGeser sampai akhir 👉\n\n📖 1 Raja-raja 19:1-18\n\nKirim ke temanmu yang sudah habis-habisan minggu ini 💌"},
    {"judul1": "Yesus", "judul2": "Berhenti", "sub": "Bartimeus di Pinggir Jalan", "ref": "Markus 10:46-52",
     "slides": [("Di pinggir jalan",
                 "Bartimeus, anak Timeus, seorang pengemis yang buta, duduk di pinggir jalan dekat Yerikho. Ia tidak bisa melihat Yesus, tapi ia mendengar bahwa Yesus lewat."),
                ("Disuruh diam",
                 "Ia berseru: Yesus, Anak Daud, kasihanilah aku! Banyak orang menegornya supaya diam. Tapi ia malah berseru semakin keras."),
                ("Yesus berhenti",
                 "Di tengah orang banyak, Yesus berhenti dan berkata: Panggillah dia! Bartimeus menanggalkan jubahnya, segera berdiri, dan pergi mendapatkan Yesus."),
                ("Melihat, lalu mengikut",
                 "Yesus bertanya apa yang ia kehendaki. Seketika ia dapat melihat, lalu mengikuti Yesus dalam perjalanan-Nya. Seruanmu tidak tenggelam di tengah keramaian.")],
     "ayat": "“Kuatkan hatimu, berdirilah, Ia memanggil engkau.”",
     "ayat_ref": "Markus 10:49",
     "caption": "Orang banyak menyuruhnya diam. Yesus berhenti dan memanggilnya 🤍\n\nGeser sampai akhir 👉\n\n📖 Markus 10:46-52\n\nBesok hari Minggu. Ketik “Ia memanggil” kalau kamu mau datang kepada-Nya lagi 🙏"},
]


# ---------- K: tipografi sinematik (skema sama dengan tenang_keren2.KINETIK) ----------
# tiap frasa = satu layar; kata dengan * = disorot (serif miring, emas). Satu kata per tanda *.
KINETIK = [
    {"frasa": ["TUHAN *memberkati*", "dan *melindungi* kamu", "wajah-Nya *menghadap*", "*kepadamu*"],
     "ref": "Bilangan 6:24-26",
     "caption": "Berkat untuk minggu yang baru 🤍\n\nSelesai ibadah, bawa pulang berkat ini. Wajah-Nya menghadap kepadamu, sepanjang minggu.\n\n📖 “TUHAN memberkati engkau dan melindungi engkau; TUHAN menyinari engkau dengan wajah-Nya dan memberi engkau kasih karunia; TUHAN menghadapkan wajah-Nya kepadamu dan memberi engkau damai sejahtera.” — Bilangan 6:24-26\n\nKirim berkat ini ke seseorang yang kamu sayangi 💌"},
    {"frasa": ["saat kamu *duduk*", "saat kamu *berdiri*", "saat kamu *berjalan*", "Dia *mengenal* kamu"],
     "ref": "Mazmur 139:1-3",
     "caption": "Dia mengenalmu: saat duduk, berdiri, berjalan, dan berbaring 🤍\n\n📖 “TUHAN, Engkau menyelidiki dan mengenal aku; Engkau mengetahui, kalau aku duduk atau berdiri, Engkau mengerti pikiranku dari jauh. Engkau memeriksa aku, kalau aku berjalan dan berbaring, segala jalanku Kaumaklumi.” — Mazmur 139:1-3\n\nKetik “Dia mengenalku” kalau kamu percaya."},
    {"frasa": ["Dia tahu kamu *rapuh*", "Dia ingat kamu *debu*", "dan Dia tetap", "*sayang*"],
     "ref": "Mazmur 103:13-14",
     "caption": "Dia tahu kamu rapuh, dan Dia tetap sayang 🤍\n\n📖 “Seperti bapa sayang kepada anak-anaknya, demikian TUHAN sayang kepada orang-orang yang takut akan Dia. Sebab Dia sendiri tahu apa kita, Dia ingat, bahwa kita ini debu.” — Mazmur 103:13-14\n\nSave untuk hari kamu merasa terlalu rapuh 🔖"},
    {"frasa": ["*mata* tertuju", "bukan ke *samping*", "bukan ke *belakang*", "tapi kepada *Yesus*"],
     "ref": "Ibrani 12:1-2",
     "caption": "Di tengah minggu yang ramai, mata tertuju kepada Yesus 👀\n\n📖 “…marilah kita menanggalkan semua beban dan dosa yang begitu merintangi kita, dan berlomba dengan tekun dalam perlombaan yang diwajibkan bagi kita. Marilah kita melakukannya dengan mata yang tertuju kepada Yesus…” — Ibrani 12:1-2\n\nKetik “mata kepada Yesus” sebagai komitmenmu minggu ini 🙏"},
    {"frasa": ["Dia *melihat*", "kesusahanmu", "lalu *mengambilnya*", "ke dalam *tangan-Nya*"],
     "ref": "Mazmur 10:14",
     "caption": "Dia melihat kesusahanmu, dan mengambilnya ke dalam tangan-Nya 🤍\n\n📖 “Engkau memang melihatnya, sebab Engkaulah yang melihat kesusahan dan sakit hati, supaya Engkau mengambilnya ke dalam tangan-Mu sendiri…” — Mazmur 10:14\n\nKirim ke seseorang yang sedang memikul kesusahan diam-diam 💌"},
    {"frasa": ["Dia *memangku*", "yang *kecil*", "dan menuntun yang *lelah*", "dengan *hati-hati*"],
     "ref": "Yesaya 40:11",
     "caption": "Gembala yang menuntun dengan hati-hati 🐑\n\nDi akhir minggu, mungkin langkahmu melambat. Dia tidak menyeretmu. Dia menuntun dengan hati-hati.\n\n📖 “Seperti seorang gembala Ia menggembalakan kawanan ternak-Nya dan menghimpunkannya dengan tangan-Nya; anak-anak domba dipangku-Nya, induk-induk domba dituntun-Nya dengan hati-hati.” — Yesaya 40:11\n\nKetik 🐑 kalau minggu ini kamu butuh dituntun pelan-pelan."},
    {"frasa": ["Dia *mengundang*", "carilah *wajah-Ku*", "maka besok", "wajah-Mu *kucari*"],
     "ref": "Mazmur 27:8",
     "caption": "Besok, datang untuk mencari wajah-Nya 🤍\n\n📖 “Hatiku mengikuti firman-Mu: ‘Carilah wajah-Ku’; maka wajah-Mu kucari, ya TUHAN.” — Mazmur 27:8\n\nKetik “wajah-Mu kucari” sebagai doamu menjelang hari Minggu 🙏"},
]


# ---------- T: teks relatable (skema sama dengan tenang_keren2.RELATABLE) ----------
# "atas" = label kecil opsional di atas teks. "\n" = baris punchline. Tanpa emoji di teks (font).
RELATABLE = [
    {"atas": "ibadah Minggu",
     "teks": "Datang telat ke gereja.\nSatu-satunya pintu yang masih terbuka: pintu depan, dekat mimbar.",
     "caption": "Jalan pelan-pelan sambil senyum ke semua orang 😅🙏\n\nTapi tetap lebih baik datang terlambat daripada tidak datang. Selamat hari Minggu! Tag teman yang pernah ngalamin ini 👇"},
    {"teks": "Di gereja ditanya: “Gimana kabarnya?”\n“Puji Tuhan, baik.”\nPadahal minggu ini berantakan banget.",
     "caption": "Kadang “baik” itu jawaban otomatis 😅\n\nDi hadapan Tuhan, kamu tidak perlu pura-pura. Semoga di gereja juga ada satu orang yang aman untuk kamu ajak jujur.\n\nTag teman yang bisa kamu ajak cerita apa adanya 🤍"},
    {"atas": "program baca Alkitab setahun",
     "teks": "Januari: semangat mulai dari Kejadian.\nOktober: masih tertahan di Imamat.",
     "caption": "Imamat memang butuh kesabaran ekstra 😂📖\n\nTidak apa-apa tertinggal. Mulai lagi hari ini, satu pasal saja, dan minta Tuhan membuka matamu.\n\n📖 “Singkapkanlah mataku, supaya aku memandang keajaiban-keajaiban dari Taurat-Mu.” — Mazmur 119:18\n\nKamu sekarang sampai kitab apa? Jawab jujur di komentar 👇"},
    {"teks": "Ngetik curhat panjang ke teman,\nhapus semuanya,\nakhirnya cerita ke Tuhan saja.",
     "caption": "Kadang yang paling kita butuhkan adalah didengar tanpa dihakimi 🤍\n\n📖 “Aku mencurahkan keluhanku ke hadapan-Nya, kesesakanku kuberitahukan ke hadapan-Nya.” — Mazmur 142:3\n\nSiapa yang juga sering begini? Ketik “aku” 👇"},
    {"atas": "pelayanan",
     "teks": "Aku: “Aku nggak bisa pelayanan, aku pemalu.”\nGereja: “Oke, kamu pegang kamera live streaming, ya.”",
     "caption": "Pelayanan di balik layar juga pelayanan 🎥😂\n\nTerima kasih untuk tim multimedia, operator slide, dan sound system yang jarang terlihat tapi sangat berarti. Tag tim multimedia gerejamu 👇"},
    {"teks": "Lagi doa serius-seriusnya,\ntiba-tiba kepikiran:\nkompor tadi udah dimatiin belum, ya?",
     "caption": "Pikiran memang suka jalan-jalan waktu doa 😂🔥\n\nTidak apa-apa. Kembali pelan-pelan ke hadapan-Nya, Dia sabar menunggu. Tapi cek kompornya dulu, ya.\n\nSiapa yang pernah begini? Ketik “aku” 👇"},
    {"atas": "ibadah Minggu",
     "teks": "Pendeta: “Saya singkat saja, ya.”\n45 menit kemudian: “Dan yang ketiga…”",
     "caption": "Tapi justru poin ketiga yang paling kena 😂🙏\n\nTerima kasih untuk para hamba Tuhan yang setia menyiapkan firman setiap minggu. Tag pendeta atau gembalamu, bilang terima kasih 👇"},
    {"atas": "menjelang Natal",
     "teks": "Mama: “Natal nanti kamu ikut paduan suara, ya.”\nAku: “Suaraku fals, Ma.”\nMama: “Tuhan lihat hatinya.”",
     "caption": "Mama selalu punya jawaban rohani untuk segala situasi 😂🎄\n\nTapi mama benar: Tuhan melihat hati. Dan sorak-sorai yang tulus tetap indah bagi-Nya.\n\n📖 “Bersorak-soraklah bagi TUHAN, hai seluruh bumi, bergembiralah, bersorak-sorailah dan bermazmurlah!” — Mazmur 98:4\n\nTahun ini kamu ikut paduan suara Natal? Jawab di komentar 👇"},
    {"atas": "liturgi",
     "teks": "“Jemaat, silakan berdiri.”\n“Silakan duduk.”\n“Silakan berdiri kembali.”\nLeg day setiap hari Minggu.",
     "caption": "Olahraga rohani dan jasmani sekaligus 😂🦵\n\nGerejamu tim banyak berdiri atau tim duduk terus? Jawab di komentar 👇"},
    {"teks": "Anak kecil di gereja\nnyanyi “Haleluya” paling kencang,\nwalaupun liriknya salah semua.",
     "caption": "Pujian paling tulus sedunia 🥹🎶\n\n📖 “Dari mulut bayi-bayi dan anak-anak yang menyusu telah Kauletakkan dasar kekuatan…” — Mazmur 8:3\n\nCeritain momen lucu anak kecil di gerejamu 👇"},
    {"atas": "menjelang Natal",
     "teks": "Natal masih dua bulan lagi.\nGrup panitia Natal: 214 pesan belum dibaca.",
     "caption": "Semangat panitia Natal sudah dimulai 😂🎄\n\nDi tengah semua rapat dan persiapan, jangan lupa Siapa yang kita rayakan.\n\n📖 “Hari ini telah lahir bagimu Juruselamat, yaitu Kristus, Tuhan, di kota Daud.” — Lukas 2:11\n\nTag teman sesama panitia Natal 👇"},
    {"atas": "tim musik gereja",
     "teks": "Latihan Sabtu: “Besok kita main santai aja, ya.”\nMinggu pagi: drummer-nya main kayak konser rock.",
     "caption": "Semangatnya memang nggak bisa ditahan 😂🥁\n\n📖 “Pujilah Dia dengan ceracap yang berdenting, pujilah Dia dengan ceracap yang berdentang!” — Mazmur 150:5\n\nTag drummer gerejamu 👇"},
    {"atas": "ibadah keluarga",
     "teks": "Papa: “Malam ini kita baca satu pasal saja.”\nPasal yang dipilih: Mazmur 119.",
     "caption": "176 ayat kemudian… 😂📖\n\nTapi terima kasih untuk papa dan mama yang membiasakan kami berdoa dan membaca firman bersama. Di rumahmu ada ibadah keluarga? Ceritain di komentar 👇"},
    {"atas": "besok pelayanan",
     "teks": "Besok jadi worship leader.\nMalam ini latihan di kamar mandi,\nsampai tetangga ikut hafal lagunya.",
     "caption": "Untuk semua yang besok pelayanan: semangat! 🎤🙏\n\n📖 “…sambil menyanyikan mazmur, dan puji-pujian dan nyanyian rohani, kamu mengucap syukur kepada Allah di dalam hatimu.” — Kolose 3:16\n\nTag teman yang besok melayani, dan doakan dia malam ini 👇"},
]


# ---------- F: photo dump (skema sama dengan tenang_keren2.DUMP) ----------
DUMP = [
    {"slides": [("jendela", "yang Tuhan lihat, walau tak ada yang tahu"), ("lilin", "doa yang kamu bisikkan sendirian"),
                ("jalan", "langkah kecil yang terus kamu ambil"), ("awan", "air mata yang kamu sembunyikan"),
                ("bintang", "hati yang tetap mau percaya")],
     "caption": "yang Tuhan lihat, walau tak ada yang tahu 🤍\n\nGeser pelan-pelan. Tidak ada satu pun yang luput dari pandangan-Nya.\n\n📖 “Tetapi jika engkau berdoa, masuklah ke dalam kamarmu, tutuplah pintu dan berdoalah kepada Bapamu yang ada di tempat tersembunyi. Maka Bapamu yang melihat yang tersembunyi akan membalasnya kepadamu.” — Matius 6:6\n\nSlide mana yang paling kamu butuhkan malam ini? Tulis nomornya di komentar 👇"},
    {"slides": [("jalan", "Tuhan juga ada di sini"), ("kabut", "di jalan macet tadi pagi"),
                ("jendela", "di meja kerja yang berantakan"), ("pohon", "di antrean makan siang"),
                ("bintang", "di perjalanan pulang yang panjang")],
     "caption": "Tuhan juga ada di sini 🤍\n\nYakub baru sadar setelah bangun tidur: Tuhan ada di tempat itu, dan ia tidak mengetahuinya. Mungkin hari ini pun begitu.\n\n📖 “Sesungguhnya TUHAN ada di tempat ini, dan aku tidak mengetahuinya.” — Kejadian 28:16\n\nDi mana kamu merasakan penyertaan-Nya hari ini? Ceritain di komentar 👇"},
    {"slides": [("jalan", "untuk kamu yang jalannya masih panjang"), ("gunung", "tanjakan bukan tanda kamu salah jalan"),
                ("awan", "berhenti sebentar juga boleh"), ("laut", "kekuatanmu ada di dalam Dia"),
                ("bintang", "dan setiap hari, kamu makin dekat")],
     "caption": "untuk kamu yang jalannya masih panjang 🤍\n\nPerjalanan iman jarang lurus dan datar. Tapi orang yang kekuatannya di dalam Tuhan berjalan makin lama makin kuat.\n\n📖 “Berbahagialah manusia yang kekuatannya di dalam Engkau, yang berhasrat mengadakan ziarah! … Mereka berjalan makin lama makin kuat, hendak menghadap Allah di Sion.” — Mazmur 84:6-8\n\nKirim ke temanmu yang sedang di tanjakan hidupnya 💌"},
    {"slides": [("jendela", "persiapan kecil untuk besok pagi"), ("lilin", "lepaskan satu kekesalan malam ini"),
                ("bintang", "tidur sedikit lebih cepat"), ("jalan", "rencanakan jam berangkat"),
                ("awan", "bawa hati yang mau mendengar")],
     "caption": "persiapan kecil untuk besok pagi ⛪\n\nIbadah besok dimulai dari malam ini: hati yang dilepaskan, tubuh yang beristirahat, dan rindu yang disiapkan.\n\n📖 “Masuklah, marilah kita sujud menyembah, berlutut di hadapan TUHAN yang menjadikan kita.” — Mazmur 95:6\n\nSlide mana yang mau kamu lakukan malam ini? Tulis nomornya di komentar 👇"},
]


# ---------- V: dulu vs sekarang (skema sama dengan tenang_keren2.DULU) ----------
DULU = [
    {"judul": "tentang sibuk",
     "pasangan": [("sibuk berarti aku penting", "sibuk bisa berarti lupa berhenti"), ("berdoa kalau sempat", "menyempatkan diri untuk berdoa"),
                  ("aku harus selalu bisa dihubungi", "Yesus pun menyepi untuk berdoa")],
     "ayat": "“Akan tetapi Ia mengundurkan diri ke tempat-tempat yang sunyi dan berdoa.”",
     "ref": "Lukas 5:16",
     "caption": "dulu vs sekarang: tentang sibuk ⏳\n\nOrang banyak berbondong-bondong mencari Yesus, tapi Ia tetap mengundurkan diri untuk berdoa. Kalau Yesus saja menyepi, kita pun boleh.\n\n📖 Lukas 5:16\n\nKetik 1, 2, atau 3: mana yang paling kamu rasakan minggu ini?"},
    {"judul": "tentang dilihat",
     "pasangan": [("aku harus dilihat orang supaya berarti", "dilihat Tuhan saja sudah cukup"), ("yang tak dipuji itu sia-sia", "Tuhan melihat yang tersembunyi"),
                  ("aku harus terlihat sempurna", "Tuhan melihat hati, bukan tampilan")],
     "ayat": "“…manusia melihat apa yang di depan mata, tetapi TUHAN melihat hati.”",
     "ref": "1 Samuel 16:7",
     "caption": "dulu vs sekarang: tentang dilihat 👀\n\nDi zaman semua orang ingin terlihat, ada kelegaan besar dalam kalimat ini: Tuhan melihat hati.\n\n📖 1 Samuel 16:7\n\nKirim ke temanmu yang lelah berusaha terlihat sempurna 💌"},
    {"judul": "tentang iman",
     "pasangan": [("iman berarti tidak pernah ragu", "iman berarti tetap melangkah walau ragu"), ("aku berangkat kalau petanya lengkap", "aku berangkat karena Dia memanggil"),
                  ("iman itu perasaan yang kuat", "iman itu bersandar pada Dia yang setia")],
     "ayat": "“Karena iman Abraham taat, ketika ia dipanggil untuk berangkat ke negeri yang akan diterimanya menjadi milik pusakanya, lalu ia berangkat dengan tidak mengetahui tempat yang ia tujui.”",
     "ref": "Ibrani 11:8",
     "caption": "dulu vs sekarang: tentang iman 🧭\n\nAbraham berangkat tanpa tahu tempat tujuannya. Yang ia tahu hanya Siapa yang memanggilnya.\n\n📖 Ibrani 11:8\n\nSave untuk hari kamu harus melangkah tanpa peta yang lengkap 🔖"},
]


# hari 1-7 (Minggu 18 Okt .. Sabtu 24 Okt 2026): 12 slot per hari -> (format, index)
# pagi 06:00, pagi3 07:30, pagi2 09:00, siang0 10:30, siang 12:00, siang2 13:30, sore 15:00, sore2 16:30,
# petang 18:00 (F hari 1/3/5/7, V hari 2/4/6), malam0 19:30, malam 21:00, larut 22:30
JADWAL = {d: {"pagi": ("BUKU", 3 * (d - 1)), "pagi3": ("MEME", 2 * (d - 1)), "pagi2": ("T", 2 * (d - 1)),
              "siang0": ("KISAH", d - 1), "siang": ("BUKU", 3 * (d - 1) + 1), "siang2": ("K", d - 1),
              "sore": ("SKRIP", 2 * (d - 1)), "sore2": ("MEME", 2 * (d - 1) + 1),
              "petang": ("F", (d - 1) // 2) if d % 2 else ("V", d // 2 - 1),
              "malam0": ("SKRIP", 2 * (d - 1) + 1), "malam": ("T", 2 * (d - 1) + 1),
              "larut": ("BUKU", 3 * (d - 1) + 2)} for d in range(1, 8)}
