"""Akun Tenang (@diam.dan.percaya) - minggu 9 (Minggu 22 Nov - Sabtu 28 Nov 2026).
Tema: "Raja yang datang" - dari Minggu Kristus Raja menuju Minggu Adven pertama (29 Nov) + hitung mundur Natal lanjut (33 -> 27 hari).
Hari: 1 Minggu (Minggu Kristus Raja: Yesus, Raja di atas segala raja), 2 Senin (Raja yang melayani, membasuh kaki),
3 Selasa (Kerajaan-Nya tidak tergoncangkan, saat dunia terasa goyah), 4 Rabu (warga Kerajaan Sorga: damai, kasih, keadilan),
5 Kamis (menanti dengan setia dan berjaga-jaga), 6 Jumat (persiapkanlah jalan untuk Tuhan: Yohanes Pembaptis, pertobatan),
7 Sabtu (besok Minggu Adven pertama: pengharapan; siap ibadah besok).
12 slot per hari, setiap slot gaya visual berbeda:
  JAM        = jam tangan pintar dengan notifikasi pagi yang lembut.                   pagi 06:00
  NAMA       = kartu nama seri "Nama-nama Yesus".                                     pagi3 07:30
  ELI        = komik Eli yang sudah jadi (hari 1, 4, 7) / RAMBU = tiga rambu jalan.   pagi2 09:00
  RESEP      = kartu resep tulisan tangan.                                           siang0 10:30
  UNDANGAN   = kartu undangan elegan dengan segel lilin.                              siang 12:00
  PROGRESS   = Reel bilah progres "instalasi", ayat muncul di akhir.                  siang2 13:30
  GLOBE      = bola salju, hitung mundur Natal.                                      sore 15:00
  MUSEUM     = lukisan di dinding galeri dengan plakat museum.                        sore2 16:30
  KASET      = kaset dengan daftar lagu mixtape tulisan tangan.                       petang 18:00
  GOSOK      = Reel kartu gosok yang digosok sampai pesannya terlihat.                malam0 19:30
  SERTIFIKAT = sertifikat berdasarkan anugerah.                                       malam 21:00
  JENDELA    = jendela berembun di malam hari, tulisan dengan jari di kaca.           larut 22:30
Kutipan ayat: Alkitab TB. Caption tanpa hashtag."""

# ---------- JAM: jam tangan pintar, notifikasi pagi (pagi 06:00) ----------
JAM = [
    {"judul": "Selamat pagi",
     "pesan": "Hari ini Minggu Kristus Raja. Mulai dengan menyembah-Nya.",
     "ayat": "“Sebab Allah adalah Raja seluruh bumi, bermazmurlah dengan nyanyian pengajaran!”",
     "ref": "Mazmur 47:8",
     "caption": "Pagi ini, siapa yang bertakhta? ⌚\n\nMazmur 47 adalah nyanyian sorak-sorai untuk Allah yang memerintah. Pemazmur tidak menyebut-Nya raja satu bangsa saja, tetapi Raja seluruh bumi. Hari ini banyak gereja merayakan Minggu Kristus Raja, Minggu terakhir dalam kalender gerejawi. Sebelum notifikasi lain berdatangan, mulailah hari dengan mengakui siapa Raja hidupmu.\n\n📖 “Sebab Allah adalah Raja seluruh bumi, bermazmurlah dengan nyanyian pengajaran!” — Mazmur 47:8\n\nKetik “Rajaku” kalau pagi ini kamu mau menyerahkan harimu kepada-Nya 👑"},
    {"judul": "Pengingat Senin",
     "pesan": "Raja kita datang untuk melayani. Hari ini, ikut Dia.",
     "ayat": "“Sebab siapakah yang lebih besar: yang duduk makan, atau yang melayani? Bukankah dia yang duduk makan? Tetapi Aku ada di tengah-tengah kamu sebagai pelayan.”",
     "ref": "Lukas 22:27",
     "caption": "Senin pagi, satu pertanyaan dari Yesus ⌚\n\nMalam itu, saat Perjamuan Terakhir, murid-murid malah bertengkar tentang siapa yang terbesar di antara mereka. Yesus tidak menjawab dengan teori. Ia menunjuk diri-Nya sendiri: Tuhan dan Guru mereka ada di tengah-tengah mereka sebagai pelayan. Minggu ini kita belajar mengenal Raja yang tidak gengsi melayani.\n\n📖 “Sebab siapakah yang lebih besar: yang duduk makan, atau yang melayani? Bukankah dia yang duduk makan? Tetapi Aku ada di tengah-tengah kamu sebagai pelayan.” — Lukas 22:27\n\nTulis satu cara kamu bisa melayani orang di sekitarmu hari ini 👇"},
    {"judul": "Tarik napas",
     "pesan": "Berita pagi boleh mengguncang. Takhta-Nya tetap tegak.",
     "ayat": "“TUHAN adalah Raja, Ia berpakaian kemegahan… Sungguh, telah tegak dunia, tidak bergoyang;”",
     "ref": "Mazmur 93:1",
     "caption": "Sebelum membuka berita pagi ini ⌚\n\nMazmur 93 adalah salah satu mazmur yang merayakan TUHAN sebagai Raja. Pemazmur mendengar sungai-sungai mengangkat suaranya dan ombak laut yang hebat menghempas. Tapi ia tahu ada yang lebih hebat dari semua gemuruh itu: TUHAN yang bertakhta di tempat tinggi. Dunia bisa terasa goyah hari ini. Takhta-Nya tidak.\n\n📖 “TUHAN adalah Raja, Ia berpakaian kemegahan… Sungguh, telah tegak dunia, tidak bergoyang;” — Mazmur 93:1\n\nKetik “Takhta-Nya tegak” kalau pagi ini kamu butuh diingatkan 🤍"},
    {"judul": "Status hari ini",
     "pesan": "Warga sorga, sedang bertugas di bumi. Selamat hari Rabu.",
     "ayat": "“Karena kewargaan kita adalah di dalam sorga, dan dari situ juga kita menantikan Tuhan Yesus Kristus sebagai Juruselamat,”",
     "ref": "Filipi 3:20",
     "caption": "Cek status kewarganegaraanmu ⌚\n\nFilipi adalah kota perantauan orang Roma. Penduduknya bangga menjadi warga Roma, meskipun tinggal jauh dari kota Roma. Paulus memakai gambaran itu: kewargaan kita ada di dalam sorga. Bukan supaya kita acuh pada dunia, tetapi supaya kita hidup di sini dengan cara Kerajaan-Nya, sambil menantikan Raja kita datang.\n\n📖 “Karena kewargaan kita adalah di dalam sorga, dan dari situ juga kita menantikan Tuhan Yesus Kristus sebagai Juruselamat,” — Filipi 3:20\n\nKetik “Warga sorga” kalau kamu mau menjalani hari ini sebagai warga-Nya 🤍"},
    {"judul": "Mode berjaga",
     "pesan": "Bangun dari tidur, juga dari hati yang lengah.",
     "ayat": "“Hati-hatilah dan berjaga-jagalah! Sebab kamu tidak tahu bilamanakah waktunya tiba.”",
     "ref": "Markus 13:33",
     "caption": "Alarm pagi yang berbeda ⌚\n\nYesus mengatakan ini di Bukit Zaitun, setelah murid-murid-Nya bertanya kapan semua yang Ia nubuatkan akan terjadi. Jawaban-Nya mengejutkan: tentang hari atau saat itu tidak ada yang tahu. Karena itu tugas kita bukan menebak-nebak tanggal, tetapi berjaga-jaga: setia mengerjakan bagian kita setiap hari, siap kapan pun Ia datang.\n\n📖 “Hati-hatilah dan berjaga-jagalah! Sebab kamu tidak tahu bilamanakah waktunya tiba.” — Markus 13:33\n\nKetik “Aku berjaga” kalau hari ini kamu mau hidup siap menyambut-Nya."},
    {"judul": "Suara pagi ini",
     "pesan": "Ada jalan yang perlu diluruskan hari ini? Mulai dari hati.",
     "ayat": "“…Akulah suara orang yang berseru-seru di padang gurun: Luruskanlah jalan Tuhan!…”",
     "ref": "Yohanes 1:23",
     "caption": "Suara pertama di hari Jumat ⌚\n\nUtusan-utusan dari Yerusalem bertanya kepada Yohanes Pembaptis: siapakah engkau? Mesias? Elia? Nabi yang akan datang? Yohanes menjawab bukan. Ia tidak mau menjadi pusat perhatian. Ia hanya sebuah suara, yang tugasnya menyiapkan orang untuk menyambut Dia yang datang sesudahnya. Pagi ini, dengarkan suara itu: luruskanlah jalan Tuhan.\n\n📖 “…Akulah suara orang yang berseru-seru di padang gurun: Luruskanlah jalan Tuhan!…” — Yohanes 1:23\n\nKetik “Luruskan jalanku” sebagai doa pagi ini 🤍"},
    {"judul": "Sabtu pagi",
     "pesan": "Besok Adven pertama. Hari ini, berjalan dalam terang-Nya.",
     "ayat": "“Hai kaum keturunan Yakub, mari kita berjalan di dalam terang TUHAN!”",
     "ref": "Yesaya 2:5",
     "caption": "Sabtu pagi, satu ajakan ⌚\n\nYesaya baru saja melihat penglihatan tentang masa depan: bangsa-bangsa datang ke rumah TUHAN, pedang ditempa menjadi mata bajak, dan orang tidak lagi belajar perang. Lalu ia berbalik kepada umatnya sendiri dengan ajakan sederhana: kalau itu masa depan yang Allah janjikan, mari mulai berjalan di dalam terang-Nya sekarang. Besok kita memasuki masa Adven.\n\n📖 “Hai kaum keturunan Yakub, mari kita berjalan di dalam terang TUHAN!” — Yesaya 2:5\n\nKetik “Berjalan dalam terang” kalau kamu mau menyambut masa Adven bersama kami 🕯️"},
]

# ---------- NAMA: kartu nama seri "Nama-nama Yesus" (pagi3 07:30) ----------
NAMA = [
    {"nama": "Raja segala raja",
     "sub": "Yesus Kristus · Anak Domba Allah",
     "kontak": [["Takhta", "kekal, tidak tergeser"], ["Kantor", "buka 24 jam lewat doa"], ["Wilayah", "langit dan bumi"]],
     "ayat": "“Dan pada jubah-Nya dan paha-Nya tertulis suatu nama, yaitu: ‘Raja segala raja dan Tuan di atas segala tuan.’”",
     "ref": "Wahyu 19:16",
     "caption": "Kartu nama untuk Minggu Kristus Raja 👑\n\nDalam penglihatan Yohanes, sorga terbuka dan tampak Dia yang menunggang kuda putih, Yang Setia dan Yang Benar, yang menghakimi dengan adil. Nama-Nya tertulis di jubah-Nya, supaya semua orang dapat membacanya: Raja segala raja. Penguasa dunia datang dan pergi, kerajaan-kerajaan runtuh. Gelar ini tidak pernah berpindah tangan.\n\n📖 “Dan pada jubah-Nya dan paha-Nya tertulis suatu nama, yaitu: ‘Raja segala raja dan Tuan di atas segala tuan.’” — Wahyu 19:16\n\nSave kartu nama ini dan buka lagi saat dunia terasa tak terkendali 🔖"},
    {"nama": "Hamba yang Dipilih-Nya",
     "sub": "Yesus Kristus · Raja yang melayani",
     "kontak": [["Jam kerja", "sejak palungan"], ["Seragam", "kain lenan di pinggang"], ["Layanan", "tanpa pilih-pilih orang"]],
     "ayat": "“Lihatlah, itu Hamba-Ku yang Kupilih, yang Kukasihi, yang kepada-Nya jiwa-Ku berkenan…”",
     "ref": "Matius 12:18",
     "caption": "Kartu nama yang mengejutkan 💼\n\nMatius mengutip nubuat Yesaya tentang Hamba Tuhan, lalu menerapkannya kepada Yesus. Saat itu Yesus baru saja menyembuhkan banyak orang dan dengan keras melarang mereka memberitahukan siapa Dia. Raja segala raja juga disebut Hamba. Ia tidak berteriak mencari panggung. Ia datang untuk melayani dan memulihkan yang lemah.\n\n📖 “Lihatlah, itu Hamba-Ku yang Kupilih, yang Kukasihi, yang kepada-Nya jiwa-Ku berkenan…” — Matius 12:18\n\nKetik “Ajar aku melayani” kalau kamu mau belajar dari Dia minggu ini 🤍"},
    {"nama": "Batu penjuru",
     "sub": "Yesus Kristus · Dasar yang teguh",
     "kontak": [["Fondasi", "tahan gempa dan badai"], ["Proyek", "membangun umat-Nya"], ["Garansi", "tidak dipermalukan"]],
     "ayat": "“yang dibangun di atas dasar para rasul dan para nabi, dengan Kristus Yesus sebagai batu penjuru.”",
     "ref": "Efesus 2:20",
     "caption": "Kartu nama untuk hari yang goyah 💼\n\nDalam bangunan kuno, batu penjuru adalah batu utama di sudut fondasi. Seluruh bangunan diukur dan disejajarkan dengannya. Paulus menggambarkan umat Allah seperti sebuah rumah yang sedang dibangun, dengan Kristus Yesus sebagai batu penjurunya. Saat banyak hal di sekitarmu terasa goyah, ingat di atas siapa hidupmu dibangun.\n\n📖 “yang dibangun di atas dasar para rasul dan para nabi, dengan Kristus Yesus sebagai batu penjuru.” — Efesus 2:20\n\nSave kartu ini untuk hari-hari yang terasa goyah 🔖"},
    {"nama": "Damai sejahtera kita",
     "sub": "Yesus Kristus · Perubuh tembok",
     "kontak": [["Keahlian", "merubuhkan tembok pemisah"], ["Proyek", "satu keluarga Allah"], ["Biaya", "lunas di kayu salib"]],
     "ayat": "“Karena Dialah damai sejahtera kita, yang telah mempersatukan kedua pihak dan yang telah merubuhkan tembok pemisah, yaitu perseteruan,”",
     "ref": "Efesus 2:14",
     "caption": "Kartu nama untuk hari Rabu 💼\n\nPaulus menulis kepada jemaat yang terdiri dari orang Yahudi dan orang bukan Yahudi, dua kelompok yang berabad-abad terpisah oleh perseteruan. Di dalam Kristus, tembok pemisah itu dirubuhkan dan kedua pihak dipersatukan. Yesus bukan hanya membawa damai. Dialah damai sejahtera kita. Warga Kerajaan-Nya dipanggil untuk hidup dalam damai yang sama.\n\n📖 “Karena Dialah damai sejahtera kita, yang telah mempersatukan kedua pihak dan yang telah merubuhkan tembok pemisah, yaitu perseteruan,” — Efesus 2:14\n\nTag teman yang dulu berbeda jalan, tapi kini satu denganmu di dalam Kristus 👇"},
    {"nama": "Bintang timur",
     "sub": "Yesus Kristus · Tunas Daud",
     "kontak": [["Terbit", "menjelang fajar"], ["Pesan", "malam hampir berlalu"], ["Kehadiran", "menyertai sampai pagi"]],
     "ayat": "“Aku, Yesus… Aku adalah tunas, yaitu keturunan Daud, bintang timur yang gilang-gemilang.”",
     "ref": "Wahyu 22:16",
     "caption": "Kartu nama untuk yang sedang menunggu 💼\n\nBintang timur bersinar paling terang di langit menjelang fajar. Bagi orang yang berjaga semalaman, munculnya bintang itu tanda bahwa malam hampir berakhir. Di halaman-halaman terakhir Alkitab, Yesus memperkenalkan diri-Nya sebagai bintang timur yang gilang-gemilang. Selama kita menanti, Dialah tanda bahwa pagi pasti datang.\n\n📖 “Aku, Yesus… Aku adalah tunas, yaitu keturunan Daud, bintang timur yang gilang-gemilang.” — Wahyu 22:16\n\nSave kartu nama ini untuk malam-malam penantianmu 🔖"},
    {"nama": "Anak Domba Allah",
     "sub": "Yesus dari Nazaret · Juruselamat",
     "kontak": [["Dikenalkan", "oleh Yohanes Pembaptis"], ["Layanan", "menghapus dosa dunia"], ["Biaya", "ditanggung-Nya sendiri"]],
     "ayat": "“Pada keesokan harinya Yohanes melihat Yesus datang kepadanya dan ia berkata: ‘Lihatlah Anak domba Allah, yang menghapus dosa dunia.’”",
     "ref": "Yohanes 1:29",
     "caption": "Kartu nama yang diperkenalkan Yohanes Pembaptis 💼\n\nYohanes Pembaptis memanggil banyak orang untuk bertobat. Tapi ketika Yesus datang, ia tidak menunjuk kepada dirinya sendiri. Ia menunjuk kepada Yesus: lihatlah Anak domba Allah. Pertobatan tidak berhenti pada menyesali dosa. Pertobatan membawa kita kepada Dia yang menghapus dosa. Persiapan terbaik menyambut Natal adalah memandang kepada Anak Domba itu.\n\n📖 “Pada keesokan harinya Yohanes melihat Yesus datang kepadanya dan ia berkata: ‘Lihatlah Anak domba Allah, yang menghapus dosa dunia.’” — Yohanes 1:29\n\nKirim kartu ini ke teman yang merasa dosanya terlalu besar untuk diampuni 💌"},
    {"nama": "Taruk dari pangkal Isai",
     "sub": "Yesus Kristus · Harapan bangsa",
     "kontak": [["Asal", "tunggul yang tampak mati"], ["Tugas", "memerintah bangsa-bangsa"], ["Keahlian", "menumbuhkan harapan"]],
     "ayat": "“…Taruk dari pangkal Isai akan terbit, dan Ia akan bangkit untuk memerintah bangsa-bangsa, dan kepada-Nyalah bangsa-bangsa akan menaruh harapan.”",
     "ref": "Roma 15:12",
     "caption": "Kartu nama menjelang masa Adven 💼\n\nIsai adalah ayah Raja Daud. Yesaya bernubuat bahwa keturunan raja-raja Daud akan ditebang seperti pohon sampai tinggal tunggulnya. Tapi dari tunggul itu akan tumbuh taruk yang baru. Paulus mengutip nubuat ini dan melihat penggenapannya dalam Yesus, Raja yang kepada-Nya bangsa-bangsa menaruh harapan. Besok di banyak gereja dinyalakan lilin Adven pertama, lilin pengharapan.\n\n📖 “…Taruk dari pangkal Isai akan terbit, dan Ia akan bangkit untuk memerintah bangsa-bangsa, dan kepada-Nyalah bangsa-bangsa akan menaruh harapan.” — Roma 15:12\n\nSave kartu nama ini untuk menemanimu selama masa Adven 🔖"},
]

# ---------- RAMBU: tiga rambu jalan (pagi2 hari 2, 3, 5, 6) ----------
RAMBU = [
    {"rambu": [["stop", "GENGSI", "Berhenti berebut kursi terdepan"], ["larangan", "MINTA DILAYANI", "Bukan cara warga Kerajaan"], ["petunjuk", "JALUR PELAYAN", "Rute yang dilalui Sang Raja"]],
     "ayat": "“Tidaklah demikian di antara kamu. Barangsiapa ingin menjadi besar di antara kamu, hendaklah ia menjadi pelayanmu,”",
     "ref": "Markus 10:43",
     "caption": "Rambu lalu lintas untuk hari Senin 🚦\n\nYakobus dan Yohanes meminta kursi terhormat di kiri dan kanan Yesus dalam kemuliaan-Nya. Sepuluh murid yang lain marah. Yesus lalu menjelaskan: penguasa dunia memerintah dengan tangan besi, tetapi di antara murid-murid-Nya tidak boleh begitu. Jalan menuju kebesaran dalam Kerajaan-Nya adalah jalur pelayan, jalan yang lebih dulu dilalui Sang Raja sendiri.\n\n📖 “Tidaklah demikian di antara kamu. Barangsiapa ingin menjadi besar di antara kamu, hendaklah ia menjadi pelayanmu,” — Markus 10:43\n\nSave rambu ini untuk dibaca lagi saat gengsi mulai naik 🔖"},
    {"rambu": [["peringatan", "GUNCANGAN", "Dunia sedang tidak stabil"], ["larangan", "PANIK", "Jangan biarkan berita menyetirmu"], ["petunjuk", "KERAJAAN TETAP", "Pegang yang tak tergoncangkan"]],
     "ayat": "“…menunjuk kepada perubahan pada apa yang dapat digoncangkan, karena ia dijadikan supaya tinggal tetap apa yang tidak tergoncangkan.”",
     "ref": "Ibrani 12:27",
     "caption": "Rambu untuk hari yang goyah 🚦\n\nPenulis Ibrani mengingatkan bahwa suara Allah pernah menggoncangkan bumi di Sinai, dan Ia berjanji akan menggoncangkan sekali lagi, bukan hanya bumi tetapi juga langit. Semua yang dapat digoncangkan akan berlalu. Yang tinggal tetap adalah apa yang tidak tergoncangkan, dan itulah kerajaan yang kita terima di dalam Kristus.\n\n📖 “…menunjuk kepada perubahan pada apa yang dapat digoncangkan, karena ia dijadikan supaya tinggal tetap apa yang tidak tergoncangkan.” — Ibrani 12:27\n\nKirim rambu ini ke teman yang hidupnya sedang terguncang 💌"},
    {"rambu": [["peringatan", "AWAS NGANTUK", "Jangan lengah di jalan iman"], ["stop", "TUNDA-TUNDA", "Setia hari ini, bukan nanti"], ["petunjuk", "TETAP BERJAGA", "Pelita menyala sampai Ia datang"]],
     "ayat": "“Karena itu, berjaga-jagalah, sebab kamu tidak tahu akan hari maupun akan saatnya.”",
     "ref": "Matius 25:13",
     "caption": "Rambu untuk perjalanan panjang 🚦\n\nYesus menutup perumpamaan tentang sepuluh gadis dengan kalimat ini. Kelima gadis yang bijaksana tidak lebih kuat menahan kantuk, karena kesepuluhnya mengantuk lalu tertidur. Bedanya, mereka sudah membawa minyak. Berjaga-jaga bukan berarti tidak pernah lelah, tetapi hidup siap: setia hari ini sambil menantikan Mempelai itu datang.\n\n📖 “Karena itu, berjaga-jagalah, sebab kamu tidak tahu akan hari maupun akan saatnya.” — Matius 25:13\n\nKirim rambu ini ke teman yang sedang lelah menunggu 💌"},
    {"rambu": [["peringatan", "JALAN BERLIKU", "Siap-siap diluruskan"], ["stop", "BALIK ARAH", "Bertobat: berbalik kepada Tuhan"], ["petunjuk", "JALAN RATA", "Menuju keselamatan dari Tuhan"]],
     "ayat": "“Setiap lembah akan ditimbun dan setiap gunung dan bukit akan menjadi rata, yang berliku-liku akan diluruskan…”",
     "ref": "Lukas 3:5",
     "caption": "Rambu proyek jalan Tuhan 🚦\n\nDi zaman kuno, sebelum seorang raja berkunjung, jalan yang akan dilaluinya diperbaiki: lubang ditimbun, tikungan diluruskan. Lukas mengutip nubuat Yesaya ini untuk menggambarkan pelayanan Yohanes Pembaptis yang menyerukan pertobatan. Ada bagian hidup yang perlu diangkat, ada kesombongan yang perlu diratakan, ada yang bengkok yang perlu diluruskan. Kabar baiknya, kita tidak mengerjakannya sendirian.\n\n📖 “Setiap lembah akan ditimbun dan setiap gunung dan bukit akan menjadi rata, yang berliku-liku akan diluruskan…” — Lukas 3:5\n\nSave rambu ini untuk masa persiapan Natal 🔖"},
]

# ---------- RESEP: kartu resep tulisan tangan (siang0 10:30) ----------
RESEP = [
    {"judul": "Resep Menyembah Sang Raja",
     "porsi": "satu jemaat",
     "waktu": "seumur hidup",
     "bahan": ["1 hati yang mau berlutut", "rasa kagum akan kekudusan-Nya", "lagu pujian, dinyanyikan sungguh", "teman seiman di bangku sebelah"],
     "langkah": ["Datang lebih awal, matikan notifikasi, tenangkan hati", "Tinggikan nama-Nya: bernyanyi, berdoa, dengarkan firman-Nya", "Bawa ibadahnya pulang sampai hari Senin, jangan ditinggal di gedung"],
     "ayat": "“Tinggikanlah TUHAN, Allah kita, dan sujudlah menyembah kepada tumpuan kaki-Nya! Kuduslah Ia!”",
     "ref": "Mazmur 99:5",
     "caption": "Resep untuk ibadah hari ini 🍳\n\nMazmur 99 dibuka dengan seruan: TUHAN itu Raja. Lalu berulang kali pemazmur mengingatkan bahwa Ia kudus. Menyembah Raja yang kudus bukan soal suasana yang pas atau musik yang bagus. Intinya adalah hati yang tunduk dan kagum kepada-Nya. Selamat beribadah di Minggu Kristus Raja.\n\n📖 “Tinggikanlah TUHAN, Allah kita, dan sujudlah menyembah kepada tumpuan kaki-Nya! Kuduslah Ia!” — Mazmur 99:5\n\nTulis di komentar satu lagu yang menolongmu menyembah Sang Raja 👇"},
    {"judul": "Resep Saling Membasuh Kaki",
     "porsi": "satu meja penuh",
     "waktu": "setiap hari",
     "bahan": ["1 baskom air hangat", "1 kain lenan, diikat di pinggang", "segenggam rendah hati", "kasih yang tidak pilih-pilih"],
     "langkah": ["Tanggalkan jubah gengsi, lalu berlutut", "Basuh kaki siapa saja di meja, termasuk yang pernah mengecewakanmu", "Ulangi besok, tanpa menunggu dipuji"],
     "ayat": "“Jadi jikalau Aku membasuh kakimu, Aku yang adalah Tuhan dan Gurumu, maka kamupun wajib saling membasuh kakimu;”",
     "ref": "Yohanes 13:14",
     "caption": "Resep dari ruang perjamuan 🍳\n\nMembasuh kaki tamu biasanya pekerjaan pelayan. Tapi malam itu Yesus sendiri bangun, mengikatkan kain lenan di pinggang-Nya, lalu membasuh kaki murid-murid-Nya satu per satu, termasuk Yudas yang Ia tahu akan menyerahkan-Nya. Sesudah itu Ia berkata: lakukanlah juga seperti itu. Resep ini mudah dibaca, tapi butuh seumur hidup untuk dipraktikkan.\n\n📖 “Jadi jikalau Aku membasuh kakimu, Aku yang adalah Tuhan dan Gurumu, maka kamupun wajib saling membasuh kakimu;” — Yohanes 13:14\n\nTag teman yang sering diam-diam melayani tanpa minta dipuji 👇"},
    {"judul": "Resep Hati yang Tidak Goyah",
     "porsi": "satu jiwa yang cemas",
     "waktu": "setiap pagi",
     "bahan": ["1 cangkir percaya kepada TUHAN", "2 sendok doa, diaduk pelan-pelan", "berita secukupnya saja", "segenggam ingatan akan janji-Nya"],
     "langkah": ["Seduh rasa percaya sebelum membuka media sosial", "Aduk dengan doa: serahkan yang tidak bisa kamu kendalikan", "Sajikan dengan tenang, sebab gunung Sion tidak goyang"],
     "ayat": "“Orang-orang yang percaya kepada TUHAN adalah seperti gunung Sion yang tidak goyang, yang tetap untuk selama-lamanya.”",
     "ref": "Mazmur 125:1",
     "caption": "Resep untuk hari Selasa 🍳\n\nMazmur 125 termasuk nyanyian ziarah, lagu yang dinyanyikan dalam perjalanan naik ke Yerusalem. Kota itu dikelilingi gunung-gunung. Pemazmur berkata, orang yang percaya kepada TUHAN seperti gunung Sion: tidak goyang. Kekuatannya bukan dari diri sendiri, tetapi dari TUHAN yang mengelilingi umat-Nya, seperti gunung-gunung mengelilingi Yerusalem.\n\n📖 “Orang-orang yang percaya kepada TUHAN adalah seperti gunung Sion yang tidak goyang, yang tetap untuk selama-lamanya.” — Mazmur 125:1\n\nTulis 🏔️ di komentar kalau hari ini kamu mau berdiri teguh bersama-Nya."},
    {"judul": "Resep Kerajaan Allah",
     "porsi": "seluruh jemaat",
     "waktu": "hari ini juga",
     "bahan": ["secangkir kebenaran", "damai sejahtera, takaran besar", "sukacita dari Roh Kudus", "0 gram ribut soal menu"],
     "langkah": ["Jangan bertengkar soal makanan, terima dulu saudaramu", "Kejar apa yang mendatangkan damai dan saling membangun", "Sajikan dengan sukacita yang dikerjakan Roh Kudus"],
     "ayat": "“Sebab Kerajaan Allah bukanlah soal makanan dan minuman, tetapi soal kebenaran, damai sejahtera dan sukacita oleh Roh Kudus.”",
     "ref": "Roma 14:17",
     "caption": "Resep yang ternyata bukan soal makanan 🍳\n\nJemaat di Roma sempat terpecah karena urusan makanan: ada yang yakin boleh makan segala jenis makanan, ada yang hanya makan sayur-sayuran. Paulus mengingatkan mereka bahwa warga Kerajaan Allah tidak diukur dari isi piring. Yang menandai Kerajaan-Nya adalah kebenaran, damai sejahtera, dan sukacita oleh Roh Kudus. Jadi, kejarlah apa yang mendatangkan damai.\n\n📖 “Sebab Kerajaan Allah bukanlah soal makanan dan minuman, tetapi soal kebenaran, damai sejahtera dan sukacita oleh Roh Kudus.” — Roma 14:17\n\nTulis di komentar bahan mana yang paling kamu butuhkan hari ini 👇"},
    {"judul": "Resep Pelita yang Menyala",
     "porsi": "satu malam panjang",
     "waktu": "sampai pagi",
     "bahan": ["1 pelita, sumbu dipangkas rapi", "minyak cadangan secukupnya", "ikat pinggang, sudah terpasang", "telinga yang peka pada ketukan"],
     "langkah": ["Isi minyak lewat doa dan firman setiap hari", "Kerjakan tugasmu dengan setia, jangan menunggu sambil tertidur", "Begitu terdengar ketukan, segera buka pintu"],
     "ayat": "“Hendaklah pinggangmu tetap berikat dan pelitamu tetap menyala.”",
     "ref": "Lukas 12:35",
     "caption": "Resep untuk masa penantian 🍳\n\nPada zaman Yesus, orang mengenakan jubah panjang. Untuk bekerja atau berlari, ujung jubah diikatkan di pinggang. Pelita yang tetap menyala berarti siap kapan saja, bahkan di tengah malam. Yesus memakai gambaran ini untuk murid-murid-Nya: hidup siap, seperti hamba yang menanti tuannya pulang dari perkawinan, supaya pintu segera dibuka saat ia mengetok.\n\n📖 “Hendaklah pinggangmu tetap berikat dan pelitamu tetap menyala.” — Lukas 12:35\n\nTulis di komentar satu kebiasaan kecil yang menjaga pelitamu tetap menyala 👇"},
    {"judul": "Resep Buah Pertobatan",
     "porsi": "untuk tetangga juga",
     "waktu": "mulai hari ini",
     "bahan": ["2 helai baju (1 untuk dibagi)", "makanan untuk dibagi", "tangan yang tidak menagih lebih", "hati yang cukup dengan gaji"],
     "langkah": ["Tanya dengan jujur: apa yang harus aku perbuat?", "Bagikan yang kamu punya kepada yang tidak punya", "Bekerja dengan jujur, jangan memeras dan jangan merampas"],
     "ayat": "“…Barangsiapa mempunyai dua helai baju, hendaklah ia membaginya dengan yang tidak punya…”",
     "ref": "Lukas 3:11",
     "caption": "Resep dari Yohanes Pembaptis 🍳\n\nSetelah mendengar seruan Yohanes untuk bertobat, orang banyak bertanya: apa yang harus kami perbuat? Jawabannya sangat praktis. Kepada orang banyak: berbagilah. Kepada pemungut cukai: jangan menagih lebih. Kepada prajurit: jangan merampas dan jangan memeras. Pertobatan tidak berhenti di perasaan. Buahnya terlihat di lemari baju, di dapur, dan di tempat kerja.\n\n📖 “…Barangsiapa mempunyai dua helai baju, hendaklah ia membaginya dengan yang tidak punya…” — Lukas 3:11\n\nTulis di komentar satu “buah” kecil yang mau kamu bagikan minggu ini 👇"},
    {"judul": "Resep Berharap Lagi",
     "porsi": "satu hati yang lelah",
     "waktu": "tiap pagi",
     "bahan": ["1 ingatan akan kasih setia-Nya", "rahmat-Nya yang baru tiap pagi", "air mata, boleh, tidak dilarang", "1 kata kecil: tetapi"],
     "langkah": ["Akui dulu dengan jujur apa yang membuatmu sedih", "Tambahkan kata ‘tetapi’, lalu ingat kesetiaan-Nya", "Diamkan semalam. Besok pagi, rahmat-Nya baru lagi"],
     "ayat": "“Tetapi hal-hal inilah yang kuperhatikan, oleh sebab itu aku akan berharap:”",
     "ref": "Ratapan 3:21",
     "caption": "Resep dari kitab yang penuh air mata 🍳\n\nPenulis Ratapan tidak menutupi rasa sakitnya. Ia menulis tentang kota yang hancur, malam-malam yang pahit, dan doa yang terasa tidak didengar. Lalu muncul satu kata kecil yang mengubah arah: tetapi. Ia sengaja mengarahkan pikirannya kepada kasih setia TUHAN yang tidak berkesudahan. Pengharapan tidak lahir dari menyangkal rasa sakit, tetapi dari mengingat siapa Allah.\n\n📖 “Tetapi hal-hal inilah yang kuperhatikan, oleh sebab itu aku akan berharap:” — Ratapan 3:21\n\nTulis 🕯️ di komentar kalau hari ini kamu sedang belajar berharap lagi."},
]

# ---------- UNDANGAN: kartu undangan dengan segel lilin (siang 12:00) ----------
UNDANGAN = [
    {"judul": "Perjamuan Kawin Putra Raja",
     "untuk": "Kamu, yang diundang",
     "acara": [["Pengundang", "Sang Raja"], ["Acara", "perjamuan kawin Anak-Nya"], ["Hidangan", "semuanya telah tersedia"]],
     "ayat": "“…hidangan, telah kusediakan… semuanya telah tersedia, datanglah ke perjamuan kawin ini.”",
     "ref": "Matius 22:4",
     "caption": "Undangan dari Sang Raja ✉️\n\nDalam perumpamaan Yesus, Kerajaan Sorga seumpama seorang raja yang mengadakan perjamuan kawin untuk anaknya. Ketika orang-orang yang diundang tidak mau datang, raja itu tidak membatalkan pesta. Ia mengutus hamba-hamba lain dengan pesan yang sama: semuanya telah tersedia. Kita tidak diminta membawa hidangan. Kita hanya diminta datang.\n\n📖 “…hidangan, telah kusediakan… semuanya telah tersedia, datanglah ke perjamuan kawin ini.” — Matius 22:4\n\nKetik “Aku datang” kalau hari ini kamu mau menyambut undangan Sang Raja 👑"},
    {"judul": "Perjamuan di Rumah Sang Tuan",
     "untuk": "Hamba-hamba yang berjaga",
     "acara": [["Tuan rumah", "Ia sendiri yang melayani"], ["Waktu", "saat Ia datang"], ["Persiapan", "tetap berjaga-jaga"]],
     "ayat": "“…Sesungguhnya ia akan mengikat pinggangnya dan mempersilakan mereka duduk makan, dan ia akan datang melayani mereka.”",
     "ref": "Lukas 12:37",
     "caption": "Undangan yang terbalik ✉️\n\nDi zaman Yesus, hamba yang melayani tuannya makan, bukan sebaliknya. Tapi dalam perumpamaan ini Yesus menggambarkan seorang tuan yang pulang, mendapati hamba-hambanya berjaga, lalu mengikat pinggangnya, mempersilakan mereka duduk, dan melayani mereka. Raja kita bukan hanya pernah melayani di bumi. Ia menggambarkan perjamuan-Nya kelak sebagai tempat di mana Ia sendiri melayani umat-Nya.\n\n📖 “…Sesungguhnya ia akan mengikat pinggangnya dan mempersilakan mereka duduk makan, dan ia akan datang melayani mereka.” — Lukas 12:37\n\nKirim undangan ini ke teman yang sedang lelah melayani 💌"},
    {"judul": "Perjamuan Kerajaan Sorga",
     "untuk": "Tamu dari segala penjuru",
     "acara": [["Tempat", "Kerajaan Sorga"], ["Teman meja", "Abraham, Ishak, Yakub"], ["Masa acara", "tidak berkesudahan"]],
     "ayat": "“…Banyak orang akan datang dari Timur dan Barat dan duduk makan bersama-sama dengan Abraham, Ishak dan Yakub di dalam Kerajaan Sorga,”",
     "ref": "Matius 8:11",
     "caption": "Undangan dari Kerajaan yang tidak runtuh ✉️\n\nYesus mengucapkan kalimat ini setelah heran melihat iman seorang perwira, orang bukan Israel, yang percaya bahwa satu perkataan Yesus cukup untuk menyembuhkan hambanya. Kerajaan Sorga ternyata lebih luas dari dugaan banyak orang. Kursi di meja-Nya tidak didapat lewat keturunan, tetapi lewat iman kepada Sang Raja. Dan perjamuan itu tidak akan pernah dibubarkan.\n\n📖 “…Banyak orang akan datang dari Timur dan Barat dan duduk makan bersama-sama dengan Abraham, Ishak dan Yakub di dalam Kerajaan Sorga,” — Matius 8:11\n\nKetik “Aku diundang” kalau kamu bersyukur ada tempat bagimu di meja-Nya 🤍"},
    {"judul": "Undangan Makan Bersama",
     "untuk": "Yang jarang diundang",
     "acara": [["Tuan rumah", "kamu, warga Kerajaan"], ["Tamu", "yang tak bisa membalas"], ["Menu", "berbagi apa adanya"]],
     "ayat": "“Tetapi apabila engkau mengadakan perjamuan, undanglah orang-orang miskin, orang-orang cacat, orang-orang lumpuh dan orang-orang buta.”",
     "ref": "Lukas 14:13",
     "caption": "Undangan yang ditulis dengan cara Kerajaan ✉️\n\nYesus sedang makan di rumah seorang pemimpin Farisi. Ia melihat tamu-tamu berusaha menduduki tempat kehormatan, lalu memberi nasihat kepada tuan rumah: jangan hanya mengundang sahabat dan tetangga kaya yang bisa membalas. Warga Kerajaan Allah membuka meja bagi orang yang sering dilupakan, karena Raja mereka lebih dulu membuka meja bagi kita.\n\n📖 “Tetapi apabila engkau mengadakan perjamuan, undanglah orang-orang miskin, orang-orang cacat, orang-orang lumpuh dan orang-orang buta.” — Lukas 14:13\n\nSiapa satu orang yang bisa kamu ajak makan minggu ini? Tulis inisialnya di komentar 👇"},
    {"judul": "Hari Perkawinan Anak Domba",
     "untuk": "Pengantin-Nya, umat-Nya",
     "acara": [["Mempelai", "Anak Domba Allah"], ["Waktu", "pada hari yang ditetapkan-Nya"], ["Busana", "lenan halus, dari-Nya"]],
     "ayat": "“Marilah kita bersukacita dan bersorak-sorai, dan memuliakan Dia! Karena hari perkawinan Anak Domba telah tiba…”",
     "ref": "Wahyu 19:7",
     "caption": "Undangan untuk yang sedang menanti ✉️\n\nKitab Wahyu menggambarkan akhir penantian panjang umat Allah sebagai sebuah pesta perkawinan. Anak Domba adalah mempelainya, dan umat-Nya adalah pengantin. Yang indah, pakaian pengantin itu tidak dibeli sendiri. Kain lenan halus itu dikaruniakan kepadanya. Hari ini kita masih menanti, tetapi undangannya sudah pasti.\n\n📖 “Marilah kita bersukacita dan bersorak-sorai, dan memuliakan Dia! Karena hari perkawinan Anak Domba telah tiba…” — Wahyu 19:7\n\nKetik “Aku menanti” kalau kamu merindukan hari itu 🤍"},
    {"judul": "Perjamuan di Rumah Lewi",
     "untuk": "Yang merasa tak layak",
     "acara": [["Tuan rumah", "Lewi, mantan pemungut cukai"], ["Tamu utama", "Yesus dari Nazaret"], ["Panggilan", "datang dan bertobat"]],
     "ayat": "“Aku datang bukan untuk memanggil orang benar, tetapi orang berdosa, supaya mereka bertobat.”",
     "ref": "Lukas 5:32",
     "caption": "Undangan dari meja makan yang dikritik ✉️\n\nLewi adalah pemungut cukai, pekerjaan yang dibenci banyak orang sebangsanya. Setelah Yesus memanggilnya, ia meninggalkan meja cukainya dan mengadakan perjamuan besar. Tamunya? Pemungut cukai dan orang-orang lain yang dicap berdosa. Orang Farisi bersungut-sungut, tapi Yesus menjawab bahwa justru untuk merekalah Ia datang. Pertobatan dimulai dari menerima undangan-Nya.\n\n📖 “Aku datang bukan untuk memanggil orang benar, tetapi orang berdosa, supaya mereka bertobat.” — Lukas 5:32\n\nKetik “Aku juga dipanggil” kalau kamu bersyukur Yesus memanggil orang seperti kita 🤍"},
    {"judul": "Perjamuan Kawin Anak Domba",
     "untuk": "Yang diundang-Nya",
     "acara": [["Tuan rumah", "Anak Domba Allah"], ["Tempat", "meja perjamuan-Nya"], ["Gladi", "ibadah Minggu besok"]],
     "ayat": "“…Tuliskanlah: Berbahagialah mereka yang diundang ke perjamuan kawin Anak Domba…”",
     "ref": "Wahyu 19:9",
     "caption": "Undangan untuk besok dan selamanya ✉️\n\nMasa Adven bukan hanya mengenang kedatangan Yesus yang pertama di Betlehem. Adven juga menantikan kedatangan-Nya yang kedua. Kitab Wahyu menggambarkan akhir penantian itu sebagai perjamuan kawin Anak Domba. Setiap kali umat-Nya berkumpul untuk beribadah, kita mencicipi sedikit dari sukacita perjamuan itu. Besok, datanglah.\n\n📖 “…Tuliskanlah: Berbahagialah mereka yang diundang ke perjamuan kawin Anak Domba…” — Wahyu 19:9\n\nAjak satu teman ke ibadah Minggu Adven besok, lalu tag dia di komentar 👇"},
]

# ---------- PROGRESS: Reel bilah progres instalasi (siang2 13:30) ----------
PROGRESS = [
    {"judul": "Mengatur ulang: takhta hati",
     "langkah": ["Memindai siapa yang bertakhta…", "Menurunkan ego dari takhta…", "Bertekuk lutut di hadapan Yesus…", "Mengaku: Yesus Kristus adalah Tuhan"],
     "selesai": "Selesai: Yesus bertakhta di hatiku",
     "ayat": "“…dalam nama Yesus bertekuk lutut segala yang ada di langit dan yang ada di atas bumi… dan segala lidah mengaku: ‘Yesus Kristus adalah Tuhan,’ bagi kemuliaan Allah, Bapa!”",
     "ref": "Filipi 2:10-11",
     "caption": "Pembaruan sistem hari Minggu ⏳\n\nPaulus menulis bahwa Yesus, yang merendahkan diri sampai mati di kayu salib, telah ditinggikan oleh Allah. Suatu hari setiap lutut akan bertekuk dan setiap lidah akan mengaku bahwa Yesus Kristus adalah Tuhan. Kita tidak menjadikan Yesus Raja. Ia sudah Raja. Yang perlu diatur ulang adalah hati kita, yang sering duduk di takhta yang bukan miliknya.\n\n📖 “…dalam nama Yesus bertekuk lutut segala yang ada di langit dan yang ada di atas bumi… dan segala lidah mengaku: ‘Yesus Kristus adalah Tuhan,’ bagi kemuliaan Allah, Bapa!” — Filipi 2:10-11\n\nKetik “Yesus Tuhan” kalau hari ini kamu mau mengakuinya bersama kami 👑"},
    {"judul": "Memasang: hati pelayan",
     "langkah": ["Menghapus file: aku harus nomor satu", "Mengunduh pikiran Kristus…", "Mengganti gengsi dengan kasih…", "Memasang celemek pelayan…"],
     "selesai": "Terpasang. Siap melayani hari ini",
     "ayat": "“Hendaklah kamu dalam hidupmu bersama, menaruh pikiran dan perasaan yang terdapat juga dalam Kristus Yesus,”",
     "ref": "Filipi 2:5",
     "caption": "Pembaruan untuk hari Senin ⏳\n\nSebelum menulis tentang Yesus yang mengosongkan diri dan mengambil rupa seorang hamba, Paulus lebih dulu meminta jemaat Filipi untuk tidak hanya memperhatikan kepentingan sendiri, tetapi kepentingan orang lain juga. Pikiran dan perasaan Kristus tidak terpasang dalam sekejap. Roh Kudus mengerjakannya pelan-pelan, hari demi hari, dalam hidup bersama.\n\n📖 “Hendaklah kamu dalam hidupmu bersama, menaruh pikiran dan perasaan yang terdapat juga dalam Kristus Yesus,” — Filipi 2:5\n\nKetik “Pasang di hatiku” kalau kamu mau mendoakannya hari ini 🤍"},
    {"judul": "Memperbarui: cara pandang",
     "langkah": ["Membaca berita yang bikin cemas…", "Mengingat siapa yang bertakhta…", "Menyerahkan yang tak bisa kuatur…", "Berpegang pada kerajaan-Nya…"],
     "selesai": "Pembaruan selesai. Hati lebih tenang",
     "ayat": "“…Allah semesta langit akan mendirikan suatu kerajaan yang tidak akan binasa sampai selama-lamanya… tetapi kerajaan itu sendiri akan tetap untuk selama-lamanya,”",
     "ref": "Daniel 2:44",
     "caption": "Pembaruan untuk hari Selasa ⏳\n\nRaja Nebukadnezar bermimpi tentang patung besar dari emas, perak, tembaga, besi, dan tanah liat. Daniel menafsirkannya sebagai kerajaan-kerajaan dunia yang datang silih berganti. Lalu sebuah batu, terungkit lepas tanpa perbuatan tangan manusia, menghancurkan patung itu dan menjadi gunung besar. Itulah kerajaan dari Allah semesta langit. Kerajaan dunia berganti-ganti, kerajaan-Nya tetap.\n\n📖 “…Allah semesta langit akan mendirikan suatu kerajaan yang tidak akan binasa sampai selama-lamanya… tetapi kerajaan itu sendiri akan tetap untuk selama-lamanya,” — Daniel 2:44\n\nKetik “Kerajaan-Nya tetap” kalau kamu mau mengingatnya hari ini 👑"},
    {"judul": "Memasang: hidup warga-Nya",
     "langkah": ["Berlaku adil di meja kerja…", "Mencintai kesetiaan di rumah…", "Rendah hati di hadapan Allah…", "Mengulang besok, dengan anugerah…"],
     "selesai": "Terpasang: warga Kerajaan, hari ini",
     "ayat": "“…apakah yang dituntut TUHAN dari padamu: selain berlaku adil, mencintai kesetiaan, dan hidup dengan rendah hati di hadapan Allahmu?”",
     "ref": "Mikha 6:8",
     "caption": "Pembaruan untuk hari Rabu ⏳\n\nUmat bertanya: dengan apa aku harus menghadap TUHAN? Ribuan domba jantan? Puluhan ribu curahan minyak? Lewat Mikha, jawabannya lebih sederhana sekaligus lebih dalam: berlaku adil, mencintai kesetiaan, dan hidup dengan rendah hati di hadapan Allah. Kita tidak memasang ini supaya diterima Allah. Di dalam Kristus kita sudah diterima, dan inilah cara hidup warga Kerajaan-Nya.\n\n📖 “…apakah yang dituntut TUHAN dari padamu: selain berlaku adil, mencintai kesetiaan, dan hidup dengan rendah hati di hadapan Allahmu?” — Mikha 6:8\n\nKetik “Adil, setia, rendah hati” kalau kamu mau mendoakannya hari ini 🤍"},
    {"judul": "Menanam: kesabaran",
     "langkah": ["Menabur benih di tanah…", "Menunggu hujan musim gugur…", "Tetap merawat walau belum tumbuh…", "Menunggu hujan musim semi…"],
     "selesai": "Bersabarlah. Ia sudah dekat",
     "ayat": "“…bersabarlah sampai kepada kedatangan Tuhan! Sesungguhnya petani menantikan hasil yang berharga dari tanahnya… Kamu juga harus bersabar dan harus meneguhkan hatimu…”",
     "ref": "Yakobus 5:7-8",
     "caption": "Progres yang tidak bisa dipercepat ⏳\n\nPetani di tanah Israel bergantung pada dua musim hujan: hujan musim gugur saat menabur dan hujan musim semi menjelang panen. Ia tidak bisa mempercepat datangnya hujan, tetapi ia juga tidak meninggalkan ladangnya. Begitulah Yakobus menggambarkan penantian kita akan kedatangan Tuhan: sabar, teguh hati, dan tetap setia merawat apa yang dipercayakan kepada kita.\n\n📖 “…bersabarlah sampai kepada kedatangan Tuhan! Sesungguhnya petani menantikan hasil yang berharga dari tanahnya… Kamu juga harus bersabar dan harus meneguhkan hatimu…” — Yakobus 5:7-8\n\nKetik “Sabar dan teguh” kalau kamu sedang belajar menunggu 🌱"},
    {"judul": "Memproses: pertobatan",
     "langkah": ["Menyadari dosa yang disimpan…", "Mengaku dengan jujur kepada-Nya…", "Berbalik, kembali kepada Tuhan…", "Dosa dihapuskan oleh-Nya…"],
     "selesai": "Selesai: waktu kelegaan dari Tuhan",
     "ayat": "“Karena itu sadarlah dan bertobatlah, supaya dosamu dihapuskan, agar Tuhan mendatangkan waktu kelegaan, dan mengutus Yesus, yang dari semula diuntukkan bagimu sebagai Kristus.”",
     "ref": "Kisah Para Rasul 3:19-20",
     "caption": "Proses yang selalu layak dijalani ⏳\n\nPetrus mengucapkan kalimat ini di Serambi Salomo, setelah seorang yang lumpuh sejak lahir disembuhkan. Ia berbicara kepada orang-orang yang ikut menyangkal Yesus. Tapi pintu tidak ditutup bagi mereka. Bertobat berarti berbalik, dan di ujung proses itu bukan hukuman, melainkan dosa yang dihapuskan dan waktu kelegaan dari Tuhan.\n\n📖 “Karena itu sadarlah dan bertobatlah, supaya dosamu dihapuskan, agar Tuhan mendatangkan waktu kelegaan, dan mengutus Yesus, yang dari semula diuntukkan bagimu sebagai Kristus.” — Kisah Para Rasul 3:19-20\n\nKetik “Aku berbalik” kalau hari ini kamu mau kembali kepada-Nya 🤍"},
    {"judul": "Menyiapkan: Minggu Adven I",
     "langkah": ["Menyetel alarm untuk ibadah besok…", "Menyiapkan hati lewat doa…", "Mengajak satu teman…", "Lilin pertama: pengharapan…"],
     "selesai": "Siap menyambut Minggu Adven",
     "ayat": "“dengan menantikan penggenapan pengharapan kita yang penuh bahagia dan penyataan kemuliaan Allah yang Mahabesar dan Juruselamat kita Yesus Kristus,”",
     "ref": "Titus 2:13",
     "caption": "Persiapan terakhir sebelum Adven ⏳\n\nPaulus menulis kepada Titus bahwa kasih karunia Allah yang menyelamatkan sudah nyata. Kasih karunia itu juga mendidik kita untuk hidup bijaksana di dunia sekarang ini, sambil menantikan penggenapan pengharapan yang penuh bahagia: penyataan kemuliaan Yesus Kristus. Itulah inti masa Adven. Kita hidup di antara dua kedatangan-Nya.\n\n📖 “dengan menantikan penggenapan pengharapan kita yang penuh bahagia dan penyataan kemuliaan Allah yang Mahabesar dan Juruselamat kita Yesus Kristus,” — Titus 2:13\n\nKetik “Siap Adven” kalau besok kamu mau beribadah 🕯️"},
]

# ---------- GLOBE: bola salju, hitung mundur Natal (sore 15:00) ----------
GLOBE = [
    {"angka": 33,
     "tanggal": "Minggu, 22 November",
     "teks": "Bayi di palungan itu adalah Raja yang kerajaan-Nya tak berkesudahan.",
     "ayat": "“dan Ia akan menjadi raja atas kaum keturunan Yakub sampai selama-lamanya dan Kerajaan-Nya tidak akan berkesudahan.”",
     "ref": "Lukas 1:33",
     "caption": "33 hari lagi 🎄\n\nSaat malaikat Gabriel menemui Maria, kabar yang dibawanya bukan hanya tentang seorang bayi. Anak itu akan menerima takhta Daud, bapa leluhur-Nya, dan memerintah selama-lamanya. Di Minggu Kristus Raja ini, kita diingatkan bahwa Natal adalah kelahiran seorang Raja, Raja yang Kerajaan-Nya tidak akan berkesudahan.\n\n📖 “dan Ia akan menjadi raja atas kaum keturunan Yakub sampai selama-lamanya dan Kerajaan-Nya tidak akan berkesudahan.” — Lukas 1:33\n\nKetik 🎄 kalau kamu ikut menghitung mundur bersama kami."},
    {"angka": 32,
     "tanggal": "Senin, 23 November",
     "teks": "Raja yang dibaringkan di palungan membalik ukuran besar dan kecil.",
     "ayat": "“Ia menurunkan orang-orang yang berkuasa dari takhtanya dan meninggikan orang-orang yang rendah;”",
     "ref": "Lukas 1:52",
     "caption": "32 hari lagi 🎄\n\nMaria, seorang gadis muda dari kota kecil Nazaret, menyanyikan nyanyian ini saat mengandung Yesus. Ia melihat cara Allah bekerja: yang berkuasa diturunkan, yang rendah ditinggikan. Natal tidak dimulai di istana, tetapi di tengah orang-orang sederhana. Raja kita datang dari bawah, untuk melayani.\n\n📖 “Ia menurunkan orang-orang yang berkuasa dari takhtanya dan meninggikan orang-orang yang rendah;” — Lukas 1:52\n\nKetik 🎄 kalau kamu ikut menghitung mundur bersama kami."},
    {"angka": 31,
     "tanggal": "Selasa, 24 November",
     "teks": "Anak yang lahir di Betlehem membawa damai yang tidak berkesudahan.",
     "ayat": "“Besar kekuasaannya, dan damai sejahtera tidak akan berkesudahan di atas takhta Daud dan di dalam kerajaannya…”",
     "ref": "Yesaya 9:6",
     "caption": "31 hari lagi 🎄\n\nNubuat Yesaya tentang seorang anak yang lahir untuk kita sering dibacakan saat Natal. Ayat ini melanjutkannya: kekuasaan anak itu besar, damai sejahteranya tidak berkesudahan, dan kerajaannya dikokohkan dengan keadilan dan kebenaran sampai selama-lamanya. Saat dunia terasa goyah, Natal mengingatkan kita bahwa ada takhta yang tidak bisa digoyahkan.\n\n📖 “Besar kekuasaannya, dan damai sejahtera tidak akan berkesudahan di atas takhta Daud dan di dalam kerajaannya…” — Yesaya 9:6\n\nKetik 🎄 kalau kamu ikut menghitung mundur bersama kami."},
    {"angka": 30,
     "tanggal": "Rabu, 25 November",
     "teks": "Kaisar mendata warganya. Raja yang sejati lahir di kota kecil.",
     "ayat": "“Pada waktu itu Kaisar Agustus mengeluarkan suatu perintah, menyuruh mendaftarkan semua orang di seluruh dunia.”",
     "ref": "Lukas 2:1",
     "caption": "30 hari lagi 🎄\n\nKaisar Agustus adalah penguasa paling berkuasa di zamannya. Cukup dengan satu perintah, seluruh kekaisaran harus mendaftarkan diri. Tapi justru perintah itu membawa Yusuf dan Maria ke Betlehem, kota yang dinubuatkan nabi Mikha sebagai tempat lahirnya seorang pemimpin bagi umat Allah. Kaisar sibuk mendata warganya. Allah sedang menggenapi janji-Nya.\n\n📖 “Pada waktu itu Kaisar Agustus mengeluarkan suatu perintah, menyuruh mendaftarkan semua orang di seluruh dunia.” — Lukas 2:1\n\nKetik 🎄 kalau kamu ikut menghitung mundur bersama kami."},
    {"angka": 29,
     "tanggal": "Kamis, 26 November",
     "teks": "Simeon setia menanti, dan Allah menepati janji-Nya.",
     "ayat": "“Adalah di Yerusalem seorang bernama Simeon. Ia seorang yang benar dan saleh yang menantikan penghiburan bagi Israel…”",
     "ref": "Lukas 2:25",
     "caption": "29 hari lagi 🎄\n\nSimeon tinggal di Yerusalem dan menantikan penghiburan bagi Israel. Roh Kudus telah menyatakan kepadanya bahwa ia tidak akan mati sebelum melihat Mesias. Ia tidak tahu kapan, tetapi ia terus menanti dengan setia. Lalu suatu hari Maria dan Yusuf membawa bayi Yesus ke Bait Allah, dan Simeon menggendong janji yang selama ini ia nantikan.\n\n📖 “Adalah di Yerusalem seorang bernama Simeon. Ia seorang yang benar dan saleh yang menantikan penghiburan bagi Israel…” — Lukas 2:25\n\nKetik 🎄 kalau kamu ikut menghitung mundur bersama kami."},
    {"angka": 28,
     "tanggal": "Jumat, 27 November",
     "teks": "Sebelum Sang Raja lahir, Allah mengutus seseorang menyiapkan jalan.",
     "ayat": "“Dan engkau, hai anakku, akan disebut nabi Allah Yang Mahatinggi; karena engkau akan berjalan mendahului Tuhan…”",
     "ref": "Lukas 1:76",
     "caption": "28 hari lagi 🎄\n\nZakharia sempat tidak dapat berbicara selama berbulan-bulan karena tidak percaya kepada kabar malaikat. Ketika anaknya lahir dan diberi nama Yohanes, mulutnya terbuka dan ia memuji Allah. Dalam nyanyiannya ia berbicara kepada bayi kecilnya: engkau akan berjalan mendahului Tuhan. Natal pertama didahului oleh persiapan. Natal kita pun begitu.\n\n📖 “Dan engkau, hai anakku, akan disebut nabi Allah Yang Mahatinggi; karena engkau akan berjalan mendahului Tuhan…” — Lukas 1:76\n\nKetik 🎄 kalau kamu ikut menghitung mundur bersama kami."},
    {"angka": 27,
     "tanggal": "Sabtu, 28 November",
     "teks": "Besok lilin Adven pertama menyala. Allah selalu menepati janji-Nya.",
     "ayat": "“Sesungguhnya, waktunya akan datang… bahwa Aku akan menepati janji… Aku akan menumbuhkan Tunas keadilan bagi Daud.”",
     "ref": "Yeremia 33:14-15",
     "caption": "27 hari lagi 🎄\n\nYeremia menerima firman ini ketika ia masih terkurung di pelataran penjagaan, sementara Yerusalem terancam tentara Babel. Di tengah masa depan yang tampak gelap, TUHAN berjanji akan menumbuhkan Tunas keadilan bagi Daud. Berabad-abad kemudian, Tunas itu lahir di Betlehem. Besok kita memasuki masa Adven, masa menantikan Allah yang selalu menepati janji-Nya.\n\n📖 “Sesungguhnya, waktunya akan datang… bahwa Aku akan menepati janji… Aku akan menumbuhkan Tunas keadilan bagi Daud.” — Yeremia 33:14-15\n\nKetik 🎄 kalau kamu ikut menghitung mundur bersama kami."},
]

# ---------- MUSEUM: lukisan di galeri dengan plakat (sore2 16:30) ----------
MUSEUM = [
    {"judul": "Anak Manusia di Atas Awan",
     "medium": "penglihatan malam di atas kanvas sejarah",
     "tahun": "zaman Babel",
     "lukisan": "kabut",
     "ayat": "“Lalu diberikan kepadanya kekuasaan dan kemuliaan dan kekuasaan sebagai raja… Kekuasaannya ialah kekuasaan yang kekal, yang tidak akan lenyap…”",
     "ref": "Daniel 7:14",
     "caption": "Di galeri hari Minggu 🖼️\n\nDaniel hidup di pembuangan, di bawah raja-raja Babel. Dalam sebuah penglihatan malam, ia melihat seorang seperti anak manusia datang dengan awan-awan dari langit, lalu menerima kerajaan yang tidak akan musnah. Yesus sering menyebut diri-Nya Anak Manusia. Kerajaan-kerajaan besar di zaman Daniel sudah lama runtuh. Kerajaan-Nya tidak.\n\n📖 “Lalu diberikan kepadanya kekuasaan dan kemuliaan dan kekuasaan sebagai raja… Kekuasaannya ialah kekuasaan yang kekal, yang tidak akan lenyap…” — Daniel 7:14\n\nSave lukisan ini untuk hari-hari ketika kuasa dunia terasa terlalu besar 🔖"},
    {"judul": "Basi dan Kain Lenan",
     "medium": "air, kain lenan, dan kasih sampai akhir",
     "tahun": "sebelum Paskah",
     "lukisan": "bintang",
     "ayat": "“Lalu bangunlah Yesus dan menanggalkan jubah-Nya… kemudian Ia menuangkan air ke dalam sebuah basi, dan mulai membasuh kaki murid-murid-Nya…”",
     "ref": "Yohanes 13:4-5",
     "caption": "Di galeri sore ini 🖼️\n\nLukisan ini tidak menampilkan mahkota atau takhta. Hanya sebuah basi berisi air dan sehelai kain lenan. Tapi di dalamnya ada potret Sang Raja yang paling jelas. Yohanes mencatat, Yesus tahu bahwa Bapa telah menyerahkan segala sesuatu kepada-Nya. Dengan kuasa sebesar itu, Ia memilih bangun, menanggalkan jubah-Nya, dan berlutut di depan kaki murid-murid-Nya.\n\n📖 “Lalu bangunlah Yesus dan menanggalkan jubah-Nya… kemudian Ia menuangkan air ke dalam sebuah basi, dan mulai membasuh kaki murid-murid-Nya…” — Yohanes 13:4-5\n\nSave lukisan ini untuk hari ketika melayani terasa berat 🔖"},
    {"judul": "Gunung di Tengah Gelora",
     "medium": "doa yang tenang di atas kanvas badai",
     "tahun": "segala zaman",
     "lukisan": "laut",
     "ayat": "“Sebab itu kita tidak akan takut, sekalipun bumi berubah, sekalipun gunung-gunung goncang di dalam laut; sekalipun ribut dan berbuih airnya…”",
     "ref": "Mazmur 46:3-4",
     "caption": "Di galeri hari Selasa 🖼️\n\nLukisan ini menggambarkan hal yang paling menakutkan bagi orang zaman dulu: gunung, lambang kekokohan, goncang dan tenggelam ke tengah laut yang bergelora. Pemazmur tidak berkata kita tidak akan takut karena badai itu tidak akan datang. Ia berkata kita tidak akan takut sekalipun semua itu terjadi, karena Allah adalah tempat perlindungan kita.\n\n📖 “Sebab itu kita tidak akan takut, sekalipun bumi berubah, sekalipun gunung-gunung goncang di dalam laut; sekalipun ribut dan berbuih airnya…” — Mazmur 46:3-4\n\nSave lukisan ini untuk hari ketika duniamu terasa runtuh 🔖"},
    {"judul": "Bukan Lagi Orang Asing",
     "medium": "kasih karunia di atas kanvas keluarga",
     "tahun": "sejak salib",
     "lukisan": "fajar",
     "ayat": "“Demikianlah kamu bukan lagi orang asing dan pendatang, melainkan kawan sewarga dari orang-orang kudus dan anggota-anggota keluarga Allah,”",
     "ref": "Efesus 2:19",
     "caption": "Di galeri hari Rabu 🖼️\n\nDi dunia kuno, orang asing dan pendatang sering hidup di pinggiran: tidak punya hak penuh, tidak punya tempat yang pasti. Paulus menulis kepada orang-orang bukan Yahudi yang dulu jauh dari umat Allah. Sekarang, di dalam Kristus, mereka bukan lagi tamu yang berdiri di luar pintu. Mereka kawan sewarga, bahkan anggota keluarga Allah.\n\n📖 “Demikianlah kamu bukan lagi orang asing dan pendatang, melainkan kawan sewarga dari orang-orang kudus dan anggota-anggota keluarga Allah,” — Efesus 2:19\n\nSave lukisan ini untuk hari ketika kamu merasa tidak punya tempat 🔖"},
    {"judul": "Pengawal Menanti Pagi",
     "medium": "penantian panjang di atas kanvas malam",
     "tahun": "sebelum fajar",
     "lukisan": "fajar",
     "ayat": "“Jiwaku mengharapkan Tuhan lebih dari pada pengawal mengharapkan pagi, lebih dari pada pengawal mengharapkan pagi.”",
     "ref": "Mazmur 130:6",
     "caption": "Di galeri hari Kamis 🖼️\n\nBayangkan seorang pengawal kota yang berjaga semalaman di atas tembok. Ia tidak bisa membuat matahari terbit lebih cepat, tetapi ia tahu pagi pasti datang. Pemazmur mengulang kalimatnya dua kali, seolah menunjukkan betapa panjangnya malam itu. Menanti Tuhan tidak selalu mudah, tetapi penantian ini punya ujung yang pasti.\n\n📖 “Jiwaku mengharapkan Tuhan lebih dari pada pengawal mengharapkan pagi, lebih dari pada pengawal mengharapkan pagi.” — Mazmur 130:6\n\nSave lukisan ini untuk malam-malam yang terasa panjang 🔖"},
    {"judul": "Suara di Padang Gurun",
     "medium": "seruan pertobatan di atas kanvas pasir",
     "tahun": "di tepi Yordan",
     "lukisan": "kabut",
     "ayat": "“Pada waktu itu tampillah Yohanes Pembaptis di padang gurun Yudea dan memberitakan: ‘Bertobatlah, sebab Kerajaan Sorga sudah dekat!’”",
     "ref": "Matius 3:1-2",
     "caption": "Di galeri hari Jumat 🖼️\n\nYohanes Pembaptis tidak berkhotbah di istana atau di Bait Allah. Ia tampil di padang gurun, memakai jubah bulu unta, dan makan belalang serta madu hutan. Pesannya singkat dan tajam: bertobatlah, sebab Kerajaan Sorga sudah dekat. Orang-orang dari Yerusalem dan seluruh Yudea datang kepadanya, mengaku dosa, dan dibaptis di sungai Yordan.\n\n📖 “Pada waktu itu tampillah Yohanes Pembaptis di padang gurun Yudea dan memberitakan: ‘Bertobatlah, sebab Kerajaan Sorga sudah dekat!’” — Matius 3:1-2\n\nSave lukisan ini sebagai pengingat di masa Adven 🔖"},
    {"judul": "Sekiranya Engkau Turun",
     "medium": "kerinduan umat di atas kanvas langit",
     "tahun": "masa penantian",
     "lukisan": "kabut",
     "ayat": "“Sekiranya Engkau mengoyakkan langit dan Engkau turun, sehingga gunung-gunung goyang di hadapan-Mu”",
     "ref": "Yesaya 64:1",
     "caption": "Di galeri menjelang Adven 🖼️\n\nLukisan ini menangkap doa umat yang lelah menunggu. Mereka merasa Allah diam dan jauh, lalu berseru: sekiranya Engkau mengoyakkan langit dan turun! Doa ini dijawab dengan cara yang tidak terduga. Allah memang turun, bukan dengan gunung-gunung yang goyang, tetapi sebagai bayi di Betlehem. Dan masa Adven mengajak kita menantikan kedatangan-Nya kembali.\n\n📖 “Sekiranya Engkau mengoyakkan langit dan Engkau turun, sehingga gunung-gunung goyang di hadapan-Mu” — Yesaya 64:1\n\nSave lukisan ini untuk menemanimu memasuki masa Adven 🔖"},
]

# ---------- KASET: kaset dengan daftar lagu mixtape (petang 18:00) ----------
KASET = [
    {"judul": "Lagu untuk Sang Raja",
     "lagu": ["Raja yang Kekal", "Takhta yang Tak Bergeser", "Bertekuk Lutut", "Hosana di Hari Minggu"],
     "ayat": "“Aku hendak mengagungkan Engkau, ya Allahku, ya Raja, dan aku hendak memuji nama-Mu untuk seterusnya dan selamanya.”",
     "ref": "Mazmur 145:1",
     "caption": "Putar ini sebelum malam tiba 📼\n\nMazmur 145 adalah puji-pujian dari Daud. Daud sendiri seorang raja, tetapi di sini ia menyapa Allah: ya Allahku, ya Raja. Raja Israel tahu bahwa takhtanya bukan yang tertinggi. Pujian yang paling jujur lahir dari hati yang tahu siapa Raja yang sesungguhnya.\n\n📖 “Aku hendak mengagungkan Engkau, ya Allahku, ya Raja, dan aku hendak memuji nama-Mu untuk seterusnya dan selamanya.” — Mazmur 145:1\n\nTulis judul lagu pujian favoritmu tentang Sang Raja di komentar 👇"},
    {"judul": "Lagu Senin Pelayan",
     "lagu": ["Celemek di Pinggang", "Merdeka untuk Melayani", "Kasih yang Turun Tangan", "Pulang Lelah, Hati Penuh"],
     "ayat": "“…kamu telah dipanggil untuk merdeka… melainkan layanilah seorang akan yang lain oleh kasih.”",
     "ref": "Galatia 5:13",
     "caption": "Mixtape untuk perjalanan pulang 📼\n\nPaulus berjuang keras supaya jemaat Galatia tidak kembali terikat pada aturan sebagai jalan untuk dibenarkan. Mereka sudah dimerdekakan oleh Kristus. Tapi merdeka tidak berarti bebas hidup semaunya. Kemerdekaan di dalam Kristus justru membuat kita bebas untuk melayani, bukan karena takut, tetapi karena kasih.\n\n📖 “…kamu telah dipanggil untuk merdeka… melainkan layanilah seorang akan yang lain oleh kasih.” — Galatia 5:13\n\nKirim mixtape ini ke teman yang hari ini pulang kerja dengan lelah 💌"},
    {"judul": "Lagu Saat Dunia Goyah",
     "lagu": ["Gunung Batuku", "Tidak Akan Goyah", "Takhta di Atas Gelombang", "Diam, Hanya pada-Nya"],
     "ayat": "“Hanya Dialah gunung batuku dan keselamatanku, kota bentengku, aku tidak akan goyah.”",
     "ref": "Mazmur 62:3",
     "caption": "Mixtape untuk hari yang goyah 📼\n\nDaud menulis mazmur ini saat orang-orang berusaha menjatuhkannya, seperti menyerbu tembok yang hendak roboh. Ia tidak berkata dirinya kuat. Ia berkata Allah adalah gunung batunya. Mazmur ini juga dibuka dengan kalimat yang dekat dengan nama akun kita: hanya dekat Allah saja aku tenang. Putar pelan-pelan, lalu diamlah di hadapan-Nya.\n\n📖 “Hanya Dialah gunung batuku dan keselamatanku, kota bentengku, aku tidak akan goyah.” — Mazmur 62:3\n\nKirim mixtape ini ke teman yang sedang goyah 💌"},
    {"judul": "Doa Warga Kerajaan",
     "lagu": ["Datanglah Kerajaan-Mu", "Di Bumi seperti di Sorga", "Roti Secukupnya", "Damai di Gang Rumahku"],
     "ayat": "“datanglah Kerajaan-Mu, jadilah kehendak-Mu di bumi seperti di sorga.”",
     "ref": "Matius 6:10",
     "caption": "Mixtape untuk sore hari Rabu 📼\n\nDoa yang diajarkan Yesus tidak meminta kita kabur dari bumi ke sorga. Doa ini justru meminta kehendak sorga terjadi di bumi: di kantor, di jalan, di rumah, dan di gang tempat kita tinggal. Setiap kali kita mendoakannya, kita juga sedang menyerahkan diri untuk ikut serta dalam kehendak-Nya.\n\n📖 “datanglah Kerajaan-Mu, jadilah kehendak-Mu di bumi seperti di sorga.” — Matius 6:10\n\nTulis di komentar: di mana kamu paling ingin melihat kehendak-Nya terjadi minggu ini 👇"},
    {"judul": "Lagu untuk Menunggu",
     "lagu": ["Apa yang Kunanti-nantikan", "Ruang Tunggu", "Pelita di Jendela", "Kepada-Mu Aku Berharap"],
     "ayat": "“Dan sekarang, apakah yang kunanti-nantikan, ya Tuhan? Kepada-Mulah aku berharap.”",
     "ref": "Mazmur 39:8",
     "caption": "Mixtape untuk ruang tunggu 📼\n\nMazmur 39 adalah doa yang jujur tentang singkatnya hidup. Pemazmur menyadari umurnya hanya beberapa telempap, dan manusia hanyalah bayangan yang berlalu. Lalu ia bertanya: kalau semua ini berlalu, apa yang sebenarnya aku nantikan? Jawabannya bukan sebuah rencana atau barang, tetapi Pribadi: kepada-Mulah aku berharap.\n\n📖 “Dan sekarang, apakah yang kunanti-nantikan, ya Tuhan? Kepada-Mulah aku berharap.” — Mazmur 39:8\n\nTulis di komentar apa yang sedang kamu nantikan dan doakan bersama Tuhan 👇"},
    {"judul": "Lagu Persiapan Jalan",
     "lagu": ["Suara di Padang Gurun", "Luruskan Jalanku", "Berbalik Pulang", "Utusan Sebelum Fajar"],
     "ayat": "“Lihat, Aku menyuruh utusan-Ku, supaya ia mempersiapkan jalan di hadapan-Ku! Dengan mendadak Tuhan yang kamu cari itu akan masuk ke bait-Nya!…”",
     "ref": "Maleakhi 3:1",
     "caption": "Mixtape dari kitab terakhir Perjanjian Lama 📼\n\nMaleakhi adalah kitab terakhir Perjanjian Lama dalam Alkitab kita. Sesudahnya, umat menunggu ratusan tahun. Lalu Injil Markus membuka kisahnya dengan mengutip janji tentang utusan yang mempersiapkan jalan ini, dan memperkenalkan Yohanes Pembaptis. Janji yang terasa sunyi selama berabad-abad akhirnya digenapi.\n\n📖 “Lihat, Aku menyuruh utusan-Ku, supaya ia mempersiapkan jalan di hadapan-Ku! Dengan mendadak Tuhan yang kamu cari itu akan masuk ke bait-Nya!…” — Maleakhi 3:1\n\nKirim mixtape ini ke teman yang sedang menantikan jawaban doa 💌"},
    {"judul": "Lagu Malam Adven",
     "lagu": ["Lilin Pertama", "Pulihkanlah Kami", "Menanti di Ambang Fajar", "Besok Kita Berkumpul"],
     "ayat": "“Ya Allah, pulihkanlah kami, buatlah wajah-Mu bersinar, maka kami akan selamat.”",
     "ref": "Mazmur 80:4",
     "caption": "Mixtape untuk malam menjelang Adven 📼\n\nMazmur 80 adalah doa umat yang sedang hancur. Mereka menggambarkan diri seperti pohon anggur yang dirusak. Tiga kali mereka mengulang permohonan yang hampir sama, seperti refrein sebuah lagu: pulihkanlah kami, buatlah wajah-Mu bersinar. Masa Adven memberi ruang bagi doa seperti ini, doa yang jujur sambil menantikan terang-Nya.\n\n📖 “Ya Allah, pulihkanlah kami, buatlah wajah-Mu bersinar, maka kami akan selamat.” — Mazmur 80:4\n\nKirim mixtape ini ke teman yang sedang menantikan pemulihan 💌"},
]

# ---------- GOSOK: Reel kartu gosok (malam0 19:30) ----------
GOSOK = [
    {"atas": "Gosok untuk kabar Minggu malam",
     "hadiah": "Ia akan memerintah sampai selama-lamanya",
     "ayat": "“…Pemerintahan atas dunia dipegang oleh Tuhan kita dan Dia yang diurapi-Nya, dan Ia akan memerintah sebagai raja sampai selama-lamanya.”",
     "ref": "Wahyu 11:15",
     "caption": "Kabar malam ini: siapa yang memegang dunia? 🎟️\n\nKetika malaikat ketujuh meniup sangkakalanya, suara-suara nyaring di sorga mengumumkan kabar ini. Berita malam ini mungkin penuh kekacauan dan nama-nama penguasa yang datang dan pergi. Tapi akhir ceritanya sudah diumumkan: pemerintahan atas dunia dipegang oleh Tuhan kita dan Dia yang diurapi-Nya, Kristus.\n\n📖 “…Pemerintahan atas dunia dipegang oleh Tuhan kita dan Dia yang diurapi-Nya, dan Ia akan memerintah sebagai raja sampai selama-lamanya.” — Wahyu 11:15\n\nKetik “Selama-lamanya” kalau malam ini kamu mau beristirahat dalam kabar ini 👑"},
    {"atas": "Gosok: pesan dari Sang Raja",
     "hadiah": "Untuk yang paling hina, berarti untuk Sang Raja",
     "ayat": "“…Raja itu akan menjawab mereka… segala sesuatu yang kamu lakukan untuk salah seorang dari saudara-Ku yang paling hina ini, kamu telah melakukannya untuk Aku.”",
     "ref": "Matius 25:40",
     "caption": "Hadiah malam ini 🎟️\n\nDalam gambaran Yesus tentang akhir zaman, Sang Raja bersemayam di atas takhta kemuliaan-Nya. Yang mengejutkan, Ia menyamakan diri-Nya dengan orang-orang yang lapar, haus, asing, telanjang, sakit, dan dipenjara. Raja ini begitu dekat dengan yang kecil, sampai pelayanan kepada mereka Ia anggap sebagai pelayanan kepada-Nya.\n\n📖 “…Raja itu akan menjawab mereka… segala sesuatu yang kamu lakukan untuk salah seorang dari saudara-Ku yang paling hina ini, kamu telah melakukannya untuk Aku.” — Matius 25:40\n\nTulis di komentar satu orang yang mau kamu layani minggu ini 👇"},
    {"atas": "Gosok untuk pesan malam ini",
     "hadiah": "Kerajaan-Nya kerajaan segala abad",
     "ayat": "“Kerajaan-Mu ialah kerajaan segala abad, dan pemerintahan-Mu tetap melalui segala keturunan…”",
     "ref": "Mazmur 145:13",
     "caption": "Pesan tersembunyi malam ini 🎟️\n\nKerajaan-kerajaan besar dalam sejarah pernah merasa akan bertahan selamanya. Mesir, Asyur, Babel, Persia, Yunani, Romawi, semuanya berlalu. Daud memuji kerajaan yang berbeda: kerajaan segala abad. Pemerintahan Allah tidak bergantung pada siapa yang sedang berkuasa atau bagaimana keadaan ekonomi minggu ini.\n\n📖 “Kerajaan-Mu ialah kerajaan segala abad, dan pemerintahan-Mu tetap melalui segala keturunan…” — Mazmur 145:13\n\nKetik “Segala abad” kalau malam ini kamu mau beristirahat dalam pemerintahan-Nya 🤍"},
    {"atas": "Gosok untuk tugas malam ini",
     "hadiah": "Berbahagialah pembawa damai",
     "ayat": "“Berbahagialah orang yang membawa damai, karena mereka akan disebut anak-anak Allah.”",
     "ref": "Matius 5:9",
     "caption": "Pesan tersembunyi untuk hari Rabu 🎟️\n\nMembawa damai tidak sama dengan menghindari konflik atau pura-pura semuanya baik-baik saja. Pembawa damai berani masuk ke tempat yang retak: mendengar, mengampuni, dan memperbaiki. Yesus menyebut mereka anak-anak Allah, karena mereka mirip Bapanya, Allah yang mendamaikan dunia dengan diri-Nya di dalam Kristus.\n\n📖 “Berbahagialah orang yang membawa damai, karena mereka akan disebut anak-anak Allah.” — Matius 5:9\n\nTag satu teman yang selalu jadi pembawa damai di kelompokmu 👇"},
    {"atas": "Gosok untuk janji malam ini",
     "hadiah": "Tuhan tidak lalai menepati janji-Nya",
     "ayat": "“Tuhan tidak lalai menepati janji-Nya, sekalipun ada orang yang menganggapnya sebagai kelalaian, tetapi Ia sabar terhadap kamu…”",
     "ref": "2 Petrus 3:9",
     "caption": "Janji di balik lapisan perak 🎟️\n\nSejak zaman Petrus sudah ada orang yang mengejek: di manakah janji tentang kedatangan-Nya itu? Petrus menjawab bahwa di hadapan Tuhan satu hari sama seperti seribu tahun. Yang terlihat seperti terlambat sebenarnya adalah kesabaran. Ia memberi waktu, karena Ia menghendaki supaya semua orang berbalik dan bertobat.\n\n📖 “Tuhan tidak lalai menepati janji-Nya, sekalipun ada orang yang menganggapnya sebagai kelalaian, tetapi Ia sabar terhadap kamu…” — 2 Petrus 3:9\n\nKetik “Dia setia” kalau malam ini kamu mau berpegang pada janji-Nya 🤍"},
    {"atas": "Gosok untuk kabar malam ini",
     "hadiah": "Segala dosa kita dilempar ke tubir laut",
     "ayat": "“Biarlah Ia kembali menyayangi kita, menghapuskan kesalahan-kesalahan kita dan melemparkan segala dosa kita ke dalam tubir-tubir laut.”",
     "ref": "Mikha 7:19",
     "caption": "Lapisan yang digosok sampai bersih 🎟️\n\nKitab Mikha banyak berisi teguran keras karena dosa umat. Tapi kitab ini ditutup dengan pujian kepada Allah yang mengampuni. Gambaran yang dipakai Mikha luar biasa: dosa-dosa tidak hanya disimpan di laci, tetapi dilemparkan ke tubir laut yang paling dalam. Pertobatan bukan jalan menuju rasa malu tanpa akhir. Pertobatan membawa kita kepada belas kasihan-Nya.\n\n📖 “Biarlah Ia kembali menyayangi kita, menghapuskan kesalahan-kesalahan kita dan melemparkan segala dosa kita ke dalam tubir-tubir laut.” — Mikha 7:19\n\nKetik “Dilempar ke laut” kalau kamu bersyukur untuk pengampunan-Nya 🤍"},
    {"atas": "Gosok untuk bekal Adven",
     "hadiah": "Pengharapan yang tidak mengecewakan",
     "ayat": "“Dan pengharapan tidak mengecewakan, karena kasih Allah telah dicurahkan di dalam hati kita oleh Roh Kudus yang telah dikaruniakan kepada kita.”",
     "ref": "Roma 5:5",
     "caption": "Bekal untuk masa Adven 🎟️\n\nPengharapan Kristen bukan sekadar berharap semoga semuanya baik-baik saja. Paulus menulis bahwa pengharapan ini tidak mengecewakan, karena dasarnya bukan keadaan kita, melainkan kasih Allah yang sudah dicurahkan ke dalam hati kita oleh Roh Kudus. Besok lilin pengharapan dinyalakan. Malam ini, simpan kalimat ini baik-baik.\n\n📖 “Dan pengharapan tidak mengecewakan, karena kasih Allah telah dicurahkan di dalam hati kita oleh Roh Kudus yang telah dikaruniakan kepada kita.” — Roma 5:5\n\nKetik “Tidak mengecewakan” kalau kamu mau membawa pengharapan ini ke ibadah besok 🕯️"},
]

# ---------- SERTIFIKAT: sertifikat berdasarkan anugerah (malam 21:00) ----------
SERTIFIKAT = [
    {"judul": "SERTIFIKAT ANGGOTA KERAJAAN",
     "nama": "KAMU",
     "isi": "Telah dikasihi, dilepaskan dari dosa oleh darah Yesus, dan dijadikan bagian dari kerajaan-Nya, menjadi imam-imam bagi Allah.",
     "dasar": "Berdasarkan darah Anak Domba",
     "ayat": "“…Bagi Dia, yang mengasihi kita dan yang telah melepaskan kita dari dosa kita oleh darah-Nya… telah membuat kita menjadi suatu kerajaan…”",
     "ref": "Wahyu 1:5-6",
     "caption": "Sertifikat untuk Minggu Kristus Raja 📜\n\nPerhatikan urutan dalam salam pembuka kitab Wahyu: Yesus mengasihi kita, melepaskan kita dari dosa oleh darah-Nya, lalu membuat kita menjadi suatu kerajaan. Semua kata kerjanya dikerjakan oleh Dia. Kita tidak mendaftar dengan prestasi. Kita diterima karena kasih-Nya.\n\n📖 “…Bagi Dia, yang mengasihi kita dan yang telah melepaskan kita dari dosa kita oleh darah-Nya… telah membuat kita menjadi suatu kerajaan…” — Wahyu 1:5-6\n\nKetik “Dikasihi-Nya” kalau kamu mau menerima sertifikat ini 🤍"},
    {"judul": "SERTIFIKAT TEBUSAN LUNAS",
     "nama": "KAMU",
     "isi": "Telah ditebus oleh Yesus, yang datang bukan untuk dilayani, melainkan untuk melayani dan memberikan nyawa-Nya.",
     "dasar": "Dibayar lunas dengan nyawa-Nya",
     "ayat": "“Karena Anak Manusia juga datang bukan untuk dilayani, melainkan untuk melayani dan untuk memberikan nyawa-Nya menjadi tebusan bagi banyak orang.”",
     "ref": "Markus 10:45",
     "caption": "Sertifikat malam ini 📜\n\nTebusan adalah harga yang dibayar untuk membebaskan seseorang. Yesus tidak hanya melayani dengan membasuh kaki dan menyembuhkan orang sakit. Pelayanan-Nya yang terbesar adalah memberikan nyawa-Nya sebagai tebusan. Kamu tidak membayar sepeser pun untuk sertifikat ini. Harganya sudah lunas dibayar oleh Raja yang melayani.\n\n📖 “Karena Anak Manusia juga datang bukan untuk dilayani, melainkan untuk melayani dan untuk memberikan nyawa-Nya menjadi tebusan bagi banyak orang.” — Markus 10:45\n\nKetik “Lunas” kalau kamu bersyukur untuk tebusan-Nya 🤍"},
    {"judul": "SERTIFIKAT WARISAN KEKAL",
     "nama": "KAMU",
     "isi": "Memiliki bagian yang tidak dapat binasa, tidak dapat cemar, dan tidak dapat layu, tersimpan di sorga. Dipelihara oleh kekuatan Allah.",
     "dasar": "Berdasarkan rahmat Allah",
     "ayat": "“untuk menerima suatu bagian yang tidak dapat binasa, yang tidak dapat cemar dan yang tidak dapat layu, yang tersimpan di sorga bagi kamu.”",
     "ref": "1 Petrus 1:4",
     "caption": "Sertifikat yang tidak bisa hilang 📜\n\nPetrus menulis kepada orang-orang pendatang yang tersebar di berbagai daerah, banyak di antaranya sedang berdukacita karena berbagai pencobaan. Rumah, harta, dan rasa aman mereka bisa hilang kapan saja. Tapi ada satu bagian yang tidak bisa dirampas: bagian yang tersimpan di sorga. Rumah bisa goyah, harga bisa naik, tetapi bagian ini tidak dapat binasa.\n\n📖 “untuk menerima suatu bagian yang tidak dapat binasa, yang tidak dapat cemar dan yang tidak dapat layu, yang tersimpan di sorga bagi kamu.” — 1 Petrus 1:4\n\nSave sertifikat ini untuk hari-hari ketika semuanya terasa tidak pasti 🔖"},
    {"judul": "SERTIFIKAT WARGA KERAJAAN",
     "nama": "KAMU",
     "isi": "Dahulu bukan umat Allah, sekarang umat-Nya. Dahulu tidak dikasihani, sekarang telah beroleh belas kasihan.",
     "dasar": "Berdasarkan belas kasihan-Nya",
     "ayat": "“kamu, yang dahulu bukan umat Allah, tetapi yang sekarang telah menjadi umat-Nya… yang sekarang telah beroleh belas kasihan.”",
     "ref": "1 Petrus 2:10",
     "caption": "Sertifikat kewarganegaraan 📜\n\nPetrus memakai kata-kata dari kitab Hosea untuk menggambarkan orang-orang percaya: dahulu bukan umat Allah, sekarang umat-Nya. Kewarganegaraan dalam Kerajaan Allah tidak bisa dibeli, tidak diwarisi dari orang tua, dan tidak bisa diraih dengan berbuat baik. Satu-satunya dasarnya adalah belas kasihan Allah.\n\n📖 “kamu, yang dahulu bukan umat Allah, tetapi yang sekarang telah menjadi umat-Nya… yang sekarang telah beroleh belas kasihan.” — 1 Petrus 2:10\n\nKetik “Umat-Nya” kalau kamu bersyukur untuk status ini 🤍"},
    {"judul": "SERTIFIKAT DIJAGA SAMPAI AKHIR",
     "nama": "KAMU",
     "isi": "Akan diteguhkan oleh Allah sampai kesudahannya, tak bercacat pada hari Tuhan Yesus Kristus. Penantianmu dipegang oleh Dia yang setia.",
     "dasar": "Berdasarkan kesetiaan Allah",
     "ayat": "“Ia juga akan meneguhkan kamu sampai kepada kesudahannya, sehingga kamu tak bercacat pada hari Tuhan kita Yesus Kristus.”",
     "ref": "1 Korintus 1:8",
     "caption": "Sertifikat untuk yang takut tidak bertahan 📜\n\nJemaat Korintus punya banyak masalah: perpecahan, kesombongan, dosa yang dibiarkan. Tapi di awal suratnya Paulus menulis kalimat yang mengejutkan ini. Bukan karena mereka hebat, tetapi karena Allah yang memanggil mereka adalah setia. Kalau kamu takut tidak bisa bertahan sampai akhir, ingat siapa yang meneguhkanmu.\n\n📖 “Ia juga akan meneguhkan kamu sampai kepada kesudahannya, sehingga kamu tak bercacat pada hari Tuhan kita Yesus Kristus.” — 1 Korintus 1:8\n\nKetik “Dia meneguhkan” kalau malam ini kamu butuh jaminan ini 🤍"},
    {"judul": "SERTIFIKAT PENGAMPUNAN",
     "nama": "KAMU",
     "isi": "Dahulu mati oleh pelanggaran, kini dihidupkan Allah bersama Kristus. Segala pelanggaran telah diampuni.",
     "dasar": "Berdasarkan anugerah",
     "ayat": "“Kamu juga, meskipun dahulu mati oleh pelanggaranmu… telah dihidupkan Allah bersama-sama dengan Dia, sesudah Ia mengampuni segala pelanggaran kita,”",
     "ref": "Kolose 2:13",
     "caption": "Sertifikat untuk akhir pekan 📜\n\nPerhatikan siapa yang bekerja dalam ayat ini. Kita dahulu mati, dan orang mati tidak bisa menghidupkan dirinya sendiri. Allah yang menghidupkan. Allah yang mengampuni. Dan bukan sebagian pelanggaran, tetapi segala pelanggaran. Pertobatan adalah respons kita, tetapi pengampunan sepenuhnya adalah pekerjaan-Nya.\n\n📖 “Kamu juga, meskipun dahulu mati oleh pelanggaranmu… telah dihidupkan Allah bersama-sama dengan Dia, sesudah Ia mengampuni segala pelanggaran kita,” — Kolose 2:13\n\nKetik “Diampuni” kalau kamu mau menerima sertifikat ini malam ini 🤍"},
    {"judul": "SERTIFIKAT HIDUP KEKAL",
     "nama": "KAMU",
     "isi": "Dibenarkan oleh kasih karunia-Nya dan berhak menerima hidup yang kekal, sesuai dengan pengharapan kita.",
     "dasar": "Berdasarkan kasih karunia",
     "ayat": "“supaya kita, sebagai orang yang dibenarkan oleh kasih karunia-Nya, berhak menerima hidup yang kekal, sesuai dengan pengharapan kita.”",
     "ref": "Titus 3:7",
     "caption": "Sertifikat untuk malam Minggu 📜\n\nSebelum ayat ini, Paulus mengingatkan bahwa Allah menyelamatkan kita bukan karena perbuatan baik yang telah kita lakukan, tetapi karena rahmat-Nya. Lalu ia menulis tujuannya: supaya kita dibenarkan oleh kasih karunia dan berhak menerima hidup yang kekal. Besok kita memasuki masa Adven bukan sebagai orang yang harus membuktikan diri, tetapi sebagai orang yang menanti dengan pengharapan.\n\n📖 “supaya kita, sebagai orang yang dibenarkan oleh kasih karunia-Nya, berhak menerima hidup yang kekal, sesuai dengan pengharapan kita.” — Titus 3:7\n\nKetik “Kasih karunia” kalau kamu bersyukur untuk anugerah-Nya 🤍"},
]

# ---------- JENDELA: jendela berembun, tulisan jari di kaca (larut 22:30) ----------
JENDELA = [
    {"teks": "Raja selamanya",
     "ayat": "“TUHAN adalah Raja untuk seterusnya dan selama-lamanya…”",
     "ref": "Mazmur 10:16",
     "caption": "Ditulis di kaca jendela malam ini 🌙\n\nMazmur 10 dibuka dengan pertanyaan yang jujur: mengapa Engkau berdiri jauh-jauh, ya TUHAN? Pemazmur melihat orang lemah ditindas dan tidak menutupi kegelisahannya. Tapi di ujung doanya ia sampai pada keyakinan ini: TUHAN adalah Raja untuk seterusnya dan selama-lamanya, dan Ia mendengarkan keinginan orang-orang yang tertindas.\n\n📖 “TUHAN adalah Raja untuk seterusnya dan selama-lamanya…” — Mazmur 10:16\n\nKetik “Amin” dan tutup Minggu Kristus Raja dengan tenang 🤍"},
    {"teks": "Dikasihi sampai akhir",
     "ayat": "“…Sama seperti Ia senantiasa mengasihi murid-murid-Nya demikianlah sekarang Ia mengasihi mereka sampai kepada kesudahannya.”",
     "ref": "Yohanes 13:1",
     "caption": "Ditulis di kaca yang berembun 🌙\n\nSebelum mengambil basi dan kain lenan, Yohanes mencatat satu kalimat tentang hati Yesus. Ia tahu saat-Nya sudah tiba, salib sudah dekat, dan murid-murid-Nya akan meninggalkan Dia. Tapi Ia tetap mengasihi mereka sampai kepada kesudahannya. Malam ini, beristirahatlah dalam kasih yang tidak berhenti di tengah jalan.\n\n📖 “…Sama seperti Ia senantiasa mengasihi murid-murid-Nya demikianlah sekarang Ia mengasihi mereka sampai kepada kesudahannya.” — Yohanes 13:1\n\nKetik “Sampai akhir” dan selamat beristirahat 🤍"},
    {"teks": "Ada sauh untuk jiwamu",
     "ayat": "“Pengharapan itu adalah sauh yang kuat dan aman bagi jiwa kita, yang telah dilabuhkan sampai ke belakang tabir,”",
     "ref": "Ibrani 6:19",
     "caption": "Tulisan di kaca malam ini 🌙\n\nSauh tidak menghentikan ombak. Sauh menahan kapal supaya tidak hanyut. Penulis Ibrani berkata pengharapan kita adalah sauh seperti itu, dan sauh itu tidak dilabuhkan di dasar laut, tetapi sampai ke belakang tabir, ke hadirat Allah, tempat Yesus telah masuk sebagai Perintis bagi kita. Ombak malam ini mungkin besar, tetapi kamu tertambat pada Dia.\n\n📖 “Pengharapan itu adalah sauh yang kuat dan aman bagi jiwa kita, yang telah dilabuhkan sampai ke belakang tabir,” — Ibrani 6:19\n\nKetik ⚓ sebelum tidur kalau kamu mau berpegang pada pengharapan ini."},
    {"teks": "Kamu terang dunia",
     "ayat": "“Kamu adalah terang dunia. Kota yang terletak di atas gunung tidak mungkin tersembunyi.”",
     "ref": "Matius 5:14",
     "caption": "Ditulis di kaca malam ini 🌙\n\nYesus tidak berkata: berusahalah menjadi terang. Ia berkata: kamu adalah terang dunia. Ini identitas warga Kerajaan-Nya, terang yang memantulkan Dia, Terang yang sejati. Di luar jendela malam ini mungkin gelap. Besok, di tempat kerja, kampus, atau rumahmu, terang itu dibawa keluar lagi.\n\n📖 “Kamu adalah terang dunia. Kota yang terletak di atas gunung tidak mungkin tersembunyi.” — Matius 5:14\n\nKetik 🕯️ dan selamat beristirahat."},
    {"teks": "Datanglah, Tuhan Yesus",
     "ayat": "“…‘Ya, Aku datang segera!’ Amin, datanglah, Tuhan Yesus!”",
     "ref": "Wahyu 22:20",
     "caption": "Doa di halaman terakhir Alkitab 🌙\n\nDi bagian paling akhir Alkitab, Yesus berjanji: Aku datang segera. Dan gereja menjawab dengan doa yang singkat: Amin, datanglah, Tuhan Yesus. Jemaat mula-mula punya doa yang mirip dalam bahasa Aram: Maranata, Tuhan kami, datanglah. Malam ini, sebelum tidur, kamu boleh menuliskannya di kaca jendela hatimu.\n\n📖 “…‘Ya, Aku datang segera!’ Amin, datanglah, Tuhan Yesus!” — Wahyu 22:20\n\nKetik “Maranata” sebagai doamu malam ini 🤍"},
    {"teks": "Ia dekat. Berserulah.",
     "ayat": "“Carilah TUHAN selama Ia berkenan ditemui; berserulah kepada-Nya selama Ia dekat!”",
     "ref": "Yesaya 55:6",
     "caption": "Ditulis di kaca malam Jumat 🌙\n\nYesaya 55 adalah undangan yang hangat: yang haus diajak datang dan minum, yang tidak punya uang diajak menerima tanpa bayaran. Lalu datang ajakan ini: carilah TUHAN, berserulah kepada-Nya selama Ia dekat. Kalimat sesudahnya berjanji bahwa Ia memberi pengampunan dengan limpahnya. Malam ini Ia dekat. Jangan ditunda.\n\n📖 “Carilah TUHAN selama Ia berkenan ditemui; berserulah kepada-Nya selama Ia dekat!” — Yesaya 55:6\n\nKetik “Aku berseru” sebagai doamu malam ini 🤍"},
    {"teks": "Hampir siang",
     "ayat": "“Hari sudah jauh malam, telah hampir siang. Sebab itu marilah kita menanggalkan perbuatan-perbuatan kegelapan dan mengenakan perlengkapan senjata terang!”",
     "ref": "Roma 13:12",
     "caption": "Ditulis di kaca malam Minggu 🌙\n\nDi luar jendela mungkin masih gelap. Tapi Paulus mengingatkan bahwa malam sudah jauh dan siang hampir tiba. Bagian surat Roma ini sejak lama dibacakan gereja di masa Adven. Hidup orang percaya adalah hidup di ujung malam, menantikan fajar kedatangan Kristus. Tidurlah dengan tenang, lalu bangunlah besok untuk menyambut Minggu Adven pertama.\n\n📖 “Hari sudah jauh malam, telah hampir siang. Sebab itu marilah kita menanggalkan perbuatan-perbuatan kegelapan dan mengenakan perlengkapan senjata terang!” — Roma 13:12\n\nKetik “Hampir siang” dan sampai jumpa di ibadah besok 🕯️"},
]

# komik Eli yang sudah jadi (folder Eli): hari 1, 4, 7 di pagi2
ELI = [("edukasi", 1), ("kuis", 2), ("saran", 4)]

_PAGI2 = {1: ("ELI", 0), 2: ("RAMBU", 0), 3: ("RAMBU", 1), 4: ("ELI", 1), 5: ("RAMBU", 2), 6: ("RAMBU", 3), 7: ("ELI", 2)}

# hari 1-7 (Minggu 22 Nov .. Sabtu 28 Nov 2026): 12 slot per hari -> (format, index)
# pagi 06:00, pagi3 07:30, pagi2 09:00, siang0 10:30, siang 12:00, siang2 13:30, sore 15:00, sore2 16:30,
# petang 18:00, malam0 19:30, malam 21:00, larut 22:30
JADWAL = {d: {"pagi": ("JAM", d - 1), "pagi3": ("NAMA", d - 1), "pagi2": _PAGI2[d],
              "siang0": ("RESEP", d - 1), "siang": ("UNDANGAN", d - 1), "siang2": ("PROGRESS", d - 1),
              "sore": ("GLOBE", d - 1), "sore2": ("MUSEUM", d - 1), "petang": ("KASET", d - 1),
              "malam0": ("GOSOK", d - 1), "malam": ("SERTIFIKAT", d - 1), "larut": ("JENDELA", d - 1)} for d in range(1, 8)}
